### ISSUE TITLE
Feature Request - Humidity Sensor

### ISSUE THREAD

**Issue by hjdhjd** [chrisjshull/homebridge-nest#101]
It would be great if a corresponding Humidity Sensor could be created for each Nest Thermostat. Clearly this information is available and in fact shows up in the logs...should be a short step to create a sensor for there.

Can we get this in an upcoming point release? :)

**Comment by adriancable** [comment]
Thanks for the great suggestion! I'll work on adding an option to break out both the temperature and humidity sensors, which I think will be useful for automations.

NB the humidity sensor readout is currently available in the 'Settings' for the thermostat.

**Comment by adriancable** [comment]
Humidity sensor is now available as a separate sensor in the latest commit.

**Comment by hjdhjd** [comment]
Thanks! Will test this out shortly. Planning to increment the version number and push to npmjs soon or are you just sticking to git?

**Comment by adriancable** [comment]
I'll push to npmjs when 3.1.0 is fully tested and stable. I've made a lot of changes under the hood - want to make sure all is reliable from publishing to npmjs.
