### ISSUE TITLE
Multiple Home / Away Sensors Duplicative

### ISSUE THREAD

**Issue by hjdhjd** [chrisjshull/homebridge-nest#103]
In scenarios where you have multiple Nest Thermostats in a home, having multiple Home / Away switches can be confusing and is redundant. I'd suggest for each home, only a single Home / Away switch gets created, regardless of the number of Thermostats. 

That would make it more consistent with the intent of Home / Away. Home / Away cannot be configured per-device...it's a global setting for the home.

Eco Mode, by comparison **can** be configured per-device, so it makes sense to have one per Thermostat.

**Comment by adriancable** [comment]
The latest commit creates separate accessories for each temperature sensor, so you should be able to move them individually to different rooms. Please try it and let me know how you get in.

Re. the Home/Away setting. I agree with what you say. At the moment the way the code is structured, each Thermostat is separate and they don't communicate with each other. I'll need to think of a good way so that multiple Home/Away switches aren't created.

**Comment by adriancable** [comment]
Latest commit now allows you to do what you want. You can set options for individual devices in config.json.

If you have two thermostats with device IDs for example ABC123 and DEF456, and you only want one Home/Away control, then add to "options" in config.json: "Thermostat.HomeAway.Disable.DEF456". That way you will only get one Home/Away control for your whole system. The device ID is listed as "Serial Number" in the Home app, if you view the settings for the device, or in the Homebridge logs.

Check it out and let me know if it works for you - then I can close this issue.

**Comment by hjdhjd** [comment]
It works...BTW - nice touch including serials in the description. So few plugins make the effort! THANK YOU.

That said...this is still hack-y, IMO. I’d suggest that the DEFAULT should be where you only add one of these and people can add in the additional home / away sensors by exception. I really think having these in the default configuration will increase confusion for newer folks. The default config should “just work” for most people without having to scratch their heads about why there are multiple Home / Away sensors instead of one.

Bonus would be to recognize that first Home / Away sensor as it’s own device (assuming it isn’t already) to be placed anywhere (e.g. a Room called “Home”).

**Comment by adriancable** [comment]
I agree. It will happen! Since what's on Github now seems to work pretty well, I will release 3.1.0 on npmjs tomorrow and then something along the lines of what you suggest, I'll implement in 3.2.0.

**Comment by hjdhjd** [comment]
Thank you!

**Comment by adriancable** [comment]
@hjdhjd - fixed in latest Github commit. Please give it a go and let me know if it is what you're looking for. You should only get one Home/Away control, and you can put it in a different room from the other devices if you want.

**Comment by hjdhjd** [comment]
Works like a charm. I think this one is good.
