### ISSUE TITLE
Cannot read property errors

### ISSUE THREAD

**Issue by CaptBeard** [chrisjshull/homebridge-nest#104]
Getting errors on home bridge startup using the latest commit.
Homebridge starts and runs fine, but all the Nest stuff isn't added to Home.

Tested running version 3.0 vs. the latest and version 3.0 works. It only breaks when I move in the new files to test the temperature sensors.

Errors:
`[Nest] TypeError: Cannot read property 'toUpperCase' of undefined
Jul 23 10:22:47 rpi homebridge[1422]:     at NestTempSensorAccessory.NestDeviceAccessory (/usr/local/lib/node_modules/homebridge-nest/lib/nest-device
Jul 23 10:22:47 rpi homebridge[1422]:     at new NestTempSensorAccessory (/usr/local/lib/node_modules/homebridge-nest/lib/nest-tempsensor-accessory.j
Jul 23 10:22:47 rpi homebridge[1422]:     at NestPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/index.js:105:39)
Jul 23 10:22:47 rpi homebridge[1422]:     at NestPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/index.js:115:17)
Jul 23 10:22:47 rpi homebridge[1422]:     at /usr/local/lib/node_modules/homebridge-nest/index.js:143:40
Jul 23 10:22:47 rpi homebridge[1422]:     at tryCatcher (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/util.js:16:23)
Jul 23 10:22:47 rpi homebridge[1422]:     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/
Jul 23 10:22:47 rpi homebridge[1422]:     at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/pro
Jul 23 10:22:47 rpi homebridge[1422]:     at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/pr
Jul 23 10:22:47 rpi homebridge[1422]:     at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/pr
Jul 23 10:22:47 rpi homebridge[1422]:     at _drainQueueStep (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/async.js:1
Jul 23 10:22:47 rpi homebridge[1422]:     at _drainQueue (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/async.js:131:9
Jul 23 10:22:47 rpi homebridge[1422]:     at Async._drainQueues (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/async.j
Jul 23 10:22:47 rpi homebridge[1422]:     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-nest/node_modules/
Jul 23 10:22:47 rpi homebridge[1422]:     at runCallback (timers.js:696:18)
Jul 23 10:22:47 rpi homebridge[1422]:     at tryOnImmediate (timers.js:667:5)
Jul 23 10:22:47 rpi homebridge[1422]:     at processImmediate (timers.js:649:5)`

**Comment by adriancable** [comment]
@CaptBeard - can you do two things. (1) that error has some of the lines cut off in the middle, unfortunately the bit showing me the code line numbers is cut off - can you copy and paste the complete error?

(2) Can you get me a HAR file as follows:

1. Go to home.nest.com in your browser and log in.
2. Enable HAR file recording.
3. Press 'Refresh'
4. Save the HAR file and email it to me: adrian.cable@gmail.com

This should help me debug. Thanks!

**Comment by adriancable** [comment]
@CaptBeard - I have pushed a new commit which may fix your issue. Please let me know - also the HAR file would still be very useful. Thanks.

**Comment by CaptBeard** [comment]
> @CaptBeard - I have pushed a new commit which may fix your issue. Please let me know - also the HAR file would still be very useful. Thanks.

The latest version fixed my issue, thanks!
Also, emailed you HAR file.

**Comment by adriancable** [comment]
One of your Temperature Sensors isn't reporting its model number for some reason. But my new code doesn't rely on that, so all should be fine now. Thanks for your help!
