### ISSUE TITLE
Updating the temperature of the room

### ISSUE THREAD

**Issue by djrams10** [chrisjshull/homebridge-nest#106]
**Describe the bug**

**To Reproduce**
1. After a reboot of the homebridge, the plugin works perfectly for a few hours, the temperature of the room updates, in the logs I see a refresh every 20 seconds of the temperature information of the nest. But after a few hours the temperature is no longer updated, and it refreshes the thermostat data less often, and the data is blocked and it does not update the new temperature. I can send a command, decrease / increase the temperature, turn off or turn on the thermostat, and all works. The problem lies just at the level of the temperature update of the room. and if I restart homebridge the problem is settled instantly.
 I have updated with the latest version of plugin 3.1

homebridge Version 0.4.50
node.js v10.16.0
 homebridge-config-ui-x v4.5.1

**Comment by adriancable** [comment]
Hi - I'm sorry you're having this problem. I have no idea what is happening!

Would you kindly run homebridge in debug mode: homebridge -D

And then, when it gets to the point where the temperature is no longer updating, please email me the last few pages of the homebridge debug output to adrian.cable@gmail.com

At this point, also please tell me what the temperature in the room is (as on the thermostat itself, or the Nest app) and what the temperature being reported by HomeKit is.

Thanks!

**Comment by djrams10** [comment]
I am currently in debug mode. I enclose the file by mail

**Comment by adriancable** [comment]
@djrams10 - good news is I can reproduce this. I left Homebridge running overnight, and in the morning indeed the thermostat state had stopped updating.

Bad news is I don't know why this is happening yet, but will figure it out and get back to you.

**Comment by djrams10** [comment]
> @djrams10 - good news is I can reproduce this. I left Homebridge running overnight, and in the morning indeed the thermostat state had stopped updating.
> 
> Bad news is I don't know why this is happening yet, but will figure it out and get back to you.

Great!!!! Thank you very much for your work again.

**Comment by adriancable** [comment]
@djrams10 - can you tell me a bit about the hardware you are running Homebridge on?

Looking at the code there are only two possibilities that I can see that would stop the update loop from executing:

1. setTimeout call gets triggered but doesn't execute. Looking on stackoverflow it seems that on some platforms, when the device sleeps, the setTimeout handler doesn't get triggered when the device wakes up.
2. Nest API socket accepts the connection for the update request, but never returns. i.e. the Nest service glitches in this particular way.
3. There may be a bug in the request-promise library. (currently I'm using an old version)

All 3 of these problems can be fixed, but I want to make sure that at least one of these is indeed the cause. So more info would be super useful. Thanks!

**Comment by djrams10** [comment]
Yes I understand, I'm on a nas synology with a plugin config ui. do you need other information?

**Comment by adriancable** [comment]
@djrams10 - I have put in workarounds for issues #1-2 above and updated request-promise. Can you pull from Github and see if this fixes your issue? I will also run for an extended time period today and check that the temperature continues to update.

Thanks!

**Comment by djrams10** [comment]
Can you describe the procedure for extracting it?

**Comment by adriancable** [comment]
@djrams10 - I've now updated the package to 3.1.1 on npmjs which includes the bug fix. Just update in the normal way: npm update -g homebridge-nest

Please let me know if this works better for you.

**Comment by djrams10** [comment]
Yes, of course, you can count on me. I'll make you a return tomorrow. thank you

**Comment by djrams10** [comment]
After 10h to turn without problem, you solution seems to work perfectly !!!! Thank you, you are too strong !!!!!!

**Comment by adriancable** [comment]
Thanks - appreciate everything you've done!

**Comment by djrams10** [comment]
I have this error there, it poses problem?


<img width="1138" alt="Capture d’écran 2019-07-27 à 11 39 08" src="https://user-images.githubusercontent.com/28505910/61993012-0e9f8980-b066-11e9-88a3-46395a5e1d3b.png">

**Comment by adriancable** [comment]
It looks like you have two versions of the plug-in installed - one from npmjs (which lives in /usr/local/lib/node_modules/homebridge-nest) and one from github (which lives in /homebridge/node_modules/homebridge-nest).

You can just delete one of them, e.g. if you want to delete the npmjs one, then use: rm -rf /usr/local/lib/node_modules/homebridge-nest

**Comment by djrams10** [comment]
good, it's good. ;)
