### ISSUE TITLE
Does not seem to work with a "new" nest account

### ISSUE THREAD

**Issue by BadMelonFarmer** [chrisjshull/homebridge-nest#107]
I set up the new plugin and as I use 2FA on my main nest account, I set up a new account specifically for home bridge and set it up

I can log into the nest app with the new credentials, but nothing appeared in the Home App when the instance was running.

I decided to try my 2FA account as part of troubleshooting and it worked perfectly.

Not sure why? maybe there is a new method of authentication?

**Comment by adriancable** [comment]
Hi - please tell me a little more about your set-up. Nest devices can only "live" in one account at once - how did you move your Nest devices from your old account to your new one?

**Comment by adriancable** [comment]
@BadMelonFarmer - I just tried the following and it worked for me. Let me know how (or if) this differs from what you did.

1. Remove Nest thermostat from my old account.
2. Go to home.nest.com, click 'Sign Up', create a new account.
3. Click 'Add a thermostat'.
4. Go to my Nest Thermostat, go to NEST APP in Settings, get the entry key.
5. Enter entry key in home.nest.com. Thermostat is added.
6. Start homebridge.

This worked OK for me. The thermostat appeared in the Home app as expected.

Looking forward to more info from you.

**Comment by BadMelonFarmer** [comment]
Hi,

I created a new “homebridge” account and added it to the household.... same way as I did for my wife and daughter.

When I log into the app with the homebridge account I can see the cameras, smoke alarms etc.

But when I use the “homebridge” credentials in the homebridge Config I can add the nest homebridge to home app, but no devices are seen in home.

As part of trying to figure out what was going on, I used my main credentials in the Config file and it worked as expected.

Not sure if is an issue with newly created accounts or an issue with “household” accounts

**Comment by adriancable** [comment]
I think it could be an issue with household accounts. Let me look into that specifically. In the mean time can you do this for me:

1. Go to home.nest.com, and log into your "household" account (i.e. the one where no devices show up in homebridge)
2. Start HAR file recording in your browser
3. Press 'Refresh' in your browser
4. Stop HAR recording and send me the file

Thanks!

I don't think it's an issue with newly created accounts - I tried creating a new account this morning and adding my Thermostat to it, and didn't have an issue.

**Comment by adriancable** [comment]
@BadMelonFarmer - I've confirmed that the plug-in today doesn't work with Family Sharing accounts. I created one and noted that the data format returned by the API is completely different from a conventional account. I will add supprting Family Sharing accounts to the list for the next release.

**Comment by BadMelonFarmer** [comment]
@adriancable - Thanks for figuring it out so quickly!

I was away from my home for the day... do you still need me to get the HAR capture for you?

**Comment by adriancable** [comment]
@BadMelonFarmer - thanks but I don't need it now. I can figure it out with my own account. I'll keep you updated!

**Comment by adriancable** [comment]
@BadMelonFarmer - the latest commit on Github (not yet on npmjs) should now work with family sharing accounts. Please let me know how you get on.

**Comment by adriancable** [comment]
Closing for now as believed resolved.

**Comment by BadMelonFarmer** [comment]
@adriancable - Thanks, just updated and it is working great!
