### ISSUE TITLE
Historic temperature and humidity data

### ISSUE THREAD

**Issue by KozzakO** [chrisjshull/homebridge-nest#108]
It would be awesome to add a feature enabling storing historic temperature and humidity data from Nest in third party apps like Eve from Elgato, the way it is implemented in [Xiaomi Mi Temperature and Humidity Plug-in](https://github.com/hannseman/homebridge-mi-hygrothermograph)

**Comment by adriancable** [comment]
@KozzakO - I'm not familiar with Eve from Elgato. Can you send me some screenshots of what the data presentation looks like?

**Comment by adriancable** [comment]
Doing a bit more digging it seems that the temperature-over-time feature in Eve from Elgato is proprietary. It is possible to pass data to Eve from Elgato as you suggest, but it wouldn't be a "generic" history capability that would work with other apps, as far as I can tell.

**Comment by KozzakO** [comment]
@adriancable Here is an example of historic data from a Homebridge-enabled Xiaomi temperature and humidity sensor displayed in the Eve app. I am not sure how it is implemented, but I find this feature very useful, especially since the data can be exported. 
![IMG_6714](https://user-images.githubusercontent.com/24995391/61960379-9da89500-afc5-11e9-8837-91a712454b37.jpg)

**Comment by hjdhjd** [comment]
You’ll need something like https://github.com/simont77/fakegato-history to do it. While I understand the desire for something like this...from a HomeKit perspective, philosophically, is this really the job of this plugin?

I would suggest that it is not. This plugin is about getting a good level of HomeKit compatibility to Nest products, for ease of control and automation. History is best left to a specific app that wants to provide ‘enhanced’ native capabilities. If there are specific use cases that make sense, I’d be curious to learn more.

In the above examples...they only work if you use the Eve HomeKit app. That’s out of scope, IMO, for a plugin like this. At that point, you can just as easily use the Nest app...which you have to use anyway to setup the Nest, set schedules, etc.

Just a thought...

**Comment by adriancable** [comment]
I agree - as Mueller would say this sounds "out of my purview". Closing for now.
