### ISSUE TITLE
Perfect PlugIn !!! ... Help for XML/JSON request ?

### ISSUE THREAD

**Issue by roe1974** [chrisjshull/homebridge-nest#109]
Thx a lot for the perfect Plug-In !!!!
i want to get some data in my Homematic System.
Therefore i want to parse a XML or JSON GET request.
Is it possible to do this ... i search a lot for the right https url for a XML/JSON request ... but didnt find anything...
can you help me ?

Richard

**Comment by adriancable** [comment]
Sorry - I don't understand the question. Please give me more detail what you are looking for.

**Comment by roe1974** [comment]
ok
i search for the browser url to get the state of my nest protect....

like https://api.nest.com/v2/mobile?user=email&password=password

something like that .... is this possible with the nest api ?

richard

**Comment by adriancable** [comment]
Feel free to look at the code in lib/nest-connection.js. This shows how to connect to the API.
