### ISSUE TITLE
Verbosity level of logging.

### ISSUE THREAD

**Issue by hjdhjd** [chrisjshull/homebridge-nest#110]
It would be terrific if you could set the level of verbosity for this plugin. Currently, it effectively spams the logs and troubleshooting or reviewing the activity of other homebridge plugins can become a challenge. I get the value of debugging information, so understand a balance is needed here.

Thanks!

**Comment by adriancable** [comment]
In the latest commit, debug verbosity has been significantly reduced, unless Debug.Verbose option is set in config.json for this plug-in.
