### ISSUE TITLE
Add MQTT support

### ISSUE THREAD

**Issue by RaymondMouthaan** [chrisjshull/homebridge-nest#112]
**Describe the solution you'd like**

Hello @adriancable,

First of all **thank you** for the solution to "Works With Nest", which shuts down in August. 

Awesome would be to add MQTT support to this plugin. So the plugin can publish and subscribe to user configured topics. This way the plugin and therefore the Nest can be controlled via MQTT as well . 

A practical example would be to set the Nest temperature from within Node-Red. Or get the measured temperature / humidity values in Node-Red which can insert them into a database.

**node-red --> mqtt topic --> homebridge-nest**
here node-red publishes a json payload to a topic, where homebridge-nest subscribes to.

E.g.
topic /livingroom/nest/get 
payload 
```
{
   "temperature" : 22 
}
```

**homebridge-nest --> mqtt topic  --> node-red**
here homebridge-nest publishes a json payload to a topic, where node-red subscribes to.

E.g.
topic /livingroom/nest/set 
payload 
```
{
   "temperature" : 21,
   "humidity": 45
}
```

The plugin [homebridge-mqttthing](https://github.com/arachnetech/homebridge-mqttthing) does this for most of the standard homekit accessories and can be used as an example to add the support for MQTT in homebridge-nest.

**Comment by adriancable** [comment]
@RaymondMouthaan - if I understand it you are looking to make the Nest devices accessible via MQTT.

Can't you do this with homekit2mqtt? My understanding is that lets you expose any HomeKit devices (including the Nest accessories exposed by homebridge-nest) to MQTT, which sounds like what you want.

**Comment by RaymondMouthaan** [comment]
@adriancable - yes, making nest devices accessible from mqtt would be great.

Doing a quick scan of homekit2mqtt gives me the idea that with the plugin one can create / define homekit accessories which are accessible from mqtt, just like mqttthing plugin (which I mentioned earlier). Both support many homekit accessories, but for both I don't see any way to hookup upon the nest accessoire / plugin (or any other accessories which is not in there list). I might be wrong, but I think mqtt client must be programmed within the plugin it self?

**Comment by adriancable** [comment]
I believe that homebridge-mqttthing and homekit2mqtt are "opposites". The first is a Homebridge plug-in lets you mount MQTT devices on HomeKit. The second doesn't use Homebridge and makes existing HomeKit devices controllable via MQTT.

I believe that homekit2mqtt, together with homebridge-nest, will do exactly what you want without any changes, i.e. make the Nest controllable and monitorable by MQTT.

**Comment by RaymondMouthaan** [comment]
Yeah, you got that right indeed... However at this point I don't see how to let nest work with mqtt 🤔, and apart from that homekit2mqtt seems to be abandoned...

**Comment by adriancable** [comment]
Interesting to think about for the future. Closing for now since outside the scope of the homebridge-nest plug-in for the moment.

**Comment by iondarie** [comment]
Hello,

Thank you for your wonderful plugin!

Is there any way that i can publish only the current temperature to a MQTT topic?

Please give me a hint of witch file i could modify to achieve this.

Thank you,
