### ISSUE TITLE
HomeAway.Disable is not working

### ISSUE THREAD

**Issue by Km81** [chrisjshull/homebridge-nest#113]
After updating and rewirting Configuration ( disable -> option ),
Thermostat.Eco.Disable is working, however HomeAway.Disable is not working in option.
please check it.

**Comment by adriancable** [comment]
You are probably using the release from npmjs (3.1.1) but following the instructions from Github.

npmjs always has the latest released version. Github usually has additional commits which are not released yet. In this case, the Github release (which will become 3.2.0 in a few days) moved the home/away switch to a separate accessory, and the syntax for disabling it has changed.

I have checked and it does work. Please check that you are following the instructions in the README matching where you got your plug-in from. If npmjs, then follow the instructions on npmjs for disabling the home/away switch.

**Comment by Nastras** [comment]
Hello, I have the same problem myself, unfortunately I can't do anything with your answer.

I installed the last plugin version via GitHub and created this entry in the config. Unfortunately the home/away switch is still displayed in HomeKit.

"options": ["HomeAway.Disable"]

I hope you can help me. Thanks a lot!

**Comment by adriancable** [comment]
Please post your config.json here (removing your passwords of course) and I'll take a look.

**Comment by Nastras** [comment]
Hey thanks for there very fast answer!!!

Here is my config.json

`{
"bridge": {
"name": "homebridge-nest",
"username": "",
"port": ,
"pin": "",
"manufacturer": "",
"model": ""
},

"plugins": [
"homebridge-nest"
],

"accessories": [
],

"platforms": [
{ 
"platform": "Nest",
"googleAuth": {
	
"issueToken": "",

"cookies": "",

"apiKey": "",

"options": ["HomeAway.Disable"]
}
}
]
}`

**Comment by Nastras** [comment]
Here is an excerpt from the log:
<img width="1053" alt="Bildschirmfoto 2019-12-14 um 06 46 10" src="https://user-images.githubusercontent.com/27686185/70844185-a0553b00-1e3d-11ea-9bdd-aafb0b7294fd.png">

**Comment by Nastras** [comment]
@adriancable 

Hello again,

I have now talked to some people in the German HomeKit Forum who also use your plugin. They still have a nest ID and the presence switch can be deactivated via the config.

Can it be related to the fact that I use google as login that it doesn't work?

I also tried export the string 
"Options: ["HomeAway.Disable"]

from the google section. Unfortunately the doesn't work anymore.

{
    "bridge": {
        "name": "homebridge-nest",
        "username": "",
        "port": ,
        "pin": "",
        "manufacturer": "@",
        "model": ""
    },

    "plugins": [
        "homebridge-nest"
    ],

    "accessories": [],

    "platforms": [{
            "platform": "Nest",
            "googleAuth": {

                "issueToken": "",

                "cookies": "",

                "apiKey": ""
            }
        },
        {
            "options": ["HomeAway.Disable"]
        }
    ]
}

<img width="1053" alt="Bildschirmfoto 2019-12-14 um 14 10 47" src="https://user-images.githubusercontent.com/27686185/70849326-39f00d00-1e7d-11ea-9f65-3a45b2b4673a.png">
n the whole Homebridge 

If you could give me a tip I would be very grateful.

Thank you!

**Comment by Nastras** [comment]
Hello and me again, I just wanted to report that the problem is solved.

It was a config error. The plugin only read the new config after I cleared the cache.

Would be a great thing if you could add an example config to the plugin.

Here is my current config that works:

{
 "bridge": {
 "name": "homebridge-nest",
 "username": "",
 "port": "",
 "pin": "",
 "manufacturer": "@",
 "model": ""
 },
 "plugins": [
 "homebridge-nest"
 ],
 "accessories": [],
 "platforms": [{
 "platform": "Nest",
 "googleAuth": {
 "issueToken": "",
 "cookies": "",
 "apiKey": ""
 },
 "options": ["HomeAway.Disable"]
 }
]
}

Thanks a lot for the cool plugin!
