### ISSUE TITLE
No temperature for sensors in ios 13 beta’s

### ISSUE THREAD

**Issue by ludgats** [chrisjshull/homebridge-nest#116]
It’s still a little early but the iOS 13 beta does not show the temperature sensors temperature. 
![FE8A9CF1-CFBD-4341-A561-B90EA62FBC09](https://user-images.githubusercontent.com/51978367/62094508-69dea100-b24b-11e9-9969-830ba4727d50.jpeg)

**Comment by adriancable** [comment]
Which iOS 13 beta are you using? I've tested on iOS 13 beta 3, and the temperatures show up OK.

**Comment by ludgats** [comment]
I’m on the developer beta 5. Just released on July 29, 2019.

**Comment by adriancable** [comment]
I have iOS 13 beta 3 on one device, which is the latest public beta. The temperature sensor read-outs show up OK, so I suspect it is a new issue with iOS.

If you press the tile of one of your temperature sensors (e.g. Bedroom), do you then see the temperature read-out in the panel that pops up?

**Comment by ludgats** [comment]
Yes I can see the temperature in the readout.

**Comment by adriancable** [comment]
I can reproduce this on the latest iOS 13 beta (but not on the one before). I am pretty sure it's a bug in the latest beta. I also note the icons in the latest iOS 13 beta are sometimes wrong, e.g. the smoke detector sometimes shows the correct item, but sometimes shows a 'weather sensor' icon instead.

**Comment by adriancable** [comment]
@ludgats - is this still an issue in the latest iOS 13 developer beta?

**Comment by Thomas034** [comment]
Hi Adrian, little problem on my HOME. The temperature sensor dont show correct temperature, all other switch (on, off, away, temp regolation) works fine. I'm on iOS 13.1 beta. Anyone have same problem?

**Comment by adriancable** [comment]
Can you send me a screenshot, along with what the real temperature is? Thanks!

**Comment by Thomas034** [comment]
Hi Adrian, this is my sceenshot of my Home App, Nest App and Google Home App.
Home app and Nest app show temp -0,5C°. Google home app correct temp.
![IMG_0341](https://user-images.githubusercontent.com/54308077/64152411-dc373800-ce2c-11e9-9a1d-7e72853997a6.PNG)
![IMG_0342](https://user-images.githubusercontent.com/54308077/64152419-dfcabf00-ce2c-11e9-8754-0b2380221d18.PNG)
![IMG_0343](https://user-images.githubusercontent.com/54308077/64152427-e22d1900-ce2c-11e9-973a-cbd3700683b2.PNG)

**Comment by adriancable** [comment]
@Thomas034 - this may be a silly question, but how do you know that the Nest app and Apple Home are wrong, and Google Home is correct, and not the other way around?

**Comment by Thomas034** [comment]
Hi,
i see directly on thermostat the correct temperature.

**Comment by muzzymate** [comment]
> @ludgats - is this still an issue in the latest iOS 13 developer beta?

I believe this has been resolved with the latest iOS13 developer betas. It affected my SimpliSafe temperature sensors too. The Nest and the SimpliSafe temperature sensors now report their temperature on the tile again.

**Comment by Thomas034** [comment]
@muzzymate you dont see any temperature or you see wrong temperature? I see allways -0,5C° on my app Home and on app Nest.

**Comment by muzzymate** [comment]
I am referring to @ludgats reported issue. The latest version of iOS13 betas resolved the missing temperature display that was reported on July 29.
