### ISSUE TITLE
the temperature does not take into account the half degrees

### ISSUE THREAD

**Issue by djrams10** [chrisjshull/homebridge-nest#119]
Hello, I have a bug it seems to me. Since the last update, the temperature does not take into account the half degrees. When I was at 25.5 on the nest in the Home application I was at 26, shortly after, the temperature dropped to 24.5, and the temperature in the home application went to 25. Is this normal? Thank you.

I'm going from version 3.1.1 to 3.2.2 directly

**Comment by adriancable** [comment]
@djrams10 - I think there is a typo in the code. Can you try editing lib/nest-thermostat-accessory.js and change line 266 from:

    if (!this.usesFahrenheit) {

To:

    if (!this.usesFahrenheit()) {

Let me know if this fixes the problem for you.

**Comment by ikura** [comment]
> @djrams10 - I think there is a typo in the code. Can you try editing lib/nest-thermostat-accessory.js and change line 266 from:
> 
> ```
> if (!this.usesFahrenheit) {
> ```
> 
> To:
> 
> ```
> if (!this.usesFahrenheit()) {
> ```
> 
> Let me know if this fixes the problem for you.

That fixed the discrepancy I was seeing, and now my °C measurements and settings align with what the Nest app shows.  However there still seems to be an underlying bug as I can't set the temperature to 0.5°C increments, it quantizes the values, even making the jumps as far as 1.5ºC between for example 22.5 and 24ºC.

**Comment by adriancable** [comment]
Are you using an iOS 13 beta? In my tests with degrees C, it adjusts fine on iOS 12 but on iOS 13 beta I get the same issue you are setting. The temperature step property in the service is being set correctly, so I think it is an iOS 13 beta bug.

**Comment by djrams10** [comment]
> That fixed the discrepancy I was seeing, and now my °C measurements and settings align with what the Nest app shows. However there still seems to be an underlying bug as I can't set the temperature to 0.5°C increments, it quantizes the values, even making the jumps as far as 1.5ºC between for example 22.5 and 24ºC.

I am on ios 12.4 and I have no problem to relieve the thermostat to 20.5 for example.

**Comment by djrams10** [comment]
> @djrams10 - I think there is a typo in the code. Can you try editing lib/nest-thermostat-accessory.js and change line 266 from:
> 
> ```
> if (!this.usesFahrenheit) {
> ```
> 
> To:
> 
> ```
> if (!this.usesFahrenheit()) {
> ```
> 
> Let me know if this fixes the problem for you.

I change this part of the code, I come back to you to confirm if all works well.

**Comment by ikura** [comment]
> Are you using an iOS 13 beta? In my tests with degrees C, it adjusts fine on iOS 12 but on iOS 13 beta I get the same issue you are setting. The temperature step property in the service is being set correctly, so I think it is an iOS 13 beta bug.

Ah yes, that seems to be the source - it works fine on my Mojave Mac but iOS13 has the 'lumpy' settings.  Oddly Catalina is also exhibiting the issue.  It only seems to affect Celsius and not Fahrenheit.

**Comment by mrjackyliang** [comment]
Not sure if this relates to my problem, but when I set both my thermostat(s) to 85°F in ECO mode, my phone shows 29°C and another one shows 29.5°C

**Comment by mrjackyliang** [comment]
Seems like the recent update fixed it!

**Comment by adriancable** [comment]
@mrjackyliang - great to hear! Closing for now.

**Comment by djrams10** [comment]
Everything works well.  thank you for your work
