### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by chrisjshull** [chrisjshull/homebridge-nest#12]
_From @kfulgham on February 26, 2018 21:57_

Ok, I'm probably really dumb, but it took me forever to diagnose why I couldn't get authenticated on Nest. 

Turns out that this part of the instructions:
```

"platforms": [
   	{
   		"platform": "Nest",
   		
   		**"token" : "token will be generated upon first run of homebridge without a token",**
   		
   		"clientId": "developer Product ID",
   		"clientSecret": "developer Product Secret.",
   		"code": "your Pincode from Nest",
   		
   		"username" : "username",
   		"password" : "password"
   	}
   ],
```

I took completely literally, and kept the text in the token field. If anyone is as dumb as me, perhaps this can be made clearer for them.

_Copied from original issue: KraigM/homebridge-nest#173_

**Comment by adriancable** [comment]
Out of date now.
