### ISSUE TITLE
Fan is now a Switch after the 3.2.2 update from 3.1

### ISSUE THREAD

**Issue by sachangregory** [chrisjshull/homebridge-nest#123]
I'm on the Latest Version/s of Raspbian Buster, Homebridge, iOS 13, iPadOS 13, tvOS 13 and the Plugins

**Comment by adriancable** [comment]
Latest beta of iOS 13 has broken the icons. (wrong icons are displayed for some accessories)

I think this is what happened, rather than anything changed between 3.1 and 3.2.2.

**Comment by sachangregory** [comment]
The fan icon used to be a button at the bottom but is now a switch

**Comment by adriancable** [comment]
Closing for now - this is an iOS 13 "issue" which will probably get resolved before release.
