### ISSUE TITLE
Separate occupancy sensors for multiple nest thermostats

### ISSUE THREAD

**Issue by zburkhardt-zz** [chrisjshull/homebridge-nest#129]
First of all, thank you for the work you have put into this plugin. I recently integrated it and it has been working great!

I was wondering if this might be possible though. I have two nest thermostats and I have been playing around with the Home/Away indicator as an occupancy sensor. I am not sure if this would even be possible, but is there a way to have two separate occupancy sensors (one for each of my thermostats)? It would be awesome to have location specific notifications of motion detected, e.g. motion detected upstairs, or motion detected in the living room, based on where each of my nest thermostats is located.

Thanks again,

**Comment by adriancable** [comment]
I agree that would be great! Unfortunately that is not how the Nest service works. While the thermostats do have a built-in motion sensor it isn't directly accessible. Instead, the Nest service combines data from all the thermostats and smoke sensors to produce just one "global" occupancy state for each structure, and this is what the API gives you.

As a result, the plug-in only produces one Home/Away indicator per structure, to match this "global" occupancy status.

**Comment by zburkhardt-zz** [comment]
Got it, that's what I was figuring. Thanks for the reply!

**Comment by rbpasker** [comment]
This makes me wonder what "room" the occupancy sensor should go in
