### ISSUE TITLE
Issue setting ECO to OFF

### ISSUE THREAD

**Issue by robertdoleson** [chrisjshull/homebridge-nest#13]
While running in single or dual mode, I get no response from ECO when trying to turn ECO "off" via the home app. The same is true for Occupancy.
I am, however, able to reliably turn ECO "on" if I set it off from the nest app.

I'm running v2.0.

**Comment by chrisjshull** [comment]
weird. can you:
1. shut down homebridge
1. launch homebridge in debug mode: `DEBUG=* homebridge -D`
1. attach the log once homebridge is up and running.

**Comment by robertdoleson** [comment]
Here is what I believe are the relevant firebase errors:

Mar 03 14:02:25 raspberrypi homebridge[841]: Sat, 03 Mar 2018 19:02:25 GMT Accessory [Homebridge] Setting Characteristic "On" to value 0
Mar 03 14:02:25 raspberrypi homebridge[841]: [2018-3-3 14:02:25] [Nest] Setting Eco Mode for Upstairs Thermostat to: undefined
Mar 03 14:02:25 raspberrypi homebridge[841]: Sat, 03 Mar 2018 19:02:25 GMT Accessory [Homebridge] Error setting Characteristic "On" to value 0:  Firebase.set failed: First argument contains undefined in property 'devices.thermostats.Vrh4W9VMOqRw6-jy97SmxdxkMSGHAikx.hvac_mode'
Mar 03 14:02:25 raspberrypi homebridge[841]: Sat, 03 Mar 2018 19:02:25 GMT EventedHTTPServer [::ffff:192.168.1.23] HTTP Response is finished
Mar 03 14:02:29 raspberrypi homebridge[841]: Sat, 03 Mar 2018 19:02:29 GMT EventedHTTPServer [::ffff:192.168.1.23] HTTP request: /characteristics
Mar 03 14:02:29 raspberrypi homebridge[841]: Sat, 03 Mar 2018 19:02:29 GMT HAPServer [CC:22:3D:E3:CE:19] HAP Request: PUT /characteristics
Mar 03 14:02:29 raspberrypi homebridge[841]: Sat, 03 Mar 2018 19:02:29 GMT Accessory [Homebridge] Processing characteristic set: [{"aid":4,"iid":41,"value":0}]
Mar 03 14:02:29 raspberrypi homebridge[841]: Sat, 03 Mar 2018 19:02:29 GMT Accessory [Homebridge] Setting Characteristic "On" to value 0
Mar 03 14:02:29 raspberrypi homebridge[841]: [2018-3-3 14:02:29] [Nest] Setting Eco Mode for Upstairs Thermostat to: undefined
Mar 03 14:02:29 raspberrypi homebridge[841]: Sat, 03 Mar 2018 19:02:29 GMT Accessory [Homebridge] Error setting Characteristic "On" to value 0:  Firebase.set failed: First argument contains undefined in property 'devices.thermostats.Vrh4W9VMOqRw6-jy97SmxdxkMSGHAikx.hvac_mode'
Mar 03 14:02:29 raspberrypi homebridge[841]: Sat, 03 Mar 2018 19:02:29 GMT EventedHTTPServer [::ffff:192.168.1.23] HTTP Response is finished
Mar 03 14:02:32 raspberrypi homebridge[841]: Sat, 03 Mar 2018 19:02:32 GMT EventedHTTPServer [::ffff:192.168.1.23] HTTP request: /characteristics
Mar 03 14:02:32 raspberrypi homebridge[841]: Sat, 03 Mar 2018 19:02:32 GMT HAPServer [CC:22:3D:E3:CE:19] HAP Request: PUT /characteristics
Mar 03 14:02:32 raspberrypi homebridge[841]: Sat, 03 Mar 2018 19:02:32 GMT Accessory [Homebridge] Processing characteristic set: [{"aid":4,"iid":41,"value":0}]
Mar 03 14:02:32 raspberrypi homebridge[841]: Sat, 03 Mar 2018 19:02:32 GMT Accessory [Homebridge] Setting Characteristic "On" to value 0
Mar 03 14:02:32 raspberrypi homebridge[841]: [2018-3-3 14:02:32] [Nest] Setting Eco Mode for Upstairs Thermostat to: undefined
Mar 03 14:02:32 raspberrypi homebridge[841]: Sat, 03 Mar 2018 19:02:32 GMT Accessory [Homebridge] Error setting Characteristic "On" to value 0:  Firebase.set failed: First argument contains undefined in property 'devices.thermostats.Vrh4W9VMOqRw6-jy97SmxdxkMSGHAikx.hvac_mode'
Mar 03 14:02:32 raspberrypi homebridge[841]: Sat, 03 Mar 2018 19:02:32 GMT EventedHTTPServer [::ffff:192.168.1.23] HTTP Response is finished

**Comment by chrisjshull** [comment]
@robertdoleson, thanks, but that didn't capture what I was looking for. Please upload the full log from debug mode.

**Comment by robertdoleson** [comment]
[log.txt](https://github.com/chrisjshull/homebridge-nest/files/1800811/log.txt)

**Comment by chrisjshull** [comment]
Hmm. Are you sure you’re running in debug mode?

**Comment by robertdoleson** [comment]
As far as I can tell. I'm launching it using systemd on a raspberry pi, so figuring out where to declare the "DEBUG=* homebridge -D" is a bit tricky. I'll keep trying.

**Comment by robertdoleson** [comment]
Looks like it was a permissions issue on the Nest developer side of things.

**Comment by cjsfj** [comment]
@robertdoleson Can you clarify the resolution to the permissions issue? I'm having this problem on 2.1.3 and can't find any API preferences regarding this mode.
