### ISSUE TITLE
syntax in config.json for several options

### ISSUE THREAD

**Issue by djrams10** [chrisjshull/homebridge-nest#130]
hello, can you explain me the syntax in config.json for several options? Thank you

**Comment by adriancable** [comment]
"option": [ "Option1", "Option2", "Option3" ],

**Comment by djrams10** [comment]
<img width="623" alt="Capture d’écran 2019-08-09 à 21 15 14" src="https://user-images.githubusercontent.com/28505910/62803524-f65e4e80-baea-11e9-8b85-ad7af751fbb0.png">

it does not work

**Comment by adriancable** [comment]
No, replace Option1 and Option2 in my example with the options, in your case HomeAway.Disable and Thermostat.SeparateBuiltInHumiditySensor.Enable.

**Comment by djrams10** [comment]
Great, thanks!!
