### ISSUE TITLE
Remote Sensors Temperature Not Honoring Units Type.

### ISSUE THREAD

**Issue by hjdhjd** [chrisjshull/homebridge-nest#131]
A minor issue, mostly cosmetic...homebridge-nest logs the temperature for remote sensors in Celsius and ignores temperature_scale. My suggestion:

Either log temperature from remote sensors with both units, similar to what's done with thermostats

-or-

Logging should only be done using temperature_scale units as it is what most people would expect / prefer. This one would be my preference...it's cleaner, IMO.

**Comment by adriancable** [comment]
Great suggestion. Will fix for the next release. I'll make it log both deg C and deg F.

**Comment by adriancable** [comment]
Fixed in 3.3.0.
