### ISSUE TITLE
Homebridge nest generating error

### ISSUE THREAD

**Issue by richardcfirth** [chrisjshull/homebridge-nest#134]
**Describe the bug**
After correctly installing and configuring the plugin and json, Homebridge gets an error 'unable to connect to nest authentication, trying again in ten seconds'

**Expected behavior**
should log in correctly

Include with your bug report this version info:
```sh
node --version
homebridge --version
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

**Comment by adriancable** [comment]
@richardcfirth - please email me (adrian.cable@gmail.com) with your config.json file (please redact your password) and the full output from Homebridge when you have run it in debug mode: homebridge -D

Thank you!
