### ISSUE TITLE
Weirdness with automation setting temperature

### ISSUE THREAD

**Issue by jpetticrew** [chrisjshull/homebridge-nest#135]
<img width="830" alt="Screen Shot 2019-08-10 at 9 01 49 PM" src="https://user-images.githubusercontent.com/5076536/62843345-d52e6700-bc7e-11e9-9096-adeaf7972988.png">

**Describe the bug**
I have an automation that sets the temperature to 72 daily at sunset, but it is being set to eco temps at the same time as it is being set to the target temperature. It is hit or miss whether it gets set to the target temp (72) or 78 (My eco temp).

**To Reproduce**
1. Automation set to change temp to 72 at sunset daily.
2. Logs say the temp is being changed to the eco temps and the target temp simultaneously.

**Expected behavior**
Just change the temp to the target temperature.

Include with your bug report this version info:
```sh
node.js v10.16.2
homebridge v0.4.50
```

**Comment by adriancable** [comment]
@jpetticrew - I can reproduce this. HomeKit should not be sending cooling/heating threshold temperature change requests when the thermostat is not in heat-cool mode - yet it does. Next version of the plug-in will include a workaround. Watch this space.

**Comment by adriancable** [comment]
Should be fixed in 3.3.0. Give it a try and let me know how you get on.

**Comment by jpetticrew** [comment]
@adriancable Thank you so much for the quick work! I just updated to 3.3.1 and while it is still sending the heat-cool mode commands it is working as it should, so whatever you did worked.

**Comment by adriancable** [comment]
That's great. It seems that the Nest gets confused if you try to change temperatures at the same time as changing modes. The plug-in groups requests that are issued close together into one, to avoid spamming the Nest API. This normally works great but not when temperature changes are preceded immediately by mode changes, which happens in automations. So now, mode changes are instant (no delay) whereas temperature changes go through the normal 2-second debounce/merge process. Seems to work!

Automations in iOS 13 are still broken, but nothing I can do about that. I have filed a ticket with Apple.
