### ISSUE TITLE
Changed my Nest password and now nothing works

### ISSUE THREAD

**Issue by jpetticrew** [chrisjshull/homebridge-nest#139]
**Describe the bug**
I got an email from Google this evening that said I needed to change my password, so I did, and after I changed it in the config.json file, I keep getting `[Nest] Could not authenticate with Nest (code 406). Retrying in 15 second(s).` It is also causing Homebridge to not run.

**To Reproduce**
1. Changed password at nest.com and I have updated it in config.json

**Expected behavior**

Include with your bug report this version info:
```sh
node --version 10.16.2
homebridge --version 0.4.50
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

**Comment by adriancable** [comment]
The 406 error is an issue on the Nest CDN side. Very often after a few retries it will connect fine. You also see 406 errors on the Nest web app - it isn't specific to Homebridge.

**Comment by jpetticrew** [comment]
I'm really not sure what is going on... If I uninstall the Nest plugin, Homebridge works fine, but if I have it installed, Homebridge will not run. I guess if it's a Nest CDN error, I'll give it until morning to work itself out.

**Comment by adriancable** [comment]
Jeremy - leave Homebridge running after you get the 406. The Nest plug-in will retry every 15 seconds until it gets through. You should find after a minute or so and a few tries, it'll connect to the service and all will be OK. Let me know how you get on.

**Comment by jpetticrew** [comment]
It has been trying to connect every fifteen seconds for about four hours now. Always the same 406 error.

**Comment by adriancable** [comment]
I'll add in the next release an option to set the maximum number of retries before it gives up, so if this kind of thing happens Homebridge won't just get stuck. Hope to get this out tomorrow.

I have seen a string of 406 errors before but right now the service is working OK for me.

**Comment by jpetticrew** [comment]
It’s very strange... I got an email from Google forcing me to change my password, like they signed me out of the Nest app and I couldn’t sign back in. Ever since I got that email no matter how many times I reset my password or reboot my server, it will not connect. Anyway, thanks for checking it out. Hopefully it will be working in the morning. Maybe my Nest account just got borked or something.
