### ISSUE TITLE
Add Nest from Field Test account

### ISSUE THREAD

**Issue by stratocaster21** [chrisjshull/homebridge-nest#14]
Would it be possible to add a Thermostat that is associated with a Nest Field Test account? I currently have my three Nest devices associated with that account and would like to still use them with homebridge.

**Comment by chrisjshull** [comment]
I’m not familiar with what this is (and a quick googling wasn’t too helpful). Can you explain what that is and how it breaks the homebridge-nest plugin today?

**Comment by stratocaster21** [comment]
It is Nest's beta testing app/site. It is pretty much the exact same as the normal Nest accounts just that once in a while a new feature will be added. As far as I can tell, things go through home.ft.nest.com instead of the normal Nest and those accounts will not work for using Nest.com

**Comment by chrisjshull** [comment]
hmm. looking at https://github.com/KraigM/homebridge-nest/issues/39, it seems there is insufficient public info about this to proceed :(.

**Comment by chrisjshull** [comment]
Closing until such time as the endpoint for Field Test accounts is known.
