### ISSUE TITLE
Note: 429/406 errors following Nest's password data breach

### ISSUE THREAD

**Issue by adriancable** [chrisjshull/homebridge-nest#140]
Many of you got emails from Nest yesterday saying your password had been reset due to a data breach of credentials at Nest. (At the same time, existing active access tokens were also revoked.)

homebridge-nest never anticipated this scenario and the result was the plug-in clobbered the Nest service, which then blocked access for up to 24 hours (issuing 429/406 responses). I'm really sorry if you were affected by this.

The latest release, 3.3.4, has significantly improved error handling which should prevent this happening again if something unexpected happens on the Nest end. In the mean time, if you continue to get 429/406 errors please wait 24 hours and then all should be OK again. (For me, things took less than 24 hours to resolve.)

**Comment by jpetticrew** [comment]
Should we remove the plugin so it stops trying to log into Nest?

**Comment by adriancable** [comment]
@jpetticrew - I would first update homebridge-nest to 3.3.4, and if see if you can log in OK.

If not, just edit config.json and change your password to blank (i.e. set "password": "") which will prevent homebridge-nest from trying to log in (essentially disabling it) but leaving the rest of Homebridge running.

Then after say 24 hours you can put your password back into config.json and hopefully all will be fine. Let me know how you get on.

**Comment by adriancable** [comment]
Closing for now since the Nest service is back to normal.
