### ISSUE TITLE
generateNestToken.sh Python Error

### ISSUE THREAD

**Issue by ChrisChiera** [chrisjshull/homebridge-nest#142]
**Describe the bug**
Tried running "generateNestToken.sh". Gave an error, about Python3, looks like that is required to run the script, but oddly no mention of needing to install it on the installation page here. Installed Homebrew, then installed Python. Ran the script again but now shows the following errors: Thoughts?

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Also the instructions mention you most certainly won't need the script, however, I assume (and certainly hope) most are using 2FA, and imagine large majority run on a NAS rather than an relying a computer always to be up and running, so would seem like a quite common use case which requires this script, unless I'm missing something? Will keep Googling in the mean time and report back if I find anything. On Mojave, all software up-to-date.

**Comment by ChrisChiera** [comment]
Update: Looks like another repo has a much easier solution that doesn't involve scripts or having to install python or anything. Rather just running two terminal commands, which I was able to just do successfully. So for others with the same issue in this common use case would recommend checking: https://github.com/KhaosT/homebridge-nest-cam.

**Comment by adriancable** [comment]
Unfortunately I'm not a Python expert (I didn't write the script) - but good guidance re. the instructions on the homebridge-nest-cam page for those that would find this useful.

The problem with the access token mode is that (as per the README) the access tokens eventually expire, which is not good if you have a NAS which is always up and running. My recommendation is that you use Nest's Family Sharing feature to create a "mirror" account without 2FA enabled, which you use with homebridge-nest. If you use a "burner address" for this account, and it does get hacked, then I think no biggie.

**Comment by ChrisChiera** [comment]
You may want to test the script yourself to confirm if it is no longer working on the latest stable version of macOS, in which case I assume you will want to remove that script or note that it no longer works.

I read the note about the family sharing feature but disregarded it, as other than bank accounts, the video/audio cameras throughout ones house is the single most thing one would never want hacked and would always want 2 factor enabled on. Having that account hacked would be quite a "biggie" vs the minor inconvenience of having to simply paste in a new token every once in a blue moon, but that is my opinion. Will close this out, as have the issue resolved using the other GitHub. Have a great weekend.

**Comment by adriancable** [comment]
@ChrisChiera - I've rewritten the script so it doesn't need Python, just bash. Please give the latest commit on Github (not yet on npmjs) a shot. Thanks!
