### ISSUE TITLE
errore after joined Nest and google account

### ISSUE THREAD

**Issue by GPL71** [chrisjshull/homebridge-nest#143]
Hello and thank you so much for this great work 
After update to last release and joined accounts (nest+google) I'm having issues.
Below a screenshot of error.
Obviously config.json is update for google account

![Schermata 2019-08-24 alle 18 55 17](https://user-images.githubusercontent.com/34108470/63640500-60f1bb80-c6a1-11e9-92a5-dc5618836acc.png)

**Comment by adriancable** [comment]
@GPL71 - please can you add "Debug.Verbose" to "options" if your config.json, and then run: homebridge -D

Then send me the homebridge log when this happens, to adrian.cable@gmail.com. Also send me your config.json.

Thanks!

-Adrian

**Comment by GPL71** [comment]
> @GPL71 - please can you add "Debug.Verbose" to "options" if your config.json, and then run: homebridge -D
> 
> Then send me the homebridge log when this happens, to [adrian.cable@gmail.com](mailto:adrian.cable@gmail.com). Also send me your config.json.
> 
> Thanks!
> 
> -Adrian

sorry I'd forget ....

Node.js Version: 9.11.2
NPM Version: 5.8.0
Homebridge Version: 4.5.0
Homebridge Config UI X Version: 4.6.1

Now I have this error too
![Schermata 2019-08-25 alle 16 03 33](https://user-images.githubusercontent.com/34108470/63651120-f056a780-c751-11e9-8cc0-034e73d3bb16.png)

**Comment by adriancable** [comment]
@GPL71 - EAI_AGAIN is a DNS resolution error, and isn't to do with homebridge-nest or even homebridge for that matter. Check your NAS settings (if you are using a NAS), and your Internet connection stability.

**Comment by GPL71** [comment]
Thank you ... problem seem solved ... I think it was a provider fail ...
Now I have the follow error.
Can you help me please?
Thank you

![Schermata 2019-08-26 alle 21 14 07](https://user-images.githubusercontent.com/34108470/63716629-b61b0200-c846-11e9-9f74-36ed8f004fcd.png)

**Comment by GPL71** [comment]
wooooowww! then all is solved now!! Thank you very much
