### ISSUE TITLE
My thermostat does not appear when I run the plug-in

### ISSUE THREAD

**Issue by tbrune0362** [chrisjshull/homebridge-nest#148]
Hi Adrian,

I have followed and double checked all steps provided (updated config.json) for a Google account but still cannot find my thermostat. Can you help me? I have spent several hours a day for the last week trying to get this to work. Thank you.

**Comment by Thomas034** [comment]
Posto your config please

**Comment by adriancable** [comment]
First, check that the Thermostat is visible if you log into your Google Account with the Nest app. If not, then you have another problem.

If you do see the Thermostat, please send me your config.json, and also the output of: homebridge -D

You can email them to adrian.cable@gmail.com. Thanks!

**Comment by tbrune0362** [comment]
The thermostat is visible in the Nest app. Followed up with a direct email.

**Comment by d1g1talweb** [comment]
I have the same issue, plugin installed, config file updated, i can see homebridge reaching out to nest and finding my devices upon restart. I just cant seem to see or add any nest accessories inside of Homekit...

**Comment by HammerAce42** [comment]
I recently added a second Thermostat to my Nest account (haven't migrated to a Google account yet) and the new Thermostat does not show up despite restarting homebridge several times. The old devices still show up fine.

**Comment by adriancable** [comment]
@HammerAce42 - thanks for reaching out. Google is introducing a new API for Nest devices which it seems they are rolling out slowly. It looks like around 5%, or less, of thermostats in the field are connecting with the new API, and I am guessing that you are one of the (un)lucky ones.

The new API is completely different from the old API, and is based on Google protocol buffers rather than REST/JSON. It is rather hard to reverse-engineer but I have made some pretty good progress on doing so, and implementing the new API in homebridge-nest.

It isn't ready yet, but if you are interested in trying an early version to see if it works for you, and help me locate and resolve any issues before release, then please send me an email at adrian.cable@gmail.com and I'll get you going.

-Adrian

**Comment by mattiacantalu** [comment]
Hello @adriancable , here Mattia. Same issue for me; I've just merged (my bad) old Nest account to new Google one. All my Nest accessories doesn't work, event if I set up correctly the config.json with google data. I can reach you via email in order to test new test integration 😉

**Comment by adriancable** [comment]
@mattiacantalu - please send me an email at adrian.cable@gmail.com and I'll get you the new code.

**Comment by mattiacantalu** [comment]
@adriancable email sent!

**Comment by schramfamily** [comment]
Hey @adriancable!

Thank you so much for all the work you put into this. I had it up and running on a homebridge I setup on my Mac, just to play. Now, after migrating to a Google Account and changing the code accordingly, I get syntax errors. *no syntax errors with the old "Nest" account though...

Can I send you my config and have you look at it real quick? I'm sure I have something in there that shouldn't be.

**Comment by adriancable** [comment]
Sure, send over the config.

**Comment by schramfamily** [comment]
Thank you so much!

It is attached. I took out the Google Authentication information. If I need to send it to you with the information in it let me know.

-Aaron

**Comment by daveblademan** [comment]
Hey Adrian, just converted over from a Nest to Google sign-in...all was working great in the old set up.. Now getting the following error:

[Nest] Error: You did not specify {'token'} or {'clientId','clientSecret','code'}, one set of which is required for the new API

I was configuring for "googleAuth"...

Is this the same issue as those above ??

Cheers

**Comment by schramfamily** [comment]
I was getting a syntax error when saving the code replacement.

-Aaron

**Comment by adriancable** [comment]
@daveblademan - that message is from a very old version of the plug-in. Please update to the latest version, then you should be good.

@schramfamily - I don't understand the question. Can you elaborate? Thanks!

**Comment by daveblademan** [comment]
Thanks Adrian - thought I’d updated it all - will redo it - thanks.

**Comment by mattiacantalu** [comment]
@adriancable as I said via email the development branch you sent me works correctly on my freeNAS...

**Comment by bassrock** [comment]
I'm seeing the same issue, the nest shows up in the nest app but does not show up via homebridge nest. Even in the logs.

**Comment by iron8130** [comment]
Same issue here too.  I see my  1 Nest thermostat and my 4 Nest protects in the Nest app, but in Homekit, I see 4 Smoke/CO sensors and 1 "Home Occupied" switch. 
<img width="602" alt="Screen Shot 2019-10-20 at 9 27 31 PM" src="https://user-images.githubusercontent.com/56809641/67172341-91dc2d00-f380-11e9-8a90-f19ac59c1164.png">

**Comment by adriancable** [comment]
@iron8130 - send me an email at adrian.cable@gmail.com and I'll get you a test new version which should work for you.

**Comment by nflute** [comment]
I have the same problem after migrate to google account 
(Keep receiving non-stop emails from google "New Log-in to your Nest Account" and that force me to migrate google, wish I had read this first.) 

When are you planing to release fix for those who migrated to google account?

**Comment by adriancable** [comment]
See here: https://support.google.com/googlenest/thread/17510832?hl=en

Need to see how that plays out. Right now it's difficult to fix on our side if Nest sends an email each time you log on.

**Comment by nflute** [comment]
Now the thermostats are not showing in home app anymore.

**Comment by malizivko** [comment]
Question, if you migrated your account from Nest to Google, is it all Nest products that are not working or just Thermostat?

I just got homebridge installed and I am trying to get it to work but I dont see any of my Nest items (Thermostat, Nest Protect, Temperature sensors, Doorbell)

**Comment by dclowd9901** [comment]
Logs from `homebridge -D`

```
[11/29/2019, 2:51:00 PM] [Nest] Initializing Nest platform...
[11/29/2019, 2:51:00 PM] [Nest] Fetching Nest devices.
[11/29/2019, 2:51:00 PM] [Nest] Authenticating via Google.
[11/29/2019, 2:51:01 PM] Loading 0 accessories...
```

**Comment by dgileadi** [comment]
First-time setup here with Google authentication, and my newly purchased Nest Thermostat isn't showing up. From the logs:

```
[12/4/2019, 10:48:02 AM] Loaded plugin: homebridge-nest
[12/4/2019, 10:48:02 AM] Registering platform 'homebridge-nest.Nest'
[12/4/2019, 10:48:02 AM] ---
[12/4/2019, 10:48:02 AM] Loading 1 platforms...
[12/4/2019, 10:48:02 AM] [Nest] Initializing Nest platform...
[12/4/2019, 10:48:02 AM] [Nest] Fetching Nest devices.
[12/4/2019, 10:48:02 AM] Loading 0 accessories...
```

**Comment by joemulray** [comment]
what are the chances that newly purchased nest devices are pointing to the new api? I am worried that I might myself in the same situation as @dgileadi

**Comment by adriancable** [comment]
@joemulray - I believe that for thermostats, the chance of them being on the new API is currently about 5%. I am not aware of any Protects or cameras being on the new API yet.

**Comment by dclowd9901** [comment]
Is this just a matter of remapping the api? I may fork and do that for us unlucky ones.

**Comment by mintacca** [comment]
I think I’m in this unlucky new-api group also. If anyone develops a fix for this on another fork please let me know! 😊

**Comment by dclowd9901** [comment]
This is proving to be quite tricky. Google uses gRPC and protobufs to transact. I’m just trying to get initial device info that’s given to the home.nest.com site, and it’s quite difficult to find how that information is fed to the front end.

**Comment by joemulray** [comment]
same boat 😢 
```
[12/15/2019, 10:54:09 PM] [Nest] Initializing Nest platform...
[12/15/2019, 10:54:09 PM] [Nest] Fetching Nest devices.
[12/15/2019, 10:54:09 PM] [Nest] Authenticating via Google.
[12/15/2019, 10:54:09 PM] Loading 0 accessories..
```

**Comment by promiseofcake** [comment]
Question, so this does not work for newly added thermostats? I did a factory-reset of my old thermostat and seem to have lost access via the standard Nest API (non-Google Account). Or is the idea that it's still a roll of the dice if we move to a Google Account to re-gain access?

**Comment by JeremyKnudsen** [comment]
I'm trying to get two newly installed thermostats up and running on an account that was migrated from a Nest account to a Google account. Tried to do some debugging myself, and the `devices` property is just an empty array. Is this the expected result if I've been migrated to the new API? 

Let me know if there's anyway I can help debug or verify the new code. I'll go ahead and send an email to @adriancable to get access to the new code as well.

**Comment by dclowd9901** [comment]
I believe this is what happens if you’ve been migrated. I saw this result
as well.

You can try digging through the XHR calls on the home.nest.com page, but I
had no luck, and I checked basically every call. I _can_ see the call
makeup of, say, changing the thermostat temp. It transmits via base64
protobuf, but I can’t tell how the page gets its initial devices list.

**Comment by promiseofcake** [comment]
I think so @JeremyKnudsen, new devices (whether on Google account or Nest account) seem to be communicating over a different endpoint and protocol.

**Comment by joemulray** [comment]
Is there a fork of this repository, or another development branch we can be working on this, a new refactor of the api

**Comment by dclowd9901** [comment]
I’ll create a fork today

**Comment by dclowd9901** [comment]
https://github.com/dclowd9901/homebridge-nest

**Comment by adriancable** [comment]
No need to create a fork or recreate any work, implementation of the new API is already done (and yes it is complicated). I was waiting for Homebridge to update to HAP-NodeJS 0.5.x so I can support cameras, but in the mean time, you can all try it (without camera support).

Assuming you are using Homebridge on a Mac or Linux (otherwise adjust the paths):
 
- cd /usr/local/lib/node_modules/homebridge-nest
- wget https://sidewinder.starlinghome.io/beta/homebridge-nest-experimental24.tar.gz
- sudo tar xvfz homebridge-nest-experimental24.tar.gz
- sudo npm install

**Comment by JeremyKnudsen** [comment]
Wow. This is fantastic. Lovely little early Christmas present. I followed the instructions and both my thermostats and all three of my temp sensors showed up and seem to work great.

**Comment by dclowd9901** [comment]
Totally surprised and delighted. And I can’t wait to see the code to see
what the solution was. This has been driving me nuts!

**Comment by adriancable** [comment]
You're all welcome. Merry Christmas!

**Comment by mintacca** [comment]
Thank you!! Working perfectly again, Merry Christmas 😁

**Comment by Radstake** [comment]
- homebridge-nest-experimental24.tar.gz detects nest
- also send commands to nest
- after x time, command / status from Nest not showing in homebrigde
- I have e-nest with heatsink

Already greatly help by @adriancable, but does any one else has this issue?

**Comment by Radstake** [comment]
PS Some extra logging:
**Nest API call to subscribe to device settings updates returned an error: ENOTFOUND**

**Comment by adriancable** [comment]
@Radstake - ENOTFOUND is a DNS lookup error. Most likely cause is something is glitchy with your Internet connection (on your router, or on the device you are running homebridge).

**Comment by Radstake** [comment]
Thx, for your reaction. So what could be ‘glitchy’? Router and device are setup ok. Never had any DNS failures. Besides homebridge tons of external requests per hour, all error free. Could it be because it’s the setup with the heatsink? Deferent endpoint?

Hartelijke groet,

Erich Radstake

**Comment by adriancable** [comment]
@Radstake - I'm not sure - it could be a Nest issue. The Nest service was down in many parts of the world yesterday, and it seems people are continuing to have issues today:

https://downdetector.com/status/nest/

**Comment by Radstake** [comment]
Thx, I’ll have a look

Hartelijke groet,

Erich Radstake

**Comment by remko2000** [comment]
> First-time setup here with Google authentication, and my newly purchased Nest Thermostat isn't showing up. From the logs:
> 
> ```
> [12/4/2019, 10:48:02 AM] Loaded plugin: homebridge-nest
> [12/4/2019, 10:48:02 AM] Registering platform 'homebridge-nest.Nest'
> [12/4/2019, 10:48:02 AM] ---
> [12/4/2019, 10:48:02 AM] Loading 1 platforms...
> [12/4/2019, 10:48:02 AM] [Nest] Initializing Nest platform...
> [12/4/2019, 10:48:02 AM] [Nest] Fetching Nest devices.
> [12/4/2019, 10:48:02 AM] [Nest] Authenticating via Google.
> [12/4/2019, 10:48:02 AM] Loading 0 accessories...
> ```

Is there someone who can share his/heres json file? I'm struggling with the right structure of my json with the info of my my nest with googleAuth. I used to work with the old client ID, clienttoken, etc. but now I'm migrated to google I also want my nest to show up in my homebridge/homekit again on my raspberry. I've already the right info of my googleauth like issuetoken, cookies, api. but how do I process this in my Json. Where do I put:

"googleAuth": {
        "issueToken": "xxx",
        "cookies": "xxx",
        "apiKey": "xxxxx"

into my json?

**Comment by JeremyKnudsen** [comment]
Your log suggests you're authenticating just fine. I'm guessing it's the same issue I faced with the new API. Have you followed the suggestions in [this comment](https://github.com/chrisjshull/homebridge-nest/issues/148#issuecomment-568822426) above to test the fixes for the new API?

**Comment by remko2000** [comment]
I try but:
' https://sidewinder.starlinghome.io/beta/homebridge-nest-experimental24.tar.gz' leaves my an error on my raspberry (No such file or directory).

**Comment by changochulo** [comment]
> No need to create a fork or recreate any work, implementation of the new API is already done (and yes it is complicated). I was waiting for Homebridge to update to HAP-NodeJS 0.5.x so I can support cameras, but in the mean time, you can all try it (without camera support).
> 
> Assuming you are using Homebridge on a Mac or Linux (otherwise adjust the paths):
> 
> * cd /usr/local/lib/node_modules/homebridge-nest
> * wget https://sidewinder.starlinghome.io/beta/homebridge-nest-experimental24.tar.gz
> * sudo tar xvfz homebridge-nest-experimental24.tar.gz
> * sudo npm install

You rock. This fixed the issue for me. My nest thermostat is now showing up in Homekit. Thanks!

**Comment by reedickulus** [comment]
> No need to create a fork or recreate any work, implementation of the new API is already done (and yes it is complicated). I was waiting for Homebridge to update to HAP-NodeJS 0.5.x so I can support cameras, but in the mean time, you can all try it (without camera support).
> 
> Assuming you are using Homebridge on a Mac or Linux (otherwise adjust the paths):
> 
> * cd /usr/local/lib/node_modules/homebridge-nest
> * wget https://sidewinder.starlinghome.io/beta/homebridge-nest-experimental24.tar.gz
> * sudo tar xvfz homebridge-nest-experimental24.tar.gz
> * sudo npm install

Can you please provide guidance on how to do this if I am using HOOBS on Raspberry Pi? I tried following the guide for "manual plugin" install in HOOBS, but it did not work.

**Comment by apabari** [comment]
Hi @adriancable , thanks for this post.  I upgraded to a Gen3 Thermostat the other day, and was wracking my brain trying to figure out why it wasn't showing up on Homebridge anymore. Thanks again for this fix.

I noticed that my Nest Camera is now showing up too, but it says "No Response".  Is this to be expected, because this is still a test / experimental branch?

Thanks !

**Comment by adriancable** [comment]
Nest Camera support will need to wait for an update to Homebridge/HAP-NodeJS. You can read the details in the Homebridge issues list on Github if you’re interested.

**Comment by remko2000** [comment]
> > No need to create a fork or recreate any work, implementation of the new API is already done (and yes it is complicated). I was waiting for Homebridge to update to HAP-NodeJS 0.5.x so I can support cameras, but in the mean time, you can all try it (without camera support).
> > Assuming you are using Homebridge on a Mac or Linux (otherwise adjust the paths):
> > 
> > * cd /usr/local/lib/node_modules/homebridge-nest
> > * wget https://sidewinder.starlinghome.io/beta/homebridge-nest-experimental24.tar.gz
> > * sudo tar xvfz homebridge-nest-experimental24.tar.gz
> > * sudo npm install
> 
> You rock. This fixed the issue for me. My nest thermostat is now showing up in Homekit. Thanks!

I've deinstalled my old nestplugin 3.5 en installed this one on my raspberry (download the image on my mac, unzipped it it and filezilla'ed into the right folder into my raspberry and then installed it with: sudo npm install). I see in my homebridge GUI that the new nestplugin version 4.0 is installed so that's OK. My google migrated nest thermostat still not show up under devices. I think my config jsonfile is still not OK (I think my googleaccountinfo is correct). Can someone help me in the right direction with my JSON: This is it now:
{
    "bridge": {
        "name": "Homebridge",
        "username": "CB:22:3D:E2:CE:31",
        "port": 51826,
        "pin": "031-45-154"
    },
    "accessories": [],
    "googleAuth": {
        "issueToken": "xxxx",
        "cookies": "xxx",
        "apiKey": "xxxxx"
    },
    "platforms": [
        {
            "name": "Config",
            "port": 9898,
            "auth": "form",
            "theme": "teal",
            "restart": "sudo -n systemctl restart homebridge",
            "tempUnits": "c",
            "sudo": true,
            "log": {
                "method": "systemd"
            },
            "platform": "config"
        },
        {
            "platform": "eDomoticz",
            "name": "eDomoticz",
            "server": "127.0.0.1",
            "port": "8080",
            "ssl": false,
            "roomid": 2,
            "mqtt": true,
            "excludedDevices": []
        },
        {
            "platform": "Nest",
            "token": "no more in use",
            "clientId": "no more in use",
            "clientSecret": "no more in use",
            "code": "no more in use"
        }
    ]
}

**Comment by JeremyKnudsen** [comment]
> I try but:
> ' https://sidewinder.starlinghome.io/beta/homebridge-nest-experimental24.tar.gz' leaves my an error on my raspberry (No such file or directory).
> 
> Can someone help me with the right pads for install on a raspberry?

What error are you getting? The download link is still valid. Make sure you are running the proper command to download.

`wget https://sidewinder.starlinghome.io/beta/homebridge-nest-experimental24.tar.gz`

**Comment by reedickulus** [comment]
Can you please place the most recent update with the implementation of the new API in the Hoobs repository? Thank you so much.

**Comment by rtgoodwin** [comment]
This fixed it for me as well, and not on a Google account. (Curse you Gsuite!).

**Comment by reedickulus** [comment]
> Nest Camera support will need to wait for an update to Homebridge/HAP-NodeJS. You can read the details in the Homebridge issues list on Github if you’re interested. From: apabari <notifications@github.com> Reply to: chrisjshull/homebridge-nest <reply@reply.github.com> Date: Monday, December 30, 2019 at 9:33 PM To: chrisjshull/homebridge-nest <homebridge-nest@noreply.github.com> Cc: Adrian Cable <adrian.cable@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [chrisjshull/homebridge-nest] Thermostat not showing in HomeKit (Google Account) (#148) Hi @adriancable , thanks for this post. I upgraded to a Gen3 Thermostat the other day, and was wracking my brain trying to figure out why it wasn't showing up on Homebridge anymore. Thanks again for this fix. I noticed that my Nest Camera is now showing up too, but it says "No Response". Is this to be expected, because this is still a test / experimental branch? Thanks ! — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

 Can you run npm pack on the project and upload the .tgz file?

**Comment by apabari** [comment]
> I try but:
> ' https://sidewinder.starlinghome.io/beta/homebridge-nest-experimental24.tar.gz' leaves my an error on my raspberry (No such file or directory).
> 
> Can someone help me with the right pads for install on a raspberry?

try:
- `cd /usr/lib/node_modules/homebridge-nest'

Then, the other instructions

- wget https://sidewinder.starlinghome.io/beta/homebridge-nest-experimental24.tar.gz
- sudo tar xvfz homebridge-nest-experimental24.tar.gz
- sudo npm install

**Comment by tman15bp** [comment]
> No need to create a fork or recreate any work, implementation of the new API is already done (and yes it is complicated). I was waiting for Homebridge to update to HAP-NodeJS 0.5.x so I can support cameras, but in the mean time, you can all try it (without camera support).
> 
> Assuming you are using Homebridge on a Mac or Linux (otherwise adjust the paths):
> 
> * cd /usr/local/lib/node_modules/homebridge-nest
> * wget https://sidewinder.starlinghome.io/beta/homebridge-nest-experimental24.tar.gz
> * sudo tar xvfz homebridge-nest-experimental24.tar.gz
> * sudo npm install

Please can you explain how to install this in more detail as it is not working for me

**Comment by Tex2043** [comment]
> > No need to create a fork or recreate any work, implementation of the new API is already done (and yes it is complicated). I was waiting for Homebridge to update to HAP-NodeJS 0.5.x so I can support cameras, but in the mean time, you can all try it (without camera support).
> > Assuming you are using Homebridge on a Mac or Linux (otherwise adjust the paths):
> > 
> > * cd /usr/local/lib/node_modules/homebridge-nest
> > * wget https://sidewinder.starlinghome.io/beta/homebridge-nest-experimental24.tar.gz
> > * sudo tar xvfz homebridge-nest-experimental24.tar.gz
> > * sudo npm install
> 
> Please can you explain how to install this in more detail as it is not working for me I am on Mac

Make sure you have wget installed. I used 

`brew install wget`

then run the rest of the commands

**Comment by Tex2043** [comment]
@adriancable Thank you so much for posting the experimental update, greatly appreciated! Ditched my ecobee and got a Nest today after finding your plugin. Sooooo glad to be back on Nest, phew. 

You're a lifesaver!

**Comment by jamezpowell** [comment]
I have tried everything above and I still cannot get my Nest devices to show up. I am using a Nest account, not Google. I see int he logs on startup that it logs into Nest, queries for devices, and then says loading 0 devices. I have 2 cameras and a thermostat that show fine in my Nest app. I am also having an issue where restarting the hoobs service causes "[Nest] Auth failed: rate limit exceeded. Please try again in 60 minutes"

I don't have 2FA on. I used to be able to do this using the tokens and all from Nest, but I recently updated (completely reformatted and started over) everything with homebridge as I was running an old instance and wanted to go the hoobs route.

**Comment by adriancable** [comment]
See #195 - you will probably need to authenticate via access token, as shown in the README. Good luck!

**Comment by jamezpowell** [comment]
> See #195 - you will probably need to authenticate via access token, as shown in the README. Good luck!

Thank you for the help. I just decided to go ahead and migrate to Google since I found a workaround for my only IFTTT action that required WWN. It’s all up and running now with the google account.

**Comment by kjustie** [comment]
I have 2 Nest thermostats, 1 of which is no longer showing in Home app, though it does show in the Nest app and web site; it does not appear in Homebridge log when "fetching nest devices."  At the beginning of Jan. this thermostat was off the wall (wiring problem) long enough that its battery died and it had to be reconfigured from scratch and re-added to my Nest account like a new device.   Is that why it's not appearing in Home, and if so what do I need to do to get it back?  Or some other problem?    (This thermostat previously appeared in Home; the period it was offline was also a period when NO Nest devices were visible in Home. I just today switched to token authentication (still Nest account), which brought everything back EXCEPT this one thermostat.)   thanks

**Comment by AFN40** [comment]
Same here. Except my Nest that disappeared has not been recently reconfigured. Additionally, I've always used Google Authentication for access. The other Nest works perfectly fine.

**Comment by kjustie** [comment]
...worth mentioning that my Nest that does NOT work is an E, in contrast to AFN40's E that does work; my working Nest is not an E.   So E vs. not-an-E is not the issue, nor is recent reconfig, nor is authentication method since AFN40 is using Google and I'm using Nest (token).

**Comment by fletchto99** [comment]
Any chance the experimental version can be cut into a beta release on NPM? I use a docker container called [hombridge_gui](https://hub.docker.com/r/siwatinc/homebridge_gui_unraid/dockerfile) which re-installs the plugin from the NPM version when restarted causing this to get reset quite often. Thanks 🎉

**Comment by gamewin1** [comment]
@AFN40 @kjustie i'm in pretty much the same boat, my nest E stopped working a few weeks ago, it just disappeared from my home app. but a comment from earlier in this issue fixed my problem, quoted below

> No need to create a fork or recreate any work, implementation of the new API is already done (and yes it is complicated). I was waiting for Homebridge to update to HAP-NodeJS 0.5.x so I can support cameras, but in the mean time, you can all try it (without camera support).
> 
> Assuming you are using Homebridge on a Mac or Linux (otherwise adjust the paths):
> 
> * cd /usr/local/lib/node_modules/homebridge-nest
> * wget https://sidewinder.starlinghome.io/beta/homebridge-nest-experimental24.tar.gz
> * sudo tar xvfz homebridge-nest-experimental24.tar.gz
> * sudo npm install

I'm running on a RPi, so the only thing i had to change to make it work with my setup is the first command. i exclude /local from the path and run as root, as so:
`cd /usr/local/lib/node_modules/homebridge-nest`

and a few notes in case the extra troubleshooting info may be helpful to others or the devs, I have a Nest E (and no other nest products), i've been using the google auth token thing since shortly after it was first supported. it's worked for many months, one day a few months ago it deauthed, i believe i recall it spamming some message every minute or so in the log, and the accessory in the home app would show as not responding. after reauthing, it worked for a few more months until just recently when the accessory just disappeared completely and i started having the issue discussed here. the log didnt spam anything, and when the nest initialized, the log would only show "initializing nest platform" then "fetching nest devices" and move on to the other modules, not saying anything related to the nest anymore. i tried reauthing, updating, and readding the homebridge to home, all to no avail, until i did those quoted instructions, and now everything works fine again

**Comment by kjustie** [comment]
gamewin1 -- thank you!  The steps you outlined worked perfectly (except that I had to substitute "curl -O" for the wget command; running on Mac / High Sierra).  Nest E reappeared upon restart and is working normally now.

**Comment by remko2000** [comment]
> @AFN40 @kjustie i'm in pretty much the same boat, my nest E stopped working a few weeks ago, it just disappeared from my home app. but a comment from earlier in this issue fixed my problem, quoted below
> 
> > No need to create a fork or recreate any work, implementation of the new API is already done (and yes it is complicated). I was waiting for Homebridge to update to HAP-NodeJS 0.5.x so I can support cameras, but in the mean time, you can all try it (without camera support).
> > Assuming you are using Homebridge on a Mac or Linux (otherwise adjust the paths):
> > 
> > * cd /usr/local/lib/node_modules/homebridge-nest
> > * wget https://sidewinder.starlinghome.io/beta/homebridge-nest-experimental24.tar.gz
> > * sudo tar xvfz homebridge-nest-experimental24.tar.gz
> > * sudo npm install
> 
> I'm running on a RPi, so the only thing i had to change to make it work with my setup is the first command. i exclude /local from the path and run as root, as so:
> `cd /usr/local/lib/node_modules/homebridge-nest`
> 
> and a few notes in case the extra troubleshooting info may be helpful to others or the devs, I have a Nest E (and no other nest products), i've been using the google auth token thing since shortly after it was first supported. it's worked for many months, one day a few months ago it deauthed, i believe i recall it spamming some message every minute or so in the log, and the accessory in the home app would show as not responding. after reauthing, it worked for a few more months until just recently when the accessory just disappeared completely and i started having the issue discussed here. the log didnt spam anything, and when the nest initialized, the log would only show "initializing nest platform" then "fetching nest devices" and move on to the other modules, not saying anything related to the nest anymore. i tried reauthing, updating, and readding the homebridge to home, all to no avail, until i did those quoted instructions, and now everything works fine again



> @AFN40 @kjustie i'm in pretty much the same boat, my nest E stopped working a few weeks ago, it just disappeared from my home app. but a comment from earlier in this issue fixed my problem, quoted below
> 
> > No need to create a fork or recreate any work, implementation of the new API is already done (and yes it is complicated). I was waiting for Homebridge to update to HAP-NodeJS 0.5.x so I can support cameras, but in the mean time, you can all try it (without camera support).
> > Assuming you are using Homebridge on a Mac or Linux (otherwise adjust the paths):
> > 
> > * cd /usr/local/lib/node_modules/homebridge-nest
> > * wget https://sidewinder.starlinghome.io/beta/homebridge-nest-experimental24.tar.gz
> > * sudo tar xvfz homebridge-nest-experimental24.tar.gz
> > * sudo npm install
> 
> I'm running on a RPi, so the only thing i had to change to make it work with my setup is the first command. i exclude /local from the path and run as root, as so:
> `cd /usr/local/lib/node_modules/homebridge-nest`
> 
> and a few notes in case the extra troubleshooting info may be helpful to others or the devs, I have a Nest E (and no other nest products), i've been using the google auth token thing since shortly after it was first supported. it's worked for many months, one day a few months ago it deauthed, i believe i recall it spamming some message every minute or so in the log, and the accessory in the home app would show as not responding. after reauthing, it worked for a few more months until just recently when the accessory just disappeared completely and i started having the issue discussed here. the log didnt spam anything, and when the nest initialized, the log would only show "initializing nest platform" then "fetching nest devices" and move on to the other modules, not saying anything related to the nest anymore. i tried reauthing, updating, and readding the homebridge to home, all to no avail, until i did those quoted instructions, and now everything works fine again

I've got also a problem with this plug in: after installed this plugin (npm homebridge-nest 3.5.1) through Homebridge Config UI X all my google devices (protects, thermostat) appear and works OK but homebridge gets unstable and after about a day all my accessoires (also my domoticz-accessoires) disappear. After re-adding I have to assign everything to a room again. A lot of work. Is this the same problem?

Is this method of installation (npm) incorrect and do I have to follow these steps (after unstalling 3.5.1)?

cd /usr/local/lib/node_modules/homebridge-nest
wget https://sidewinder.starlinghome.io/beta/homebridge-nest-experimental24.tar.gz
sudo tar xvfz homebridge-nest-experimental24.tar.gz
sudo npm install

Do this solve the problem of instability?

**Comment by fletchto99** [comment]
Hey @adriancable I've forked this repo and added the experimental code in https://github.com/fletchto99/homebridge-nest

I've pubished this to npm under [`homebridge-nest-fletchto99`](https://www.npmjs.com/package/homebridge-nest-fletchto99). If/when you publish a new release with the official version I'll happily remove my fork and published package. I've done this so that I'm able to pull in the latest version automatically into a docker container I use for homebridge.

For other folks manually installing the package please note you _can_ use `npm install homebridge-nest-fletchto99` to have the experimental changes. Please note that this fork will likely go away in the future in favor of the official repo.

**Comment by AFN40** [comment]
Thanks gamewin1!! Worked perfectly.

**Comment by maydaydarkhorse** [comment]
I have successfully installed @fletchto99 's fork and now have my thermostat back in Homekit.  Any chance someone could help me with the necessary steps to get ffmpeg installed so my cameras will work?  All the instructions say on his fork is "install ffmpeg" but for the life of me I can't find any instructions... (yes, I am a noob to all this - any help would be greatly appreciated!)

**Comment by adriancable** [comment]
Closing now 4.4.0 is released.

**Comment by bkalai321** [comment]
cd /usr/local/lib/node_modules/homebridge-nest had to create homebridge-nest with sudo mkdir homebridge-nest
wget https://sidewinder.starlinghome.io/beta/homebridge-nest-experimental24.tar.gz needed to use sudo
sudo tar xvfz homebridge-nest-experimental24.tar.gz
sudo npm install

this solution rocks all i had to do afterward is add my access code to the config.json and all my nests product showed in accessories as well as home app
Thanks @adriancable for this

**Comment by bkalai321** [comment]
The  https://sidewinder.starlinghome.io/beta/homebridge-nest-experimental24.tar.gz site is not available any longer

**Comment by adriancable** [comment]
It has no purpose. It is an old old beta which eventually became 4.4.0, which itself is out of date compared with the current published version, and has a lot of bugs (hence the ‘experimental’ in the title). There are no circumstances when you would use it over the current published version in github.

@bkalai321 - please just use the current released version on Github. Your thermostat will be there, and everything will work great.
