### ISSUE TITLE
Only 1 Protect(of 2) shows the occupancy sensor/switch

### ISSUE THREAD

**Issue by dVIAN13** [chrisjshull/homebridge-nest#149]
Hello,

I am wondering why only one of my Protect alarms show the occupancy sensor/switch? is this on purpose? also, is there a way to turn off the occupancy sensor/switch all together? 

lastly, is there a plan or currently a way to use the motion sensor as such? seems like the sensor shows up, however currently mimics the occupancy setting.

please excuse my ignorance if this was already discussed. thanks!

**Comment by adriancable** [comment]
Occupancy is a property of your whole home, not of the Protect. No matter how many Protects or Thermostats you have, you will only have one Occupancy sensor/switch per home.

The Nest system determines occupancy by amalgamating data from all sorts of sources, including the motion sensor on Protects. So, sometimes the occupancy state may well be similar to the motion sensed state.

**Comment by dVIAN13** [comment]
@adriancable thanks for the reply and clarification! 

Wondering if there is a way to disable the occupancy and only use the Individual motion sensors in the devices themselves.

**Comment by adriancable** [comment]
By "disable" do you mean simply not display it in HomeKit? To do that, you can set the HomeAway.Disable option - the README tells you how.

**Comment by lruckman** [comment]
Just leaving a comment for the next person who has this issue like I did. Once I went into the nest app and added the new nest protect device as something that determines if people are home (settings > home/away assist > what decides if you're home) and restarted home bridge the new device now has a occupancy sensor along with smoke and co2.

**Comment by mpjalexander** [comment]
I have both of my Protects set to "No" in the Nest app, yet they both have presence sensors in HomeKit (via Homebridge and this plug-in).
