### ISSUE TITLE
Nest current temp and the set temp are not showing correct in Home app

### ISSUE THREAD

**Issue by dswee999** [chrisjshull/homebridge-nest#15]
I got homebridge to add Nest to my Home app. However, the temperature showing in Home as well as the temperature it shows Nest is set to, is not the actual temperature that the Nest app or the physical Nest shows. Any idea why or how to fix?

**Comment by chrisjshull** [comment]
Hmm. What temperature does Home say, and what temperature does the Nest say?

~Chris

**Comment by dswee999** [comment]
Homebridge shows that the nest has the heat turned on and that it is set to 64 and that it is 66 in the house. The Nest app and the physical Nest shows that it is set to 65 and 67 in the house.

**Comment by chrisjshull** [comment]
weird. can you:
1. shut down homebridge
1. launch homebridge in debug mode `DEBUG=* homebridge -D`
1. attach the log once homebridge is up and running.

**Comment by dswee999** [comment]
launching in debug does not work, possibly because I installed using docker? Maybe that is also why the temp is wrong?

**Comment by dswee999** [comment]
is there a way to run it in debug mode within docker?

**Comment by chrisjshull** [comment]
I think I see what's happening; the °C numbers from the API can be wrong when in °F mode. E.g. the API will say it's 19°C when the temp is 67°F, even though (67-32)/1.8 = 19.44. Right now the code only looks at the °C values because HomeKit only talks °C anyway. Looks like we'll have to detect °F mode, take the °F value, and then do our own conversion to °C.

**Comment by mriksman** [comment]
This may be the same issue I am having.

I have a Heat-only Nest (UK Nest - we don't have AUTO or COOLING). 
My Nests (for the example below) are;
Guest: OFF. Target temp previously at 18 deg C. I have no idea where it is getting 20 deg C from for the target_temperature_low_c variable. When it is ON, it displays 18 correctly.
Living: ECO. Eco temperature is set to 18 deg C. In Home app it shows 10. Looking at the variables it uses to obtain the TargetTemperature - there is clearly something wrong;

```
[3/9/2018, 6:17:36 AM] [Nest] Guest Thermostat target_temperature_c: 18
[3/9/2018, 6:17:36 AM] [Nest] Guest Thermostat target_temperature_low_c: 20
[3/9/2018, 6:17:36 AM] [Nest] Living Room Thermostat eco_temperature_low_c: undefined
[3/9/2018, 6:17:36 AM] [Nest] Living Room Thermostat eco_temperature_low_c: undefined
```

When I set Guest to ECO, I get the same;
```
[3/9/2018, 6:17:52 AM] [Nest] Guest Thermostat eco_temperature_low_c: undefined
[3/9/2018, 6:17:52 AM] [Nest] Guest Thermostat eco_temperature_low_c: undefined
```

Log entries located at lines 241;
```
                case "eco":
                        this.log(this.name + "eco_temperature_low_c: " + this.device.eco_temperature_low_c);
                        return this.device.eco_temperature_low_c;
                case "heat-cool":
                default:
                        this.log(this.name + "target_temperature_low_c: " + this.device.target_temperature_low_c);
                        return this.device.target_temperature_low_c;
```

And here at line 226 ;

```
NestThermostatAccessory.prototype.getTargetTemperature = function () {
        switch (this.device.hvac_mode) {
                case "heat-cool":
                case "eco":
                        if (!this.device.can_cool) {
                                return this.getHeatingThresholdTemperature();
                        } else if (!this.device.can_heat) {
                                return this.getCoolingThresholdTemperature();
                        }

                        switch (this.device.hvac_state) {
                                case "heating":
                                        return this.getHeatingThresholdTemperature();
                                case "cooling":
                                        return this.getCoolingThresholdTemperature();
                                case "off":
                                default:
                                        return this.getCurrentTemperature();
                        }
                default:
                        **this.log(this.name + "target_temperature_c: " + this.device.target_temperature_c);**
                        return this.device.target_temperature_c;
        }
};

```

**Comment by mriksman** [comment]
I have confirmed, at least for the UK Nest, that eco_temperature does not exist. When in AWAY/ECO, the correct temperature is available in **away**_target_temperature_

**Comment by chrisjshull** [comment]
v2.1.2 should now have this fixed. let me know if you experience otherwise

**Comment by dswee999** [comment]
Updated and the temp seems to be spot on now. Thanks!
