### ISSUE TITLE
Cannot setup after Google migration

### ISSUE THREAD

**Issue by nscheffer** [chrisjshull/homebridge-nest#150]
Hi,

I migrate my Nest account to a Google account and I create another Google account with no MFA enabled.
I follow your guide and I got always the same error : 

sept. 01 12:09:55 raspi3 homebridge[13160]: Unhandled rejection StatusCodeError: 401 - {"error":{"code":401,"message":"Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.","status":"UNAUTHENTICATED"}}

Here is my config : 
       {
            "platform": "Nest",
            "googleAuth": {
                "issueToken": "https://accounts.google.com/o/oauth2/iframerpc?action=issueToken&response_......2F%2Fhome.nest.com",
                "cookies": "OCAK=cMDnun......LcOBeRZUA5ZKZU9rGr9qhBF8",
                "apiKey": "AIzaSyAdkSIMN.......sX9UOWkS5P6sZE4"
            }
        }

I don't know why and how to solve it ?
Many thanks in advance.
Regards,

Nicolas

**Comment by xrv1ck** [comment]
Running into the same error here as well after following the setup closely.

Here's my config:
    "platforms": [
        {
            "platform": "Nest",
            "googleAuth": {
                "issueToken": "https://accounts.google.com/o/oauth2/iframerpc?action=issueToken&response_type=token%20id_token&login_hint=AJD***GIQ&client_id=733***r9lrq.apps.googleusercontent.com&origin=https%3A%2F%2Fhome.nest.com&scope=openid%20profile%20email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fnest-account&ss_domain=https%3A%2F%2Fhome.nest.com",
                "cookies": "OCAK=9v***2e4;",
                "apiKey": "A***5P6sZE4"
            },
        },

**Comment by adriancable** [comment]
@nscheffer & @xrv1ck - please can you take your config.json, scramble a few characters of the cookies string (but do not delete or add characters), and then email me to: adrian.cable@gmail.com

Thanks!

**Comment by adriancable** [comment]
@nscheffer - can you also add [ "Debug.Verbose" ] to "options", then run homebridge -D and send me the full log, including the 401 error but also showing the lines above and below so I have the full context. Thanks!

**Comment by adriancable** [comment]
All of these were solved offline - the cookies in config.json were not fully pasted in.

**Comment by xrv1ck** [comment]
Got around to copying the entire cookie jar. It works perfect! Thanks so
much for the help. Keep up the great work :)

Regards,
Victor Lui
