### ISSUE TITLE
Support for 

### ISSUE THREAD

**Issue by mareknow** [chrisjshull/homebridge-nest#151]
Hi,

Is it possible to add support for Google Nest xYale Lock? I setup Homebridge and was not able to find plugin that supports Google Nest Lock. Not sure what would it take to extend homebridge-nest plugin to support this device. 

Thanks!

**Comment by adriancable** [comment]
@mareknow - can you control the lock from the home.nest.com Nest web app? If so, could you please do the following:

1. Go to home.nest.com in Chrome and log in
2. Start HAR recording in Dev Tools
3. Press 'Refresh' in your browser
4. Stop HAR recording, and send me the HAR file
5. Start HAR recording again
6. Unlock the lock via the web app
7. Stop HAR recording, and send me the HAR file
8. Start HAR recording again
9. Lock the lock via the web app
10. Stop HAR recording, and send me the HAR file

That would be awesome! Thank you.

**Comment by mareknow** [comment]
@adriancable unfortunately Google removed ability to perform lock control actions in web browser except for some preferences. Only way to perform such actions at least when logged in using google account is using Nest app or Google Home. Communication from these apps to home.nest.com server is encrypted and using proxy server doesn’t work.
On another hand, I could not find Google documentation for APIs to control lock other then Google Assistant so finding out APIs called by the apps will be difficult.

**Comment by adriancable** [comment]
Thanks for the heads up. Closing for now, but will keep the support for the Nest x Yale lock as a possibility for the future.
