### ISSUE TITLE
Econnreset

### ISSUE THREAD

**Issue by krazyflipj** [chrisjshull/homebridge-nest#153]
I keep seeing the following error in my log

![485C368F-4ADC-496E-9349-35B9CB58AC4D](https://user-images.githubusercontent.com/10282165/64468910-e41e0300-d0de-11e9-9790-633f07b88c25.jpeg)

**Comment by Thomas034** [comment]
try to repeat sync with google

**Comment by adriancable** [comment]
@krazyflipj - this isn't an issue with the plug-in - as you can see your Ring plug-in is giving similar errors. Check your Internet connection and router. Closing for now.
