### ISSUE TITLE
Thermostat Auto-Grouped

### ISSUE THREAD

**Issue by seldridge1** [chrisjshull/homebridge-nest#155]
Did something change in a recent update that auto-grouped the thermostat with the fan and Eco-mode switch? Eco-mode used to be it’s own tile that was much more convenient to view/change the status of. I also cannot find a way to ungroup the three accessories.

**Comment by black01gt** [comment]
Running the IOS13 Beta? That is new in IOS

**Comment by seldridge1** [comment]
Alas, I am; was afraid that might be the case. Is there away to add a manual tile separate of the thermostat grouping?

**Comment by adriancable** [comment]
Unfortunately not - this is an iOS 13 "feature". I actually like it, but I know many that do not! Maybe one day it will be a configurable option.

**Comment by seldridge1** [comment]
Makes sense. Thanks!
