### ISSUE TITLE
Thermostat configured but not detected:Thermostat configured but not detected:

### ISSUE THREAD

**Issue by vinacc** [chrisjshull/homebridge-nest#156]
I have a homebridge system on my raspberry pi 3b and a Nest Thermostat E with HeatLink.

I configured the plug-in but I can't add the thermostat to Homekit, it isn't detected. I wanted to know what was wrong.

This is the log.

> [9/21/2019, 2:17:25 AM] [Nest] Initializing Nest platform...
> [9/21/2019, 2:17:25 AM] [Nest] Fetching Nest devices.
> [9/21/2019, 10:21:49 PM] [Nest] Nest API call to subscribe to device settings updates returned an error: EAI_AGAIN
> [9/21/2019, 10:21:49 PM] [Nest] Retrying in 40 seconds.
> [9/21/2019, 11:18:41 PM] [Nest] Reauthenticating on Nest service ...
> [9/22/2019, 12:18:56 AM] [Nest] Reauthenticating on Nest service ...
> [9/22/2019, 1:19:11 AM] [Nest] Reauthenticating on Nest service ...
> [9/22/2019, 2:19:27 AM] [Nest] Reauthenticating on Nest service ...
> [9/22/2019, 3:19:42 AM] [Nest] Reauthenticating on Nest service ...

**Comment by adriancable** [comment]
@vinacc - right now the plug-in does not support Thermostat E with Heat Link, which uses a completely different API.

However, I have an experimental version of the plug-in under development which works in a different way, which may be close to working with Thermostat E with Heat Link. Could you send me an email at adrian.cable@gmail.com and I will send you some code to test? That would be very helpful! Thank you.

**Comment by vinacc** [comment]
hello, I sent you an email.

Inviato da iPhone

**Comment by adriancable** [comment]
@vinacc - I didn't receive it. Can you check you got my address right? Thanks!

**Comment by vinacc** [comment]
Check in spam please

**Comment by adriancable** [comment]
Got it. Thanks!

**Comment by Radstake** [comment]
Hi! I got the same set-up. Authentication via Google is ok but E with heatlink not found. I send you a mail already, but really wanting to use your new version as well, thank you!

**Comment by Radstake** [comment]
@vinacc did you get it to work? I can't seen to get in touch with @adriancable via mail or here...

**Comment by adriancable** [comment]
Erich - apologies - I am on vacation right now. Will get back to you in the next couple of days.

**Comment by Radstake** [comment]
No worries @adriancable :-) Have a great holiday!

**Comment by vinacc** [comment]
> @vinacc did you get it to work? I can't seen to get in touch with @adriancable via mail or here...

works but is not very stable.  when I restart the server the thermostat is not always detected.  but when detected it works very well.

**Comment by Radstake** [comment]
Ok, thanks. Can you share that version with me? That would be great, thanks.

Hartelijke groet,

Erich Radstake

**Comment by adriancable** [comment]
Erich - I'll get you and Vincenzo the latest code base tomorrow when I'm back. Much more stable than the version Vincenzo got a while back.

-Adrian

**Comment by Radstake** [comment]
Awesome, looking forward to it!

Hartelijke groet,

Erich Radstake

> Op 25 nov. 2019 om 00:12 heeft Adrian Cable <notifications@github.com> het volgende geschreven:
> 
> ﻿Erich - I'll get you and Vincenzo the latest code base tomorrow when I'm back. Much more stable than the version Vincenzo got a while back.
> 
> -Adrian
> 
> Sent from my iPhone
>

**Comment by vinacc** [comment]
> Erich - I'll get you and Vincenzo the latest code base tomorrow when I'm back. Much more stable than the version Vincenzo got a while back.
> […](#)

fantastic.  I can't wait to try it.

**Comment by adriancable** [comment]
Closing for now - code published in #148
