### ISSUE TITLE
ENOTFOUND when adding NEST Platform

### ISSUE THREAD

**Issue by TheTrueWizard** [chrisjshull/homebridge-nest#159]
[10/9/2019, 1:45:07 PM] Loaded plugin: homebridge-nest               
[10/9/2019, 1:45:07 PM] Registering platform 'homebridge-nest.Nest'  
[10/9/2019, 1:45:07 PM] ---                                          
[10/9/2019, 1:45:07 PM] Loading 1 platforms...                       
[10/9/2019, 1:45:07 PM] [Nest] Initializing Nest platform...         
[10/9/2019, 1:45:07 PM] [Nest] Fetching Nest devices.                
[10/9/2019, 1:45:07 PM] Loading 0 accessories...                     
**[10/9/2019, 1:45:08 PM] [Nest] Could not authenticate with Nest (code ENOTFOUND). Retrying in 15 second(s).**                               
**[10/9/2019, 1:45:25 PM] [Nest] Nest API call to subscribe to device settings updates returned an error: ENOTFOUND**                         
[10/9/2019, 1:45:25 PM] [Nest] Retrying in 40 seconds.               
**[10/9/2019, 1:46:05 PM] [Nest] Nest API call to subscribe to device settings updates returned an error: ENOTFOUND**                         
[10/9/2019, 1:46:05 PM] [Nest] Retrying in 40 seconds.               
**[10/9/2019, 1:46:46 PM] [Nest] Nest API call to subscribe to device settings updates returned an error: undefined**                         
[10/9/2019, 1:46:46 PM] [Nest] Retrying in 40 seconds.

versions:
homebridge@0.4.50
homebridge-nest@3.5.1

Added the "googleAuth" JSON object and "issueToken", "cookies", and "apiKey" keys.

Any help would be appreciated.
Thank you

**Comment by adriancable** [comment]
@TheTrueWizard - ENOTFOUND means DNS can't resolve the Nest domain. It isn't a plug-in problem. Check your Internet connection etc.

-Adrian

**Comment by TheTrueWizard** [comment]
nslookup succeeds from inside the container. not sure what I'm doing wrong.
I'll look into it further. Thanks anyway.

/homebridge # nslookup home.nest.com
Name:      home.nest.com                                             
Address 1: 3.208.130.64 ec2-3-208-130-64.compute-1.amazonaws.com     
Address 2: 34.199.36.191 ec2-34-199-36-191.compute-1.amazonaws.com   
Address 3: 35.173.79.129 ec2-35-173-79-129.compute-1.amazonaws.com   
Address 4: 52.44.251.153 ec2-52-44-251-153.compute-1.amazonaws.com   
Address 5: 34.225.60.196 ec2-34-225-60-196.compute-1.amazonaws.com   
Address 6: 54.175.182.233 ec2-54-175-182-233.compute-1.amazonaws.com 

/homebridge # nslookup www.nest.com                        
Name:      www.nest.com                                              
Address 1: 35.241.20.76 76.20.241.35.bc.googleusercontent.com        

/homebridge # nslookup www.google.com
Name:      www.google.com                                            
Address 1: 172.217.13.196 yul03s05-in-f4.1e100.net                   
Address 2: 2607:f8b0:4020:804::2004 yul02s04-in-x04.1e100.net

**Comment by TheTrueWizard** [comment]
nslookup and dig were giving some... odd results...

I started from scratch downloading the latest container, launching a new image.

fixed itself.
