### ISSUE TITLE
Nest home/away with only cameras

### ISSUE THREAD

**Issue by lobo5519** [chrisjshull/homebridge-nest#160]
I am only using cameras with Nest but I would like to trigger the home/away status with homekit automation. 

The idea here is that when everyone is gone, i get notifications from the cameras but when everyone is home I don't. This is really the only good way to configure notifications for me with Nest as letting the app use presence flips it self back to away if I manually set it to home. 

I believe I have the plugin setup correctly as there are no errors only a log saying "Fetching Nest Devices" - but nothing shows up. I was hoping for just the Home switch to show up to tigger Home/Away.

My thought is its nothing appearing as I have no other compatible devices - Is that accurate and possible to change?

**Comment by adriancable** [comment]
@lobo5519 - right now the plug-in doesn't have any support for cameras at all. But I am working actively on this - the limitation is the current version of Homebridge has broken camera support for various reasons, so we need to wait for an update. But watch this space!

**Comment by lobo5519** [comment]
Yea I get that - was hoping to just get the ability to flip home/away - don’t need to see or control cameras at all but those are the only devices I have - so I was wondering if that’s why home/away wasn’t an option for me in homebridge - pretty sure that’s a global Nest feature right?

**Comment by adriancable** [comment]
@lobo5519 - the next version of the plug-in will do what you want, and also add full support for cameras (live video/audio + doorbell support for Nest Hello). I am waiting on an update for Homebridge to use HAP-NodeJS 0.5.0 since that's required for camera support to work.
