### ISSUE TITLE
Nest protect not shown as someksensor on hoobs 3.0 desktop 

### ISSUE THREAD

**Issue by GitMeHenk** [chrisjshull/homebridge-nest#163]
Nets protect shows up in the Hoobs service as two seperate squaes withoud data or functionality

Screenshot attached

![C21D22A1-09BC-4BDB-B35B-7440E6ADA7E2](https://user-images.githubusercontent.com/52503571/66716029-2d423080-edca-11e9-9b13-c264ac325803.png)

**Comment by adriancable** [comment]
homebridge-nest does not currently support HOOBS. Support may be added in the future. Closing for now.
