### ISSUE TITLE
Question: Will the Nest API shut-down affect this plugin?

### ISSUE THREAD

**Issue by mikesalz** [chrisjshull/homebridge-nest#164]
Hello! I'm considering purchasing a Nest Protect, but will only do so if I can use it with HomeKit.  Will this plugin be affected by the Nest API shut-down?  Thanks in advance for your help!

**Comment by adriancable** [comment]
The Nest API is not being shut down. The "Works with Nest" developer program has been shut down. The plug-in does not use "Works with Nest" and so you will be fine.

**Comment by adriancable** [comment]
Yes - that's correct. Enjoy!

**Comment by mikesalz** [comment]
Great, thanks!!
