### ISSUE TITLE
Asking Siri “what is the thermostat set to?” says the device “is off”

### ISSUE THREAD

**Issue by aaronbushnell** [chrisjshull/homebridge-nest#166]
**Describe the bug**
I’ve got the accessory setup (great work, by the way!). But when I ask Siri “what’s the thermostat set to?” She simply responds with “The Hallway is off”. Which I assume “Hallway” is the name of the location of my thermostat. 

Is there something I can do to have Siri report to me what I have the temperature set to—regardless if the heat or A/C is actively running?

Or is this an iOS bug?

**To Reproduce**
1. Ask Siri what the thermostat is set to. 

**Expected behavior**
Siri should respond back with what my thermostat is set to in Celsius or Fahrenheit 

Include with your bug report this version info:
```sh
node --version
12.11.0

homebridge --version
0.4.50
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

**Comment by adriancable** [comment]
@aaronbushnell - if the thermostat is off, HomeKit has no concept of what the temperature is set to. You can ask something like "Siri, what's the temperature in the Hallway" which will tell you the ambient temperature.

Unfortunately this is a HomeKit limitation.

**Comment by aaronbushnell** [comment]
Thanks! Makes total sense and I’ll look into this further
