### ISSUE TITLE
No decimal points .5 when changing the heat

### ISSUE THREAD

**Issue by cryptobrian** [chrisjshull/homebridge-nest#169]
On iOS 13, the is no ability to set the temperature to .5 degree. Only whole numbers.  Ie: can either set to 20 or 21 degrees C.  Cannot set at 20.5C.

**Comment by adriancable** [comment]
@cryptobrian - interesting. I don't have a degrees C system but will try and fudge things so I can verify this.

**Comment by cryptobrian** [comment]
Additional info.  Nest thermostats let you toggle C and F.  Previously on iOS 12, half degrees Celsius was possible with heating and cooling.  

@adriancable thanks!! Amazing work with this plugin!

**Comment by adriancable** [comment]
@cryptobrian - looks like this is an iOS 13 bug: https://www.reddit.com/r/HomeKit/comments/d8w6mk/home_app_on_ios_131_no_longer_able_to_set_05/

I've posted a note on HAP-NodeJS in github though, in case anyone is able to find a workaround.

**Comment by adriancable** [comment]
Apple have now restored 0.5 degree increments in iOS 13.4. Excellent news!
