### ISSUE TITLE
New log-in to your Nest Account

### ISSUE THREAD

**Issue by jankais3r** [chrisjshull/homebridge-nest#170]
I am not sure if I am the only one with this problem, but here we go. When using a Nest email+password combo for login, I receive a notification email on every restart of homebridge. The email says:
```
New log-in to your Nest Account
--
We noticed a recent log-in to your Nest Account REDACTED. If this wasn’t you, you can reset your password now.
```

My homebridge server is being rebooted on schedule every night, generating these emails from Google in the process. I was wondering if there was a way to modify the login process so that Google sees it as the same device (which it is) and does not generate this warning every time.

**Comment by mike391** [comment]
I cant login at all.

Im getting:

"Could not authenticate with Nest (code 406). Retrying in 15 second(s)."


But to answer your question, this happens anytime you login. Logging in through nest.com and homeassistant both send those emails as well.

**Comment by jankais3r** [comment]
Apparently there is currently no solution unless Nest decides to give us an option to opt out of these emails.
