### ISSUE TITLE
Migrated my Nest to Google Account

### ISSUE THREAD

**Issue by mazzy89** [chrisjshull/homebridge-nest#175]
First @adriancable I'd like to say thanks for your great work here. Do reverse engineering of API is tedious and hard work. It is requested a lot of patience. But you did. So thank you.

I'm here just to ask a question not related to Homebridge but about Nest functioning via Google Auth. Perhaps it might help others passing by or maybe you can figure out the thing.

I'm using Wireless Sensor Tag http://wirelesstag.net/ and they support Nest. Unfortunately, they don't support Google Auth. Trying to link Nest to their platform I get this.

![image](https://user-images.githubusercontent.com/5463218/68790383-827e9580-0647-11ea-8765-f03fcfcbb0fb.png)

Fair enough I said to myself.

Luckily they support the endpoint https://wirelesstag.net/NestLink.asmx?op=Associate

which associates the Nest Link to their platform.

```txt
{
    nest:{
        "device_id": string
        "auth":string
        "name":string
        "comment":string
        "is_online":boolean
        "lastComm":long
        "slaveId":int
        "renamed_to":string
    }
}
```

One of the request parameters in the body is `auth`. I supposed that this `auth` is the access token that you parse here https://github.com/chrisjshull/homebridge-nest/blob/master/lib/nest-connection.js#L200

Now I know that it's not your area of support and feel free to ignore me but I'm just wondering one thing. The change of auth made by Google (from Nest to Google Auth), left unchanged other functionalities in how Nest fetches data? Because if I would be able to serve the right token to the endpoint `https://wirelesstag.net/NestLink.asmx/Associate` then all the rest should work. Or maybe not?

I know that without watching the backend of Wireless Tag is impossible to reply correctly but asking here if you did any changes to the operability of the plugin, when Google Auth was introduced.

**Comment by mazzy89** [comment]
I think I have partially found out the answer to my question here: https://github.com/chrisjshull/homebridge-nest/issues/164#issuecomment-544268875

Then my question is: which kind of API is used here if not the one Work From Nest? There are sny other documented API to control Nest products or is just reverse engineering work? thank you

**Comment by adriancable** [comment]
@Mazzy89 - the Google auth process is as follows: the client completes the Google OAuth flow requesting a private Nest scope. Google returns an access token. You then call an API function to exchange the Google access token for a Nest access token. This token then works in the normal way with the Nest APIs, except that it expires after an hour (whereas Nest Account tokens last for a long time - I think a month). When it expires you have to repeat the process again.

The plug-in uses the same API that the Nest app uses - it was reverse engineered. There is currently no documented API that Nest developers can use.

**Comment by mazzy89** [comment]
Thanks a lot @adriancable to stop by and find the time to reply to this. this helps me a bit to understand the thing. I can think we can close this ;-)

**Comment by mazzy89** [comment]
@adriancable thanks a lot to stop by here and find the time to answers. this also clarifies the thing. I thought since the beginning that there would be only an API this was using Work With Nest.
