### ISSUE TITLE
Thermostats not show up in Home app

### ISSUE THREAD

**Issue by nflute** [chrisjshull/homebridge-nest#176]
I had an issue with my thermostats early today with Nest app, remove them and re-added them back. Reconfig Nest Homebridge config file (Follow instruction, as I successfully done it before) ... now my thermostats are not show up in Home app.

[2019-11-14 23:18:15] [Nest] Initializing Nest platform...
[2019-11-14 23:18:15] [Nest] Fetching Nest devices.

Any idea how to fix this?

Thank you.

**Comment by adriancable** [comment]
@nflute - please can you send me an email at adrian.cable@gmail.com and I'll try to figure out what is happening.

**Comment by nflute** [comment]
Email sent.
