### ISSUE TITLE
Current room temperature export to MQTT

### ISSUE THREAD

**Issue by iondarie** [chrisjshull/homebridge-nest#178]
Hello,

Thank you for your wonderful plugin!

Is there any way that i can publish only the current temperature to a MQTT topic?

Thank you,

**Comment by adriancable** [comment]
@iondarie - this is beyond the scope of the plug-in, but check out homekit2mqtt. It lets you publish stuff from any HomeKit device (which would include the thermostat from homebridge-nest) via MQTT.
