### ISSUE TITLE
Add Service.Switch to set away / home feature for Nest Cam.

### ISSUE THREAD

**Issue by outaTiME** [chrisjshull/homebridge-nest#18]
Hi guys, 
it will great to have an Service.Switch for each device to set away or set home to create better automations in homekit, i create a simple PR to handle that with nest cam.

I'll be waiting for your feedback, thanks !!!

**Comment by adriancable** [comment]
The plug-in does not currently support the Nest Cam. Please take a look at the homebridge-nest-cam plug-in - it may do what you need.
