### ISSUE TITLE
Current status of new Google API compatibility

### ISSUE THREAD

**Issue by bdshet** [chrisjshull/homebridge-nest#180]
Hello, I just finished completing the steps to use my Google Account associated with the Nest for setup through the API process. I've been unable to ascertain, however, if this program is currently supported following the changes Google made to APIs in the late-summer. It seems all of the feedback plus the instructions date back to before Google locked down their APIs.

I was not successful in setting up my Nest to work with Homebridge. Please let me know if it is still possible and then I will begin to further troubleshoot. Thank you!

**Comment by bdshet** [comment]
And with that, I've already solved my problem. I had a json syntax error & I read through many of the closed comments to verify that this process still works following Google's changes. (I didn't realize you could access closed comments when I originally posted!)   Thank you Adrian for an incredible plugin.

For anyone wondering what a complete config.json file looks like for a brand new Homebridge setup with only the Nest plugin installed, I'm attaching below. This example would have helped immensely during my initial attempts.

{
    "bridge": {
        "name": "Homebridge",
        "username": "CB:22:3D:E2:CE:31",
        "port": 51826,
        "pin": "033-44-254"
    },
    "accessories": [ ],
    "platforms": [
        {
        "platform": "Nest",
        "googleAuth": {
             "issueToken": "https://accounts.google.com.....",
             "cookies": "OCAK=J0oF1ISZK.....",
             "apiKey": "AIzaSyAdkSIMN....."
             }
        }
]
}

My syntax error was in the number of commas included toward the end. All is good now with the above syntax.

**Comment by adriancable** [comment]
@bdshet - glad you have everything working! Yes - the plug-in is fully supported and works now, and will continue to work into the foreseeable future. And, your suggestion of providing a complete config is a good one.
