### ISSUE TITLE
NestProtect MotionSensor

### ISSUE THREAD

**Issue by mihailescu2m** [chrisjshull/homebridge-nest#181]
Can you please explain the MotionSensor from Nest Protect?

AFAIR, Nest never exposed a motion sensor in their API, only had the HomeAway. which may use  motion detected by Protect (among others), but I think it's based on a 30min window (on the app it says "Activity detected in the last 30 mins"), so it's kind of approximate.
So how timely is the MotionSensor? E.g. can it be used to trigger an alarm if someone breaks in? (For this scenario, having an API to trigger the sound on the protect as an alarm would be cool as well if possible).

**Comment by adriancable** [comment]
@mihailescu2m - the motion sensor is used internally to set Home/Away mode, and for Pathlight. It is not exposed by the "official" API but I can still get access to it.

It is quite timely. When the motion sensor detects movement, it triggers within a few seconds. (It takes a little while - a couple of minutes - to turn off after detection.)

Unfortunately the alarm on the Protect can't be triggered via an API, but you can use a HomeKit Automation to take some other action based on the motion sensor.

**Comment by mihailescu2m** [comment]
Thanks.
