### ISSUE TITLE
Shortcuts returning temperature in Celsius

### ISSUE THREAD

**Issue by radiocolin** [chrisjshull/homebridge-nest#182]
When using the "get state of home" function in Shortcuts, "target temperature" is returning Celsius. Nest and iOS are both set to use Farenheit.

**Comment by adriancable** [comment]
@radiocolin - I think this must be a Shortcuts bug. What iOS version are you using? I will try to reproduce.

**Comment by radiocolin** [comment]
13.3 (17C5046a)

**Comment by adriancable** [comment]
Confirmed. This is definitely a Shortcuts/iOS bug.
