### ISSUE TITLE
Celcius temp 0.5 step

### ISSUE THREAD

**Issue by perote2000** [chrisjshull/homebridge-nest#183]
When I change temperature on my nest thermostats (I use C degrees) they increase o decrease by 0.5 C degrees. My Nest App also increase and decrease by 0.5 degrees.
In Homekit I'm able to see 0.5 decree steps when I change temperature outside homekit, but i'm unable to change temp in 0.5 degrees in homekit

Could you please add an option to set steps to 0.5?

**Comment by adriancable** [comment]
@perote2000 - unfortunately this is an iOS 13 bug. See here: https://www.reddit.com/r/HomeKit/comments/d8w6mk/home_app_on_ios_131_no_longer_able_to_set_05/

The plug-in does request 0.5 increments in degrees C mode, and prior to iOS 13 this worked, but now HomeKit ignores it.
