### ISSUE TITLE
Adding boiler support (Nest3 EU)

### ISSUE THREAD

**Issue by daliquidalien** [chrisjshull/homebridge-nest#184]
[Nest boiling photo.zip](https://github.com/chrisjshull/homebridge-nest/files/3908266/Nest.boiling.photo.zip)

Is it possible to add the boiler functionality?

![IMG_1892](https://user-images.githubusercontent.com/55291154/69914888-7d905300-1449-11ea-8459-62af4d5f2321.PNG)
![IMG_1893](https://user-images.githubusercontent.com/55291154/69914889-7d905300-1449-11ea-97e7-4230da1fa223.PNG)
![IMG_1894](https://user-images.githubusercontent.com/55291154/69914890-7d905300-1449-11ea-8117-26a80b9eedb1.PNG)

 It's supported by Nest3 EU. When you want to force water heating/boiling, you can select 30 mins, 1h or 2h heating on the nest device.

Thanks,

/F

**Comment by BenjiBoisemont** [comment]
Yes, this functionality would be nice

**Comment by adriancable** [comment]
Now supported in 4.4.0.
