### ISSUE TITLE
Nest Protect - Battery Status as a Sensor

### ISSUE THREAD

**Issue by cvknage** [chrisjshull/homebridge-nest#185]
**Describe the solution you'd like**
I would like it if the battery status of a Nest Protect was available as a sensor, so that I can use it in HomeKit Automations. 

**Additional context**
Example of automation I want to make: When battery is low, trigger a IFTTT Webhook, that adds a reminder on my shopping list to buy the appropriate amount of batteries.

**Comment by Nastras** [comment]
If the API lets you do that, it would be a great extension.

**Comment by adriancable** [comment]
Interesting idea. I wonder what kind of HomeKit sensor the battery status would most straightforwardly map to? There isn't a native battery state service, as far as I know.

**Comment by HammerAce42** [comment]
Many accessories already have a battery state. As an example, the [homebridge-ring](https://www.npmjs.com/package/homebridge-ring) plugin exposes the battery level of many of the accessories.

Maybe I am missing the point of this in that this can't currently be used as an automation trigger?

**Comment by adriancable** [comment]
@HammerAce42 - that's right. To my knowledge there's no way to use battery state as an automation trigger, with the Home app. Third party HomeKit apps may be able to do it.
