### ISSUE TITLE
Nest Thermostat Gen 3

### ISSUE THREAD

**Issue by ryanleeis** [chrisjshull/homebridge-nest#188]
I have a Homebridge setup on a Raspberry Pi 3.  it is only detecting the Gen 2 Nest and the Gen 3 doesn't show up.. im stumped.. is that a limitation or am I doing something Wrong.

Here is my Config.json file with the keys partially removed.
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},
	"accessories": [],
	"platforms": [{
		"platform": "Nest",
		"googleAuth": {
			"issueToken": "",
			"cookies": "OCAK=",
			"apiKey": "AIzaSyAdkSIM....."
		}
	}]
}

**Comment by adriancable** [comment]
@ryanleeis - try my solution at the end of #148.
