### ISSUE TITLE
Motion Sensor does not trigger for Nest Cam IQ

### ISSUE THREAD

**Issue by krmkrx** [chrisjshull/homebridge-nest#19]
Does the motion sensor exposed on the basis of an Nest Cam IQ work for anyone? 

My Nest Cam IQ is turned on, it detects motion but the HomeKit motion sensor does not trigger. 

However, the motion sensor exposed from my Nest Cam Outdoor works. It triggers every time someone walks by. 

Any advice on how to fix this for the Nest Cam IQ?

**Comment by chrisjshull** [comment]
The best thing to do would be to see if this is a Nest API issue, or an homebridge-nest issue. To do that you'd have to use the API directly and see if it works. The API explorer might be able to help: https://developers.nest.com/documentation/api-reference

Sadly, I do not have a Nest Cam IQ with which to test myself.

**Comment by krmkrx** [comment]
Thank you for your reply. Unfortunately I don’t have any knowledge when it comes to APIs and how to handle them. If you could advise me on how to proceed I’d really appreciate it.

**Comment by chrisjshull** [comment]
Not having one myself I don’t feel confident I could guide you. 
You probably won’t like this answer, but if you want to buy me a Nest Cam IQ I’d be happy to look into it on my own.
