### ISSUE TITLE
Feature Options (Disable) Not Working

### ISSUE THREAD

**Issue by sherwinius** [chrisjshull/homebridge-nest#190]
As stated, trying to disable several features but they're still appearing in Home. All features working as expected otherwise. Using a Google Account. New install.

Excerpt:
` "options": [
          "Thermostat.Eco.Disable",
          "HomeAway.Disable",
          "Protect.All.Disable",
          "Protect.MotionSensor.Disable"
        ]
`

Tried "clearing cache" as well and reading to Home. No changes.

**Comment by adriancable** [comment]
Your "options" is probably in the wrong place in config.json. It should be at the same level as "platform", "googleAuth" etc. Not inside them.

**Comment by sherwinius** [comment]
You're right, I had the wrong level. However, even though I have "Protect.All.Disable", CO2 and Smoke is still appearing. Is the "Protect.MotionSensor.Disable" interfering with "Protect.All.Disable"?

**Comment by adriancable** [comment]
Make sure you've read the README fully. It's "Protect.Disable".

**Comment by sherwinius** [comment]
Closed. Completely user error, works like a dream!
