### ISSUE TITLE
Asking for Google Auth Inputs when using a Nest Account

### ISSUE THREAD

**Issue by fLyRhyTHeMz** [chrisjshull/homebridge-nest#191]
**Describe the bug**
Running nest plugin on HOOBS 3 on Mac. Everything was running fine, then this morning, plugin is suddenly asking for google auth info when I am using a nest account. 

**To Reproduce**
1. Start HOOBS service
2. View Logs 
3.  ` [Homebridge] [12/22/2019, 1:16:02 PM] [Nest] When using googleAuth, you must provide issueToken, cookies and apiKey in config.json. Please see README.md for instructions`
4. Config: Nest email: ********* and Nest Pass: *********

**Expected behavior**

Normally loads thermostat and protect without issue. 

Include with your bug report this version info:
```sh 
node --version Node.js v12.13.1 
homebridge --version HOOBS v 3.1.1
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`
Plugin Version: 3.5.2

**Comment by adriancable** [comment]
This looks like an issue with HOOBS, as the homebridge-nest plugin hasn't been changed for several months. Ask on the HOOBS forum?
