### ISSUE TITLE
Google aut. in json

### ISSUE THREAD

**Issue by remko2000** [chrisjshull/homebridge-nest#192]
After migration of my nest thermostat to google I try to adjust my json file. I think this is the right file but my thermostat doesn't appear in homekit. My json file is now:
[voorbeeld.txt](https://github.com/chrisjshull/homebridge-nest/files/3998581/voorbeeld.txt)
Probably there is something wrong with my file. Do I have to remove the old nest account info (token, clientID, clienttoken) in my json?  I've read that after a migration this isn't work anymore. And is the googleAuth in the right place? 

I have the right info of my googleaccount (I followed the wiki, opening incognito chrome tab and follow all the steps to get api, cookie and issutoken).

**Comment by adriancable** [comment]
googleAuth is in the wrong place - it should go under "platform": "Nest". Yes, you might as well remove the token/clientID/clienttoken since it's no longer used (although harmless).
