### ISSUE TITLE
Nest API error: ENOTFOUND

### ISSUE THREAD

**Issue by harbri** [chrisjshull/homebridge-nest#194]
Since a few days the following errormessage shows up in my homebridge log:
"Nest API call to subscribe to device settings updates returned an error: ENOTFOUND"

Rebooting homebridge helps but in about a day the error returns.

**Comment by adriancable** [comment]
This is a DNS lookup error. It could be an issue on the Nest side, or (more likely) an issue with your Internet connection. Not a homebridge-nest issue. Closing for now.
