### ISSUE TITLE
Unable to authenticate on Nest Accounts

### ISSUE THREAD

**Issue by DJBenson** [chrisjshull/homebridge-nest#195]
My password on home.nest.com has an exclamation mark and this does not seem to work with the plugin. I have tried escaping the exclamation mark in the config file but I either get a JSON validation error (which prevents Homebridge from starting) or it starts but the password is still rejected.

**Plugin Version**: 3.5.1
**Homebridge Version**: 0.4.50
**Node Version**: v13.5.0

[02/01/2020, 20:37:34] [Nest] Auth failed: Nest rejected the account email/password specified in your Homebridge configuration file. Please check
[02/01/2020, 20:37:34] [Nest] Unable to connect to Nest service.

**Config.json snippet**:

`        {
            "platform": "Nest",
            "email": "user@gmail.com",
            "password": "PasswordWith!Mark",
            "options": [
                "HomeAway.AsOccupancySensor",
                "Protect.MotionSensor.Disable"
            ]
        },`

**Comment by DJBenson** [comment]
Changed my password on home.nest.com and still unable to authenticate.

**Comment by DJBenson** [comment]
The generateNestToken.sh script also returns a null access code so something is amiss with the authentication for me.

**Comment by gadgetfreak88** [comment]
I'm getting the same error since restarting homebridge today, config / password have not changed.

**Comment by HammerAce42** [comment]
I too am seeing the same issue.

**Comment by rtaylor-coxauto** [comment]
My Nest authentication also stopped working today.  I switched to use an access token for now.  I suspect something has changed on the Google/Nest end of things.

**Comment by joubin** [comment]
Same

**Comment by joubin** [comment]
I did a fresh install of home bridge before I found this post and the issue still persists.

**Comment by DJBenson** [comment]
access_token works for me as a workaround but it seems it expires monthly?

**Comment by claproth** [comment]
Same issue. Disabled Nest for now

**Comment by BenjiBoisemont** [comment]
Same issue for me. Nest refuses my credentials.
Plugin Version: 3.5.1
Homebridge Version: 0.4.50
Node Version: v13.5.0

**Comment by BenjiBoisemont** [comment]
> access_token works for me as a workaround but it seems it expires monthly?

How did you get your access_token?
Could yo give any sample for the config.json with access_token?

**Comment by galaxydpw** [comment]
> access_token works for me as a workaround but it seems it expires monthly?

How do you get the token
I have no longer access to my nest developer account...

Thanks

**Comment by DJBenson** [comment]
> > access_token works for me as a workaround but it seems it expires monthly?
> 
> How did you get your access_token?
> Could yo give any sample for the config.json with access_token?

Log in to https://home.nest.com with your credentials then browse to https://home.nest.com/session in the same tab, you will see a JSON object of your session. Look for the string enclosed in the quotes after "access_token" and copy that to the clipboard (copy the full string between the two quotes).

It looks something like this:

{"2fa_state":"none","access_token":"***REDACTED***"...

In your Homebridge config.json, remove the email and password fields and create a new parameter called "access_token" like such:

        {
            "platform": "Nest",
            "access_token": "***REDACTED***,
            "options": [
                "HomeAway.AsOccupancySensor",
                "Protect.MotionSensor.Disable"
            ]
        },

**Comment by DJBenson** [comment]
> > access_token works for me as a workaround but it seems it expires monthly?
> 
> How do you get the token
> I have no longer access to my nest developer account...
> 
> Thanks

See above - no need for a developer account.

**Comment by galaxydpw** [comment]
> > > access_token works for me as a workaround but it seems it expires monthly?
> > 
> > 
> > How do you get the token
> > I have no longer access to my nest developer account...
> > Thanks
> 
> See above - no need for a developer account.

Excellent!
Working again, and renewing the token every 30 days.
It will give me some time to look for a replacement of this Thermostat... Lol

**Comment by adriancable** [comment]
So sorry about all of this. Since this morning, Nest is now using a Google Recaptcha service **for Nest accounts**. If the Google-generated Recaptcha token is missing from the log-in API call (as it is in homebridge-nest), the log-in will fail. This is what is happening.

Right now, if you have a Nest Account, the best workaround is to use the access token method as described by @DJBenson above.

*Please note, this problem does not happen with Google Accounts. If you migrate your Nest Account to a Google Account, that will then work fine.*

**Comment by BenjiBoisemont** [comment]
Thanks a lot for your answer
It works fine for me.
Regards

**Comment by stone-401** [comment]
I had the same issue, so I migrated to a Google Account. Now, when I close the terminal, all my Homebridge accessories disappear from Homekit. Is it logging me out of Google when I do this? Anyone else having this issue? How do I stay logged in according to the Homebridge-nest instructions.

**Comment by mrjackyliang** [comment]
@stone-401 What do you mean by Terminal?

**Comment by stone-401** [comment]
Sorry - Terminal in Mac. I'm using it to login to a raspberry pi via SSH.

**Comment by mrjackyliang** [comment]
@stone-401 Do the accessories come back out as new accessories, or do they all just disappear and never come back?

**Comment by stone-401** [comment]
they come back if I log back into terminal, stop Homebridge, and start it again. But then when I close terminal, the devices disappear again. It's like it's logging me out of Nest or shutting down the Homebridge app altogether.

**Comment by mrjackyliang** [comment]
@stone-401 I don't think the problem you have is related to this. Homebridge isn't supposed to stop when you log out of SSH. It doesn't make sense.

**Comment by stone-401** [comment]
yeah, you are right. I've discovered that it is unrelated to the login issue. It is not related to this issue like I originally thought. Thanks for the replies anyway though! I'll search for a solution elsewhere.

**Comment by stjagu** [comment]
I have tried changing my config to access token per the @DJBenson post and Homebridge is now running but Nest not showing up in Home App at all.

**Comment by claproth** [comment]
Working now with google authentication!

**Comment by danbridgland** [comment]
> Since this morning, Nest is now using a Google Recaptcha service **for Nest accounts**. If the Google-generated Recaptcha token is missing from the log-in API call (as it is in homebridge-nest), the log-in will fail. This is what is happening.
>

Thanks @adriancable for following up so quickly.  I appreciate this change is not of your doing, but can you give any indication of the likelihood that a solution will be found for Nest accounts?   

I refuse to migrate to or sign up for a google account, and whilst the monthly token reset is a suitable temporary work around, I really don’t want to have to do this every month.  I appreciate this is a change that has been applied by Google and without prior warning,  and I also realise I seem belligerent in my stance, however I bought into Nest before google acquired it, as I did for Ring and Eero before Amazon acquired them, I’m tired of this trade in a digital user base.  Whilst Nest accounts are still accepted, I’d like to keep it in force.

I hope you understand my perspective.

Thanks
Dan

**Comment by neilmorton** [comment]
Thanks for the access_token heads up @DJBenson.

@adriancable:
 Would you suggest that migrating to a Google Account is now the best option moving forward? I have held off this until now, but am considering setting up a specific account for this only. 

If I follow the instructions [here](https://github.com/chrisjshull/homebridge-nest#using-a-google-account), am I correct in thinking that as long as I don't logout of the browser window, and just simply close it, the token should remain valid indefinitely, as there was no logout ever processed?

Are there any other issues you have seen with migrating to Google that suggest sticking with the Nest login?

Thanks.

**Comment by cryptobrian** [comment]
Ran into the same problem, was using a nest account.  Can confirm that migrating the nest account to Google, and going through the steps to get the issueToken, APIkey, and cookies works.  

Amazing work & support on this plugin!

**Comment by mrjackyliang** [comment]
> I have tried changing my config to access token per the @DJBenson post and Homebridge is now running but Nest not showing up in Home App at all.

@stjagu It works for me! Did you log out of Nest after doing it?

**Comment by stjagu** [comment]
> > I have tried changing my config to access token per the @DJBenson post and Homebridge is now running but Nest not showing up in Home App at all.
> 
> @stjagu It works for me! Did you log out of Nest after doing it?

Still not going. Issue I’m having is, I believe, proper config.json setup. I migrated and have google auth, cookie an token but need to update my config. Is the google auth nested in the hombridge-nest { }?

**Comment by mrjackyliang** [comment]
Yes

**Comment by stjagu** [comment]
> > > I have tried changing my config to access token per the @DJBenson post and Homebridge is now running but Nest not showing up in Home App at all.
> > 
> > 
> > @stjagu It works for me! Did you log out of Nest after doing it?
> 
> Still not going. Issue I’m having is, I believe, proper config.json setup. I migrated and have google auth, cookie an token but need to update my config. Is the google auth nested in the hombridge-nest { }?

This is the error message:

[Nest] You did not specify your Nest account credentials {'email','password'}, or an access_token, or googleAuth, in config.json

**Comment by stjagu** [comment]
> > > > I have tried changing my config to access token per the @DJBenson post and Homebridge is now running but Nest not showing up in Home App at all.
> > > 
> > > 
> > > @stjagu It works for me! Did you log out of Nest after doing it?
> > 
> > 
> > Still not going. Issue I’m having is, I believe, proper config.json setup. I migrated and have google auth, cookie an token but need to update my config. Is the google auth nested in the hombridge-nest { }?
> 
> This is the error message:
> 
> [Nest] You did not specify your Nest account credentials {'email','password'}, or an access_token, or googleAuth, in config.json

OK. I'm back up. Thanks all.

**Comment by mrjackyliang** [comment]
Confirms working for me!

**Comment by fahaad9** [comment]
Working for me with the Token. Hopefully there will be some workaround for people like me who do not want to migrate to Google account!

**Comment by leendersf** [comment]
> Please note, this problem does not happen with Google Accounts. If you migrate your Nest Account to a Google Account, that will then work fine.

I migrated to a Google Account but I cannot login using email and password. I use access_token for now. But it should work with just my Google credentials if above information is correct?

**Comment by mrjackyliang** [comment]
> > Please note, this problem does not happen with Google Accounts. If you migrate your Nest Account to a Google Account, that will then work fine.
> 
> I migrated to a Google Account but I cannot login using email and password. I use access_token for now. But it should work with just my Google credentials if above information is correct?

You're supposed to follow the instructions for Google Auth. You can no longer use an email and password.

**Comment by leendersf** [comment]
> @leendersf You're supposed to follow the instructions for Google Auth. You can no longer use an email and password.

But I cannot leave my browser open forever?

> > > Please note, this problem does not happen with Google Accounts. If you migrate your Nest Account to a Google Account, that will then work fine.
> > 
> > 
> > I migrated to a Google Account but I cannot login using email and password. I use access_token for now. But it should work with just my Google credentials if above information is correct?
> 
> @leendersf You're supposed to follow the instructions for Google Auth. You can no longer use an email and password.

But I cannot leave my browser open forever? It is better to use the access_token that keeps running for 30 days. Right?

**Comment by mrjackyliang** [comment]
> > @leendersf You're supposed to follow the instructions for Google Auth. You can no longer use an email and password.
> 
> But I cannot leave my browser open forever?
> 

@leendersf You don't need to. Simply start an incognito session, follow the directions, and once it starts working again just close the incognito session window without logging out.

**Comment by leendersf** [comment]
> > > @leendersf You're supposed to follow the instructions for Google Auth. You can no longer use an email and password.
> > 
> > 
> > But I cannot leave my browser open forever?
> 
> @leendersf You don't need to. Simply start an incognito session, follow the directions, and once it starts working again just close the incognito session window without logging out.

It worked!! Thank you very much Jacky!!

**Comment by mrjackyliang** [comment]
> > > > @leendersf You're supposed to follow the instructions for Google Auth. You can no longer use an email and password.
> > > 
> > > 
> > > But I cannot leave my browser open forever?
> > 
> > 
> > @leendersf You don't need to. Simply start an incognito session, follow the directions, and once it starts working again just close the incognito session window without logging out.
> 
> It worked!! Thank you very much Jacky!!

@leendersf You're welcome!

**Comment by roninniagara** [comment]
so, i migrated my account to google....

a few quick questions.

the platforms part of the json, where does that go?! im having a hard time getting it to go. i put it at the top under the bridge portion above platforms. homebridge starts, but i see no devices get recognized and none show up in homekit.

also, if my partner logs into nest at his place using firefox, does that screw up my homebridge config then?! i did the incognito mode. but we also use the app a lot and web based....

thanks guys. pretty frustrated :\

**Comment by mrjackyliang** [comment]
@roninniagara The `googleAuth` object should be inside where the Nest Platform is. Nothing that belongs to this plugin should go outside of the Nest object.

**Comment by roninniagara** [comment]
ah ok...

> 
> 
> @roninniagara The `googleAuth` object should be inside where the Nest Platform is. Nothing that belongs to this plugin should go outside of the Nest object.
> 
> And for the question you have about using the web interface, it should be fine. As long as you don't go to Google and remove the device where you logged in from, Incognito or not.

ah ok. so, i added the google auth part to the nest platform.

getting "unexpected token { in json at position 2283"

about to rip out the last few hairs i have, lol :\

**Comment by mrjackyliang** [comment]
> ah ok...
> 
> > @roninniagara The `googleAuth` object should be inside where the Nest Platform is. Nothing that belongs to this plugin should go outside of the Nest object.
> > And for the question you have about using the web interface, it should be fine. As long as you don't go to Google and remove the device where you logged in from, Incognito or not.
> 
> ah ok. so, i added the google auth part to the nest platform.
> 
> getting "unexpected token { in json at position 2283"
> 
> about to rip out the last few hairs i have, lol :\

@roninniagara Check line 2283 and see if you mistakenly put an extra `}`.

**Comment by roninniagara** [comment]
> 
> 
> > ah ok...
> > > @roninniagara The `googleAuth` object should be inside where the Nest Platform is. Nothing that belongs to this plugin should go outside of the Nest object.
> > > And for the question you have about using the web interface, it should be fine. As long as you don't go to Google and remove the device where you logged in from, Incognito or not.
> > 
> > 
> > ah ok. so, i added the google auth part to the nest platform.
> > getting "unexpected token { in json at position 2283"
> > about to rip out the last few hairs i have, lol :\
> 
> @roninniagara Check line 2283 and see if you mistakenly put an extra `{`.

got it. the part  "googleAuth": { 

after that, i had to add one }

got it working! yay!!!!! this all started because of a power outage! just hope the app and web based dont screw my setup over. :P

**Comment by jeffmarcilliat** [comment]
I’m so relieved everyone else is having this issue! Can anyone point me to instructions on how to migrate to Google authentication and then get the info needed for my `config.json`? Thanks!

**Comment by mrjackyliang** [comment]
@jeffmarcilliat There aren't straight forward directions, but you must first migrate Nest to Google account before proceeding.

Then read the README on instructions on retrieving the information, and create an object that goes inside the Nest configuration.

**Comment by jeffmarcilliat** [comment]
Thanks @mrjackyliang. Do you have a sample object so I can make sure it’s correct in my config.json? I’ll do the migration to Google today.

**Comment by mrjackyliang** [comment]
@jeffmarcilliat I can create one on the fly. But try not to copy and paste it cause every configuration is different.

```json
{
    "platform": "Nest",
    "name": "Nest",
    "googleAuth": {
        "issueToken": "",
        "cookies": "",
        "apiKey": ""
    },
    "structureId": "",
    "options": []
}
```

**Comment by starlessblack** [comment]
Ugh, I thought I'd save time for now and just go the API token route, but now that it's back up and running, it's redetected all my Nest devices from scratch, throwing them in the default room and removing them from my scenes and automations :-(

**Comment by jeffmarcilliat** [comment]
I’m reading through https://developers.google.com/identity/protocols/OAuth2. Which scenario does Homebridge fall into? @mrjackyliang

**Comment by mrjackyliang** [comment]
@jeffmarcilliat You're supposed to read [this readme](https://github.com/chrisjshull/homebridge-nest), not the developers manual.

**Comment by jeffmarcilliat** [comment]
Ok yep this is done and works! Thanks @mrjackyliang. I'm assuming I can quit Chrome and that will not log me out? Or do I need to be running Chrome on my Raspberry Pi and repeat these steps?

**Comment by mrjackyliang** [comment]
@jeffmarcilliat Yes, you can quit Chrome now.

**Comment by efipso** [comment]
Hi guys,

I have a question before migrating my account to Google:
If I restart my homebridge, I have to reconfigure it? I mean do again all about getting the apikey, cookies and all this stuff

I restart it once a week and I don't want to do all this every time I restart it. If that's the case, for me it's better to stay on a nest account and renew the token every month...

Thanks to all!

**Comment by mrjackyliang** [comment]
@efipso No you won't need to. As long as you don't remove the login session from the Google My Account area you are good.

The whole point of using Incognito is to isolate all the cookies in one session and to destroy them locally so you don't accidentally mix the login session up with Homebridge.

**Comment by rpersche** [comment]
Hello, thanks for the information. I am still reluctant to migrate my Nest account to Google since IFTTT warns users not to do so in Aug 2019 (https://help.ifttt.com/hc/en-us/articles/360022524734-Important-update-about-the-Nest-services). However, I came across this blog entry from Google https://blog.google/products/google-nest/works-with-nest  where they talk about. "_We’ll also invite smart home developer enthusiasts to participate in our Device Access for Individuals sandbox, allowing you to directly control your own Nest devices for your private integrations and automations._"
I will stick to the monthly access_token for now. Thanks!

**Comment by mriksman** [comment]
I've successfully migrated to googleAuth. But the Nest items are not appearing in Home...?
```
[1/20/2020, 1:50:44 PM] [Nest] initing thermostat "Guest": deviceId: 02AA01AC0615098N structureId: 0de15b80-015c-11e5-9cdc-22000b1e805f
[1/20/2020, 1:50:44 PM] [Nest] Initializing platform accessory 'Guest'...
```

**Comment by ekobres** [comment]
> So sorry about all of this. Since this morning, Nest is now using a Google Recaptcha service **for Nest accounts**. If the Google-generated Recaptcha token is missing from the log-in API call (as it is in homebridge-nest), the log-in will fail. This is what is happening.
> 
> Right now, if you have a Nest Account, the best workaround is to use the access token method as described by @DJBenson above.
> 
> _Please note, this problem does not happen with Google Accounts. If you migrate your Nest Account to a Google Account, that will then work fine._

It looks like we're stuck with this and it looks like it probably affects most if not all homebridge-nest users. You might want to update readme.md with the most up-to-date info. It still recommends a Nest account with username/password. I had to go through a lot of troubleshooting before I found this issue in Github - after carefully looking for the answer in readme. 

Cheers!

**Comment by gdotp01** [comment]
Well I was struck yesterday by this anti-competitive action by google. Ive temporality re-authenticated by moving my next to google but I will be looking for an non-google solution now and making sure that i don't use any google products any longer .

**Comment by h00pak** [comment]
> So sorry about all of this. Since this morning, Nest is now using a Google Recaptcha service **for Nest accounts**. If the Google-generated Recaptcha token is missing from the log-in API call (as it is in homebridge-nest), the log-in will fail. This is what is happening.
> 
> Right now, if you have a Nest Account, the best workaround is to use the access token method as described by @DJBenson above.
> 
> _Please note, this problem does not happen with Google Accounts. If you migrate your Nest Account to a Google Account, that will then work fine._

Are you saying that I can migrate the account and then the email address solution will work again? Thanks.

**Comment by mrjackyliang** [comment]
@h00pak You must follow the Google Account directions in the README located on this repository.

**Comment by Nate872711** [comment]
The googleAuth method doesn’t work for me.  The config.json is correct also but it still won’t authenticate.  I get a bunch of errors in red when running homebridge from terminal.

I can use the access_token method instead just fine though.

**Comment by Nate872711** [comment]
The googleAuth method doesn’t work for me. The config.json is correct also but it still won’t authenticate. I get a bunch of errors in red when running homebridge from terminal.

Unhandled rejection StatusCodeError: 401 - {"error":{"code":401,"message":"Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.","status":"UNAUTHENTICATED"}}
    at new StatusCodeError (/usr/local/lib/node_modules/homebridge-nest/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/homebridge-nest/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/homebridge-nest/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-nest/node_modules/request/request.js:185:22)
    at Request.emit (events.js:197:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:197:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:285:13)
    at IncomingMessage.emit (events.js:202:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)

I can use the access_token method instead just fine though.

**Comment by mrjackyliang** [comment]
@Nate872711 If you can use the access token just fine, then you didn't migrate your Nest account to a Google account yet.

Nest accounts migrated to Google cannot use `access_token`.

**Comment by Nate872711** [comment]
@mrjackyliang  I migrated to Google a while back, so that doesn't make any sense.  It has 2fa and everything.

**Comment by mrjackyliang** [comment]
@Nate872711 It could possibly be that the values pasted are wrong. I also have 2FA on my Google account, and it works perfectly.

**Comment by Nate872711** [comment]
@mrjackyliang  What is the structureId for?  I didn't have that in my format.

**Comment by mrjackyliang** [comment]
@Nate872711 `structureId` is for defining the home that is hosting the specific thermostats. Some have two homes, so the ID would basically separate them.

It's optional, but I included it in my config just for re-enforcement.

**Comment by kcprice11** [comment]
I'm debating migrating my nest protects to a google account.  My question is,  if I migrate and get it all working and use the incognito session as specified above, will I have to redo this setup if I reboot my pi?  If so, I think I will skip it. I already bought an ecobee for several reasons, not the least of which is Googles position on stuff like this.  But I still own some Nest protect devices and would like to see them in HomeKit.  If after getting it setup (Which seems like a pain) I have to redo the setup every time I boot my pi, I think I will skip it.  

thanks

**Comment by mrjackyliang** [comment]
@kcprice11 No you won't need to redo your setup unless you:

1. Logged out while in Incognito mode.
2. Removed the logged in device in Google.
3. Reset your Homebridge.

I've said this throughout the thread already.

**Comment by kcprice11** [comment]
Thank you






> @kcprice11 No you won't need to redo your setup unless you:
> 
> 1. Logged out while in Incognito mode.
> 2. Removed the logged in device in Google.
> 3. Reset your Homebridge.
> 
> I've said this throughout the thread already.

Thank you

**Comment by Nate872711** [comment]
@mrjackjyliang  I got it working with googleAuth finally.  I had to sign out of all devices and resign in with the Google account.  Thanks for the help.

**Comment by mrjackyliang** [comment]
@Nate872711 That's definitely worth mentioning to future readers. Thanks!

**Comment by adriancable** [comment]
Closing now 4.4.0 is released.
