### ISSUE TITLE
Disallow changes to thermostat mode (Heat, Off, Heat and Cool)

### ISSUE THREAD

**Issue by thirdopticaltool** [chrisjshull/homebridge-nest#197]
Siri is often turning the whole system off entirely instead o just setting the temperature 1º lower than the ambient temp. Or turning on the AC instead of just turning off the heat. 

If it doesn't already exist, ideally there'd be a flag to disallow any mode changes – if I literally never want Siri to be able to stupidly change the mode and only want mode changes to happen manually. 

Any other way to solve this infuriating issue of Siri interpreting statements like "set the temperature one degree lower" to mean "Turn the AC on in the middle of winter"?

**Comment by adriancable** [comment]
@thirdopticaltool - this is probably not the answer you want to hear, but you could just not say things to Siri that it can't interpret correctly.

Siri (compared with e.g. Alexa) is famously bad at doing the wrong thing if you don't phrase things as it expects. For example, with thermostats the only way to set the temperature is to specify the target temperature exactly, e.g. Hey Siri, set the thermostat to 65 degrees. If you do this, you will be fine.
