### ISSUE TITLE
Motion Sensor not resetting 

### ISSUE THREAD

**Issue by rhy5davie5** [chrisjshull/homebridge-nest#201]
My only Wired version of the Protect ( I have 2 battery versions) are reporting ‘motion detected’ on the device in the Home App, which is great. But the motion doesn’t ‘reset’ and remains on ‘motion detected’. Other homebridge motion sensors are resetting after 1 sec etc.

**To Reproduce**
1. Trigger a motion on a wired protect sensor and see the change in the iOS Home App.

Running latest version of homebridge and homebridge-Nest plugin.

**Comment by rhy5davie5** [comment]
OK so it seems to be resetting but takes an absolute age to reset. A good 10-15 minutes.

**Comment by rhy5davie5** [comment]
Timed it and it’s not far off a crisp 10 minutes to the second.

**Comment by adriancable** [comment]
The motion sensor is an undocumented feature of the Nest Protect, and unfortunately that's just how it seems to work! It triggers very quickly, but then takes 10 minutes to reset.
