### ISSUE TITLE
Eco switch

### ISSUE THREAD

**Issue by djrams10** [chrisjshull/homebridge-nest#202]
Hello, in config I have not put any option and I do not have the Eco switch. Could you help me? thanks

**Comment by adriancable** [comment]
@djrams10 - can you post a screenshot of your thermostat in the Home app? I don't understand how the Eco switch can be missing. Thanks!

**Comment by djrams10** [comment]
It's good he came back thank you.  On the other hand I have another problem which arose I do not know if it comes from your plugin.
 After a certain time The value corresponding to the eco temperature changes on its own and returns to the temperature at which my thermostat is set without it being in eco mode.
 For example when I set the eco temperature to 16 ° and the normal temperature of my thermostat is 21 °, the temperature value of the eco mode changes to be 21 °.  Is this a known problem on your side?  Thank you

**Comment by adriancable** [comment]
@djrams10 - which version of the plug-in are you using?

**Comment by djrams10** [comment]
3.5.1

**Comment by adriancable** [comment]
Please upgrade to 4.4.0. That should fix your issue.

**Comment by djrams10** [comment]
Thanks
