### ISSUE TITLE
Devices in 2 homes appear in the same home

### ISSUE THREAD

**Issue by lucanaut** [chrisjshull/homebridge-nest#203]
Hello I have updated everything with my google account (migrated from nest).  The devices appear in my home app fine, but so do the devices from my parents' house (of which I am a part of).  Worst case scenario I can create a room and put them in there - just wondering if there is a way to either exclude them or move them to their home in my home app or....what else would you do with them?

**Comment by adriancable** [comment]
Hi - yes, you can either put them in a Room, or you can set the structureId field in config.json to select just one single home (and ignore the devices from the other home). Instructions are in the README. Good luck!
