### ISSUE TITLE
Protect - Smoke & CO2 Detection - Cleared

### ISSUE THREAD

**Issue by inetjnky** [chrisjshull/homebridge-nest#206]
When creating automations for the Nest Protects, I see an available automation for smoke detected and co2 detected, however there is no automation for smoke detection cleared and co2 detection cleared?  The only option in the detected states is Turn off Never or after a period of time.  It would be useful to have this setting set to never, and then create a new automation for "Stops Detecting" like there is for motion.

**Comment by muzzymate** [comment]
Unfortunately, Apple would have to implement and support this request. It might be possible using a third party Homekit app, but your requested automation is not supported using Apple's Home app.
