### ISSUE TITLE
Issues after 4.4 upgrade

### ISSUE THREAD

**Issue by baja0006** [chrisjshull/homebridge-nest#207]
Getting this in logs:
Feb 18 13:08:09 raspberrypi homebridge[2718]: [2020-2-18 13:08:09] [Nest] TypeError: this.updateData(...).then(...).catch(...).finally is not a function
Feb 18 13:08:09 raspberrypi homebridge[2718]:     at Connection.dataTimerLoop (/usr/lib/node_modules/homebridge-nest/lib/nest-connection.js:1123:15)
Feb 18 13:08:09 raspberrypi homebridge[2718]:     at resolve (/usr/lib/node_modules/homebridge-nest/lib/nest-connection.js:1177:14)
Feb 18 13:08:09 raspberrypi homebridge[2718]:     at new Promise (<anonymous>)
Feb 18 13:08:09 raspberrypi homebridge[2718]:     at Connection.subscribe (/usr/lib/node_modules/homebridge-nest/lib/nest-connection.js:1176:12)
Feb 18 13:08:09 raspberrypi homebridge[2718]:     at NestPlatform.accessories (/usr/lib/node_modules/homebridge-nest/index.js:144:29)
Feb 18 13:08:09 raspberrypi homebridge[2718]:     at <anonymous>
Feb 18 13:08:09 raspberrypi homebridge[2718]:     at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by adriancable** [comment]
What version of node are you using? My suspicion is an old one, before they added a native finally to promises.

**Comment by baja0006** [comment]
Updated to 12.16.0 and that resolved the issue - thank you!

**Comment by DMBlakeley** [comment]
Running node 12.6.1, using Nest login (not transitioned to Google) and have refreshed access token. Getting following errors:

`[2/19/2020, 3:50:36 PM] [Nest] API observe: resolving null, code { details: [], code: 4, message: 'context timed out' }`

and

`
[2/19/2020, 4:26:01 PM] [Nest] API observe: error Error [ERR_HTTP2_STREAM_ERROR]: Stream closed with error code NGHTTP2_INTERNAL_ERROR
    at ClientHttp2Stream._destroy (internal/http2/core.js:2148:13)
    at ClientHttp2Stream.destroy (internal/streams/destroy.js:38:8)
    at ClientHttp2Stream.[kMaybeDestroy] (internal/http2/core.js:2164:12)
    at Http2Stream.onStreamClose (internal/http2/core.js:511:26) {
  code: 'ERR_HTTP2_STREAM_ERROR'
}`
