### ISSUE TITLE
Nest hello

### ISSUE THREAD

**Issue by remko2000** [chrisjshull/homebridge-nest#208]
I installed today versio 4.4.0. I've 2 protects and a themostate. The works fine with this plugin. I bought a nest hello and want to use this one also with in homebridge/homekit. I already installed Homebridge Camera Ffmpeg. How do I adjust my config with this camera?

**Comment by adriancable** [comment]
We don't support Nest cameras.

**Comment by remko2000** [comment]
I'm a little confused. I read in the readme:

> # homebridge-nest
Nest plug-in for [Homebridge](https://github.com/nfarina/homebridge) using the native Nest API. See what's new in [release 4.0.0](https://github.com/chrisjshull/homebridge-nest/releases/tag/v4.0.0).

Integrate your Nest Thermostat (including Nest Temperature Sensors), Nest Protect and Nest Cameras **(including Nest Hello doorbell)** devices into your HomeKit system. Both Nest Accounts (pre-August 2019) and Google Accounts are supported.

Currently, homebridge-nest supports all Nest Thermostat, Protect and Camera models, now including the EU/UK model of the Thermostat E with Heat Link. Nest Secure/Detect support may come later. (I don't currently own those devices.)

So I don't understand.

**Comment by adriancable** [comment]
@remko2000 - where did you find that README? 4.0.0 was never released publically. Yes, there were alpha versions of this plug-in floating around that had some camera support using hacked homebridge configurations. But, that was never released.

Please use the official 4.4.0 homebridge-nest, and the latest homebridge-nest-cam for your cameras. It isn't a great experience with the cameras, but it's the best there is right now.

**Comment by HammerAce42** [comment]
Is there a plan to at least land the motion/person/sound sensing pieces of Nest Hello into an official build in the near future? Those don't appear to be supported by homebridge-nest-cam, and they are more important than the actual images/audio coming through to homekit. I am using the homebridge-nest-fletchto99 fork until the motion sensing pieces land in the official build.
