### ISSUE TITLE
TypeError? Please make sure you are using a modern NodeJS version

### ISSUE THREAD

**Issue by woodgieboodgie** [chrisjshull/homebridge-nest#209]
Upgrade went successfully, however now getting following error when Homebridge starts:
![Capture](https://user-images.githubusercontent.com/52473319/74816270-e4d5e900-534e-11ea-84ed-14d613b520d0.JPG)

**Comment by danhausman** [comment]
I have the same issue.

[2020-2-19 08:05:54] [Nest] TypeError: this.updateData(...).then(...).catch(...).finally is not a function
    at Connection.dataTimerLoop (/usr/lib/node_modules/homebridge-nest/lib/nest-connection.js:1123:15)
    at resolve (/usr/lib/node_modules/homebridge-nest/lib/nest-connection.js:1177:14)
    at new Promise (<anonymous>)
    at Connection.subscribe (/usr/lib/node_modules/homebridge-nest/lib/nest-connection.js:1176:12)
    at NestPlatform.accessories (/usr/lib/node_modules/homebridge-nest/index.js:144:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by adriancable** [comment]
This is because you are using a very old version of Node - please upgrade. For production applications, 12.16.1 LTS is recommended.

Pinning this so others can see.

**Comment by perote2000** [comment]
Works fine on mine

**Comment by danhausman** [comment]
yeah, guilty, i was using node 8 on my raspberry pi....    I was lazy, what can I say.  If anyone else is being lazy like me...  [https://github.com/nodesource/distributions#debinstall](https://github.com/nodesource/distributions#debinstall)   You can upgrade your pi here. 

Adrian, thank you for the help and the nudge in the right direction.

**Comment by perote2000** [comment]
I recommend you to install homebridge under docker container (https://github.com/oznu/docker-homebridge). 
You are able to periodically update image, with components already installed in the image... if you upgrade image, all configs and plugins resides outside it... so no need to reinstall...

I previously used your way... but In my opinion is better and easy to maintain with docker.

**Comment by sdevo619** [comment]
I ran this from the Homebridge main page instructions, but did not fix the issue. Do I need to install a specific version of nodeJS???
node --version

**Comment by adriancable** [comment]
What version of node are you using?

**Comment by sdevo619** [comment]
While appreciate your help very much, your advice to update nodeJS jacked up my installation, to where, I had to uninstall nodeJS and now I can't get it to reinstall. Any ideas on how to fix this??
bash: npm: command not found

**Comment by adriancable** [comment]
First try here to install node: https://nodejs.org/en/download/

If that doesn't work, tell me what command(s) you're typing to try to install node, along with what platform you're running on, and I'll try to help.

**Comment by sdevo619** [comment]
Again, thank you very much!!! Just because I am impatient, I decided to dump the entire docker image and restart from a fresh one. Unfortunately, the same issue still persists, even on a fresh install. This is the update command I am running.
![image](https://user-images.githubusercontent.com/7008354/75595652-272fb200-5a42-11ea-9b90-da5b44d4b365.png)


I am also seeing this error message after updating to the newer version of nodejs, and this was also why I scrapped the previous docker image.

![image](https://user-images.githubusercontent.com/7008354/75595680-37479180-5a42-11ea-8582-62d75fda6532.png)
Any ideas??

**Comment by sdevo619** [comment]
I also tried to install NodeJS12 and 13 and am still having the same problem. I am pretty sure this is an issue with your plugin from what I can tell so far.

**Comment by sdevo619** [comment]
Ok, I got it to work. Not sure what I did differently, but I blew out the entire homebridge config again, followed the same steps. This is what I have in the startup script, were it is now working related to node. Thanks again for your help today. 

node --version
npm i -g npm

**Comment by gdotp01** [comment]
Hi. Im seeing this error too and now know its a version issue with Node.

My Pi is running V9.7.1 

However I can't see how to update node. When I try the link above (https://nodejs.org/en/download/)  I get the error 
"You appear to be running on ARMv6 hardware. Unfortunately this is not currently supported by the NodeSource Linux distributions. Please use the 'linux-armv6l' binary tarballs available directly from nodejs.org for Node.js 4 and later."

Not being debian/Linux expert Im now stumped. 

Any help would be very appreciated. 

G.P

**Comment by gdotp01** [comment]
Ok I managed after some faffing to get it upgraded to 11.9 but that appears to be the last version supported on armv6. It fixed the issue but I’m still getting a very occasional error in the log file from the nest plugin.

**Comment by gdotp01** [comment]
STET the above. I can see that this is a reported issue already so i've commented in the relevant report

**Comment by adriancable** [comment]
Unpinning this - 4.4.4 adds a polyfill to support older Node versions.
