### ISSUE TITLE
My nest is added to Home App but it is not updating

### ISSUE THREAD

**Issue by alifmusa** [chrisjshull/homebridge-nest#210]
Hi, I recently added nest to my home kit, but it is not updating. The ambient temperature is 68F on Nest and temperature is set to 72F. But HomeKit is saying that the temperature is 70F and it is cooling to 69F.

**Comment by adriancable** [comment]
What version of the plug-in are you using?

Have you tried restarting the Home app on iOS? (force close it, then re-open it)

If this doesn't work, then please edit your config.json, and below "platform": "Nest" put:

"options": [ "Debug.Verbose" ],

Then run: homebridge -D

Then when the problem happens, send me the full output from homebridge, along with a description of what the temperature settings really are, vs. what HomeKit is saying they are.

**Comment by alifmusa** [comment]
I'm using 3.5.2

I believe the problem I was encountering was due to access_token. I tried that method despite having a google account for nest. I think it worked once and then it didnt. So I just have to configure the the googleAuth but when I follow the steps to find my googleAuth, I dont get any network calls on my dev tools window in google chrome.

**Comment by adriancable** [comment]
@alifmusa - (1) update to the latest version, (2) clear your Chrome cache then follow the steps again to find your googleAuth. The steps do work as listed. Good luck!
