### ISSUE TITLE
Additional errors since update to 4.4.0

### ISSUE THREAD

**Issue by DMBlakeley** [chrisjshull/homebridge-nest#211]
**Describe the bug**
Since the latest update to home bridge-nest I am getting errors such as:

`[2/19/2020, 3:50:36 PM] [Nest] API observe: resolving null, code { details: [], code: 4, message: 'context timed out' }`

and
`
[2/19/2020, 4:33:17 PM] [Nest] API observe: error Error [ERR_HTTP2_STREAM_ERROR]: Stream closed with error code NGHTTP2_INTERNAL_ERROR
    at ClientHttp2Stream._destroy (internal/http2/core.js:2148:13)
    at ClientHttp2Stream.destroy (internal/streams/destroy.js:38:8)
    at ClientHttp2Stream.[kMaybeDestroy] (internal/http2/core.js:2164:12)
    at Http2Stream.onStreamClose (internal/http2/core.js:511:26) {
  code: 'ERR_HTTP2_STREAM_ERROR'
}`

The Nest thermostat and Protect seem to be providing status correctly. I am using Nest.com account to login. I have not transitioned to Google. I have also updated my Nest access token as a troubleshooting step.

Running:
node --12.16.1
homebridge --0.4.50

**Comment by adriancable** [comment]
The first is not an error - it's completely normal, and part of the API flow.

The second - not precisely sure what this is but the plug-in should recover seamlessly from HTTP2 errors so this should have no impact on functionality.

**Comment by adriancable** [comment]
@DMBlakeley - regarding the NGHTTP2_INTERNAL_ERROR, I need to see what is happening around that in more detail. Please can you edit your config.json, and under "platform": "Nest", insert:

"options": [ "Debug.Verbose" ],

Then run: homebridge -D

Then leave it running for a while, and after you get this error again, email me the complete output to: adrian.cable@gmail.com

Thanks!

**Comment by andy-dinger** [comment]
> The first is not an error - it's completely normal, and part of the API flow.
> 

Although normal, the previous message "Reauthenticating on Nest service ..." was slightly more user-friendly!

**Comment by DMBlakeley** [comment]
Adrian,

I have run in diagnostic mode now for several days and have not been able to catch the NGHTTP2_INTERNAL_ERROR in the terminal log.

Regards,
Doug

---
Douglas Blakeley
Douglas.Blakeley@gmail.com

**Comment by gdotp01** [comment]
Im seeing this error too. 
[Nest] API observe: resolving null, code { details: [], code: 4, message: 'context timed out' }

Its happened since the latest update. All seems to be working ok however
