### ISSUE TITLE
Nest Hello Doorbell support

### ISSUE THREAD

**Issue by novemTeam** [chrisjshull/homebridge-nest#216]
**Is your feature request related to a problem? Please describe.**
I have 2 Nest Hello doorbells, but I am annoyed by the fact that I can't add it to Homekit. There are no notifications for doorbell rings.

**Describe the solution you'd like**
Would be nice to let the camera in HomeKit actually be a doorbell.

**Additional context**
I know the Starlink hub can do it, but I thought I would be able to use Hoobs, but it doesn't really do what I want. The Starlink hub is expensive...

**Comment by novemTeam** [comment]
I see that you are waiting for HAP-NodeJS to support cameras, but the camera shows up in HomeKit, it's just not a doorbell with ring notifications/sensor.

**Comment by adriancable** [comment]
@novemTeam - if Nest cameras show up in HomeKit, it has nothing to do with this plug-in, which does not support cameras. Maybe you are using homebridge-nest-cam? We are not affiliated with that, so maybe you want to redirect your question to their GitHub issues page.

**Comment by novemTeam** [comment]
Yes indeed, my bad. I was looking at the wrong git.

But I also have npm added to Hoobs, but is it possible to add doorbell support? 
I only have the home switch in homekit with this. 

Adding the Nest Hello would be nice.
