### ISSUE TITLE
Having a hard time using "options"

### ISSUE THREAD

**Issue by ericdhkim** [chrisjshull/homebridge-nest#218]
This is probably not an issue, but user error, but nevertheless, I'm having a hard time utilizing the "options" feature of the plugin

> {
            "platform": "Nest",
            "googleAuth": {
                "issueToken": xxx,
                "cookies": xxx,
                "apiKey": xxx,
                "options": [
                    "Thermostat.Fan.Disable",
                    "Thermostat.Eco.Disable",
                    "HomeAway.Disable"
                ]
            }
        },

> 

I've been enjoying using the plugin just fine and it still works okay, but even with the three options I've placed, the accessories for fan, eco, and home/away occupancy still appear in the Home app. Am I doing something wrong here?

**Comment by adriancable** [comment]
"options" goes outside "googleAuth", not inside it. The only things inside "googleAuth" should be "issueToken", "cookies" and "apiKey".
