### ISSUE TITLE
Could not authenticate with Nest (code ENORECAPTCHA).  Retrying in 15 second(s).

### ISSUE THREAD

**Issue by dawger1** [chrisjshull/homebridge-nest#219]
Rebooted my Homebridge server running on a raspberry pi just now, and upon rebooting, the homebridge service will not restart because of what appears to be an authentication error with Nest. Has anybody else seen this?  If so, how did you fix it?  

I’m running homebridge-next v4.4.0 on Homebridge v0.4.50.

**Comment by adriancable** [comment]
@dawger1 - please read the README. You can't authenticate on Nest using username and password any more. You need to use an access token.

**Comment by dawger1** [comment]
Sorry to waste your time. Updated and all is well again. Thank you for your great work!
