### ISSUE TITLE
Only Nest Thermostat shows as an accessory

### ISSUE THREAD

**Issue by MrGreen718** [chrisjshull/homebridge-nest#220]
I am currently using homebridge on unraid as a docker. I have been able to get the nest account setup in homebridge but it is only seeing my thermostat. I have 2 cameras and a nest doorbell and a nest guard security system that are not showing. Can you help me with this?

config.json is below.

> {
>     "bridge": {
>         "name": "Homebridge",
>         "username": "CC:22:3D:E3:CE:30",
>         "port": 51826,
>         "pin": "031-45-154"
>     },
>     "description": "This is an example configuration file with gui. You can use this as a template for creating your own configuration file containing devices you actually own.",
>     "accessories": [],
>     "platforms": [
>         {
>             "platform": "config",
>             "name": "Config",
>             "port": 8124,
>             "sudo": true
>         },
>         {
>             "platform": "Nest",
>             "googleAuth": {
>                 "issueToken": "XXXXXXXXXXXXXXXX",
>                 "cookies": "XXXXXXXXXXXXXXXXXX",
>                 "apiKey": "XXXXXXXXXXXXXXXXXXXX"
>             }
>         }
>     ]
> }
> 
>

**Comment by adriancable** [comment]
We do not support cameras or Nest Guard. Sorry! Check the README for full details of supported devices.
