### ISSUE TITLE
Chrome extention for Google Account

### ISSUE THREAD

**Issue by EjvindHald** [chrisjshull/homebridge-nest#221]
I am having some difficulties in finding the keys for my Google account, as you write.

Therefore, I am asking if it is possible to make a Google Chrome extension, which will simply show the issueToken, cookies and apiKey. This is suggested in [this ](https://github.com/oznu/homebridge-config-ui-x/issues/582)thread.

**Comment by EjvindHald** [comment]
It is working fine now - you do not have to do anything. However, a Chrome extension with a simple display of the values for copy/paste would make it easier.
Thank you very much for this contribution - it is highly appreciated.

**Comment by adriancable** [comment]
It's definitely possible to write a Chrome extension to do this, and I welcome anyone who wants to give this a shot, so I'll leave this open for a while.

**Comment by mbierman** [comment]
Could this be done simply with a bookmarklet that you use after logging in to nest? That might reduce the effort considerably.
