### ISSUE TITLE
Push config.schema.json to npm?

### ISSUE THREAD

**Issue by donavanbecker** [chrisjshull/homebridge-nest#222]
**Is your feature request related to a problem? Please describe.**
No, but if you push this to npm like version 4.4.1.... then it will be available on config ui x

**Describe the solution you'd like**
want [config.schema.json](https://github.com/chrisjshull/homebridge-nest/blob/master/config.schema.json) pushed to npm maybe 4.4.1? so it can be used.

**Describe alternatives you've considered**
v4.5.0?

**Additional context**
@adriancable this would be nice! Thanks!

**Comment by adriancable** [comment]
@donavanbecker - when the next version of the plug-in gets pushed to npm (in the next day or so), the config file will be included. Hope this helps!

**Comment by donavanbecker** [comment]
@adriancable Thanks for doing this!

**Comment by adriancable** [comment]
Not at all, thanks for your contribution!
