### ISSUE TITLE
Plugin not adding thermostat Google account. 

### ISSUE THREAD

**Issue by daniel4099** [chrisjshull/homebridge-nest#223]
Hi

I have a problem. While loading thermostat plugin. 

Please see below Screen. 
![46965946-E29C-495E-AAA9-41222182A48D](https://user-images.githubusercontent.com/25808596/76173215-b99c2800-619d-11ea-9ca5-398609ae0944.jpeg)

**Comment by adriancable** [comment]
@daniel4099 - please help keep the issues list tidy by not filing duplicate issues, especially duplicates of a pinned issue. Thank you!
