### ISSUE TITLE
Support multiple Nest accounts

### ISSUE THREAD

**Issue by tknoblau** [chrisjshull/homebridge-nest#224]
**Is your feature request related to a problem? Please describe.**
I want to connect to 2 different Nest accounts.

**Describe the solution you'd like**
Ideally, the plugin would support a list of account credentials.

**Describe alternatives you've considered**
I tried duplicating the Nest platform config giving them unique names each. This does not work however and home bridge fails to start. I tested that my account configs (using access_token) work individually, but they do not work both at the same time.
I have considered forking your repo and installing a clone if this plugin under a separate plugin ID, but I am just starting out with home bridge and don't know where to start with that.

**Additional context**
It is not possible to merge the devices into the same Nest account.

**Comment by adriancable** [comment]
Have you tried running two instances of Homebridge on different ports?

**Comment by tknoblau** [comment]
Duh... that is actually an awesome idea. Never thought of it myself, but works exceptionally well.
