### ISSUE TITLE
Reoccurring error in logs

### ISSUE THREAD

**Issue by notorioustubze** [chrisjshull/homebridge-nest#225]
Hello, I keep getting an error over and over, thermostat still shows in Home app and can still be controlled via Siri/home app so not sure what’s wrong. Please help :) TIA
![EAE96F2A-409E-415E-B187-563BD496297F](https://user-images.githubusercontent.com/53260708/76389917-527ca000-6364-11ea-8181-eb7bebc9bf1a.png)

**Comment by adriancable** [comment]
@notorioustubze - you can ignore this. It isn't an error, and this message should not be displayed. It was fixed a little while ago, but it looks like HOOBS is out of date.
