### ISSUE TITLE
Error updating the plugin

### ISSUE THREAD

**Issue by leendersf** [chrisjshull/homebridge-nest#226]
**Describe the bug**
Updating the plugin results in this error:
USER: root
DIR: /homebridge
CMD: npm install --save homebridge-nest@latest

npm WARN enoent ENOENT: no such file or directory, open '/homebridge/node_modules/homebridge-gsh/node_modules/hap-node-client/node_modules/fsevents/package.json'

npm ERR! code EISGIT
npm ERR! path /homebridge/node_modules/homebridge-gsh/node_modules/hap-node-client
npm ERR! git /homebridge/node_modules/homebridge-gsh/node_modules/hap-node-client: Appears to be a git repo or submodule.
npm ERR! git     /homebridge/node_modules/homebridge-gsh/node_modules/hap-node-client
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-11T18_47_57_273Z-debug.log

Command failed. Please review log for details.

**To Reproduce**
1. I update on my Raspberry 3 using the update plugin button.

**Expected behavior**
Normally it updates fine..

Include with your bug report this version info:
```sh

Node.js Version | v12.14.1
npm version v6.13.4
-- | --
homebridge --version
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

**Comment by adriancable** [comment]
This error is coming from homebridge-gsh, whatever that is, so I would look there. I'm not sure what the issue is, but I'm not familiar with homebridge-gsh.

Also you talk about an "update plug-in button". I'm not familiar with such a button, but it sounds like a third-party piece of software. Maybe the issue is there.
