### ISSUE TITLE
Nest Google Accounts Expired Issue?

### ISSUE THREAD

**Issue by mrjackyliang** [chrisjshull/homebridge-nest#228]
**Describe the bug**
I noticed when I came home, the automation to turn on the thermostats did not run. When I checked the Homebridge logs, it appears that the value is wrong?

**To Reproduce**
1. Set thermostat to any temperature.

**Expected behavior**
To have temperature changed.

Include with your bug report this version info:
```sh
node v12.14.1
homebridge v0.4.52
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
```
[3/12/2020, 9:20:17 PM] [Nest] Setting heating threshold temperature to 12.8 °C / 55 °F
[3/12/2020, 9:20:17 PM] [Nest] Setting heating threshold temperature to 21.1 °C / 70 °F
[3/12/2020, 9:20:17 PM] [Nest] Setting temperature to 25.3 °C / 77.5 °F
[3/12/2020, 9:20:17 PM] [Nest] Setting heating threshold temperature to 21.1 °C / 70 °F
[3/12/2020, 9:20:17 PM] [Nest] Setting temperature to 25.3 °C / 77.5 °F
[3/12/2020, 9:20:17 PM] [Nest] Setting cooling threshold temperature to 29.400000000000002 °C / 85 °F
[3/12/2020, 9:20:17 PM] [Nest] Setting cooling threshold temperature to 29.400000000000002 °C / 85 °F
[3/12/2020, 9:20:17 PM] [Nest] Setting cooling threshold temperature to 29.400000000000002 °C / 85 °F
```

**Comment by mrjackyliang** [comment]
I was browsing earlier logs that the plugin was complaining the `googleAuth` config was wrong, so I set up the Google authentication again and it worked.

@adriancable Not sure why, but I thought it was weird since you told me the cookies don't expire? I haven't touched the Google accounts login since I created the keys for the plugin.

Will be keeping this open, just in case anyone comes across it.

**Comment by mrjackyliang** [comment]
It doesn't seem like anyone's having this issue, so I'll just self-close it for now.

**Comment by andrewgribben** [comment]
Just happened to me today and I'm also on the same versions of the plugin and homebridge

**Comment by mrjackyliang** [comment]
Interesting to know! Any word out on this @adriancable?

**Comment by seldridge1** [comment]
This has happened to me twice in the last couple of weeks.

**Comment by pponce** [comment]
Happened to me as well.
I went through the Google authentication steps again to get things working again.
For me this issue actually stopped homebridge from loading completely. 
It would hang during startup.
Once i fixed the authentication issue homebridge loaded up fine.

**Comment by timothymiller** [comment]
> I went through the Google authentication steps again to get things working again.

Any word on how frequently you need to re-run the steps to receive a new token?

**Comment by Sylanorr** [comment]
Same problem here ...
Every 3-4 days I need to add a new token because the actual one expired.

**Comment by mrjackyliang** [comment]
I haven't changed my token since I last posted this issue. About 17 days ago.

**Comment by efipso** [comment]
I had this problem this weekend. Token configured since 13th January.
Reconfigured and working again, but if this would be recurrent it will be good to know when it will happen again and update de readme with something like "This token will work for X months".

**Comment by mrjackyliang** [comment]
I believe it has to do with Google re-asking for the password once in a while, which leads to the invalidation of the cookies.

It may just be random, but I'm sure it will get invalidated much more often if you use the account in public places.

**Comment by adriancable** [comment]
I don't know how long the cookies last. From @efipso they must last at least 10 weeks, but I wonder if Google did some back-end upgrade and invalidated a whole bunch of cookies, causing a block of plug-in users to have to log in again recently?

**Comment by efipso** [comment]
> 
> 
> I believe it has to do with Google re-asking for the password once in a while, which leads to the invalidation of the cookies.
> 
> It may just be random, but I'm sure it will get invalidated much more often if you use the account in public places.

I've been configuring Google account on new devices a few days before, maybe that's the cause (at least on my side). But it's curious that happened on many people at the same time

**Comment by neilmorton** [comment]
Just to add that I have also seen this happen. 

All has been working fine since I swapped to the Google auth instead of Nest, however today I updated Homebridge Config UI X and restarted Homebridge, after which the logs were showing an authentication issue with Google.

Went through the steps to re-create the auth keys, updated them, and now all is running fine again.

**Comment by tooh** [comment]
+1

**Comment by mrjackyliang** [comment]
@neilmorton Mine as been running fine since I first created this issue. I'm going to keep this open as a timestamp.

So far it is been over a month, and I have not been logged out yet.

@tooh Please don't create comments with `+1` in them. Everyone receives notifications that have no meaning. GitHub isn't a forum. I mean no harm, just as a reminder, thanks.

**Comment by neilmorton** [comment]
@mrjackyliang Thanks. Will keep and eye on this, and like you say having this here gives us timestamps.

I guess what strikes me is that perhaps we don't see the 'log out' until we restart the service. Just a thought.

**Comment by mrjackyliang** [comment]
@neilmorton Yeah, it's very surprising.

The curious part about the issue is that the plugin only detects one instance of a log out instead of the entire log being plagued with it (not sure if it's a pro or con🤔, but anyways), it just inherently stops working.

I only notice it, because when I came home, my thermostats are still in the OFF position. And so I just wonder. But, we'll start counting down to our logouts and timestamp them here in this issue.

**Comment by neilmorton** [comment]
@mrjackyliang Yes, lets keep a track of our logouts here.

**Comment by themainframe** [comment]
Think I ran into this issue last night. The most annoying aspect is that the rejection of the promise doing the auth appears to be unhandled so it crashed out and seemed to mess up other bits of Homebridge for me:

```[4/20/2020, 10:25:44 PM] [Nest] Reauthenticating on Nest service ...
Unhandled rejection StatusCodeError: 401 - {"error":{"code":401,"message":"Request had invalid authentication              credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-  project.","status":"UNAUTHENTICATED"}}
 at new StatusCodeError (/usr/local/lib/node_modules/homebridge-nest/node_modules/request-promise-core/lib/errors.js:   32:15
at Request.plumbing.callback (/usr/local/lib/node_modules/homebridge-nest/node_modules/request-promise-core/lib/       plumbing.js:104:33
at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/homebridge-nest/node_modules/request-promise-core/  lib/plumbing.js:46:31
at Request.self.callback (/usr/local/lib/node_modules/homebridge-nest/node_modules/request/request.js:185:22
at Request.emit (events.js:189:13)
at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/node_modules/request/request.js:1161:10)
at Request.emit (events.js:189:13)
at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/node_modules/request/request.js:1083:12)
at Object.onceWrapper (events.js:277:13)
at IncomingMessage.emit (events.js:194:15)
at endReadableNT (_stream_readable.js:1103:12)
at process._tickCallback (internal/process/next_tick.js:63:19)
```

The underlying issue was resolved by re-obtaining and reconfiguring credentials but I only noticed the issue had occurred because other, unrelated, sensors also run by my Homebridge instance had stopped working.

**Comment by adriancable** [comment]
@themainframe - I don't know, except that this error is in a module that isn't used in modern versions of homebridge-nest. Since it's difficult to support old versions indefinitely, please upgrade and see if things now work.

**Comment by themainframe** [comment]
Up to date now. Apologies I should have checked the current released code to see if that had been resolved already. Will update if I see it happen again. Fantastic project by the way, done what the squabbling children (Apple and Google) could not 👌🏼 Great work owner/maintainers.

**Comment by paulsahner** [comment]
Similar issue for me. Every time my homebridge sever reboots, my Google credentials are no longer valid and I need to repeat the authorization steps. I perform the steps in a copy of Chrome on a different device, which never gets used for anything...so the cookie isn’t being invalidated by that session being logged out or anything. In fact, even when homebridge fails to authenticate, I can still access home.nest.com in that copy of Chrome without logging back in.

This started after updating to homebridge 1.0 and the latest homebridge-nest plugin.

**Comment by efipso** [comment]
> 
> 
> Similar issue for me. Every time my homebridge sever reboots, my Google credentials are no longer valid and I need to repeat the authorization steps. I perform the steps in a copy of Chrome on a different device, which never gets used for anything...so the cookie isn’t being invalidated by that session being logged out or anything. In fact, even when homebridge fails to authenticate, I can still access home.nest.com in that copy of Chrome without logging back in.
> 
> This started after updating to homebridge 1.0 and the latest homebridge-nest plugin.

Your case is weird, the last time I've reconfigured token was on 30th March, and working fine since then. I've updated homebridge and plugin, and restarted server (and raspberry) many many times.

Maybe that copy of Chrome logs in on background and logs out from bridge? I always opened a private tab (on Firefox, but is irrelevant), got the token, configured on bridge and, without close session manually on browser, just closed the tab. That token is registered on my Google account, but browser can't access alone.

**Comment by neilmorton** [comment]
> > Similar issue for me. Every time my homebridge sever reboots, my Google credentials are no longer valid and I need to repeat the authorization steps. I perform the steps in a copy of Chrome on a different device, which never gets used for anything...so the cookie isn’t being invalidated by that session being logged out or anything. In fact, even when homebridge fails to authenticate, I can still access home.nest.com in that copy of Chrome without logging back in.
> > This started after updating to homebridge 1.0 and the latest homebridge-nest plugin.
> 
> Your case is weird, the last time I've reconfigured token was on 30th March, and working fine since then. I've updated homebridge and plugin, and restarted server (and raspberry) many many times.
> 
> Maybe that copy of Chrome logs in on background and logs out from bridge? I always opened a private tab (on Firefox, but is irrelevant), got the token, configured on bridge and, without close session manually on browser, just closed the tab. That token is registered on my Google account, but browser can't access alone.

I agree with @efipso , I had this issue in the past, but reboots etc of homebridge or the RPi, including a complete power off and on of the RPi just now to test, have not resulted in any logout occurring.

I also followed the private tab route, simply closing the tab after completion, without logging out etc.

**Comment by adriancable** [comment]
@paulsahner - something else is happening here. Google knows a lot about you, but it certainly doesn't know when your Homebridge server restarts, or what version of Homebridge you have!

I suspect something like: you are using Docker and the changes you make to the config aren't persistent, so they're lost on every reboot. Or you have multiple copies of Homebridge installed by accident, and you are changing one configuration file, but the Homebridge service that starts on boot is using a different config file.

**Comment by mrjackyliang** [comment]
So last night, my tokens have expired. And it appears the expiration time is exactly 10 weeks!
```
[5/18/2020, 7:43:54 PM] [Nest] Google authentication was unsuccessful. Make sure you did not log out of your Google account after getting your googleAuth parameters.
[5/18/2020, 7:43:54 PM] [Nest] Access token acquisition via googleAuth failed (code undefined).
[5/18/2020, 7:43:54 PM] [Nest] Auth failed: access token specified in Homebridge configuration rejected
```

**Comment by themainframe** [comment]
Curious. That's about the same time I observed too. Crikey. How much more difficult can Google make this? Are we going to need this plugin to integrate WebKit and do the ridiculous login process itself? ;)

**Comment by mrjackyliang** [comment]
@themainframe Ah, well. I guess I'll just create a reminder to update the login manually every 65 days or so. Every 10 weeks is 70 days, so I guess that will work for now.

**Comment by kemayo** [comment]
Happened to me last night again -- this particular token lasted... somewhere between one and two months, I think? I don't believe I did any logging in/out that might have affected it.

**Comment by mrjackyliang** [comment]
This is mostly Google's limitation. I guess since we know, I can close off this issue as this is not something @adriancable can fix unless Google makes a comeback with an API for Nest.

**Comment by kemayo** [comment]
I will say, in my re-setup, I decided to try using the Nest account steps again _despite_ being migrated to a Google account... and that works currently. So, worth working out if that'll keep working or if it's subject to similar expiration issues.

**Comment by mrjackyliang** [comment]
@kemayo I'll try that out later, thanks!

**Comment by mrjackyliang** [comment]
It's wise to note the issue with Nest accounts here. If you are using Nest access tokens, it may expire every month.

[Link to Issue #195 comment](https://github.com/chrisjshull/homebridge-nest/issues/195#issuecomment-570559226)

Although if it doesn't, let us know! I'll switch over to using Nest tokens!
