### ISSUE TITLE
API observe error

### ISSUE THREAD

**Issue by woodgieboodgie** [chrisjshull/homebridge-nest#229]
![Capture](https://user-images.githubusercontent.com/52473319/76601917-009f6a00-655e-11ea-8bdc-fb0f44c5fd2a.JPG)

Receiving the above error, running Homebridge 0.4.52, Node.js v13.10.1, NPM v6.13.7

Starts fine, but randomly presents this error on screen.  Service remains lit and can be controlled via plugin.

**Comment by starlessblack** [comment]
I'm seeing a decent amount of these errors as well.

**Comment by mrjackyliang** [comment]
I believe `ECONNRESET` errors are normal. They just represent network connection issues to and from the Nest service.
