### ISSUE TITLE
Temperature sensor appears twice

### ISSUE THREAD

**Issue by jmissig** [chrisjshull/homebridge-nest#231]
I have a Nest Temperature Sensor in my master bedroom.

By default it seems it appears twice — it’s a sub-accessory of my Thermostat, but also it is its own accessory.

**Comment by jmissig** [comment]
Fwiw, `Thermostat.Disable.[Serial]` doesn’t work—presumably because this extra separate temperature is a NestTempSensorAccessory and not a NestThermostatAccessory.

**Comment by adriancable** [comment]
@jmissig - it shouldn't appear twice. The "sub-accessory of your Thermostat" is the temperature at the Thermostat. It may be that by coincidence it's the same temperature as one of your temperature sensors - is that what's happening?

**Comment by jmissig** [comment]
Perhaps it could be because I have that thermostat’s “Manage Sensors” (w/in Nest app) already set to use the remote sensor during certain times of day?

**Comment by jmissig** [comment]
I think you’re right that it’s not actually appearing twice. It’s that there are two different temperature readings for my thermostat when using the remote sensor as main temp. Here the Nest app screenshot makes it a little clearer what’s going on.

Note the Home app thermostat device shows 21.5º (remote sensor) in the upper-left corner, and 21.0º at the bottom. I then have a separate device (the sensor) also showing me 21.5º.

![IMG_5189](https://user-images.githubusercontent.com/1448107/78584670-6a253800-77ed-11ea-99b0-6425676f09fb.png)
![IMG_5190](https://user-images.githubusercontent.com/1448107/78584747-875a0680-77ed-11ea-8bf3-8c63f7bd4fd2.png)
![IMG_5193](https://user-images.githubusercontent.com/1448107/78584764-8fb24180-77ed-11ea-9c75-8b0f1e9deb11.png)

**Comment by adriancable** [comment]
@jmissig - this all looks correct. I think all is working as it should. Closing for now.

**Comment by jmissig** [comment]
Thanks for looking at this. Looks like I should be able to `TempSensor.Disable` to get what I prefer.
