### ISSUE TITLE
Nest Auth Failure blocking the complete startup of Homebridge recently

### ISSUE THREAD

**Issue by glowfishDE** [chrisjshull/homebridge-nest#234]
Hi,
i´ve created an Issue for Oznu´s Homebridge Docker Image [https://github.com/oznu/docker-homebridge/issues/285] - however it turned out, the problem is originating from the homebridge-nest plugin blocking the startup of homebridge due to an auth problem during start:

`[4/6/2020, 4:17:43 PM] [Nest] Google authentication was unsuccessful. Make sure you did not log out of your Google account after getting your googleAuth parameters.`

and
`
[4/6/2020, 4:17:43 PM] [Nest] Access token acquisition via googleAuth failed (code undefined).`

I removed the nest platform part from my config.json and homebridge starts up fine again.
It was working like 4 days before just fine.

For some reason the google tokens cannot be verified anymore. More details are in the link above (Oznus Github Bug Tracker).

Bug is happening in homebridge-nest v4.4.4
Node.js Version v12.16.1
NPM Version v6.13.4

I could start Homebridge with the Nest Plugin again after re-creating the Google Auth Tokens following the manual here: https://github.com/chrisjshull/homebridge-nest#readme

However the startup of homebridge should not be blocked by a non working auth procedure.

I also wonder why my tokens did not work anymore.

What i see is, that google probably changed the structure of their auth cookies:

Old Cookie starts with:

`cookies": "OCAK=zyx-redacted; SID=xyz-redacted`

New Cookie starts with: 

cookies":  `SID=xzy-redacted.; __Secure-3PSID=redacted`

So it seems the new cookie does not come with the "OCAK" String anymore and instantly starts with the "SID String"

**Comment by remko2000** [comment]
same problem here, this error blocking the start of homebridge so I've to remove the plugin completely.

**Comment by glowfishDE** [comment]
remko - please try to re-issue a google auth token. It solved the auth failure for me. However the plugin is still not supposed to kill the whole homebridge on startup due to an auth issue - so the dev needs to fix this

**Comment by remko2000** [comment]
> remko - please try to re-issue a google auth token. It solved the auth failure for me. However the plugin is still not supposed to kill the whole homebridge on startup due to an auth issue - so the dev needs to fix this

I have done several times but the problem remains. I also get an error from my edomoticz plugin (Error: connect ECONNREFUSED edomotiz). Is it perhaps a problem that has a link with domoticz? I have now removed my nest plugin otherwise homebridge no longer works at all. After removing everything everything works again (no more error from domoticz).

**Comment by adriancable** [comment]
Auth issues with Nest no longer block Homebridge start in 4.4.6. Closing.
