### ISSUE TITLE
Clean install causing: [Nest] Could not authenticate with Nest (code ENORECAPTCHA). Retrying in 15 second(s).

### ISSUE THREAD

**Issue by bencollier** [chrisjshull/homebridge-nest#235]
Running 4.4 on latest HOOBS.

This is different from #219 as it's happening with and without an access_token set. I reinstalled it and this continues to happen (including with empty config).

Once I set an access_token, everything connects fine but this error continues:

```
[Homebridge] [4/8/2020, 6:32:11 PM] [Nest] initing thermostat "Living Room Thermostat": deviceId: XXXXXXXXXX structureId: XXXXXXXXX
[Homebridge] [4/8/2020, 6:32:11 PM] [Nest] initing home_away_sensor "Home Occupied":  deviceId: XXXXXXXXXX structureId: XXXXXXXXX
Homebridge] [4/8/2020, 6:32:11 PM] [Nest] initing protect "Kitchen": deviceId: XXXXXXXXXX structureId: XXXXXXXX
[Homebridge] [4/8/2020, 6:32:11 PM] [Nest] initing protect "Upstairs": deviceId: XXXXXX structureId: XXXXXXXX
[Homebridge] [4/8/2020, 6:32:11 PM] [Nest] Initializing platform accessory "Living Room Thermostat".
[Homebridge] [4/8/2020, 6:32:11 PM] [Nest] Initializing platform accessory "Home Occupied".
[Homebridge] [4/8/2020, 6:32:11 PM] [Nest] Initializing platform accessory "Kitchen".
[Homebridge] [4/8/2020, 6:32:11 PM] [Nest] Initializing platform accessory "Upstairs".
[Homebridge] [4/8/2020, 6:32:11 PM] Service is running on port 51826.
[Homebridge] { code: 'ENORECAPTCHA', status: undefined }
[Homebridge] [4/8/2020, 6:32:16 PM] [Nest] Could not authenticate with Nest (code ENORECAPTCHA). Retrying in 15 second(s).
[Homebridge] { code: 'ENORECAPTCHA', status: undefined }
[Homebridge] [4/8/2020, 6:32:31 PM] [Nest] Could not authenticate with Nest (code ENORECAPTCHA). Retrying in 15 second(s).
```

**Comment by adriancable** [comment]
@bencollier - sorry if this is obvious but we don't have anything to do with HOOBS. So unless something is clearly a homebridge-nest issue, I'm not sure I can help.

The 'could not authenticate' message only happens during the auth stage. Given the plug-in has clearly got past that, it looks like HOOBS may have started two copies of Homebridge running. The first is still producing those messages, but the second is running OK.

Closing for now - I don't think this is a homebridge-nest issue.

**Comment by bencollier** [comment]
I'd have to agree with you now having tested a little further. I setup homebridge on my Mac and couldn't replicate the issue, and now it's stopped on my HOOBs too.

In case you didn't know, homebridge-nest comes as a HOOBs certified plugin so a recommended install, if I see anything else odd, I'll test on Mac before reporting to you or them.

Thanks for the snappy response!
