### ISSUE TITLE
New HOOBS install - errors

### ISSUE THREAD

**Issue by resgroupmsr** [chrisjshull/homebridge-nest#237]
Hoobs log showing this:
[Homebridge] [4/16/2020, 8:02:51 PM] [Nest] Could not authenticate with Nest (code ENORECAPTCHA). Retrying in 15 second(s).
[Homebridge] { code: 'ENORECAPTCHA', status: undefined }

I had existing Homebridge install, added HOOBS to my Raspberry PI.  Now installed the plug in (again) in HOOBS.  Any idea what I'm doing wrong?

**Comment by adriancable** [comment]
I'm sorry, we don't have expertise in HOOBS. I would ask them. All I can say is this error is a consequence of using the old username/password authentication which isn't possible any more. With a Nest account you need to use the access token method. I don't know how you do this through HOOBS - sorry for not being more helpful.
