### ISSUE TITLE
Only use Nest Protect....

### ISSUE THREAD

**Issue by roe1974** [chrisjshull/homebridge-nest#24]
Hi
I only use the Nest Protect devices.....
i currently use version 1.1.3-no legacy ....
Can i update to 2.1.3 if i only use Nest Protect devices ?

regards
Richard

**Comment by roe1974** [comment]
any help/answer out there ? ;-)

Richard

**Comment by chrisjshull** [comment]
@roe1974, sorry for the slow reply. I don't see any reason why it wouldn't, but I also don't have a Nest Protect to verify myself. Let me know how it goes!
