### ISSUE TITLE
Pushing test alarm on nest protect is not registered.

### ISSUE THREAD

**Issue by iwensfortis** [chrisjshull/homebridge-nest#242]
**Describe the bug**

Manual Test alarm by Pushing on the nest protect is not registered as alarm, it also does not trigger. And there is nothing logged in de logfiles. I can control the thermostat so that is working.

**To Reproduce**
1. Push on nest protect the test button and start the test alarm routine, all nestprotects will sound a alarm but no trigger is registered in logs or in homekit.

**Expected behavior**

Trigger the CO and smoke alarm condition so the routines can be tested.

Latest version fresh install 2 days ago.

**Comment by adriancable** [comment]
@iwensfortis - thanks for your note - I'll look into this. I'm not sure if a manual alarm test is actually reported via the Nest API, but if it is, I will adjust the plug-in so it works how you want because I agree this is the right thing.
