### ISSUE TITLE
Unable to authenticate with Google/Nest.

### ISSUE THREAD

**Issue by kcharwood** [chrisjshull/homebridge-nest#244]
**Describe the bug**

Trying to setup Nest on my Homebridge with a Google Account.

```
[4/28/2020, 11:31:12] [Nest] Access token acquisition via googleAuth failed (code 400).
[4/28/2020, 11:31:12] [Nest] Unable to authenticate with Google/Nest.
```

I've followed the steps very closely multiple times, and continue to get this. I was actually trying to reproduce some of your auth code in python for a different project, and was also getting a 400 there where it was complaining about a missing `client_id`.

Include with your bug report this version info:
```sh
node --version
homebridge --version
```

```
node --version
v12.16.2
homebridge --version
1.0.2
````

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Done

**Comment by kcharwood** [comment]
Still struggling here. Happy to get down to cURL level and debug if possible.

**Comment by adriancable** [comment]
Kevin,

Please email me your config.json and I’ll take a look. (adrian.cable@gmail.com)

 

-Adrian

**Comment by brn2prgrm** [comment]
I've had the same thing crop up in the past few days as well:

`[5/3/2020, 23:05:24] [Nest] Access token acquisition via googleAuth failed (code EAI_AGAIN).
[5/3/2020, 23:05:24] [Nest] Unable to authenticate with Google/Nest.`

**Comment by kcharwood** [comment]
Adrian was able to identify my problem. I was using Tot to jot down values, but I was not in plain text mode. It was removing underscores `_` from my issue token, and converting it to italics, so when I pasted it in the values were actually wrong.

Thanks Adrian.
