### ISSUE TITLE
NestDeviceAccessory inheriting from HAP-NodeJS Accessory class

### ISSUE THREAD

**Issue by Supereg** [chrisjshull/homebridge-nest#245]
Quick question, why is nest inheriting from the HAP.NodeJS Accessory class? 
https://github.com/chrisjshull/homebridge-nest/blob/a2165e5b572dfa488408ef09192099852d2619d9/lib/nest-device-accessory.js#L18

First of all it is not used (expect of some weird method the create the AccessoryInformation service) and additionally it must not be accessed when doing a homebridge plugin.
homebridge-nest is a StaticPlatformPlugin, meaning it just exposes a method `accessories` which returns an array of 'accessory objects' to the first argument of the supplied callback. Those accessory objects are basically the same as a normal accessory plugin would expose. The object must expose a method `getServices` which just returns the set of services which should be added to the accessory (which homebridge creates itself).

With homebridge 1.0.0 the handling of the AccessoryInformation service was redone. Now ALL added characteristics are transferred to the AccessoryInformation service of the homebridge created accessory. Additionally all event ('get' and 'set') listeners are also transferred to make it possible to hook for example get listeners for the Name characteristic.
As homebridge-nest returns an AccessoryInformation service created by the internal HAP-NodeJS Accessory - this service has already hooked up a listener for the Identify characteristic - and will cause the listener to be transferred into the homebridge manage accessory and it's accessory information service, resulting in two listeners being hooked and producing a crash like described in https://github.com/homebridge/homebridge/issues/2542.

Homebridge will probably ensure to any listeners on the identify characteristic in a future version, but the inheritance of the HAP-NodeJS's Accessory should be removed nonetheless.

**Comment by adriancable** [comment]
@Supereg - the answer to "why is it doing this" is that's what it always did, and it always used to work. Not a great answer, but equally it was never clear to me that this was the "wrong" thing before it broke in homebridge 1.0.

I'll work on an alternative approach but the plug-in relies on the assumption that the Nest device objects inherit from Accessory (so I can call methods like addService directly) so it will need some refactoring and testing.

**Comment by Supereg** [comment]
The latest homebridge beta mitigated this issue.

`addService` service wouldn't do anything at all, anyways? It would just a a service to a random Accessory object lying there in memory and which didn't get added to the bridge 🤔 
If you want to dynamically change the set of accessories or alter accessories itself you may have to move to another type of Plugin architecture (now referred to as DynamicPlatformPlugins).

Hit me up if you need any more details. The new typescript definitions explains those different plugin types quite well honestly. Maybe also have a look at the homebridge-examples repo, there it is also explained in much detail.

I assume this fixes the issue and it can be closed?

**Comment by adriancable** [comment]
@Supereg - each Nest device is a NestDeviceAccessory which inherits from Accessory. My method 'accessories' then returns the array of NestDeviceAccessory objects. The constructor of each uses addService to add the services it needs. It felt logical to me, but maybe doesn't feel logical to you.

I can certainly as an alternative make NestDeviceAccessory not inherit from Accessory, and then do this.accessory = new Accessory ... and then 'accessories' contains an array of [NestDeviceAccessory object].accessory rather than just the NestDeviceAccessory objects themselves if you think that would be better.

**Comment by Supereg** [comment]
The only thing homebridge expects from you is that there is a function `getServices` (on every instance of an `accessory` which returns an array of Service object (HAP-NodeJS service objects) and those can just be instantiated like `new Service.MotionSensor('example name');` or `new Service.AccessoryInformation()` (you may don't want to specify a displayName for the AccessoryInformation service as this conflicts currently with some stuff.

I don't know why you would want to create an Accessory object?
