### ISSUE TITLE
Home/Away status change not logged

### ISSUE THREAD

**Issue by Seaniau** [chrisjshull/homebridge-nest#246]
**Describe the bug**
About a week ago, I upgraded from 4.4.0 to 4.4.6
Since then, the Home/Away status change no longer appears in the console/log. Other changes made via the plugin such as tstat temperature show absolutely fine. The H/A status changes as expected when toggled.

On top of this, since the update I am have issues where the Home/Away status is reverting to Away on it's own at random times. Unsure if related?

Include with your bug report this version info:
```sh
node --version **idk**
homebridge --version **1.0.4**
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

**Comment by Seaniau** [comment]
I have now completely uninstalled and reinstalled Homebridge and Homebridge-Nest.
Home/Away status changes are still not logged and my Home/Away status is changing itself with Homebridge seeming to be the cause;
Disabling all automations for Home/Away status does not stop status changing at random.
Shutting Homebridge down **does** stop random status changes.

**Comment by adriancable** [comment]
@Seaniau - are you sure that the status changes are happening at random? I know of one other plug-in user who also experienced something like what you were describing. After a lot of digging it turned out they were saying things like 'Hey Siri, turn off the Living Room' which of course also turns off the home/away switch along with all other switches.

Try adding "HomeAway.Disable" to the options array in your config.json, and see if that makes a difference.

**Comment by Seaniau** [comment]
@adriancable Thanks for getting back to me.

> @Seaniau - are you sure that the status changes are happening at random? I know of one other plug-in user who also experienced something like what you were describing. After a lot of digging it turned out they were saying things like 'Hey Siri, turn off the Living Room' which of course also turns off the home/away switch along with all other switches.

I'm actually not really using Homebridge and Homebridge-Nest for anything but Home/Away automation. I am not asking Siri to do anything almost ever.

> Try adding "HomeAway.Disable" to the options array in your config.json, and see if that makes a difference.

I'm actually trying to just that right now but i'm not too great with JSON!
When I can get the config to be valid, Homebridge starts but none of the Nest devices are loaded. Maybe you could tell me what I am doing wrong here?:

        "platforms": [{
                "platform": "Nest",
                "googleAuth": {
                        "issueToken": "https://accounts.google.com/o/oauth2/ifr$
                        "cookies": "NID=203=EKfQrCjX26-5$
                        "apiKey": "AIzaSyAdkSX9UOWkS5P6sZE4"
                },
        "options": {
                "title": "Feature Options",
                "type": "array",
                "items": {
                        "type": "string",
                        "placeholder": "HomeAway.Disable"
                }
        }
        }]
}

**Comment by adriancable** [comment]
@Seaniau - first take out the "options" object in your JSON above since it isn't quite right. Then, under

`"platform": "Nest",
`
put

`"options": [ "HomeAway.Disable " ],
`

**Comment by Seaniau** [comment]
@adriancable - That's done it, thank you. I will run this for 24 hours and update with my finding.

**Comment by Seaniau** [comment]
Hi @adriancable,
I've deciphered that it is not Homebridge causing the random Home/Away change. Must be a Nest issue. Apologies for that.

I would like to reduce this Issue to just the Home/Away status change not being logged if that's alright? As I do feel this was a useful function.

Thanks for your help.

**Comment by adriancable** [comment]
@Seaniau - thanks, I'll take a look.
