### ISSUE TITLE
Authentication Issue: config.json

### ISSUE THREAD

**Issue by tahirijaz** [chrisjshull/homebridge-nest#247]
Before I dive into the problem I am having I want to thank you for homebridge-nest!

I wanted to request your help in getting homebridge-nest working for me. I am getting the following error: 

`Error: You did not specify {'token'} or {'clientId','clientSecret','code'}, one set of which is required for the new API`

I am trying to use the access_token from https://home.nest.com/session. This is what my config.json looks like: 

`{
    "bridge": {
        "name": "Homebridge",
        "username": "XX:22:XX:XX:XX:X0",
        "port": 41969,
        "pin": "031-XX-XXX"
    },
    "platforms": [
	    {
		"platform": "Nest",
		"access_token": "g.0.eyJraWQiOiIyMzhiNTUxj1U6BgNq9BOM9v8OobcJvzRgy9Kt5AcdrS7vA..."
	    }
    ]
}`

Is there something I am doing wrong? I even tried adding my email above the access_token but that didn't change anything. I would really appreciate your help.

**Comment by adriancable** [comment]
This message is coming from an extremely old version of the plug-in. Please update. Thanks!

**Comment by tahirijaz** [comment]
Thank you so much Adrian. Not sure what happened, I have updated everything now and Homebridge is running without any errors. However, I am having trouble trying to add the accessory in HomeKit. I have tried using the QR code as well as entering the code. Wanted to request if you have any ideas?

Thanks, 
Tahir

**Comment by adriancable** [comment]
@tahirijaz - to add to HomeKit, the device you are using to scan the QR code (or enter the code) and the device running Homebridge, must be on the same network, and able to communicate using Bonjour to find each other.

So some causes for not being able to add the accessory are:

- iOS device used to scan the code, and device used to run Homebridge, are on different networks, e.g. one is on Wi-Fi, the other on LTE, or one is connected to a VPN
- your router is blocking Bonjour (mDNS) packets. This is rarely enabled by default except on some Linksys Velop routers, but you might want to check your router's admin to make sure anything that might block or filter or firewall packets is turned off

Hope this helps.
