### ISSUE TITLE
Hot Water Switch triggers 30min Boost - New feature request

### ISSUE THREAD

**Issue by currybeast** [chrisjshull/homebridge-nest#248]
Excellent plug-in - many thanks.
The hot water switch appears to issue a Boost for 30 mins command

I would be grateful if the hot water switch can be configured in the config.json to send  either the default of 30, 60, or 120 minutes of boost as per the Nest App.  So when I hit the switch and I have 120 mins in the config.json, it sends a 2 hour boost command.

Many thanks.

**Comment by adriancable** [comment]
@currybeast - you can already do this today - via an undocumented secret setting :-)

In your config, under "platform": "Nest", put something like:

`hotWaterDurationMinutes: 120,`

Let me know how you get on.
