### ISSUE TITLE
Nest Secure

### ISSUE THREAD

**Issue by rselover** [chrisjshull/homebridge-nest#250]
I've gone the Homebridge route, this is working great!

BUT - I'd love to get support for Nest Secure - is that in the pipeline? I see the commercial solutions, but so far this has worked great... I can kick in on PayPal if that helps motivate...

Thanks!

**Comment by adriancable** [comment]
@rselover - I may add support for Nest Secure in the future to the plug-in. Sorry I can't be more specific! But as you note, if you want it now there is Starling Home Hub.
