### ISSUE TITLE
Nest Protect

### ISSUE THREAD

**Issue by reesion** [chrisjshull/homebridge-nest#251]
Hi

I’ve used your plugin to add my Nest protect. They showed up fine as smoke detector, carbon monoxide detector and Motion detector. However, when I integrate it to Home Assistant, it only shows motion detector and another binary sensor(not sure if this is smoke or carbon monoxide detector). It seems to be missing another sensor?

Any idea?

**Comment by adriancable** [comment]
@reesion - I'm sorry, but I'm not familiar with Home Assistant and can't provide support with Home Assistant. I suggest you contact them for advice.

**Comment by simonlock** [comment]
For me all accessories for Nest and all other homebridge accessories are available in HA; all except the nest carbon monoxide sensors. Is there something different regarding the nest carbon monoxide sensors?
