### ISSUE TITLE
Thermostat - incorrect return value reported when setting the heat via Siri (reported for last set is current room temp rather than last set temp)

### ISSUE THREAD

**Issue by ventz** [chrisjshull/homebridge-nest#253]
**Describe the bug**

The bug is that when setting the heat to a new value, the return value to Siri for the "changing from" part is incorrectly the current room temperature, rather than the previous SET temperature.

> For example: given _current_ room temp is 70, and let's say the heat was manually (via physically turning or via Nest app) set to 60 -- then set the temp via Siri to 65 - in this case Siri will return that it's "Changing the temperature from 70 to 65", but in reality it should say that its "Changing the temperature from 60 to 65", as the last set temp was actually 60.

**To Reproduce**

1. Set Nest Thermostat manually/via Nest app to a number **lower** or **higher** than the _current_ temperature

> For example: if the _current_ temp is 70, set heat to 60

![IMG_1073](https://user-images.githubusercontent.com/38256974/82020585-5d4efc00-9657-11ea-8b19-3fa3c9cce28c.PNG)

2. Use Siri (via voice) to set the thermostat to a different number

> For example: given _current_ room temp is 70, and let's say the heat was manually (via turning or via Nest app) set to 60 -- then set via Siri to 65 

![IMG_1075](https://user-images.githubusercontent.com/38256974/82020664-840d3280-9657-11ea-83d5-e1b9abf8161e.PNG)

The bug at this point is that Siri first (correctly) tells you  it changed the temperature **to** the new desired **SET** temperature, however, incorrectly that it changed **from** the current ROOM temperature (rather than the **SET**)

> For example: given _current_ room temp is 70, and let's say the heat was manually (via turning or via Nest app) set to 60 -- then set via Siri to 65 - in this case Siri will return that it's "Changing the temperature from 70 to 65", but in reality it should say that its "Changing the temperature from 60 to 65"

**Expected behavior**
Return and claim that it will change the heat "set" number from the previously set, rather than the current room temperature, which has not been achieved yet.

Include with your bug report this version info:
```
$ node --version
v12.16.2

$ homebridge --version
1.0.4

```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

```
pi@homebridge:~ $ npm upgrade -g homebridge homebridge-nest
pi@homebridge:~ $ 
```
> Confirmed

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`
> I believe not necessary in this case since this is a simple "which temp is returned" bug.

Please let me know if anything in addition would be helpful.

**Comment by adriancable** [comment]
@ventz - unfortunately this is a Siri thing. Yes, I agree that what it says is confusing! But, unfortunately there is no way to change it.

**Comment by ventz** [comment]
@adriancable Hi - isn't Siri just speaking out what is returned from the "setTemp" function?

**Comment by adriancable** [comment]
@ventz - Siri is programmed to speak this:

Okay, I changed the temperature from {{ current_room_temperature }} to {{ new_set_temperature }}.

Instead, you would want it to speak this: (and I agree this makes more sense)

Okay, I changed the temperature from {{ old_set_temperature }} to {{ new_set_temperature }}.

Unfortunately there's no way to change the pattern that Siri says. I can't simply provide the old_set_temperature when HomeKit asks me for the current_room_temperature because that messes up everything else in HomeKit, not just Siri.

**Comment by ventz** [comment]
@adriancable Thanks for the information. That is interesting. I wonder if it’s “current” in terms of the item being controlled (ex: when set, current being set, vs retrieved being “ambient”).

To your point - it doesn’t make a lot of sense and It is very confusing, especially with multiple locations, multiple thermostats, and even more so when the current ambient temperature is above what you are setting it, and you are setting it “up” (to heat). Assuming the same issue in reverse for cooling. Essentially it will tell you that it’s changing it up (to heat) to a number lower than the current :)

Out of curiosity, will something break within Homekit if proving the current set temperature? Asking this in terms of — it does make sense that the current set will either be achieved, in which case it doesn’t really matter, or it will not be achieved (not heated/cooled to that point yet, in which case the temperature that’s set makes sense). To rephrase - if the set temperature matches the ambient, there’s no downside to providing the set temp.,  but for the cases where it doesn’t, it seems it only will help to provide the set temp instead. Would a check for that condition potentially make sense?
