### ISSUE TITLE
Nest Protect Always Showing Motion Detected

### ISSUE THREAD

**Issue by Wildcat1** [chrisjshull/homebridge-nest#254]
Per the title I'm seeing all my Protects showing Motion Detected all the time. Is this a known issue ? Anyone know how to fix ? Thanks

**Comment by mbierman** [comment]
I don't see that in my installation. But I notice that even a small  motion like when someone is sleeping and rolls over does show motion.

**Comment by BatMahn** [comment]
Brand new install of homebridge-nest on a Pi, seeing the same thing? Motion on the protect is always showing as "triggered" on the Home app. It went back to off once, but seems mostly stuck on, so automations aren't behaving..

**Comment by Wildcat1** [comment]
In further testing it appears that if you start Homebridge cold with Homevridge-nest just run, motion is off on the protects. As soon as you walk by one, it triggers motion (as you would expect) but then just seems to keep reporting it as triggered from then on out. In other words it becomes stuck. Not sure if this is a polling issue and with more frequent polling would rectify ? Any assistance with this is greatly appreciated

**Comment by adriancable** [comment]
@Wildcat1 - does it genuinely become stuck forever, or does it just have a long relaxation time? (10-15 minutes)

**Comment by BatMahn** [comment]
Just tested again with a newly installed Protect. Takes 10 minutes to stop registering motion.
