### ISSUE TITLE
Nest Protect - Batteries issue

### ISSUE THREAD

**Issue by phis5533** [chrisjshull/homebridge-nest#257]
**Describe the bug**

Since 4/5 months, the batteries of my Nest Protect are drained very fast
I have to change them twice in 5 months.
Before it was at least every year.

**To Reproduce**
1. 

**Expected behavior**

Include with your bug report this version info:
```sh = zsh 5.3
node --version = v12.16.1
homebridge --version = 1.1.0 (now, but I update every week)
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

**Comment by adriancable** [comment]
@phis5533 - I'm sorry your batteries are draining fast. The most likely cause is that you are not using lithium batteries.

Nest Protect is not connected to your Wi-Fi network 99.5% of the time, so nothing network related is a cause for short battery life. It isn't related to homebridge, sorry.

**Comment by phis5533** [comment]
ok, thx for your advice, I'll check :-) 
BR

**Comment by adriancable** [comment]
No problem! By the way, I understand that Nest Protect batteries draining too fast is the #1 reported issue to Nest customer support. Customers start off with the lithium batteries that come with the device, which work fine, but then when they change them they use alkaline batteries instead and then the problems start. The Protect's battery level sensor is calibrated for lithium batteries, which have a higher voltage than alkaline. So, when you use alkaline batteries, they will report that they are running low too early. Hope this helps.

**Comment by phis5533** [comment]
Sure it will help 👍 Thx a lot
