### ISSUE TITLE
Add temperature info to historic data on Eve Home app

### ISSUE THREAD

**Issue by efipso** [chrisjshull/homebridge-nest#260]
Hi,

Since I bought Nest Thermostat many years ago I want to be able to know what temperature had the room not just in the moment I check it but an historic one. Just like Eve Room and Eve Degree on his app Eve Home.

And now I've seen that another plugin ([homebridge-panasonic-air-conditioner](https://github.com/codyc1515/homebridge-panasonic-air-conditioner)) adds this functionality using [fakegato-history](https://www.npmjs.com/package/fakegato-history) and I thought that maybe you can implement it too.

As I say, just have and historic registry and can see what was the temperature, for example, during the night or when I was out of home.
And as Nest also have humidity sensor, why just stop on temperature? Just integrate as much sensors and data as we can!

Thanks

**Comment by fjs21** [comment]
Just to open this up again. It would be great to have the temperature history exposed as with other platforms. Track room temps and see how they are affected by fans, etc.
