### ISSUE TITLE
[Nest] API observe: error Error [ERR_HTTP2_STREAM_ERROR]

### ISSUE THREAD

**Issue by ethempekin** [chrisjshull/homebridge-nest#264]
I am using the plug in with Hoobs (rp4).
All updated.

I have two nest protects at home. 
Have the following error lately and the only way to solve it is to reboot the hoobs. What could be the cause of this error in my case?

`10/06/2020, 21:10:34 [Nest] API observe: error Error [ERR_HTTP2_STREAM_ERROR]: Stream closed with error code NGHTTP2_INTERNAL_ERROR at ClientHttp2Stream._destroy (internal/http2/core.js:2101:13) at ClientHttp2Stream.destroy (internal/streams/destroy.js:38:8) at ClientHttp2Stream.[kMaybeDestroy] (internal/http2/core.js:2117:12) at Http2Stream.onStreamClose (internal/http2/core.js:493:26) { code: 'ERR_HTTP2_STREAM_ERROR' } 10/06/2020, 21:10:34 [Nest] Retrying in 10 seconds. 10/06/2020, 21:19:19 [Nest] API observe: error Error [ERR_HTTP2_STREAM_ERROR]: Stream closed with error code NGHTTP2_INTERNAL_ERROR at ClientHttp2Stream._destroy (internal/http2/core.js:2101:13) at ClientHttp2Stream.destroy (internal/streams/destroy.js:38:8) at ClientHttp2Stream.[kMaybeDestroy] (internal/http2/core.js:2117:12) at Http2Stream.onStreamClose (internal/http2/core.js:493:26) { code: 'ERR_HTTP2_STREAM_ERROR' } 10/06/2020, 21:19:19 [Nest] Retrying in 10 seconds. 10/06/2020, 21:20:49 [Nest] API observe: error Error [ERR_HTTP2_STREAM_ERROR]: Stream closed with error code NGHTTP2_INTERNAL_ERROR at ClientHttp2Stream._destroy (internal/http2/core.js:2101:13) at ClientHttp2Stream.destroy (internal/streams/destroy.js:38:8) at ClientHttp2Stream.[kMaybeDestroy] (internal/http2/core.js:2117:12) at Http2Stream.onStreamClose (internal/http2/core.js:493:26) { code: 'ERR_HTTP2_STREAM_ERROR' }`

**Comment by Loomaanaatii** [comment]
`[6/12/2020, 6:01:02 AM] [Nest] API observe: error Error [ERR_HTTP2_STREAM_ERROR]: Stream closed with error code NGHTTP2_INTERNAL_ERROR
    at ClientHttp2Stream._destroy (internal/http2/core.js:2148:13)
    at ClientHttp2Stream.destroy (internal/streams/destroy.js:38:8)
    at ClientHttp2Stream.[kMaybeDestroy] (internal/http2/core.js:2164:12)
    at Http2Stream.onStreamClose (internal/http2/core.js:511:26) {
  code: 'ERR_HTTP2_STREAM_ERROR'
}
[6/12/2020, 6:01:02 AM] [Nest] Retrying in 10 seconds.`

Same issue here

**Comment by adriancable** [comment]
Is this actually an issue? Yes, sometimes we find the Nest service just drops client connections. This happens with the official web app too. The clients just immediately reconnect and all is good again.

Or are you actually experiencing a service issue, beyond the error message?

**Comment by Loomaanaatii** [comment]
For myself at least it becomes unresponsive and I have to restart homebridge for it to continue to work again.

**Comment by adriancable** [comment]
@Loomaanaatii - can you email me (adrian.cable@gmail.com) a longer log showing the transition between stuff working and you getting this message? If you don't already have such a log, can you also take the opportunity to add the line

"options": [ "Debug.Verbose" ],

under

"platform": "Nest",

in config.json, and also run homebridge with the -D parameter. Thanks!

**Comment by Loomaanaatii** [comment]
@adriancable Sure I'll update the config to show a more verbose log and email you if it happens again.

**Comment by adriancable** [comment]
Thank you! :-)

**Comment by ethempekin** [comment]
Thanks for the suggestion on optional line. I now added. In my case (hoobs) needs to be rebooted to bring my devices back to life. I will now search how to run home bridge with the -D parameter.

**Comment by NainRouge** [comment]
Also getting this same error message.  It says it will retry in 10 seconds, but never seems to.  Homebridge hangs until I restart the service.

**Comment by adriancable** [comment]
@NainRouge - can you kindly enable verbose debugging by editing config.json and below the "platform": "Nest" line, add:

`"options": [ "Debug.Verbose" ],`

Then run: homebridge -D

Then when it happens, email me the error line, plus 30 seconds of log before, plus 30 seconds of log after, to adrian.cable@gmail.com. Thanks!
