### ISSUE TITLE
Make using google for auth easier

### ISSUE THREAD

**Issue by natefanaro** [chrisjshull/homebridge-nest#266]
**Is your feature request related to a problem? Please describe.**

Recently had my token expire from google. I'll have to follow the 14 (at the moment) steps to grab the right config values for google auth. The steps are well written and explain exactly what to do. The problem is there are too many of them, and the process is more time consuming than I would like. 

**Describe the solution you'd like**

Something like what the ring plugin does. There is an extra cli tool to walk you through authenticating and getting the token. It even handles two factor! I'm not looking for the exact same thing here, but the closer the better.

**Describe alternatives you've considered**

Some people might not enjoy entering passwords in to a program like that. (I am the same way.) I have seen a pattern before where a cli tool provides a url for you to visit in your browser. This sends you to the login flow with google. At the end of that login there is a link/code/etc that you paste back in to the cli tool. Then, in this case, the tool might make any extra calls needed to get the right credentials.

**Additional context**

There have been a few auth related issues raised already. https://github.com/chrisjshull/homebridge-nest/issues?q=is%3Aissue+google++auth

Good discussion on expiring tokens for reference. https://github.com/chrisjshull/homebridge-nest/issues/228

**Comment by donavanbecker** [comment]
Homebridge-Nest-cam plugin has a automated login as part of his plugin. That makes it easier to get all the login info!

**Comment by adriancable** [comment]
@donavanbecker - yes, there is a lot to like about homebridge-nest-cam these days! And, you can use its 'automated login' via puppeteer to get the bits you need to run homebridge-nest as well.

**Comment by natefanaro** [comment]
Ah, that was exactly what I was looking for. Not sure if it is worth replicating that tool in this repo. I'll leave it up to the owners/collaborators here. Thanks for the info and for working on this plugin!

**Comment by donavanbecker** [comment]
@natefanaro can this be closed?

**Comment by natefanaro** [comment]
I think so. This works for me.

**Comment by EvanGrote** [comment]
So are we saying the workaround is to install the [homebridge-nest-cam](https://github.com/Brandawg93/homebridge-nest-cam) plugin and authenticate using the Google login script used by that plugin?

I'm attempting to use the login script from homebridge-nest-cam now, but I run all my docker containers on a headless NAS, so judging by the chromium installation it asked for after invoking the script, I don't think this workaround will work for me.

**Comment by Brandawg93** [comment]
@EvanGrote It works both headful and headless, so long as your Google account does not have 2FA via SMS.

**Comment by jdtsmith** [comment]
This info should be added to the README IMO.  The README also says it's once and done: "Setting up a Google Account with homebridge-nest is a pain, but only needs to be done once, as long as you don't log out of your Google Account."  I haven't found this.  Others have presented evidence that the Google Auth expires every 10 weeks, and that's consistent with my experience.
