### ISSUE TITLE
Error checking alerts: 403 every 10 seconds

### ISSUE THREAD

**Issue by Rubenfer** [chrisjshull/homebridge-nest#267]
**Describe the bug**

Homebridge log reports the following error every 10 seconds:

`Error checking alerts: 403`

This happens since last update to v.4.4.6.

**To Reproduce**
1. Install homebridge-nest v.4.4.6 and configure it

**Expected behavior**

No errors.

**Comment by adriancable** [comment]
This error isn't produced by homebridge-nest. Good luck finding the source!

**Comment by Rubenfer** [comment]
Oops. Wrong repo lol. Sorry for the inconvenience!

**Comment by adriancable** [comment]
@Rubenfer - no worries at all! :-)
