### ISSUE TITLE
Nest thermostat is removed from Home app when restarting Raspberry Pi but reappears when Homebridge is restarted

### ISSUE THREAD

**Issue by idealdreams** [chrisjshull/homebridge-nest#268]
I am running the latest version of Homebridge and this plugin on a Raspberry Pi. I have been using this plugin for several months with no issues. Recently, I've noticed that if I restart my Raspberry Pi, when the Homebridge service restarts, the Nest thermostat is missing in my Home app. To get it back, I have to open Homebridge and restart it. After it starts back up, the Nest thermostat is back again.

The minor annoyance comes from the fact that whenever the thermostat is removed from Home, any automations or scenes that were created with it also have any reference to that device removed. Meaning every time I restart my Raspberry Pi, I have to then restart Homebridge manually and go through all of my scenes to add the thermostat controls back to each one.

**To Reproduce**
1. Restart Raspberry Pi.
2. Open Home app
3. Observe missing Nest thermostat from Home app
4. Restart Homebridge
5. Observe Nest thermostat appearing again

**Comment by andresfb3** [comment]
I have the same issue but typically manifests itself with a network interruption. All other accessories work after network connectivity is resolved except for the nest ones. Restart does the trick and throws everything like new into default room.

**Comment by adriancable** [comment]
@andresfb3 - are you saying that the other accessories stick in their rooms, but the Nest accessories move back to the Default Room?

This is super weird. The plug-ins themselves aren't directly exposed to (or aware of) room assignments.

**Comment by andresfb3** [comment]
> @andresfb3 - are you saying that the other accessories stick in their rooms, but the Nest accessories move back to the Default Room?
> 
> 
> 
> This is super weird. The plug-ins themselves aren't directly exposed to (or aware of) room assignments.

Hi @adriancable yes. But this is similar behavior to what others have reported [like this one](https://github.com/chrisjshull/homebridge-nest/issues/265)

**Comment by adriancable** [comment]
@andresfb3 - is it though? In #263, the issue the OP had was related to Homebridge starting when the googleAuth parameters had expired. As a result the plug-in saw 0 devices, and so Homebridge cleared its accessory cache, and so when the accessories later came back after the credentials were updated, HomeKit didn't realise they were the same accessories, so they ended up back in the Default Room.

What you're saying sounds a little different, if I understand the sequence right: that you have some network issue while running Homebridge, you resolve the issue while running Homebridge, and then you restart Homebridge, and the Nest devices have moved.

**Comment by Hpridham** [comment]
@adriancable I have the same issue. My modem is on a powerbar I frequently turn off by accident (*sigh*).  When it turns back on everything is work and in the right room except for Nest stuff. A restart of homebridge causes them to reappear but in the wrong room (default room).

**Comment by adriancable** [comment]
@Hpridham - the cause here is probably that Homebridge starts before the network is back up. It tries to connect to Nest, it fails, it returns an empty accessory list and your room assignments are gone.

Maybe introduce a sleep 30 before Homebridge starts?

**Comment by mikeb3408** [comment]
Hi I have this same issue. Mine Nest products return to the default room when my OSX homebridge server loses internet connection. They seem fine on a normal homebridge restart.

Are there any solutions to this?

**Comment by adriancable** [comment]
@mikeb3408 - it's not losing Internet connection while Homebridge is running that causes this, it's Homebridge starting up (or restarting) when the Internet connection isn't working, or it can't connect to Nest for any other reason.

There are many possible solutions. Simplest one I can think of is to edit whatever script you are using to start Homebridge to check the internet connection is working, so Homebridge doesn't start if it isn't.

**Comment by mikeb3408** [comment]
@adriancable Hi Adrian, thank you for the quick explanation!

I am running homebridge on my mac using the config UI. I'm not too sure how to edit this to not try to start without an internet connection.

Can you give anymore guidance on how I might be able to do that? I understand if not

**Comment by adriancable** [comment]
@mikeb3408 - sorry, I'm not familiar with the config UI at all - I've never used it.

From looking at https://github.com/oznu/homebridge-config-ui-x it seems that it registers Homebridge as a service on Mac OS, so there must be a script somewhere that the service starts that launches Homebridge with the right command line parameters. This is what you'd need to edit. Maybe post on that Github since I'm sure someone there will be able to help.

**Comment by mbierman** [comment]
@mikeb3408 I know on Docker there is a setting for auto restart. I don’t run homekit on macOS so I’m not sire what the equivalent Is. I’m guessing it is a service like almost everything else that auto starts on macOS. 

I’m curious why you want to not run if there is no connection though. What’s your goal?

**Comment by adriancable** [comment]
Consolidated under #299.
