### ISSUE TITLE
Access token acquisition via googleAuth failed (code ETIMEDOUT)

### ISSUE THREAD

**Issue by songzh96** [chrisjshull/homebridge-nest#269]
HI

when I run homebridge, it will show the error. **Access token acquisition via google auth failed (code ETIMEDOUT)**
I suspect that my computer sent an HTTP get request, but the server did not respond.

But I tested this get request on the postman, there is a response.

So, is this a problem with my computer's HTTP proxy?
How can I solve this problem

Best Regards
Songzh

**Comment by brandon-vidoori** [comment]
https://developers.google.com/nest/device-access

**Comment by adriancable** [comment]
@brandon-vidoori - currently, vaporware.

**Comment by adriancable** [comment]
@songzh96 - your note isn't quite clear to me, but it sounds like you're using an HTTP proxy. I don't believe Homebridge supports HTTP proxies, so you may be SOL.

**Comment by brandon-vidoori** [comment]
> @brandon-vidoori - currently, vaporware.
> 
> In general, if one person reports a connectivity issue, it is 99%+ something to do with their network set-up, rather than anything Google/Nest has done. This plug-in has tens of thousands of users: if Google changed something on their end which broke the plug-in (and this has happened), we would all know about it quite fast.

Glad this isn't the case.  Thanks for taking the time to reply.  I've hidden the comment as off-topic.

**Comment by songzh96** [comment]
> sounds

Thanks for taking the time to reply

I think this problem is related to my network

1. When I run homebridge-nest, it will show
![image](https://user-images.githubusercontent.com/26770241/85350188-03353680-b533-11ea-9dfe-bc5df365e600.png)

2. So I went to study the source code and found a GET request in nest-connection.js

```
req = {
                    method: 'GET',
                    // followAllRedirects: true,
                    timeout: API_TIMEOUT_SECONDS * 1000,
                    url: issueToken,
                    headers: {
                        'Sec-Fetch-Mode': 'cors',
                        'User-Agent': NestEndpoints.USER_AGENT_STRING,
                        'X-Requested-With': 'XmlHttpRequest',
                        'Referer': 'https://accounts.google.com/o/oauth2/iframe',
                        'cookie': cookies
                    }
                };
```

I can't get the response information by running homebridge-nest, but I can get the response information by testing this GET request in "Postman"

So, it should be my network problem
