### ISSUE TITLE
Better Service for Nest Thermostat?

### ISSUE THREAD

**Issue by justinfanok** [chrisjshull/homebridge-nest#27]
Hello,

I think it's awesome you picked up the development work on this plugin. I've been playing around with the HomeKit Accessory Simulator and noticed they have a new service for heating and cooling "heater cooler". I think this would work a lot better for the thermostat and how it functions. As I understand it, the plugin changes the temp for whichever is closest as a way to deal with how different the thermostat service functions in homekit. Do you think it would be possible to expose it using this service? I forked it and was trying to play with it, but I'm running into some issues.

![img_1018](https://user-images.githubusercontent.com/6954156/37376785-7144ff74-26fc-11e8-985b-cbe7492ec15a.PNG)
![img_1017](https://user-images.githubusercontent.com/6954156/37376786-7156310e-26fc-11e8-98bd-986318be068d.PNG)
![img_1016](https://user-images.githubusercontent.com/6954156/37376787-71645086-26fc-11e8-9442-24218ea072ee.PNG)

**Comment by justinfanok** [comment]
This is a project that utilizes the new heatercooler service
https://github.com/nitaybz/homebridge-tado-ac

**Comment by justinfanok** [comment]
Nests function normally by running "heat" "cool" "eco" or the most frequently used "heat - cool" setting. Where you give an upper range and lower range for temperature. This is not possible in the current implementation of the plugin. From what I can tell, it only changes whatever temperature is closer to the current temperature. Not necessarily ideal; it was created before the heater cooler service was developed for IOS 11.

https://github.com/KraigM/homebridge-nest/issues/36

Here's a discussion on the original repo^

**Comment by chrisjshull** [comment]
Have you updated to v2 of homebridge-nest? v2 has proper Auto mode support (Home UI shows a range like in your last screenshot).

**Comment by justinfanok** [comment]
Ah- when I updated npm, it didn't update properly. This is really fantastic! Thanks again!
