### ISSUE TITLE
Siri Not Setting Temperature

### ISSUE THREAD

**Issue by ValoV83** [chrisjshull/homebridge-nest#270]
**Describe the bug**

I cannot make verbal temperature adjustments using Siri on any of my Apple Products - iPhone, iPad, HomePod.
Siri reports the change has been successful but no changes have been made. No attempts to change the temperature within the HOOBS logs are present either.

Manually adjusting the temperature on the Nest Thermostat within the Home app correctly sets the desired temperature on the thermostat itself, within the Nest app and is registered within the HOOBS logs.

**To Reproduce**
1. 

**Expected behavior**
Ask Siri to increase or decrease temperature. Siri confirms change. Desired change is made on Thermostat

Include with your bug report this version info:

HOOBS: 3.2.6
Node: 12.16.2
HOOBS-Nest Plugin 4.4.6

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

**Comment by adriancable** [comment]
@ValoV83 - unfortunately this is 'operator error' (although I prefer to see it as Siri being badly designed and tested). It's beyond my remit to fix. Apple will have to do it.

In the mean time, don't say: Hey Siri, set the temperature to whatever.

Instead, say: Hey Siri, set the Front Room Thermostat to whatever.

**Comment by ValoV83** [comment]
I’ve tried saying that combination to set the thermostat and it’s still not responding.

Siri seems to think it’s successful setting the desired temp, but the changes don’t register on the log in the HOOBS interface. 

The only changes that successfully register are changes made within the Home app on my devices or turning the thermostat ring.

**Comment by adriancable** [comment]
@ValoV83 - can you post a screenshot from the Home app showing the Room where the thermostat is located, including the thermostat accessory tile itself? Also, tell me word-for-word what you are asking Siri to do. Thanks!

**Comment by ValoV83** [comment]
Hopefully these are what you are after....

![2EFCD935-6A28-4601-BEFE-3FA0D18C22AF](https://user-images.githubusercontent.com/53697662/85480953-d0ce1c80-b5b8-11ea-9c51-e039396bc23d.png)
![9B3F160B-3B0D-4B3F-9DE7-6658AAE140DC](https://user-images.githubusercontent.com/53697662/85480967-d6c3fd80-b5b8-11ea-942c-9ad3cbd042e8.png)

I’ve tried the following Siri commands that used to work:

Hey Siri, Set the heating to 15
Hey Siri, Set the nest thermostat to 15
Hey Siri, Set the hall thermostat to 15

Hey Siri, Set the heating to 15 degrees 
Hey Siri, Set the nest thermostat to 15 degrees 
Hey Siri, Set the hall thermostat to 15 degrees 

It’s a Gen2 Nest thermostat and I’m in the uk. It’s heating only. 

Every command is acknowledged with ‘I’ve set the temperature.’

**Comment by ValoV83** [comment]
I've solved the issue this morning.

I removed the HOOBS Bridge from the Home app.
Changed the bridge username and HomeKit pin in the settings
Re-added HOOBS back in Home app

Everything is now working as it should.
