### ISSUE TITLE
Nest Auth failed with Google Auth

### ISSUE THREAD

**Issue by gee4vee** [chrisjshull/homebridge-nest#271]
I have set up config.json using Google Auth per the readme but I'm getting this:

```
[Nest] Auth failed: access token specified in Homebridge configuration
 rejected
```
Is there any way to get more info to debug this? I have not logged out of home.nest.com.

Here is a redacted snippet of the config:
```
  "platforms": [
    {
      "platform" : "Nest",
      "googleAuth": {
         "issueToken": "https://accounts.google.com/o/oauth2/iframerpc?action=issueToken&response_type=token%20id_token&login_hint=A...",
         "cookies": "ANID=AHWq...",
         "apiKey": "A..."
      }
    }
  ]
```

**Comment by adriancable** [comment]
@gee4vee - that's interesting. That error suggests the Google auth is succeeding, but then when the resulting access token is passed to Nest, it's rejecting it.

First can you post the complete output from Homebridge, not just the one 'auth failed' line. What leads up to it is important.

Next, can you take your whole config.json file, redact the auth bits not by truncating with '...' but by scrambling a few characters here and there, and email to adrian.cable@gmail.com and I'll take a look?

**Comment by gee4vee** [comment]
Will get that info. Also a question to see if I'm doing it correctly: I'm logging into home.nest.com via a browser on a different computer. In this case Homebridge is running on a Raspberry Pi. Is this ok or do I have to log in on the rpi?

**Comment by adriancable** [comment]
@gee4vee - that's fine (using a different computer).

**Comment by gee4vee** [comment]
@adriancable Sent the info to your email. Let me know if you don't get it.

**Comment by gee4vee** [comment]
I feel so silly. I was editing the wrong config.json: the one in my home folder instead of /var/lib/homebridge. Everything is working perfectly when edited there (what a surprise!). Thanks for the help.
