### ISSUE TITLE
Nest Sensors show temperature but are unusable as automation sensors

### ISSUE THREAD

**Issue by cstout1** [chrisjshull/homebridge-nest#273]
My Nest Sensors are all assigned to rooms and report temperature great. I noticed today that they are unavailable in the Home app for use with Automations. Is there any way to enable this functionality in the config.json or is it a limitation of how these sensors are currently supported via Homebridge?

**Comment by adriancable** [comment]
@cstout1 - neither. It is a limitation with the Home app.

Download Home+ from the App Store. This lets you create automations based off temperature. Then, bizarrely, once you have created these automations, you can go back to the Home app to edit and maintain them.

**Comment by cstout-jamf** [comment]
Thank you for such a quick reply. How strange is that? I'm happy to say that Home+ has not only achieved this goal, but exceeded expectations in everything else it can do. Thanks again.

**Comment by cstout1** [comment]
Thank you for such a quick reply. How strange is that? I'm happy to say that Home+ has not only achieved this goal, but exceeded expectations in everything else it can do. Thanks again.

**Comment by adriancable** [comment]
@cstout1 - super strange, right? I'll leave this issue open in case anyone else has the same question about temperature automations.
