### ISSUE TITLE
Nest won't give me a new api

### ISSUE THREAD

**Issue by serenacloos** [chrisjshull/homebridge-nest#277]
My Nest got kicked out of HomeKit. This happened to me before and then I'd just fill in the url, cookie and api again.
Now I don't seem to get new settings, api stays the same, so HomeBridge won't 'read' it.

Any ideas?

`[2020-6-29 8:25:13 PM] [Nest] Access token acquisition via googleAuth failed (code ERR_INVALID_CHAR).
[2020-6-29 8:25:13 PM] [Nest] Unable to authenticate with Google/Nest.`

**Comment by adriancable** [comment]
@serenacloos - can you take your config.json, scramble a few characters in the cookies (to invalidate them) and email it to me at adrian.cable@gmail.com?

**Comment by serenacloos** [comment]
> @serenacloos - can you take your config.json, scramble a few characters in the cookies (to invalidate them) and email it to me at [adrian.cable@gmail.com](mailto:adrian.cable@gmail.com)?

You've got mail
