### ISSUE TITLE
Adjusting fan duration problem

### ISSUE THREAD

**Issue by syniast** [chrisjshull/homebridge-nest#280]
I'm trying to get the default fan run time to be set at 2 hours instead of the default 15 minutes.  I've added "fanDurationMinutes": "120" in my config.json under the credentials for my nest account yet this doesn't seem to change how long the fan runs for.  I am able to turn the fan on and off, but the duration seems to be the same with or without that line in my homebridge config.json.  Do I need to add more options into my config to enable this?  Right now I've got this

   {
"platform": "Nest",
            "name": "Nest",
            "access_token": "xxxx",
            "fanDurationMinutes": "120"
        }

Thanks for any help.

**Comment by adriancable** [comment]
Try removing the quotes around the 120.

**Comment by syniast** [comment]
Removing the quotes doesn't actually seem to make a difference.  Sorry I
didn't respond sooner.  I was out of town for the 4th and just got to
trying it.

**Comment by adriancable** [comment]
@syniast - can you send me your complete config.json (scramble the access token) to adrian.cable@gmail.com and I'll take a look.

**Comment by syniast** [comment]
Sure see below

{
    "bridge": {
        "name": "Homebridge A07A",
        "username": "0E:A0:E3:E6:A0:7A",
        "manufacturer": "homebridge.io",
        "model": "homebridge",
        "port": 51327,
        "pin": "727-69-702"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "platform": "config",
            "port": 8581,
            "auth": "form",
            "theme": "deep-purple",
            "tempUnits": "f",
            "lang": "auto",
            "sudo": false,
            "log": {
                "method": "file",
                "path": "/var/lib/homebridge/homebridge.log"
            }
        },
        {
            "platform": "Nest",
            "name": "Nest",
            "access_token": "x",
            "fanDurationMinutes": 120
        }
    ]
}

**Comment by adriancable** [comment]
@syniast - it looks fine to me. Can you try restarting Homebridge and running the fan again? Then, after starting the fan from HomeKit, can you go to the Nest app and see what it says for how long the fan timer is remaining for, and send me a screenshot?

**Comment by syniast** [comment]
I'll restart my pi and report back.

**Comment by syniast** [comment]
Thanks for hanging in there with me.  I finally got it working, it seemed
restarting the system fixed whatever was wrong.

**Comment by adriancable** [comment]
@syniast - great! Thanks for the update. Enjoy the plug-in.
