### ISSUE TITLE
Temperature Change

### ISSUE THREAD

**Issue by tannerscore** [chrisjshull/homebridge-nest#282]
While using the home app. Nest shows up through homebridge. I have three options; Temperature, eco mode and fan. When selecting any of these options. They show up as changed for 3 seconds and then revert back to whatever they were before. None of the commands actually make it to the nest.

**Comment by adriancable** [comment]
@tannerscore - to your config.json, under "platform": "Nest", please add the line:

`"options": [ "Debug.Verbose" ],
`

Then, run: `homebridge -D`

Then, adjust the thermostat settings, confirm it still doesn't work, then email me the complete Homebridge output to adrian.cable@gmail.com and I'll take a look.

**Comment by tannerscore** [comment]
this seemed to fix my issue thank you. Do I remove this from my config file now?

**Comment by adriancable** [comment]
@tannerscore - if turning on debug mode fixed your issue there is a placebo at work. These options don't change the plug-in's HomeKit behaviour in any way.
