### ISSUE TITLE
Fan Turning On when AC Turns On

### ISSUE THREAD

**Issue by thehauntedmattress** [chrisjshull/homebridge-nest#283]
I've been noticing lately that the when my AC turns on, both the Home app in HomeKit and Homebridge-Config-UI-X are reporting that the fan is running, even though I did not turn on the fan.  Is this expected normal behavior?

**Comment by adriancable** [comment]
@thehauntedmattress - I might be missing something, but generally doesn't your AC's system's fan run when the AC turns on? In which case if the Home app is reporting the fan is running, it's actually correct?

**Comment by thehauntedmattress** [comment]
Before one of the updates that was recently pushed out, this was not the behavior exhibited.  Besides, while yes the fan does probably run when the AC does, I for example like to have independent control over the fan.  This for example would be for when I set my thermostat to a specific temperature overnight, and when the temperature inside reaches that temperature setting, the AC will shut itself off.  I turn on the fan independently so that the fan will not shut off when the desired temperature is reached.  I'm not sure I will be able to do this from the Home app or Homebridge-Config-UI-X, if the fan is reported on and not independent from the AC.
