### ISSUE TITLE
High Memory usage

### ISSUE THREAD

**Issue by mbierman** [chrisjshull/homebridge-nest#284]
**Describe the bug**
I noticed very high CPU usage on my homebridge and I believe the source is this plugin. 

**To Reproduce**
At @OZNU's recommendation,
1.  I removed all plugins.
1. Restored an empty `config.json` 
1. Reinstalled one plugin at a time updating the `config.json` for that plugin.
1. Restart homebridge after each plugin installed. 
1. Measure Memory after each plugin installed.

**List of the plugins I run**
1. @milo526/homebridge-tuya-web
1. homebridge-accessory-neurio
1. homebridge-dummy
1. homebridge-synology
1. homebridge-chamberlain
1. homebridge-http-switch
1. homebridge-nest
1. homebridge-powerloss-ifttt-notifier
1. homebridge-automation-calendar
1. homebridge-schedule
1. homebridge-weather-plus

**Results (output from `top`)**
```
 Base install, no plugins 
283m  14%  

Added:
npm i  @milo526/homebridge-tuya-web v0.3.3
npm i  homebridge-accessory-neurio v0.9.9

Result:  306m  15%  

Added:
npm i homebridge-dummy v0.4.1
Result:   306m  15%

Added:
npm i homebridge-synology v0.3.1
Result:  313m  16%  

Added:
npm i homebridge-chamberlain v1.6.1
Result:  311m  16%  

Added:
npm i homebridge-http-switch
Result:  324m  16%  

Added:
npm i homebridge-nest
Result:    1344m  67%  

Added:
npm i homebridge-powerloss-ifttt-notifier
Result:   1347m  67% 

Added:
npm i homebridge-automation-calendar
Result:   1346m  67% 

Added:
npm i homebridge-schedule
Result: 1347m  67%  

Added:
npm i homebridge-weather-plus
Result:  1381m  69% 
```

**Expected behavior**

Include with your bug report this version info:
* **Node.js Version**: 12.18.2
* **NPM Version**: 6.14.6
* **Homebridge Version**: 1.1.1
* **Homebridge Config UI X Version**: v4.23.2
* **Operating System**: Docker
* **Process Supervisor**: Docker
* **homebridge-nest**:   4.4.6

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

**Comment by adriancable** [comment]
@mbierman - this is super odd and not something I've seen (or has been reported) before. Not at all clear to me why the plug-in seems to be taking up so much memory.

Can you try removing homebridge-nest and looking at the memory usage, and then put it back, look again, then remove, look again? Just to make sure it really is homebridge-nest that's causing this.

Also while doing this, would be useful to get VIRT, RES and SHR from (h)top to try and see where that memory is being allocated from.

**Comment by mbierman** [comment]
So I had done what you suggested or at least as close as I could. It was suggested to me that I remove all the plugins and add them one by one to find what was causing the unusual memory usage. So after completely removing every plugin and re-adding them one by one (and their respective configuration) I learned that that was probably a somewhat useless exercise because the bottom line is that the numbers are skewed by the host envornment and I can't isolate whatever else the host is doing from docker.  Of course that meant having to redo my rules, etc too. 👎   So that was fun. :)

Apparently in docker, the reported temperature, memory and CPU are not representative of the docker image but of the host environment itself. This is, in my view, not terribly useful, but it is how it works as far as I am told. So for all I know the numbers I took down were not the cause of the high usage simply a symptom of whatever else the Synology was doing at the time. I will say that in the last few months usage is consistently higher than it was for a long time before that even though I don't think I have changed much else on the device.

I would be happy to collect any info that is useful. I'm not familiar with VIRT, RES, and SHR though. It seems they are more associated with virtual machines than docker but if you can point me at something that suggests how to save them I will provide whatever I can.
