### ISSUE TITLE
Programmatically Adjust Fan Schedule

### ISSUE THREAD

**Issue by jocamero** [chrisjshull/homebridge-nest#285]
Is there a way to program changes to the fan schedule? (Not just statically set it in the config.json)

e.g. run fan 60 min each hour from 10pm to 8am. Then at 8am change to running the fan 15 minutes each hour until 10pm.

I used to do this years ago with https://github.com/gboudreau/nest-api and a simple PHP script but Google killed Nest's dev program and I'm not up to date on current options. Searching reddit, GitHub, and the Internet didn't come up with any immediate solutions.

Maybe, create a virtual switch in HomeKit that gets changed at 10pm and 8am?
Change the "fanDurationMinutes" section of config.json 2x a day?

Thanks in advance for any ideas / suggestions!

**Comment by adriancable** [comment]
@jocamero - you can make HomeKit automations to turn the fan on at a specific time. So it seems the 'missing piece' is the variable running time.

Can't you just simulate this with multiple automations? e.g. set the fan run time to 15 minutes, and then make automations at e.g. 8:00PM, 8:15PM, 8:30PM, 8:45PM to keep it running for that whole hour?

**Comment by mbierman** [comment]
You can use https://github.com/kbrashears5/homebridge-schedule#readme. 

That creates a switch that can do what you want Then create an automation that says when the switch above turns on or off change the state of your nest.

**Comment by jocamero** [comment]
While this is certainly an option I was hoping there was a simpler way than having to make 32 scheduled HomeKit automations (e.g. 8am fan on, 8:15am fan off 16 times for 16 hours). Previously I just switched the Nest setting from nonstop operation to Nest's run 15 min per hour.

> @jocamero - you can make HomeKit automations to turn the fan on at a specific time. So it seems the 'missing piece' is the variable running time.
> 
> Can't you just simulate this with multiple automations? e.g. set the fan run time to 15 minutes, and then make automations at e.g. 8:00PM, 8:15PM, 8:30PM, 8:45PM to keep it running for that whole hour?

**Comment by jocamero** [comment]
I think what I'm leaning towards is setting `"fanDurationMinutes": 600,` in config.json and at 10pm turn the fan on in with a HomeKit scheduled Automation which will then turn the fan off at 8am. Then Nest's built in Fan Schedule of run 15 min each hour from 8am to 10 pm will take over during the day.

What do you guys think? Any better way?
