### ISSUE TITLE
A thank you not an issue

### ISSUE THREAD

**Issue by bwp91** [chrisjshull/homebridge-nest#286]
First of all let me clarify this is not an issue so please close as suits.
But thought you’d appreciate some good feedback.
I only use the nest plugin for my smoke alarms. And i’ve had this plugin installed for over a year — in this case no notifications is good right considering only smoke alarms.
This evening the first time one of the smoke alarms activated and homekit also notified me straight away.
So i’m sure you’re aware anyway but your plugin really does work!
So this is just a thanks.
![75E2CCC0-EEB3-400D-8965-E70D286A26AE](https://user-images.githubusercontent.com/43026681/88488567-fbc7d980-cf85-11ea-96e4-1a59172d876c.jpeg)

**Comment by adriancable** [comment]
@bwp91 - great to hear you're enjoying the plug-in! Thanks for the great feedback, I really do appreciate it. Hope your home is OK after the smoke alarm went off.
