### ISSUE TITLE
Nest Guard - adding to DIY plugin?

### ISSUE THREAD

**Issue by pdgill** [chrisjshull/homebridge-nest#289]
Hi! Wondering if you'd be adding the Nest Guard stuff to the homebridge plugin here or are you going to keep that on Starling only?

Thanks!

**Comment by jdrizzle** [comment]
I would also like to see this integration.

**Comment by Robert91112** [comment]
I as well

**Comment by ssarwa** [comment]
Love this plugin. I would love to see the Nest Guard/Detect DIY mode as well. I see it is already done with Starling. Please let me know if i can help in anyway?

**Comment by sfhoo** [comment]
I would love to have this as well. I took a look at the nest web portal, I believe the only way to do it is to reverse engineer how to subscribe to the trigger aka motion on the detect. I do see the changing setting is using the BatchUpdateState when I switch on an off the path light on detect pathlight_settings type.nestlabs.com/nest.trait.ui.PathlightSettingsTrait

**Comment by ssarwa** [comment]
any update or help needed here?

**Comment by stubble0seven** [comment]
Also quite interested in this feature!

**Comment by twebster22** [comment]
Same!

**Comment by Robert91112** [comment]
https://arstechnica.com/gadgets/2020/10/google-kills-the-nest-secure-its-500-home-security-system/

Maybe not worth it?

**Comment by edd1echau** [comment]
is Starling using a fork of homebridge-nest to support Nest secure? or we just need to know some custom config options to enable?

**Comment by adriancable** [comment]
@edd1echau - sorry, the plug-in doesn't support Nest Secure.
