### ISSUE TITLE
Changing temperature switches Modes

### ISSUE THREAD

**Issue by sparkleys** [chrisjshull/homebridge-nest#291]
If ambient temperature is less than desired temperature, telling Siri to change the temperature will change mode from Cool to Warm/Cool.

**To Reproduce**
1. Thermostat temperature is low (example - 65F) on setting Cool
2. "Set temperature to 70"
3. Thermostat is now changed to Warm/Cool with Warming to 70

**Expected behavior**
Should be able to change the thermostat setting without changing modes so house can heat up its own.

Include with your bug report this version info:

Node.js Version  v12.15.0
Npm v6.13.4
Homebridge Nest  v4.4.6

**Comment by adriancable** [comment]
@sparkleys - unfortunately from what I can tell this is a Siri thing. If you request a temperature warmer than the ambient, Siri will change mode to Heat or Auto, if the mode is currently Cool or Off.

I think this is intended as a convenience feature so you can just request a temperature and Siri will do the right thing ... or at least what Apple thinks is the right thing ... which, it seems, you would disagree with and I don't necessarily disagree with you.
