### ISSUE TITLE
Issue getting API after log-out

### ISSUE THREAD

**Issue by sopmacsl** [chrisjshull/homebridge-nest#292]
Hi everyone. 

I've been using this plugin for a while now and as discuss by others is a pain to re-add your login details every once in a while, a pain but is worth it after all! 

Sadly I have run today into a pickle trying to get the API Key value. I have try for over 2 hours with different browsers and login out, clear caches... you name it. to get the API key value, but it doesn't show me that value anymore in the "request headers". I haven't change anything in my google account so im so confused. I have try to find other people with similar issues and all seam to be able to fix it after just log back in... but no chance!

Anyway, I wonder if anyone had a similar issue or any idea of what else I could try. Thank you! 

Please find a pic attached with all the values Chrome show me for the Request Headers. I hope that helps. 

<img width="129" alt="Screenshot 2020-08-17 at 09 47 55" src="https://user-images.githubusercontent.com/69790949/90376833-f9c9d580-e06e-11ea-8bd9-aeb1bc35b754.png">

**Comment by adriancable** [comment]
@sopmacsl - that screenshot shows you selected the OPTIONS pre-call. You should be choosing the (final) POST call. The x-goog-api-key header is still there - I just checked.

**Comment by sleepyarmistice** [comment]
I'm actually having the same problem using the POST call. 
![Screen Shot 2020-08-18 at 10 07 06 AM](https://user-images.githubusercontent.com/16965095/90523281-afae2600-e13a-11ea-96f5-4f5d4e7c4cac.png)

**Comment by adriancable** [comment]
@sleepyarmistice - clear your cache then try again. The Nest web app can make more than one call to the issue_jwt endpoint. Some of them don't include the x-goog-api-key header. How many POST calls do you see in your network tab?

**Comment by sleepyarmistice** [comment]
This time around, there were two, with the second one containing the the api key. When I was doing it earlier, there was only the one. Anyway, I cleared the cache and it worked, which seems odd because I was working in an incognito window. Thanks for your help and for the great plugin!
