### ISSUE TITLE
Feature: Ignore Backplate Temperature

### ISSUE THREAD

**Issue by taavo** [chrisjshull/homebridge-nest#295]
First: I just set up homebridge-nest and it is awesome. Thank you so much for your work.

Then: I have my Nest Thermostats installed on the exterior wall of my home, which means the temperatures they report from the backplates are so far off from the temperatures inside the house as to be useless. In the summer they're just a degree or two warm, but in the winter they could be 5-10 degrees off. When I ask Siri "what temperature is it in here", I don't want her to say anything about what's happening on exterior walls, and I don't want to see that temperature anywhere in Home.

I can't speak to feasibility, but I can imagine a couple options to make this better:

1. The Nest app lets me define "the temperature" for a thermostat as what's happening at a particular sensor. This is ideal, but (as an engineer) that sounds like it could be tricky given the UX available in the Home app. Maybe a config option? e.g. `Thermostat.<ID GOES HERE>.UseTemperatureFromSensor.<OTHER ID GOES HERE>`?

2. If it were possible to just turn off backplates, that'd be almost as good. So something like `Thermostat.DisableBackplateTemperature`, and then Home just doesn't show anything. But I'm not sure if that's even possible.

What do you think?

**Comment by adriancable** [comment]
@taavo - thanks for your note, and happy you're enjoying the plug-in!

Your use case is really unusual. I didn't even know that the Nest Thermostat was designed to be installed on an external wall ... I don't believe it was designed for example to get (very) wet ... so I am quite surprised it works!

I have to be honest that there probably aren't a lot of people with your use case, and I'm generally against adding features/clutter that don't have a broad audience. I'm not even sure what the right way to approach it technically would be. A thermostat in HomeKit always has to report "some" temperature, so maybe the Thermostat.DisableBackplateTemperature switch makes the thermostat just report whatever the currently selected Temperature Sensor is reporting? Watch this space ... I'll have a think.

**Comment by mbierman** [comment]
I’m guessing he means _inside_ of an exterior wall?

**Comment by adriancable** [comment]
@mbierman - I don't think so ... in that case, the temperature reported by the thermostat should be a fair representation of the inside of the house (even if the wall itself is cold) and I don't think the OP would then say that the temperature reported by the backplate is "so far off ... [the interior temperature] as to be useless".

**Comment by taavo** [comment]
Yup @mbierman got it right. My home has through-the-wall HVAC, so the only place I could put the Nests was on the same wall the unit goes through. Temperatures on that wall—from the backplate—are pretty far from what you experience in the room, which is why my Nest installer suggested I buy sensors.

It’s especially noticeable in the winter. Might be 20 degrees outside, 64 on the backplate, and 70 in the room.

Thanks!

**Comment by SchubyTuesday** [comment]
Hang on, I highly doubt this use case is that unusual. Anyone using external nest temperature sensors to control their nest are likely doing so because the temperature detected by the built-in temperature sensor is inaccurate. This is my case as well. I have my nests embedded in wall units directly next to my AC unit, and use temperature sensors because they are highly inaccurate.

**Thermostat.BuiltInTemperatureSensor.Disable** would be valuable to me and I assume anyone else using external temperature sensors.
