### ISSUE TITLE
Feature request : integration with homebridge-config-ui-x

### ISSUE THREAD

**Issue by EjvindHald** [chrisjshull/homebridge-nest#296]
It would be cool if you could create integration to homebridge-config-ui-x for automatic creation and updates of Google id's. It is done for homebridge-nest-cam

See https://github.com/oznu/homebridge-config-ui-x/issues/831#issuecomment-683268837 for more info.

Thanks.

**Comment by djrams10** [comment]
that would be really great !!! if I understood correctly, it automatically recovers it as soon as it expires? Or do you have to do a manipulation? Thank you.
