### ISSUE TITLE
HomeAway.Disable still shows switch in HomeKit 

### ISSUE THREAD

**Issue by TheRealGreatOldOne** [chrisjshull/homebridge-nest#297]
**Describe the bug**
I have added the option homeaway.disable to my config, to prevent the occupancy switch from my nest protect smoke detector showing up in HomeKit - but it still appears.

**To Reproduce**
1.  Add the line “options”: [“HomeAway.Disable”] to nest setup in Homebridge config.
2. Restart homebridge
3. Check HomeKit 

**Expected behavior**
The home occupied accessory should not appear in HomeKit. The CO detector and Smoke detector should.

Include with your bug report this version info:
Node.js Version | v12.16.2
Npm Version | v6.14.4
Homebridge | v1.1.2
Homebridge-nest | v4.4.6
iOS | v 13.6.1

**Comment by adriancable** [comment]
@TheRealGreatOldOne - please can you share your config.json (with the sensitive bits removed). The switch works, so it's probably in the wrong place in your config.

**Comment by TheRealGreatOldOne** [comment]
@adriancable 

Here's my config entry:

       {
            "name": "Nest",
            "googleAuth": {
                "issueToken": "xxxx",
                "cookies": "xxxx",
                "apiKey": "xxxx",
                "options": [
                    "HomeAway.Disable"
                ]
            },
            "platform": "Nest"
        }

**Comment by adriancable** [comment]
@TheRealGreatOldOne - it goes outside googleAuth, not inside. Fix that and you will be in good shape.
