### ISSUE TITLE
Candidate fix for Nest devices moving back to Default Room after connection failure

### ISSUE THREAD

**Issue by adriancable** [chrisjshull/homebridge-nest#299]
Please give it a try and let me know how it works out for you, if you have experienced this issue.

In this release, if the plug-in cannot connect to the Nest service for whatever reason (e.g. Google credentials expire), rather than remove the Nest devices from HomeKit, it leaves them in (albeit unresponsive), so that when the connection to the Nest service comes back, the accessories are still present, keeping room associations, automations etc.

**Comment by shamoon** [comment]
Really appreciate this update, this has been a frustrating issue, will get to testing ASAP!

Not to hijack this thread but is there any consideration to integrating a similar authentication workflow [as was recently added to nest-cam with config-ui-x](https://github.com/oznu/homebridge-config-ui-x/releases/tag/4.27.0) ?

**Comment by soulcook** [comment]
Thank you so much for doing this. This issue was a nightmare.

**Comment by adriancable** [comment]
@shamoon / @soulcook - look forward to your feedback.

This fix isn't perfect though. If Homebridge can't log into Nest, your devices won't disappear but they will be non-functional without any warning. For example, you can move switches and they stick but have no effect. If only Apple hadn't deprecated the reachability characteristic ... not really sure why that seemed like a smart idea. If anyone knows how to force devices to show 'no response' then please let me know, although going through the threads for HAP-NodeJS/Homebridge it does appear it's not possible to reliably do this.

**Comment by soulcook** [comment]
@adriancable  Thanks again. Will test and let you know what happens. 

I understand about the devices not being marked as offline, but it’s still a lot better than losing them. 

I’m really puzzled though. When Google/Nest authentication initially fails, the affected devices are immediately marked “No response” on the home app. How do they acquire this state, and why does it not persist? (You seem to be saying that it doesn’t).

**Comment by adriancable** [comment]
@soulcook - I don't know for sure. I may be wrong but I don't think they are immediately marked "no response". What I think happens is that when you try to adjust their state, the plug-in returns an error condition to the callback and at that point HomeKit marks that accessory as "No Response". Are you saying that they switch to no response before you try to manipulate them? If so can you double check?

**Comment by soulcook** [comment]
Sorry -- I usually install via npm but 4.4.7 isn't on npm yet. How do I install it from GitHub? (On a Mac).

**Comment by adriancable** [comment]
@soulcook - for installing, just use: npm i chrisjshull/homebridge-nest ... regarding reverting to the default room, not sure. I'm not sure why that would happen, but will do some testing here.

Issue 2, you can edit your config.json and replace the cookies with 'X' or similar, and then restart homebridge, to simulate expiring credentials.

**Comment by shamoon** [comment]
I think he means because 4.4.7 isnt pushed to npm yet. I did install manually with github e.g. git clone `https://github.com/chrisjshull/homebridge-nest.git` and then just copy the files over to where you have the plugin currently installed

**Comment by shamoon** [comment]
Ps. Not sure if related to the update but after I installed my Google auth failed and all of my devices disappeared... Setup again and will see from here.

**Comment by shamoon** [comment]
Oh weird, I just looked again and my accessories are in "Default Room" and I cant change them. When I set the room in the iOS scroll control as soon as I close it it just ticks right back to "Default Room". Im running iOS 14 beta 7 and tvOS 14 beta, not sure if thats related...

**Comment by adriancable** [comment]
@shamoon - so the auth failed wouldn't be related to the update - likely just bad luck. And I would expect the devices to disappear as you observed. But now you have the new version, I would also hope that if/when the auth fail happens again the devices won't disappear.

Regarding not being able to change rooms ... super odd. Could be an iOS 14 beta bug. As you probably know the room assignment is handled entirely by iOS and (as an accessory) we don't have any access to, or influence over, the room assignments. You might want to try removing Homebridge from HomeKit and then re-adding.

**Comment by shamoon** [comment]
Yea I know it's all handled by iOS, just odd. Im not sure about timing since I actually updated to beta 7 this morning just to make things more confusing 😀

**Comment by soulcook** [comment]
@adriancable Yes, as @shamoon says, 4.4.7 not on npm yet. 

I can certainly change the cookies to something invalid in config.json s as you suggest, but that won’t take effect until I restart homebridge, so I won’t be able to observe the dynamic behaviour when authentication fails.

**Comment by djrams10** [comment]
thank you for your progress.  I'm looking forward to the update

**Comment by soulcook** [comment]
Ok. Finished testing it now. 

The good news: it now correctly preserves accessories on restart with failed authentication. Great. 

The BAD news: accessories no longer get marked as “No Response” when authentication fails. They look as if they are still working, even after you interact with them. But they aren’t. This is a real setback. Previously the way I knew that it was time to update the cookie was that the Nest accessories would all show “No Response”. But now it’s really hard to tell, and you just have to notice that changes aren’t having the desired effect.

(Detailed behaviour: After authentication failure, thermostat controls  – for example – still appear to be active, and still show an ambient temperature and set temperature. But the ambient temperature is no longer correct, and while you can adjust the set temperature, it obviously doesn’t affect the actual thermostat, and the icon colour doesn’t update to show the heating on/off state. But no indication that it’s not working.)

Clearly the “No Response” state still exists in the Home app, and it still appears immediately on other accessories if they go offline for some reason (I’ve checked). But it no longer appears on homebridge-nest accessories. 

You’ve explained that Apple has depreciated the reachability characteristic, which you could previously have used to mark accessories as offline. So there are only two possible explanations as far as I can see.
  Either
(1) Other HomeKit bridges are continuing to use the reachability characteristic, and it still works
  Or
(2) There is some other way of the app detecting that an accessory is offline

Either way, it surely should be possible to get it to notice that Nest devices are offline. 

Or am I missing something?

**Comment by adriancable** [comment]
@soulcook - I am happy to hear the good news!

Regarding the bad news, I have just pushed 4.4.8 of the plug-in. This hopefully will make devices report 'no response' in the auth fail scenario. Please can you give it a go? (Note that the Home app seems to wait a while before updating the status to 'no response' - you can try closing it and re-opening if this happens.)

**Comment by shamoon** [comment]
Nice workaround 👍🏼

**Comment by soulcook** [comment]
@adriancable – Thank you. I have installed it, it's working fine so far, and I'm now waiting for the Google cookie to go stale. It never does it when you want it to!

**Comment by adriancable** [comment]
I think we can assume it's fixed in the latest for now, but please keep me updated. 4.4.9 now pushed to npm. Thanks for your help!

**Comment by aherstein** [comment]
This did not work for me; all my plugins showed up again under Default Room and favorited (I have to un-favorite them ever time)

**Comment by adriancable** [comment]
@aherstein - first can you check what version of the plug-in you have. Next can you get hold of the logs that show what the plug-in was doing when this happened? If you're running homebridge as a service, you should be able to get the logs using journalctl for example.

**Comment by djrams10** [comment]
for me also after the update of the plugin (4.4.9), all devices have been renamed and parts have changed and added to favorites.  however, once reconfigured, and after restarting, I no longer have to reconfigure the accessories

**Comment by adriancable** [comment]
@djrams10 / @aherstein - maybe this is the source of the misunderstanding. @djrams10 is correct. If the new version of the plug-in runs and authenticates correctly then the devices shouldn't subsequently disappear/unfavourite. But if your auth token expires, you run the old version of the plug-in, your devices disappear/lose their assocations, then upgrade the plug-in to the newest version, unfortunately we can't bring back the dead. But if everything is working the issue won't then happen again.
