### ISSUE TITLE
Last 2 versions not published to npm?

### ISSUE THREAD

**Issue by stevehoek** [chrisjshull/homebridge-nest#300]
4.4.7 and 4.4.8 are not available on NPM yet, so Homebridge Config does not offer the update, and a restart of Homebridge does not upgrade either.

**Comment by muzzymate** [comment]
See https://github.com/chrisjshull/homebridge-nest/issues/299. It appears they are testing a workaround for the issue mentioned before pushing it out to all.

**Comment by adriancable** [comment]
@muzzymate - yes, that's right. Want to make sure this new release effectively addresses the disappearing devices issue and doesn't introduce any new issues before publishing more broadly to npm.
