### ISSUE TITLE
Plugin does not provide unique stable identifier for Home/Away sensor via API

### ISSUE THREAD

**Issue by RogerSelwyn** [chrisjshull/homebridge-nest#301]
**Describe the bug**
I am trying to integrate my Nest to Home Assistant via a route other than Smartthings. In my Nest environment I have multiple locations which each have an occupancy sensor (Home/Away). However when these are presented via the api to the Home Assistant add-on they have no stable way of identifying them uniquely. This is because they have no serial number presented (I presume because they have no hardware/software associated with them), and I understand the Accessory ID (AID) may not always be the same across multiple pairing (i.e. if you re-pair it isn't necessarily the same). The only other 'unique' identifier I can see is the Name, but of course this can be changed and therefore isn't stable.

The reason I am reporting as a bug is because I think this means it doesn't meet the HAP spec.

Is it possible to provide a unique stable identifier as its 'serial number' via the API?

**To Reproduce**
This isn't visible at the Homebridge end, but is shown at the Home Assistant end as shown in this bug - https://github.com/home-assistant/core/issues/39704 

**Expected behavior**

I'd expect that all accessories have a unique identifier provided to the API.

Include with your bug report this version info:

- Hoobs - 3.2.6
- Nest plugin - 4.4.6

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

**Comment by adriancable** [comment]
@RogerSelwyn - this is a good spot and you're absolutely correct. I think we should provide the Nest structure ID as the 'serial number' for the home/away sensor, unless you have some alternative suggestions.

I'll fix this in the next plug-in version, but leave open till then.

**Comment by RogerSelwyn** [comment]
That would be great. Save me having to fudge the Home Assistant code (which I'm much more familiar with and setup to debug)....

**Comment by adriancable** [comment]
@RogerSelwyn - latest commit to Github (4.4.9 - not yet on NPM) now has this fix.

**Comment by RogerSelwyn** [comment]
Thanks

**Comment by RogerSelwyn** [comment]
@adriancable do you have a timeline for release to NPM, I'm hoping your closing this means you are about to :-) Just so I can line up my transition from Smartthings provided Nest to Hoobs provided. One less piece of hardware on the shelf!!

**Comment by adriancable** [comment]
@RogerSelwyn - if I don't have any negative feedback/bug reports in the next 48 hours following the large change I made last week relating to device persistence, then I will publish on Thursday.

**Comment by RogerSelwyn** [comment]
Cool, thanks
