### ISSUE TITLE
Feature Request - Hot Water Boost sends 30 mins only.

### ISSUE THREAD

**Issue by currybeast** [chrisjshull/homebridge-nest#302]
Hot water switch only sends a 30 min boost.

Please match Nest App by allowing up to 2hrs of Water Heating selectable via config.json.

Donation sent in advance.

Many thanks.

**Comment by adriancable** [comment]
@currybeast - actually this feature has been in for a while, but it wasn't documented. Now amended the README accordingly. In config.json add something like:

`"hotWaterDurationMinutes": 60,`

Thanks so much for your donation - much appreciated.

**Comment by karlc28** [comment]
@adriancable i tried adding that line but it says my json is invalid could you add a sample config with the hot water set to 60 minutes please as I cannot get this to work

**Comment by adriancable** [comment]
@karlc28 - if you post your config.json (with sensitive parts redacted) I will tell you what is wrong.

**Comment by karlc28** [comment]
{
    "bridge": {
        "name": "Homebridge ****",
        "username": "****",
        "port": ****,
        "pin": "****",
        "advertiser": "ciao"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": ****,
            "platform": "config"
        },
        {
            "pollInterval": ****,
            "_bridge": {
                "username": "*****",
                "port": ****
            },
            "platform": "playstation"
        },
        {
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideScanFrequencyButton": false,
            "hideLearnButton": false,
            "port": ****,
            "hideWelcomeMessage": false,
            "hosts": [
                {
                    "address": "192.168.0.57",
                    "mac": "***",
                    "isRFSupported": true,
                    "isRM4": true
                }
            ],
            "accessories": [
                {
                    "name": "Soundbar",
                    "type": "tv",
                    "data": {
                        "on": "2600a00093940f120f120f120f120f330f3210110f120f330f330f330f320f120f120f120f120f950f120f120f120f120f120f110f120f120f330f330f330f120f320f330f330f330f120e120f120f330f00071993940f120f120f120f120f330f320f120f120f330f330f3210320f120f120f120f120f9510110f120f1110110f120f120f120f120f330f330f320f120f330f330f330f320f120f120f120f330f000d05000000000000)",
                        "off": "2600a00093940f120f120f120f120f330f3210110f120f330f330f330f320f120f120f120f120f950f120f120f120f120f120f110f120f120f330f330f330f120f320f330f330f330f120e120f120f330f00071993940f120f120f120f120f330f320f120f120f330f330f3210320f120f120f120f120f9510110f120f1110110f120f120f120f120f330f330f320f120f330f330f330f320f120f120f120f330f000d05000000000000)",
                        "remote": {
                            "playPause": "26005000929510110f120f120f120f320f330f120f120f330f3210320f330f120f120f120f120f940f120f120f120f120f120f330f120f320f120f120f120f330f330f120f320f120f330f330f320f120f000d05000000000000"
                        },
                        "volume": {
                            "up": "2600a000939410110f120f120f120f330f330f120f110f330f330f330f330f110f120f120f120f950f120f120f120f120f320f330f330f120f330f320f330f120f120f120f120f3210110f120f120f330f000718939410110f120f120f120f330f330f120e120f3310320f330f320f120f120f120f120f9510110f120f120f120f320f330f330f120f320f330f330f120f120f120f120f320f120f120f120f330f000d05000000000000)",
                            "down": "2600500092950f1110110f120f120f330f330f120f120f320f330f330f330f120f110f120f120f950f120f120f120f120f120f120f120f320f330f330f330f120f320f330f330f120f120f120f110f330f000d05000000000000)"
                        }
                    }
                }
            ]
        },
        {
            "name": "Nest Thermostat",
            "googleAuth": {
                "issueToken": "******",
                "cookies": "*****"
            },
            "options": [
                "hotWaterDurationMinutes":60,
            ],
            "platform": "Nest"
        }
    ]
}

**Comment by adriancable** [comment]
The line doesn't go inside "options". It goes at the same level as "platform", "name" etc.

**Comment by karlc28** [comment]
> The line doesn't go inside "options". It goes at the same level as "platform", "name" etc.

Sorry I'm not great a json how and where would I put it

**Comment by adriancable** [comment]
Here’s a good article on learning about JSON. It’s worth learning.

https://www.digitalocean.com/community/tutorials/an-introduction-to-json
