### ISSUE TITLE
Allow temperature sensor to drive automation

### ISSUE THREAD

**Issue by petersterling** [chrisjshull/homebridge-nest#304]
Using the option Thermostat.SeparateBuiltInTemperatureSensor.Enable is fine. But it does not appear to allow automations to be built based on the sensor value (i.e. when it changes). Is this because it is being represented as an accessory and not a sensor? Either way, it would be good to have...  :-)

**Comment by adriancable** [comment]
Automations based on temperature are supported by HomeKit but not by the Home app. You can create temperature automations using a third-party HomeKit app (like Home+) and then, after they are created, you can go back to the Home app to manage/edit them.

Strange but true!
