### ISSUE TITLE
Nest x Yale lock reporting incorrect state in HomeKit

### ISSUE THREAD

**Issue by geoffreyspencer** [chrisjshull/homebridge-nest#306]
I look at my Nest devices in Home app. It says both of my doors are unlocked but the Nest app says they are locked and I go to the doors themselves and they are locked. 

node version: v10.21.0
homebridge version: 1.2.3
homebridge-nest version: 4.4.9

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D` -- where do I put this line in the config page?

**Comment by adriancable** [comment]
@geoffreyspencer - sometimes the HomeKit state gets stuck (on the HomeKit side) and maybe this is what's happening, but it's hard to know for sure without the logs. First, edit your config.json and under the "platform": "Nest" line, add:

`
"options": [ "Debug.Verbose" ],
`

Then, if you are running Homebridge as a service, easiest is to stop that service (systemctl stop homebridge) and then run Homebridge manually from the command line as: homebridge -D

Then do some operations with the locks, and when something goes wrong post your log and the screenshot of the Home app and that'll help see what's going on.
