### ISSUE TITLE
Google login like Homebridge-Nest-Cam plugin

### ISSUE THREAD

**Issue by Jarvichi** [chrisjshull/homebridge-nest#309]
**Is your feature request related to a problem? Please describe.**
Logging in is a real pain, especially when the token expires. Configuration from a mobile phone is almost impossible...

**Describe the solution you'd like**
The Homebridge-Nest-Cam plugin offers a Google login dialog which goes and gets the auth token etc. It would be great to have the same feature in the Homebridge-Nest plugin

**Comment by adriancable** [comment]
@Jarvichi - you can use the Google login from homebridge-nest-cam to get the information you need for homebridge-nest. I believe the author of homebridge-nest-cam uses exactly the same format for the Google auth data in the config.json as I use.

Regarding configuration from a mobile phone, can you do that with homebridge-nest-cam?

**Comment by Jarvichi** [comment]
Thanks for the reply, I totally appreciate that I can use the nest cam plugin to get the data, but it doesn't provide the api field data, which is a pain. That's why I was wondering if it would be possible to add the same functionality to the nest plugin as well.
The nest cam plugin configuration does work perfectly from mobile, using the web based ui, you then need to copy and paste the auth and cookie fields into the nest configuration, which is easy enough to do, but still a faff... but as I mentioned above because the api key is missing it still doesn't entirely work.

**Comment by adriancable** [comment]
@Jarvichi - the API key is essentially fixed. (It changed once back in September 2019 about a month after Google Account support was added, and has remained the same since then.)

So I think you can still use the issueToken and cookies fields from homebridge-nest-cam, and just keep the API key the same.
