### ISSUE TITLE
Thermostat Home & Eco sensors

### ISSUE THREAD

**Issue by gerarddvb** [chrisjshull/homebridge-nest#31]
Could you modify nest-thermostat-accessory.js line 128-135?
It will expose 'Home Occupancy Switch' as a occupancy sensor and 'Eco Mode' as a motion sensor.

  if (this.platform.shouldEnableFeature("Thermostat.Home")) {
    const homeService = this.addService(Service.OccupancySensor, "Home Occupied", "home_occupied");
    this.bindCharacteristic(homeService, Characteristic.OccupancyDetected, "Home Occupied", this.getHome, this.setHome);
  }

  if (this.platform.shouldEnableFeature("Thermostat.Eco")) {
    const thermostatEcoModeService = this.addService(Service.MotionSensor, "Eco Mode", "eco_mode");
    this.bindCharacteristic(thermostatEcoModeService, Characteristic.MotionDetected, "Eco Mode", this.getEcoMode, this.setEcoMode);

**Comment by bartdorsey** [comment]
I've got this working in my fork. I added a PR to merge this into this repo. https://github.com/chrisjshull/homebridge-nest/pull/35

**Comment by chrisjshull** [comment]
@gerarddvb, why the close?

**Comment by gerarddvb** [comment]
@bartdorsey opened a PR including these modifications.

**Comment by ersan** [comment]
Unless you're adding an additional accessory I don't see why you would want eco mode exposed as a motion sensor.  I (and I assume others) use the switch to set eco mode using HomeKit occupancy rules instead of Nest because I find it to be much more reliable.

**Comment by adriancable** [comment]
Added in latest commit.
