### ISSUE TITLE
Error while updating

### ISSUE THREAD

**Issue by noppie** [chrisjshull/homebridge-nest#310]
Error: Plugin "[object Object]" Not Found

1.  Updating from the web interface

Include with your bug report this version info:

node v12.16.3
homebridge v 1.2.3
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

**Comment by adriancable** [comment]
Hi @noppie - this error doesn't come from homebridge-nest, or from homebridge itself. Are you using homebridge-config-ui-x? If so, maybe you'd have more luck asking your question there? Sorry I can't help.
