### ISSUE TITLE
Thermostat not discovered : TypeError: Cannot read property 'addService' of undefined

### ISSUE THREAD

**Issue by fbaudens** [chrisjshull/homebridge-nest#311]
Hello
I've just updated my Homebridge-nest plugin after a while (1 year or so). I changed my Auth Token (from old token to access_token with nest account). And now there is an error after fetching new device.

Here is my config extract :
{
"name": "Nest",
"access_token": "MY TOKEN",
"platform": "Nest"
},

Here is the log about Nest plugin :
Registering platform 'homebridge-nest.Nest'
[Nest] Initializing Nest platform...
[Nest] Fetching Nest devices.
[Nest] initing thermostat "Thermostat salon Thermostat": deviceId: 02AXXXXXXXX2PS structureId: 570XXXXXXXXXXX0b6d02f6
[Nest] TypeError: Cannot read property 'addService' of undefined
at new NestDeviceAccessory (/usr/lib/node_modules/homebridge-nest/lib/nest-device-accessory.js:52:62)
at new NestThermostatAccessory (/usr/lib/node_modules/homebridge-nest/lib/nest-thermostat-accessory.js:17:9)
at NestPlatform.<anonymous> (/usr/lib/node_modules/homebridge-nest/index.js:60:47)
at NestPlatform.<anonymous> (/usr/lib/node_modules/homebridge-nest/index.js:67:17)
at API.NestPlatform.api.on (/usr/lib/node_modules/homebridge-nest/index.js:99:40)
[Nest] NOTE: Because we couldn't connect to the Nest service, your Nest devices in HomeKit will not be responsive.

All other devices work well.

node version : v10.22.1
Homebridge version : 0.4.46
homebridge-nest v4.4.10

I've seen nothing about these logs. Anybody can help ?
Thanks a lot, I like driving my Nest thermostat with Homekit and Siri.

**Comment by fbaudens** [comment]
Ok, seems like an upgrade problem... sorry. I've updated Homebridge and all plugins and now it's alive, my thermostat is back in home app again. 
But my Blynk plugin is crashing Homebridge :( I have to look after this.
Bye !

**Comment by dtb3** [comment]
I know this is closed but I'm having the same issue.  Downgraded homebridge-nest to 4.4.6 for now fixed it, so something past that point.

**Comment by adriancable** [comment]
@dtb3 - the original poster's problem was due to the fact he was using a very old, obsolete version of Homebridge (0.4.46). I am willing to bet your problem has the same cause. I don't believe this is a problem with the plug-in.

**Comment by dtb3** [comment]
@adriancable I'm at homebridge v1.1.6 but I did just upgrade to it today from an old version.  I think I traced the block of code the error is coming from, I'll see if I can figure out a resolution but for tonight I'm happy sitting at 4.4.6 and it working.

**Comment by dtb3** [comment]
right after typing that I see that homebridge is at v1.2.3, hrm not sure why it's showing that I'm fully updated.  I'll get to 1.2.3 and reassess.  thanks!

**Comment by adriancable** [comment]
@dtb3 - nest-device-accessory.js includes this line:

    this.addService = this.accessory._associatedHAPAccessory.addService.bind(this.accessory);

And the "issue" is that the _associatedHAPAccessory object was only added to the Accessory class in Homebridge 1.0, whereas the OP was using Homebridge 0.4.46.

Homebridge 1.1.6 is the latest version on npm. 1.2.3 is available on Github, but was unpublished from npm due to stability issues for some people. So, 1.1.6 is probably the best choice for most people and will work fine with homebridge-nest.

If Homebridge 1.1.6 does not work with homebridge-nest for you, then please reach out because it means you're not having the same issue as the OP after all, and we should troubleshoot.

**Comment by dtb3** [comment]
@adriancable I found out I had a very old version of homebridge in /usr/local/lib and the current version in usr/lib.  Everything was showing me the version in usr/lib being up to date, but the one in /usr/local/lib must have been getting called. I rm -rf'd that fool and everything is working as intended.  Thanks so much for the guidance!!

**Comment by adriancable** [comment]
@dtb3 - excellent! Very happy to hear all is now well. Thanks for the update!
