### ISSUE TITLE
Access toke for nest account expiries after one/two hours.

### ISSUE THREAD

**Issue by randy3k** [chrisjshull/homebridge-nest#313]
**Describe the bug**

I am using the the nest account approach to login. The access token works initially and the nest thermostat is functional. However, after one/two hour, the following pops up in the log

```
[10/5/2020, 10:29:50 PM] [Nest] Reauthenticating on Nest service ...
[10/5/2020, 10:29:51 PM] [Nest] Auth failed: access token specified in Homebridge configuration rejected

```

I didn't log out any google or nest accounts. It happens even I was doing nothing.

**Comment by adriancable** [comment]
Do you have a Nest account or a Google account?

Please post the first 10 characters (only) of your access token.

**Comment by randy3k** [comment]
It starts at `g.0.xxxxxxx`. 
I think I have missed up the nest and google accounts. Sorry for the noise.

**Comment by Wirepower** [comment]
> It starts at `g.0.xxxxxxx`.

does this mean its a google account if it starts with g.0? 
What do nest accounts usually start with?

**Comment by adriancable** [comment]
They start with b.

**Comment by Wirepower** [comment]
Ok. That must explain my other issue, as I’m using nest instructions which work but I keep getting kicked off after approx 2 hours. 
Will have to re-try the Google instructions, but when I follow the node url it gives me a nest 404 error. So will have to try the cookie method again :)

**Comment by adriancable** [comment]
Yes, right now if you have a Google account the only method that will work is the Google cookies method.
