### ISSUE TITLE
No Response 

### ISSUE THREAD

**Issue by chemicalsam** [chrisjshull/homebridge-nest#316]
I added this in Hoobs, I am using a Nest Account. The Protects show up fine but they all say No Response.

**Comment by adriancable** [comment]
@chemicalsam - do you have other Homebridge devices set up in HOOBS which work?

Before we take the time to troubleshoot, we need to establish whether this is a problem with the homebridge-nest plug-in, or a problem that lies elsewhere.

**Comment by currybeast** [comment]
Hello, I have the same issue.  I am not using HOOBS, I am via Config-UI-X  HB Service.  Was fine before the recent updates.

**Comment by currybeast** [comment]
No obvious error, other than it does not do the change.

![nesterror2](https://user-images.githubusercontent.com/32799616/96581188-5c3e8c80-12d1-11eb-8521-605f0c18e16a.jpg)
![nesterror1](https://user-images.githubusercontent.com/32799616/96581192-5d6fb980-12d1-11eb-82b7-b51bb8483429.jpg)
