### ISSUE TITLE
Nest Protect doesn't show up in Apple Home app

### ISSUE THREAD

**Issue by Scrantch** [chrisjshull/homebridge-nest#317]
Everything installed correctly and I can see the Protect smoke and carbon monoxide as active with info in the Homebridge Dashboard but how do I get the Protect in Apple's Home app? I need a code or something to enter don't I? Am I missing something?

**Comment by adriancable** [comment]
@Scrantch - what are you expecting to see in the Home app, vs. what are you actually seeing?

In iOS 14, only devices you can control (so not for example smoke alarms) appear as tiles. Other devices only appear in the 'status' bar at the top of their corresponding room.

Before we troubleshoot I want to make sure that there is actually a problem here.

**Comment by Scrantch** [comment]
Hi Adrian. Well I'm not seeing it at all. Don't see it in the status bar at the top of it's (or any) room. Obviously we can't really control the Protect but shouldn't I be able to put it into automations so if its activates I can do something? Not seeing it listed there either.

**Comment by adriancable** [comment]
@Scrantch - can you go to the Home app, click the 'house' icon (top left), Home Settings, Hubs & Bridges, Homebridge, then see if the Protects are listed there.

In iOS 14, when you added Homebridge to the Home app, the app gives you a walkthrough of all the devices being added, with a chance to confirm each of their names etc. Did the Protects appear at this point in the process, and then disappear later? What about any other (non-Nest) Homebridge devices - are they there in the Home app?

**Comment by Scrantch** [comment]
Hmmmm. Perhaps that is the problem. I don't even see the Homebridge listed there. Yet I also have harmony bridge installed and it is working.

**Comment by adriancable** [comment]
@Scrantch - have you added Homebridge to HomeKit? (press '+ in the Home app, then Add Accessory)

**Comment by Scrantch** [comment]
No, I followed the directions after installing harmony bridge for Homebridge! Added the Homebridge proper and now it's working. Thank you!

**Comment by adriancable** [comment]
Great! Glad everything is now working.
