### ISSUE TITLE
Heat/cool mode inconsistency based off ambient temperature

### ISSUE THREAD

**Issue by kiefferbp** [chrisjshull/homebridge-nest#318]
**The bug**
When changing the temperature with Siri while the thermostat is in heat/cool mode, the behavior depends on the ambient temperature and, therefore, you don't 100% know what's going to happen.

For example, consider the following current conditions:
1. Thermostat is set to 64/68.
2. Ambient temperature is 69.

If you tell Siri to set the temperature to 70, the thermostat will be set to 70/74. The end result is that the room warms up to 74 (the heat kicks on to bring the temperature to 70, and then the room warms up to 74 before the AC turns on again).

Now, consider the following current conditions:
1. Thermostat is set to 64/68.
2. Ambient temperature is 71.

Telling Siri to set the temperature to 70 in this case will instead adjust the thermostat to 66/70, which will cool the room to 70 and keep it there unless the temperature drops under 66.

As you can see, the difference in the effective temperature setpoint is significant (74 vs 70) just because the room temperature is 2 degrees different.

**How it should be**
When telling Siri to change the temperature, the result shouldn't depend on the ambient temperature. On Android, telling the assistant a setpoint will set the temperature range where the setpoint is the midpoint, and is therefore always consistent.

**Comment by adriancable** [comment]
@kiefferbp - can you edit config.json, and under "platform": "Nest", add:

`"options": [ "Debug.Verbose" ],`

Then, run: homebridge -D

Then instruct Siri to change the temperature in each of these two cases, and send me the log to adrian.cable@gmail.com, along with what you actually asked Siri and when, and I'll take a look.

My suspicion is that Siri's behaviour in the case where you ask for a specific setpoint in heat/cool mode (which actually needs 2 setpoints) may be undefined, but the homebridge log will tell us whether this is anything we can influence on our side or not. Thanks!

**Comment by kiefferbp** [comment]
Thanks for the reply!

Sorry for the late response. I will be doing this today.
