### ISSUE TITLE
Hiding any specific nest asset

### ISSUE THREAD

**Issue by bluepixel00** [chrisjshull/homebridge-nest#32]
I have multiple nest assets and I am wondering if there is a way to "hide" any specific asset from the home app?

Thanks

**Comment by chrisjshull** [comment]
If it happens to be multiple homes, you can use the structureId config option.
Otherwise, we'll need to add a device filter. Can you discuss more about what you're situation is?
In the interim, you can do what I do and hide the things I don't care about in a separate room (and un-favorite them).

**Comment by chrisjshull** [comment]
Closing as filer is unresponsive. Feel free to reopen/refile with more info if you want this issue tracked.
