### ISSUE TITLE
Home shows Fahrenheit; Plugin Web Page shows Celsius

### ISSUE THREAD

**Issue by wolfgangrumpf** [chrisjshull/homebridge-nest#320]
I am using homebridge-nest v4.4.12 and while my iOS HOME app shows Fahrenheit, the Homebridge web page for the plugin shows Celsius.  I can find no way to change the plugin to display Fahrenheit.

**Comment by mbierman** [comment]
Hamburger menu > IO Settings

**Comment by wolfgangrumpf** [comment]
Well now I feel stupid.  Thanks!

As an aside - is there a way to combine all of the various Nest buttons into a single Nest button with multiple panes under a long press?



Cheers,


Dr. Wolfgang Rumpf

Professor, Dept. of Biotechnology, UMGC
Robert.rumpf@faculty.umgc.edu
wolfgang.rumpf@gmail.com
Mobile - (614) 638-6797

**Comment by adriancable** [comment]
@wolfgangrumpf - unfortunately not. Some types of accessories (like light bulbs) can be combined into a group, but this isn't possible in general for HomeKit devices.

**Comment by wolfgangrumpf** [comment]
Understood, and thanks for getting back to me!



Cheers,


Dr. Wolfgang Rumpf

Professor, Dept. of Biotechnology, UMGC
Robert.rumpf@faculty.umgc.edu
wolfgang.rumpf@gmail.com
Mobile - (614) 638-6797
