### ISSUE TITLE
Automation when heating/cooling

### ISSUE THREAD

**Issue by tylerdorazio** [chrisjshull/homebridge-nest#322]
**Is your feature request related to a problem? Please describe.**
Hi - I’m looking to create some automation when the thermostat goes into heating/cooling mode. I had originally thought I can do this when the fan accessory is on (as the fan is _always on_ on these modes) but it shows the fan as off when actually heating/cooling.

Essentially I have a device that I want to control any time the furnace fan kicks on.

**Describe the solution you'd like**
Can there be a switch accessory that shows on/off when the hvac system is running? I think this would be extremely useful! Unless you’re aware of a way to do this as of now? It seems I can’t create automation based on the thermostat accessory.

**Comment by adriancable** [comment]
@tylerdorazio - use a third-party HomeKit app like Home+ which can create this kind of automation. Once created in the third party app, you can then go back to the regular Home app to manage and edit the automation if you wish. Strange but true.
