### ISSUE TITLE
Thermostat - Ability to set duration on fan runtime

### ISSUE THREAD

**Issue by smidley** [chrisjshull/homebridge-nest#325]
It would be great if we had the ability to set the length of time the fan runs, just like in the Nest app.  It would also be nice if you could set a fan schedule - Something like, starting at 9pm, run the fan for 30mins every hour, until 6am.

**Comment by adriancable-lifesize** [comment]
@smidley - regarding setting the fan duration, please check the README. It tells you how.

Regarding a fan schedule, just set the fan duration in the plug-in to 30 minutes, then create a bunch of automations that turn the fan on, at 9PM, 10PM etc.

**Comment by adriancable** [comment]
@smidley - regarding setting the fan duration, please check the README. It tells you how.

Regarding a fan schedule, just set the fan duration in the plug-in to 30 minutes, then create a bunch of automations that turn the fan on, at 9PM, 10PM etc.

**Comment by adriancable** [comment]
@smidley - I think your config.json is wrong, and there is also a bug on our side. (although the bug is actually harmless, apart from producing that annoying warning)

Please can you post the fanTimerDuration line from your config.json here. Thanks!
