### ISSUE TITLE
HomeAway.AsOccupancySensor not working for thermostat

### ISSUE THREAD

**Issue by Tom2527** [chrisjshull/homebridge-nest#328]
I have both a Nest Thermostat v3 and a Nest Protect. The option "HomeAway.AsOccupancySensor" is added to the config file. Whenever the Protect notices movement, the Occupancy Sensor in Home is immediately triggered. However, this does not work for the Thermostat. It remains as if there is no motion.

When I set this up, everything worked fine. The main difference since then is the upgrade to iOS 14.

**To Reproduce**
1. add HomeAway.AsOccupancySensor to the config.json file

**Expected behavior**
Occupancy Sensor in Home should be triggered when the Thermostat senses motion

Include with your bug report this version info:
```sh
node --version = v12.14.0
homebridge --version = 1.1.6
```

While launching homebridge I do see "[Nest] initing home_away_sensor "Home Occupied - xxx": deviceId: xxx"

**Comment by adriancable** [comment]
@Tom2527 - there are currently issues on the Nest cloud side which is affecting the Home/Away function in general (including when just using the Nest app). It is quite likely this is the cause in your case. I'm looking into a workaround, but the better solution is for Nest to fix it their end so we will see which happens first.

**Comment by adriancable** [comment]
Should be improved in 4.5.1, just published. Give it a shot.
