### ISSUE TITLE
New Google Nest Thermostat Not Found

### ISSUE THREAD

**Issue by bzurc** [chrisjshull/homebridge-nest#332]
Picked up the new [Google Nest Thermostat](https://store.google.com/us/product/nest_thermostat) this weekend and as expected, it is not detected by homebridge-nest (and can't be added to nest.com).

Anyone been able to reverse engineer the auth and API for devices on Google Home? Is there another homebridge project that will support it maybe?

**Comment by adriancable** [comment]
@bzurc - I plan to add support for the new thermostat soon. It uses the same gRPC API as Nest Secure and the Nest x Yale lock. Watch this space!

**Comment by bzurc** [comment]
@adriancable amazing, thank you!  happy to help test if you need!

**Comment by daniyalj** [comment]
Happy to test as well!

**Comment by adriancable** [comment]
I've just published version 4.5.0, supporting the new thermostat - give it a go and let me know how you get on.

**Comment by bzurc** [comment]
@adriancable detected it automatically and working great!  thanks for the quick update and for maintaining this great project!

**Comment by adriancable** [comment]
@bzurc - great to hear! Let us know if you have any issues.

**Comment by thecaseman90** [comment]
hey guys, I just installed home bridge and I have the new google nest thermostat. Can you help me get set up? I try following the instructions but when I log into nest my thermostat does not show because it is through google. Thank you
