### ISSUE TITLE
Doorbell camera

### ISSUE THREAD

**Issue by UKenGB** [chrisjshull/homebridge-nest#333]
**Is your feature request related to a problem? Please describe.**
Lack of native HomeKit doorbell solutions

**Describe the solution you'd like**
Support for Nest's Hello doorbell camera

**Describe alternatives you've considered**
Many other Doorbell cams

**Additional context**
Is there any chance this plug-in will ever support a Nest doorbell camera?

**Comment by adriancable** [comment]
@UKenGB - no plans, because there is the excellent homebridge-nest-cam by @Brandawg93. Give that a shot!
