### ISSUE TITLE
Unable to get current temperature when asking Siri

### ISSUE THREAD

**Issue by ccwillia** [chrisjshull/homebridge-nest#335]
**Describe the bug**
I am able to see the current temperatures for both my nest devices in homekit, but when asking siri for the current temperature of a given thermostat it says the given thermostat is off.  However if i have siri for the current temperature of my home it gives me the rang

**To Reproduce**
1. use Siri, "Hey, Siri what is the temperature downstairs" 

**Expected behavior**
For Siri to provide the temperature but instead it says "the downstairs thermostat is off" 

Include with your bug report this version info:
```sh
node --version
homebridge --version
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

**Comment by adriancable** [comment]
This is a Siri interpretation limitation that we don't have control over. When you ask for the temperature, Siri will report the thermostat's setpoint (if it's heating or cooling), or just tell you it's off if that's the case. I agree it's not very useful. Write to Apple?

**Comment by ccwillia** [comment]
I discovered if i move the thermostat to a given room and ask Siri for the temperature in that room it does provide the temperature you just can not use the thermostat name.  That said I also have one of those remote sensors and i can see it as an accessory in the homebridge-ui but it does appear in homekit.  Can that be added?
