### ISSUE TITLE
Feature Request: Multiple structureId in a comma delimited form

### ISSUE THREAD

**Issue by StephenShamakian** [chrisjshull/homebridge-nest#336]
It would be nice to be able to specify in a comma delimited form the structureId config value. This is due to the fact that I would like to import two homes in Nest but not a third.

Basically on line 55 of index.js instead of looking for the exact value maybe do a search on an exploded array of structureIds by a comma. If that structureId is present in the array then include it.

**Comment by adriancable** [comment]
@StephenShamakian - a great suggestion - I'll aim to add this for the next release. In the mean time you can manually exclude specific device IDs in "options" if you like (as described in the README), to achieve the same effect, albeit with a lot more effort.

**Comment by StephenShamakian** [comment]
@adriancable Awesome! Regarding the exclude pattern, the only thing is there is about 15-20 devices with the protects, temperature sensors, thermostats and locks in the home I want to exclude. It's a good tactical fix for the time being I guess.
