### ISSUE TITLE
Possibility to disable the default temp sensor

### ISSUE THREAD

**Issue by kevinberthiaume** [chrisjshull/homebridge-nest#340]
**Is your feature request related to a problem? Please describe.**
I have a Nest Learning Thermostat and two Nest temp sensor. The Nest is in my living room, a temp sensor also in the living room and a temp sensor in the bedroom. My problem is that the thermostat is on top of 4 smart switches that causing false temperature reading by the thermostat. I have add a temp sensor a couple of feet away and there is about 2 Celcius degrees difference. I have set my to temp sensor as default temp in the Nest app. The issue is that the Home app reporting the default temperature of top the the screen (see capture). The temperature in the green dot is ok. 

**Describe the solution you'd like**
Possibility to disable the default thermostat temp sensor in Homekit or use only the temp sensor as set in the Nest app. None of my temp sensor setting using the default temperature sensor but the default sensor are reported to Homekit.

**Describe alternatives you've considered**
I have try the properties Thermostat.SeparateBuiltInTemperatureSensor.Enable to try to disable it after in Homekit, but it change nothing in Homekit. Regardless of the setting, I see 3 temp sensor in Homekit (default + 2 sensor) and the thermostat icon.

**Additional context**
In the capture (the one with sensor), in Salon, the Température Nest salon (additionnal sensor) reporting 20.5 and set as daytime sensor in Nest app. The thermostat default sensor is reporting 23. In the capture with the temp setting, in the header you see 20 - 23 with is wrong because the default sensor isn't set in the Nest app. The correct header should be 20 - 20.5
![IMG_3957](https://user-images.githubusercontent.com/29066537/100548344-f3d0bc80-3239-11eb-8f8c-3bd9adb32120.PNG)
![IMG_3958](https://user-images.githubusercontent.com/29066537/100548345-f7644380-3239-11eb-9b56-382dd7722cde.PNG)

**Comment by adriancable** [comment]
@kevinberthiaume - edit lib/nest-thermostat-accessory.js, and change line 131 from

`this.bindCharacteristic(tempService, Characteristic.CurrentTemperature, 'Temperature', this.getBackplateTemperature, null, this.formatAsDisplayTemperature);`

to:

`this.bindCharacteristic(tempService, Characteristic.CurrentTemperature, 'Temperature', this.getCurrentTemperature, null, this.formatAsDisplayTemperature);`

Let me know how you get on.

**Comment by kevinberthiaume** [comment]
@adriancable - that's fix the behaviour perfectly. Is it possible to add a setting to manage that?

Also, I don't know if it's the normal behavior when using extra Nest sensor, but by default I have a temp sensor created in Homekit for the thermostat default temp. I didn't set Thermostat.SeparateBuiltInTemperatureSensor.Enable setting.

Thanks for this wonderful plugin!

**Comment by kevinberthiaume** [comment]
Up. (To prevent auto closing)

**Comment by kevinberthiaume** [comment]
Up. For pemanent config in the plugin. Thanks!

**Comment by kevinberthiaume** [comment]
@adriancable : is it possible to have a parameters pour this situation? I loose the modification every time I update. I think it can be usefull for people with Nest sensors. Thanks again for this plugin!

**Comment by kevinberthiaume** [comment]
Up.

**Comment by sweetw0r** [comment]
+1

**Comment by kevinberthiaume** [comment]
Up

**Comment by kevinberthiaume** [comment]
Up.

**Comment by kevinberthiaume** [comment]
Up to prevent stale

**Comment by adriancable** [comment]
@kevinberthiaume - persistence wins the day. I'll add an option for you in the next update to the plug-in, which will be soon (as I'm working on a couple of stability improvements).

**Comment by kevinberthiaume** [comment]
> @kevinberthiaume - persistence wins the day. I'll add an option for you in the next update to the plug-in, which will be soon (as I'm working on a couple of stability improvements).

Thanks @adriancable !

**Comment by adriancable** [comment]
@kevinberthiaume - the latest release (4.6.4) contains a new option you can set in the "options" array in config.json, which does what you want:

Thermostat.UseActiveTempSensorAsThermostatTemperature.Enable

Give it a try!
