### ISSUE TITLE
Nest Fan On/Off malfunction

### ISSUE THREAD

**Issue by jjbrooks62** [chrisjshull/homebridge-nest#341]
**Describe the bug**
I use Nest Learning Thermostats.  The plug-in works as described except for fan control.   When I select the icon to turn the Fan "ON" the HVAC fan begins to operate the icon displays "ON" and the fan graphic begins to rotate,   After approximately 30 seconds, the fan graphic stops rotating and the icon displays "OFF".   Problem is the HVAC fan continues to run for the set time period and there's no way to turn the fan off unless I go back to the Nest app.  

**To Reproduce**
1. Select the HVAC Fan icon on the Homebridge accessory page.

**Expected behavior**
When I select the fan icon the HVAC Fan will start, when I select the fan icon a second time while the HVAC fan is running the HVAC fan will stop.    

Include with your bug report this version info:
Plugin 4,5,1
node -- 14.15.1
homebridge --Windows
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

**Comment by adriancable** [comment]
@jjbrooks62 - thanks for the note and this definitely sounds like a bug! (although we can't reproduce it here)

Can you send me an email at adrian.cable@gmail.com so we can try to debug? Thanks!

**Comment by victoras** [comment]
+1

**Comment by adriancable** [comment]
@victoras - I have isolated the problem. It happens only with thermostats on the protobuf API (about 5% of total thermostats). Fix should be coming within the next 24 hours.

**Comment by victoras** [comment]
@adriancable thank you for your amazing plugin and great work!

**Comment by jjbrooks62** [comment]
Note Only two screen videos attached.  Separate email with third follows.

Installed the new HVAC file.  The Homebridge accessory still has issues. I attached some screen videos.   For the Main Level Fan, control indicates fan is on (HVAC fan goes on).  The control then goes off (HVAC fan still running), Click control again, control indicates fan is running (HVAC fan is running), click control again, control indicates fan is off (HVAC fan is off).

 Upper Level Fan works normal - click control on (HVAC Fan goes on), click control off (HVAC fan goes off)

Top Level is really odd. (FYI - The top level and upper level is a Zoned system.  One HVAC unit controlled by two thermostats.  The thermostats basically start the HVAC system then open/close dampers that shut off air flow between the levels.   As you see in the video when you click the Top Level Fan the Upper Level Fan control goes on but the Top Level HVAC Fan is actually running.

Thanks for helping let me know if you need anything.  Julius



________________________________

**Comment by jjbrooks62** [comment]
Third video screen capture.  Julius

________________________________

**Comment by edlucky1** [comment]
Also experiencing this issue. Press fan button, starts fan and shows on, then button goes to off while fan still running. When fan starts via schedule button shows as off.

Plugin -- 4.5.1
node -- 14.15.3
homebridge -- Raspbian

**Comment by adriancable** [comment]
@edlucky1 - if you have the time and interest in helping test a potential fix, please email me at adrian.cable@gmail.com. Thanks!

**Comment by cormacmahalick** [comment]
I’m also experiencing this issue. Running the latest packages.
