### ISSUE TITLE
"Home Occupancy" not working

### ISSUE THREAD

**Issue by alxalxnet** [chrisjshull/homebridge-nest#342]
I tried both the option "HomeAway.AsOccupancySensor" and "HomeAway.AsOccupancySensorAndSwitch" but in homekit the sensor does not show any occupancy (whether I walk in front of the Nest unit or touch it). Everything else works fine.

**Comment by adriancable** [comment]
@alxalxnet - I think there may be a disconnect between what this function actually does, and what you are hoping it does.

As you know the Nest app has a Home/Away switch, which works two ways - it shows you Nest's current view of whether you are Home or Away, and also lets you override it. By default we expose this as a Switch in HomeKit.

Some people for various reasons though would rather expose this as an occupancy sensor (so you can see the current state, but not change it). That's what this option does.

It doesn't enable any "new" functionality. In general Nest devices don't broadcast over the Nest API when someone walks near them or touches them so we can't respond to that kind of thing.

Hope this clarifies!
