### ISSUE TITLE
Can't find issue token

### ISSUE THREAD

**Issue by macdeutsche** [chrisjshull/homebridge-nest#344]
I am following the direction to the letter, but I can't find issue token. 
There is no iframerpc call in developer tool. no issueToken can be found. 

I think what needs to be put in issuetoken is 
https://accounts.google.com/o/oauth2/iframerpc?action=issueToken&response_type=token%20id_token&login_hint=UNIQUE_VALUE_HERE&client_id=733249279899-44tchle2kaa9afr5v9ov7jbuojfr9lrq.apps.googleusercontent.com&origin=https%3A%2F%2Fhome.nest.com&scope=openid%20profile%20email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fnest-account&ss_domain=https%3A%2F%2Fhome.nest.com

The UNIQUE_VALUE_HERE is what I am looking for, but can't find it...

**Comment by adriancable** [comment]
@macdeutsche - are you definitely using a Google Account rather than a Nest Account? Feel free to take a screen recording of the process you're going through, and send to me at adrian.cable@gmail.com and I'll take a look.

**Comment by macdeutsche** [comment]
Sorry for inconvenience. I was recording it and found it... feel stupid.

**Comment by adriancable** [comment]
Great. Enjoy the plug-in!
