### ISSUE TITLE
Can't use humidity sensor in Apple Home automation

### ISSUE THREAD

**Issue by swl2861** [chrisjshull/homebridge-nest#347]
**Describe the bug**
When I'm trying to create a new automation in Apple Home based on a sensor I can't find/select the humidity sensor from the Nest/Google thermostat. I'd like to select that to automate my humidifier. I can see the Nest/Google humidity sensor in the Apple home app tho. 

**To Reproduce**
1. In Apple Home, Go to automation
2. Select a Sensor detects something
3. Can't find the humidity sensor 

**Expected behavior**
Selectable humidity sensor 

Include with your bug report this version info:
```sh 
node --version homebridge-nest v4.5.1
homebridge --version homebridge-config-ui-x v4.35.0
```

**Comment by swl2861** [comment]
I just found it was a limitation from Apple Homekit itself...

**Comment by JeffroDB** [comment]
If I set "Thermostat.SeparateBuiltInHumiditySensor.Enable" I'm able to automate using the Home+ ios app.

**Comment by swl2861** [comment]
I'm trying diff apple apps now :)
