### ISSUE TITLE
Thermostat Turns Off

### ISSUE THREAD

**Issue by letizido** [chrisjshull/homebridge-nest#351]
My thermostat is turning off some time in the early morning every day. Is there any particular log message I should look for to try to troubleshoot this issue? The only option I'm using is Thermostat.Eco.Disable. I have just removed that, so now no options. Will report on behavior tomorrow morning. The thermostat does not turn off when the Nest plugin is disabled.

**Comment by adriancable-lifesize** [comment]
@letizido - assuming this is related to the plug-in, add to your config.json under the "platform": "Nest" line:

`"options": [ "Debug.Verbose" ],`

Then run: homebridge -D

Then leave Homebridge running for a while, so you capture a log when this happens. Then email me the log to adrian.cable@gmail.com, along with the time this happens, and I'll take a look.

Note: the plug-in only has the ability to change device state on receipt of commands from HomeKit. It doesn't have the ability to do anything of its own accord. So, if this does happen, the trigger will be a Siri command, a scene, or an automation that is not working the way you expect.

**Comment by adriancable** [comment]
@letizido - assuming this is related to the plug-in, add to your config.json under the "platform": "Nest" line:

`"options": [ "Debug.Verbose" ],`

Then run: homebridge -D

Then leave Homebridge running for a while, so you capture a log when this happens. Then email me the log to adrian.cable@gmail.com, along with the time this happens, and I'll take a look.

Note: the plug-in only has the ability to change device state on receipt of commands from HomeKit. It doesn't have the ability to do anything of its own accord. So, if this does happen, the trigger will be a Siri command, a scene, or an automation that is not working the way you expect.

**Comment by brandonroth** [comment]
I am also experiencing this issue and I'm not sure if it's the plugin, or the home bridge application itself.  My symptoms are similar to the OP.  In my case I have two thermostats and only the downstairs unit experiences this problem.  It seems like it happens sometime during the night, but I saw one instance where it happened sometime during the morning/early afternoon.  It's not every day, but close. I sent an email with the relevant logs.
