### ISSUE TITLE
Occupancy Sensor stays triggered in HomeKit

### ISSUE THREAD

**Issue by skwasimo** [chrisjshull/homebridge-nest#352]
Hi there!
I am using homebridge-nest since 1,5y. It's configured via Nest account and I'm not planning on changing it to an Google account anytime soon. 
I have only one Nest Wall Thermostat (T3010GB) which is connected to a heating pump, everything works just fine.
For the last 3 months the occupancy sensor in HomeKit is and stays triggered, even though the nest thermostat is in Away-Mode and the nest log shows no change to "occupied".
Since the beginning "HomeAway.AsOccupancySensor" was activated. For troubleshooting I activated "HomeAway.AsOccupancySensorAndSwtich" a few days ago. I changed the Occupancy manually to "away" in HomeKit and after a while it went back on. During the whole time the Nest App showed a "Away" no change happened in the Nest log as well. Anyone similar issues, or some troubleshoot?

**Comment by adriancable-lifesize** [comment]
@skwasimo - this is an interesting problem! Can you kindly do the following. First, in your config.json, please add "Debug.Verbose" in your "options". Then, make sure the Homebridge service (if you use it) is not running, and then start it manually from the command line: homebridge -D

Once everything is up and running, please change the Home/Away state back and forth in HomeKit (and you might want to confirm again there is no change in the Nest app or the Nest log). After doing this, post the complete output from Homebridge here, or email it to me directly at adrian.cable@gmail.com, and I'll take a look.

**Comment by adriancable** [comment]
@skwasimo - this is an interesting problem! Can you kindly do the following. First, in your config.json, please add "Debug.Verbose" in your "options". Then, make sure the Homebridge service (if you use it) is not running, and then start it manually from the command line: homebridge -D

Once everything is up and running, please change the Home/Away state back and forth in HomeKit (and you might want to confirm again there is no change in the Nest app or the Nest log). After doing this, post the complete output from Homebridge here, or email it to me directly at adrian.cable@gmail.com, and I'll take a look.

**Comment by skwasimo** [comment]
Thanks for reaching out adriancable,
I will get to that soon. I reconfigured the access token, just in case. I changed the setting back to "HomeAway.AsOccupancySensor" as well. Just to monitor, how long it's going to take to change itself to "occupied" in Home-App again.
Funny/strange thing is, that I do see the change to "Away" in the nest log after I switch the trigger off in Home, even though it was never changed to "occupied" in first place. The change to "occupied" happens only in HomeKit.
I will get back to you, with the log after this happens again. Is that ok?

**Comment by skwasimo** [comment]
Hi, 
so it happened again. I'm sorry, but I'm not that good in this stuff.
How exactly do you want me to start Homebridge? I have all of that in my nest-options:
"Thermostat.SeparateBuiltInHumiditySensor.Enable",
"HomeAway.AsOccupancySensorAndSwitch",
"Debug.Verbose"
I am using Homebridge UI as well as ssh from Mac. I suppose I have to run this from terminal using homebridge -D. But it starts with an error, that config.json cannot be found. All Buttons in Homekit stay grey. I can only start homebeige properly using sudo systemctl start homebridge.

**Comment by adriancable** [comment]
@skwasimo - if it says it can't find the config.json from the terminal, then it means the config.json isn't in ~/.homebridge. So find where it actually is, then run homebridge like so:

`homebridge -D -U /path/to/config.json`

**Comment by skwasimo** [comment]
Hello Adrian, is this issue fixed in the newest 4.5.2 version, or should I wait with updating while using the hot fix you provided?

**Comment by adriancable** [comment]
@skwasimo - please update to 4.5.2!
