### ISSUE TITLE
Node application to automate collection of google authentication items for Nest login

### ISSUE THREAD

**Issue by Nastras** [chrisjshull/homebridge-nest#354]
Hello @adriancable,

I just discovered this tool and find it quite interesting. But I have not tested it.

I had the idea that maybe you can integrate this tool into your plugin to get its current credentials displayed in the journalctl when starting the plugin or similar.

Advantage would be the first time you set up the plugin would be displayed directly the correct credentials or If the cookie changes again you would only need the current from the journalctl back into the config.

https://github.com/felipeazucares/nestAuth

Greetings Nastras

**Comment by adriancable** [comment]
Hi @Nastras - the problem with this tool (and the login tool that's part of homebridge-nest-cam, which is basically the same thing) is that it uses puppeteer, which is remote-controlled Chromium, which is explicitly disallowed by Google for log-ins. This isn't just a T&Cs issue, they enforce it technically! So, there is this puppeteer-plugin-extra-stealth which tries to hide the remote-controlled part from Google. And so there is this endless game of cat and mouse. If you look at the commits for puppeteer-plugin-extra-stealth you will see a release, then Google breaks it, then another commit, then Google breaks it, and so on and so on. At any time it could break and never work again, and in fact this isn't just a puppeteer thing, there is simply no known Google login approach via headless (or remote-controlled) browser that Google hasn't eventually blocked. And if I include it as part of the "official" homebridge-nest distribution, then I have to support that and people will quite reasonably expect it to work, which means I have to take on the endless cat and mouse, and to be honest, I don't think I have the stomach for it.

By contrast, the browser approach I describe in the README may be a little cumbersome, but it has the advantage of always working for sure.

There's nothing to stop you using any of these tools to collect the tokens yourself, as a convenience feature - while it still works.

Hope this helps explain the background to my decision not to include this.

**Comment by Nastras** [comment]
Hey @adriancable,

thanks for the very detailed answer. Yes it helps a lot to understand the reasons and why you don't want to implement it.

As I said I just found the tool interesting and did not know that you already have knowledge about this logging possibility therefore the suggestion.

So thanks again and have a nice week!
