### ISSUE TITLE
Home Occupied switch not working

### ISSUE THREAD

**Issue by soulcook** [chrisjshull/homebridge-nest#355]
The “Home Occupied” switch doesn’t have any effect on the home/away status in Nest. I can switch it on or off in the Home app, and the state persists in the app, but the home/away state in the Nest app doesn’t change and the thermostats don’t switch on and out of Eco mode as they should.  

I’m running Homebridge Nest v4.5.1 on Homebridge v1.2.5 with Node JS v14.15.4 on a Mac under Bug Sur. 

Here’s an excerpt from the log which may or may not be relevant:

```
[37m[1/21/2021, 10:14:26 AM] [39m[36m[Nest] [39m[31mAPI observe: error Error: read ECONNRESET[39m
[31m    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20) {[39m
[31m  errno: -54,[39m
[31m  code: 'ECONNRESET',[39m
[31m  syscall: 'read'[39m
[31m}[39m
```

**Comment by adriancable** [comment]
@soulcook - unfortunately this is not relevant.

Please can you, underneath "platform": "Nest" in the config.json, add:

`"options": [ "Debug.Verbose" ],`

Then run: homebridge -D

Then flip the home/away switch in HomeKit and see what happens in the Nest app, then post the complete log. Thanks!

**Comment by soulcook** [comment]
Thanks Adrian.

Ok, this is weird. I did as you requested, and the log is attached. After the most recent restart of Homebridge shown in the log, I checked the Nest app, and the home/away status was showing AWAY. I then checked the Home app and it was showing Occupied. I toggled it a few times backwards and forwards between Occupied and Unoccupied. It had no effect on the status in Nest.

That was yesterday. And that's how it's always been.

BUT today it's all working perfectly! The status in Nest matches the status in Home and instantly responds to the switch.

The only thing I can think of that has changed in the interim is that I told the app to ignore phone locations for me and my wife in home/away settings. I've now re-enabled that feature, as a test, and it continues to work.

I'm letting you know all this in case it helps in case this issue arises in the future. Maybe toggling phone geofencing off and on again is a fix? 🤷🏼

**Comment by soulcook** [comment]
Thanks Adrian.

Ok, this is weird. I did as you requested. It won't let me append the log to this message as it's too long, so here's a link to it:

https://www.dropbox.com/s/fff520hm0enjjou/homebridge.log?dl=0

After the most recent restart of Homebridge shown in the log, I toggled the Nest occupancy switch in the Home app a few times backwards and forwards between Occupied and Unoccupied. It had no effect on the status shown in the Nest app, which remained on Away.

That was yesterday. And that's how it's always been.

BUT today it's suddenly all working perfectly! The status in Nest matches the status in Home and instantly responds to the switch.

The only thing I can think of that has changed in the interim is that I told the app to ignore phone locations for me and my wife in home/away settings. I've now re-enabled that feature, as a test, and it continues to work.

I'm letting you know all this in case it helps in case this issue arises in the future. Maybe toggling phone geofencing off and on again is a fix? 🤷🏼

**Comment by jamie-2bit** [comment]
I've just experienced the same issue. It happens perhaps 1 or 2 times, unprompted at random times.

[8/10/2021, 2:02:37 AM] [Nest Thermostat] API observe: error Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
[8/10/2021, 2:02:37 AM] [Nest Thermostat] Retrying in 10 seconds.
