### ISSUE TITLE
Setting automations on current temperature not working

### ISSUE THREAD

**Issue by danshaw** [chrisjshull/homebridge-nest#356]
I'd like to set up automations based on the current temperature that my Nest is displaying. I am using the Home+ ios app to set this up. I have tried to set the trigger to be an exact temperature and also set a wide range, but the action is never triggering for some reason when the temperature is in that range.

**To Reproduce**
1. Create automation with the trigger set to a temperature range of 32F-70F.
2. Set an action to turn on an outlet switch, light switch, or any sensor to turn on or off.
3. Have temperature hit that range.

**Expected behavior**
I have a Homekit outlet that I would like to turn off or on depending on the current temperature from the Nest. The goal is to keep the temperature in between 68-72F degrees. So I have one automation that is set to turn on the switch when the temperature is 40-68F and one to turn it off when it is 72-100F.

homebridge-nest v4.5.1
node --version = v12.13.0
homebridge --version = v1.1.7

I'm curious if others have seen this or if I am doing something wrong?

![IMG_02104298737E-1](https://user-images.githubusercontent.com/6180024/105498082-b3b41600-5c8d-11eb-8a17-7baba3ff0cdb.jpeg)

**Comment by adriancable** [comment]
@danshaw - this kind of thing should definitely work. (We have tested a similar thing here with Home+.)

One thought: automations like this only trigger if the temperature starts outside the trigger range, and then enters it. So for example your 32 degrees F to 70 degrees F range - for that automation to trigger, the temperature will need to start at > 70 degrees F or < 32 degrees F, and then "drop into" the 32-70 F range. If your temperature is already inside that range, the automation will not trigger. Is this the issue?

**Comment by danshaw** [comment]
@adriancable That's great to hear. I thought that might be the issue too, but I have also tried doing a test where I set the range outside of the current and I still don't have any luck. In the example I gave, I made sure that the current temp was showing 72F at the time.

**Comment by danshaw** [comment]
Figured it out! I looked at the Home+ support documentation and it turns out that for temperatures, you need to format the logic differently. Below is what is working for me.

![IMG_3184](https://user-images.githubusercontent.com/6180024/105561756-bfcbc200-5ce5-11eb-9b5f-4df35cbd2cc0.jpg)
