### ISSUE TITLE
Want to use Fahrenheit instead of Celsius.  How do I set that?

### ISSUE THREAD

**Issue by MartyMcFly210** [chrisjshull/homebridge-nest#358]
**Describe the bug**

**To Reproduce**
1. 

**Expected behavior**

Include with your bug report this version info:
```sh
node --version
homebridge --version
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

**Comment by meadeiator** [comment]
The display of Celsius or Fahrenheit for Homebridge apps is set via Homebridge. Via the Homebridge interface, select Settings (triple dot in upper right) / Homebridge UI and then select the desired Temperature Display Units.  In your case, Fahrenheit.  Although individual apps can then make their own conversions, that is not necessary with this app. The home bridge-nest app respects the global setting.  You will have to restart Homebridge after changing the setting.  That should take care of it.

**Comment by MartyMcFly210** [comment]
Kerry, thanks so much for getting back to me so quickly!

I did what you said and set the temperature to Fahrenheit through Homebridge and restarted Homebridge - that worked!

Thanks!

However, on my iPhone, under the Home app, the Nest Thermostat is still showing up in Celsius.  My iOS software is up to date (version 14.3).

How do I  change to Fahrenheit in the Home app?

Thanks!

Jeff

**Comment by meadeiator** [comment]
In all likelihood, that is being determined by the settings you have on your iPhone/iOS/macOS.  On iOS, go to Settings>General>Language&Region>Temperature and select Fahrenheit.  You can confirm the correct setting on Homebridge (the steps detailed previously) by viewing the settings of the attached Nest unit/device within HomeKit on your device under Hardware Display Unit.  That will NOT change what you see on your iOS device in HomeKit in my experience. If that doesn't work for your specific situation, try Googling "How to switch between Celsius and Fahrenheit on your Apple devices."  I'm not affiliated with this repo but just saw the post when looking for something else and tried to help out.  I can with a fairly high level of confidence confirm, however, that this app works as expected across multiple devices and usage of C and F is managed by the platform and not this app.

**Comment by MartyMcFly210** [comment]
Thank you so much!  That worked!

I am not exactly iOS illiterate and yet I did not know that was a setting in iOS.

Thanks again.

Jeff

**Comment by UltimateForce21** [comment]
> In all likelihood, that is being determined by the settings you have on your iPhone/iOS/macOS. On iOS, go to Settings>General>Language&Region>Temperature and select Fahrenheit. You can confirm the correct setting on Homebridge (the steps detailed previously) by viewing the settings of the attached Nest unit/device within HomeKit on your device under Hardware Display Unit. That will NOT change what you see on your iOS device in HomeKit in my experience. If that doesn't work for your specific situation, try Googling "How to switch between Celsius and Fahrenheit on your Apple devices." I'm not affiliated with this repo but just saw the post when looking for something else and tried to help out. I can with a fairly high level of confidence confirm, however, that this app works as expected across multiple devices and usage of C and F is managed by the platform and not this app.

Changing temperature units in the iphone settings as you described worked for me. Thx
