### ISSUE TITLE
10 degrees celsius

### ISSUE THREAD

**Issue by stlouey** [chrisjshull/homebridge-nest#36]
Hi, the lowest setting using the dail of the nest thermostat is 9 degrees .
When using siri and issuing the command to set the temperature to 9 degress it acknowledges but the temperature is always set to 10. It is as if the lowest temperature thats can be set using homebridge nest plugin is 10 degrees celsius. Using siri i can set it to anything else but not 9 degrees.
Is this an issue with the nest plugin? Thanks

**Comment by chrisjshull** [comment]
Hi @stlouey, can you attach your homebridge logs? 

can you:
1. shut down homebridge
1. launch homebridge in debug mode: `DEBUG=* homebridge -D`
1. attach the log once homebridge is up and running.

**Comment by stlouey** [comment]
Hi Chris, will do as soon as possible. Would also like to mention that the nest thermostat reports ambient temperature in .5 of a degree e.g 17.5 .. but in homekit its displayed rounded up 18. Are you aware of this issue? Thanks

**Comment by stlouey** [comment]
Hi Chris, running homebridge as a service. As requested debug log attached. Thanks
[homebridge.txt](https://github.com/chrisjshull/homebridge-nest/files/1942297/homebridge.txt)

**Comment by stlouey** [comment]
Hi Chris,

Any updated? Thanks

**Comment by stlouey** [comment]
Hi Chris, it’s been several months with no update. Can you please advise? Thanks

**Comment by chrisjshull** [comment]
Sorry, new job has been keeping me busy. But if anyone wants to submit a PR I can squeeze in review time.

**Comment by adriancable** [comment]
Fixed in the latest commit on github (not yet on npmjs).

**Comment by adriancable** [comment]
Now published to npmjs - closing for now.
