### ISSUE TITLE
Protect Occupancy sensor shows triggered when no one in room

### ISSUE THREAD

**Issue by tamorgen** [chrisjshull/homebridge-nest#360]
I just installed homebridge-nest on a new Homebridge build.  I am using the Github release (homebridge-vera v0.8.3-beta.12).  I'm trying to set up scenes based on the occupancy sensor on several Nest Protects, but some rooms show as occupied when there is no one there (at least 24 hours).  

**To Reproduce**
1. Specific rooms, Guest Bedroom and Upper Hallway

**Expected behavior**
Only should show as occupied when movement current or very recent.

Include with your bug report this version info:
```sh
pi@homebridge:~ $ node --version
v14.15.1
pi@homebridge:~ $ homebridge --version
1.1.7```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`
[hoembridge-debug.log](https://github.com/chrisjshull/homebridge-nest/files/5911240/hoembridge-debug.log)

**Comment by pxzel** [comment]
I have the same issue. Two Nest protects (with Smoke Alarm Occupancy tiles)  and one is constantly showing "OCCUPIED". The other Nest Protect triggers (OCCUPIED in HomeBridge) when I walk by and then after 10 minutes of inactivity "OCCUPIED" message goes away.

Ive reinstalled the plugin and unhooked and rehooked the actual Nest protect... still always showing OCCUPIED.

Im using  1.6
homebridge-nest 4.6.9

**Comment by adriancable** [comment]
@pxzel - can you send me an email at adrian.cable@gmail.com? I'd like to work with you to try to debug this. Thanks.
