### ISSUE TITLE
[Question] Battery Operated Nest Protects

### ISSUE THREAD

**Issue by nathantsmith** [chrisjshull/homebridge-nest#361]
Hey, Just curious if the Nest Protect Battery Variants produce any motion events in certain conditions?  Hoping they may be used for some night time automations when the path light would be activated... 

thanks ahead of time.

**Comment by adriancable** [comment]
@nathantsmith - unfortunately, they do not. The battery-powered Nest Protect is almost never connected to your home Wi-Fi, unless it is doing a connection check (typically every 2 days, for no more than a few seconds) or there is an alarm event. So, there is no way for it to report motion events over the network. Sorry!

**Comment by nathantsmith** [comment]
Thank you for the quick & detailed response!
