### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by CountryLimits** [chrisjshull/homebridge-nest#362]
**Describe the bug**
Using Hoobs, and after setting up Homebridge for the first time (using Google Account settings), I'm getting a "Cannot read property 'toLowerCase' of undefined" error 

**To Reproduce**
1. Populated Issue Token, Cookies, API Key as instructed, but am getting a "[Nest] Nest API call to subscribe to device settings updates returned an error: TypeError: Cannot read property 'toLowerCase' of undefined" error.

**Expected behavior**

Include with your bug report this version info:
```sh
node --version
homebridge --version
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

**Comment by adriancable** [comment]
What Nest devices do you have? Can you supply the full Homebridge log output (not just that one line). Thanks!

**Comment by CountryLimits** [comment]
Sure, see below (I believe this is what you asked for). As for my devices, I have a single Nest Learning Thermostat w/ two temp sensors. Additionally, I have nine cameras (6 - Nest Cam Outdoor, 1 - Nest Cam IQ, 1 - Dropcam Pro, 1 - Nest Cam). Separately, I have two other "structures" under the same Google/Nest Account.


2/5/2021, 2:26:36 PM Got SIGINT, shutting down Bridge...
2/5/2021, 2:26:43 PM Loaded plugin 'homebridge-nest'
2/5/2021, 2:26:43 PM [2/5/2021, 3:26:43 PM] Registering platform 'homebridge-nest.Nest'
2/5/2021, 2:26:43 PM Loading 1 platforms...
2/5/2021, 2:26:43 PM [Nest] Initializing Nest platform...
2/5/2021, 2:26:43 PM [Nest] Fetching Nest devices.
2/5/2021, 2:26:43 PM Bridge is running on port 51826.
2/5/2021, 2:26:47 PM [Nest] Nest API call to subscribe to device settings updates returned an error: TypeError: Cannot read property 'toLowerCase' of undefined
2/5/2021, 2:26:47 PM [Nest] Retrying in 10 seconds.

**Comment by adriancable** [comment]
Hi - can you kindly send me an email at adrian.cable@gmail.com so we can continue debugging? Thanks!

**Comment by CountryLimits** [comment]
Sure, see below. I have a single Nest Learning Thermostat w/ two temp sensors. Additionally, I have nine cameras (6 - Nest Cam Outdoor, 1 - Nest Cam IQ, 1 - Dropcam Pro, 1 - Nest Cam). Separately, I have

**Comment by CountryLimits** [comment]
Thank you, just emailed you.

**Comment by adriancable** [comment]
After further debugging, we found the cause of this to be a thermostat that wasn't fully set up. After removing the thermostat from the Nest app, the problem went away. I will add a fix for the next version of the plug-in to ignore devices with incomplete property sets (with a warning) rather than prevent loading of the plug-in.
