### ISSUE TITLE
Duplicate Nest Devices in HOOBS "Available Accessories"

### ISSUE THREAD

**Issue by rtmoose73** [chrisjshull/homebridge-nest#363]
chrisjshull,

First, thank you for developing this plug-in and the time it takes to make truly useful content. I am sure the complaints can outstrip the thank you's and that must suck when you are doing something just to make the world a little better.

Second, my issue.
I just installed Nest 4.5.1 in HOOBS 3.3.2 and when I go to add accessories I see several duplicates of the Nest devices in my home/account. As such I have some questions:

Is this normal?
Should I add all, or 1, or the third one only?
Is this an issue with my Google Nest config (which seems to be fine) or my HOOBS config or some other thing?
Thank you in advance and please let me know where I can contribute financially for your time and work.

Respectfully,

Tony

Below is a screen shot of the "Add Accessories" screen:
<img width="648" alt="add accessories" src="https://user-images.githubusercontent.com/78661641/107156586-26d7b080-694d-11eb-8fba-0ef0f6c83016.png">

**Comment by adriancable** [comment]
Hi @rtmoose73 - I think this is an issue on the HOOBS side and may well best be directed there in the first instance. I'm personally not very familiar with HOOBS and so can't advise. Sorry!
