### ISSUE TITLE
Heating turns off after a few seconds.

### ISSUE THREAD

**Issue by alxalxnet** [chrisjshull/homebridge-nest#366]
Since yesterday, when I turn on the Nest thermostat through the homebridge-nest plugin, Nest received the command and shows the temperature I set on the Home app correctly. However, after 5-7 seconds the thermostat is switched off automatically.

The issue does NOT occur if I set the temperature via the Google Home app.

**Comment by adriancable** [comment]
@alxalxnet - logs with `homebridge -D` and `"options": [ "Debug.Verbose" ],` under `"platform": "Nest",` in your config.json please, or impossible to troubleshoot. Thank you!
