### ISSUE TITLE
Home Away and Temperature Sensor Firmware Alert with Homebridge 1.3.x Betas

### ISSUE THREAD

**Issue by cscott365** [chrisjshull/homebridge-nest#368]
Error in the logs for Firmware Revision and an improper null value as follows:
[Home Occupied@@Firmware Revision] characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics

This applies to the Home Occupied/Away and also to the Nest Temperature Sensors so far. Might apply to other items that have that feature.

**To Reproduce**
1. Install latest Homebridge beta
2. Install latest homebridge-nest plugin
3. Start Homebridge and the alert will be in the logs

**Expected behavior**
Set appropriate data for the entry

Include with your bug report this version info:
node --version: 14.15.5
homebridge --version: 1.3.0-beta.67 (error has existed since I started running 1.3.0 beta)

**Comment by cscott365** [comment]
I also think this is causing the "Fan" Switch to not work as when it hits the Home Occupied Switch and sees the illegal value it then breaks the next steps and so the Fan never gets processed.

**Comment by adriancable** [comment]
Should be fixed in 4.5.2.
