### ISSUE TITLE
Improve API rate limiting code

### ISSUE THREAD

**Issue by Midifreakz** [chrisjshull/homebridge-nest#37]
After a succesfull install and tinkering around a bit with the slider in the ios home app on my iphone, i've seen the code run smoothly in terminal and all was working fine. 

However after a short period of time there was an error coming up in terminal ending with 'BLOCKED' 

Creating a new 'product' at the nest developer platform and re-adding this to the .json config file seems to have fixed the issue.. 

Not sure what was causing this... I know with other nest control apps that sending to many commands in a short period of time can stall this app to send any more commands to the nest thermostat.

**Comment by chrisjshull** [comment]
Yeah, there is code in place to try to rate limit calls to the nest API, but it isn't perfect. Next time this happens, you should be able to wait an hour and be un-blocked. Please also attach your hombridge logs.

**Comment by timcharper** [comment]
I hit this right away when I installed the plugin

**Comment by timcharper** [comment]
Here are some logs from a block scenario:

https://gist.github.com/timcharper/fad3beae25b36777837a2b78c7e512d3

The thermostat somehow was associated with a scene I guess and trying to trigger the scene created a quick blocked scenario.

**Comment by adriancable** [comment]
Should no longer be an issue after refactoring the network code.
