### ISSUE TITLE
Google authentication was unsuccessful from time to time

### ISSUE THREAD

**Issue by Mrdindon** [chrisjshull/homebridge-nest#370]
**Is your feature request related to a problem? Please describe.**
from time to time, connection with Google API will drop generating : 
Nest] Google authentication was unsuccessful. Make sure you did not log out of your Google account after getting your googleAuth parameters.
[19/02/2021, 02:17:08] [Nest] Access token acquisition via googleAuth failed (code USER_LOGGED_OUT).
[19/02/2021, 02:17:08] [Nest] Unable to authenticate with Google/Nest.
[19/02/2021, 02:17:08] [Nest] NOTE: Because we couldn't connect to the Nest service, your Nest devices in HomeKit will not be responsive.

**Describe the solution you'd like**
Instead of manually get the token back and all the the infos, automate that process from homebridge directly so that we only have to provide our google creds from within the plugin and the plugin initiate a session with google to gather the tokens direclty

**Describe alternatives you've considered**

**Additional context**
provide the plugin google creds, and do the work in background of updating key, token, etc..

**Comment by adriancable** [comment]
This would be great if feasible, unfortunately, as far as I'm aware there is no method for the plug-in to "initiate a session with Google to gather the tokens". Yes, there are approaches with puppeteer/puppeteer-extra-stealth and similar which, as "automated logins" Google explicitly disallows and generally work for a short period of time only before Google break them.

Sorry!

**Comment by demonbane** [comment]
I've been having this same issue with both homebridge-nest and [homebridge-nest-cam](https://github.com/Brandawg93/homebridge-nest-cam), and since homebridge-nest-cam switched to the refresh token method it's completely gone away there, but keeps happening with homebridge-nest. I don't know enough about how it works or if it's something that's likely to break, but if it's possible to do the same thing here it'd certainly help me out.

**Comment by fleiscpj** [comment]
@demonbane I agree. This is my experience as well. Please change to Google Accounts using the refresh token.

**Comment by Brandawg93** [comment]
I've added PR #394 to add refresh token authentication to the plugin. It may need more work by the maintainer, though, before it is ready to be published in a new version. For now, if you've already retrieved a refresh token from homebridge-nest-cam, you can simply modify the files changed in the PR within your installed homebridge-nest plugin, modify your config, and restart homebridge, and it should work.

**Comment by protomartyr** [comment]
> I've added PR #394 to add refresh token authentication to the plugin. It may need more work by the maintainer, though, before it is ready to be published in a new version. For now, if you've already retrieved a refresh token from homebridge-nest-cam, you can simply modify the files changed in the PR within your installed homebridge-nest plugin, modify your config, and restart homebridge, and it should work.

I was able to get this to work, thanks @Brandawg93 !
