### ISSUE TITLE
Nest Protect repeated log error

### ISSUE THREAD

**Issue by kronic357** [chrisjshull/homebridge-nest#371]
I keep getting this error every 10-20 seconds in my logs.  I already requested a new token through Nest website and reset wifi connections on my Nest protects but keep having the same error and they don’t work in Home.  It shows room occupied even though there’s no one in the room for hours. Also the automations set for occupancy sensor stopped working.
I currently have installed: 
HOOBS version 3.3.2 
Node version 14.5.1
Nest plugin version 4.5.1

![A5FC7D31-858E-47EE-8B15-73DF09FC6967](https://user-images.githubusercontent.com/79218971/108538688-74410f80-72b5-11eb-80ed-c1f96971b9fb.jpeg)

**Comment by adriancable** [comment]
Do you have a Nest account or a Google account? 400 means the token or Google credentials aren't valid. It could be a copy-and-paste error.

**Comment by kronic357** [comment]
I have a Nest account. I will try and retrieve the token again.

**Comment by kronic357** [comment]
> Do you have a Nest account or a Google account? 400 means the token or Google credentials aren't valid. It could be a copy-and-paste error.

Tried entering the Nest token again but still have the same error.

**Comment by adriancable** [comment]
@kronic357 - can you add `"options": [ "Debug.Verbose" ],` in your config.json under the `"platform": "Nest"` line, then run `homebridge -D` and send the full log to me at adrian.cable@gmail.com, so I can take a look. Thanks!

**Comment by kronic357** [comment]
> @kronic357 - can you add `"options": [ "Debug.Verbose" ],` in your config.json under the `"platform": "Nest"` line, then run `homebridge -D` and send the full log to me at [adrian.cable@gmail.com](mailto:adrian.cable@gmail.com), so I can take a look. Thanks!

Done, let me know if you need anything else. Thanks

**Comment by adriancable** [comment]
Same issue as #380 - watch there for updates.
