### ISSUE TITLE
This plugin generated a warning from the characteristic

### ISSUE THREAD

**Issue by iwensfortis** [chrisjshull/homebridge-nest#372]
**Describe the bug**
Repeated characteristics errors in log

This plugin generated a warning from the characteristic 'Active Identifier': characteristic was supplied illegal value: number -1 exceeded minimum of 0

**To Reproduce**
1. Install the latest homebridge version v 1.3

**Comment by adriancable** [comment]
@iwensfortis - can you share why you think that warning has anything to do with this plug-in? Looking through the HAP-NodeJS code, that warning comes from Characteristic.ActiveIdentifier, which is used to specify TV inputs from remote controls - not a function that relates in any way to Nest.

**Comment by iwensfortis** [comment]
U are completely right it indeed was the harmony plug-in sorry for the confusion.
