### ISSUE TITLE
Homebridge 1.3.0

### ISSUE THREAD

**Issue by crissmil** [chrisjshull/homebridge-nest#373]
Did anyone update homebridge to latest version 1.3.0?
Is nest plugin still working?

**Comment by mbierman** [comment]
Works for me. Did you adjust your [mDNS](https://github.com/homebridge/homebridge/wiki/mDNS-Options) a settings (if needed)

**Comment by androwis** [comment]
I’ve setup homebridge nest as a child bridge and have noticed some hiccups. The nest protects show up but one appears to always have the occupancy sensor triggered while the others do not have any occupancy detection. Haven’t had one of them trigger. 

The nest lock functionality works fine, but wanted to see if anyone else noticed that issue or had a solution

**Comment by adriancable** [comment]
@androwis - the ones that don't have occupancy detection are battery powered ones. They don't report occupancy state over the network (because they are almost never connected to the network). Unfortunately this is not a bug, although I agree that is frustrating!

Regarding the one that appears to always be triggered, are you sure? The occupancy/presence state has a very long 'reset' time, something like 10 minutes, which is appropriate for the intended function (guiding Nest's Home/Away state) so your system doesn't go into Away mode just because you're a little still for a few moments. Is this what you're experiencing?

**Comment by androwis** [comment]
Thanks for getting back to me! Not quiet my experience.
- All my protects are wired. 
- These were all working as expected prior to the 1.3.0 update.  
- To help debug: All the occupancy sensors appear for each protect, but none (except the one that's persistently activated) activate when we pass through the rooms with them
- The one that is persistently activated; stays activated at all times of the day; even when we're not home. 

When I restart my home bridge with Nest as a child bridge, these are the only real outputs I get :

[22/02/2021, 17:08:15] [Nest] Initializing Nest platform...
Starting to advertise 'office pi 8D22' using ciao backend!
[22/02/2021, 17:09:20] Homebridge v1.3.0 (office pi) is running on port 51736.
Initializing HAP-NodeJS v0.9.1...
[22/02/2021, 17:09:20] [Nest] Launched external bridge with PID 1776
[22/02/2021, 17:09:33] Registering platform 'homebridge-nest.Nest'
[22/02/2021, 17:09:44] [Nest] Loaded homebridge-nest v4.5.2 successfully
Preparing Advertiser for 'Nest 00DA' using ciao backend!
[22/02/2021, 17:09:53] [Nest] Fetching Nest devices.
Starting to advertise 'Nest 00DA' using ciao backend!
[22/02/2021, 17:09:57] Homebridge v1.3.0 (Nest) is running on port 47664.
[22/02/2021, 17:10:55] [Nest] Nest API call to subscribe to device settings updates returned an error: ECONNRESET
[22/02/2021, 17:10:55] [Nest] Retrying in 10 seconds.
[22/02/2021, 17:11:51] [Nest] Nest API call to subscribe to device settings updates returned an error: ECONNRESET
[22/02/2021, 17:11:51] [Nest] Retrying in 10 seconds.

**Comment by androwis** [comment]
Just in case this helps others, I had a weird issue where Homebridge 1.3.0 cached multiple child bridges for the nest-plugin. I deleted those cached instances of the nest plugin for the child bridges, restarted the service, and everything worked smoother after that.

**Comment by adriancable** [comment]
@androwis - would you kindly email me at adrian.cable@gmail.com? I'd like to spend some time digging into your strange issue and then get back on Github once we have some additional insight on what's happening. Thanks!
