### ISSUE TITLE
Fan Switch Issue with 4.5.x vs 4.4.x

### ISSUE THREAD

**Issue by cscott365** [chrisjshull/homebridge-nest#374]
The fan switch no longer triggers with version 4.5.x vs the 4.4.x version. I think it is related to the adjustment for the minimum fan time error that 4.4.x produced.

**To Reproduce**
1. Upgrade to 4.5.x of the plugin
2. Attempt to get an event for when the fan turns on, no event fires
3. Downgrade to 4.4.15
4. Fan event for On/Off now fire, but error for minimum fan time now produced in logs.

**Expected behavior**
Minimum fan time error not in logs and fan status of on/off firing correctly.
Include with your bug report this version info:

Node.js Version | v14.15.5
Homebridge | 1.3.0

**Comment by adriancable** [comment]
@cscott365 - thanks for this - I'll need a little help/more info.

In your step 2, can you kindly explain what you mean by "attempt to get an event". Please tell me exactly what you're trying here. Turning the fan on from HomeKit? From the Nest app?

In your step 4, please can you share the exact error (copy & paste) not paraphrase. There are many similar-sounding errors with different causes. Thanks!

**Comment by cscott365** [comment]
Sorry that was a bit ambiguous of me.

Attempt to get an event = Turn fan on from Nest app and get the Fan switch to show the Fan is running. Also if you try to turn the Fan on from Homebridge, the fan shows disabled and sometimes turns on and then immediately turns off. 

Error message on the fan is the following with 4.4.15, but the Fan switch works fine: 
[Entryway Thermostat@@Fan Timer Duration] characteristic was supplied illegal value: number 0 exceeded minimum of 15.

This plugin generated a warning from the characteristic 'Fan Timer Active': characteristic was supplied illegal value: undefined! This might throw errors in the future! See https://git.io/JtMGR for more info.
This plugin generated a warning from the characteristic 'Fan Timer Duration': characteristic was supplied illegal value: number 0 exceeded minimum of 15. See https://git.io/JtMGR for more info.

With 4.5 the errors go away, and I see the code change to fix them, but the Fan switch appears to get a disabled icon and no longer will detect when the fan turns on.

**Comment by cscott365** [comment]
and, I am also running this in a Child Bridge process currently. It should not matter, but wanted to make sure you knew that.

**Comment by adriancable** [comment]
@cscott365 - thanks for the clarification - much appreciated. I think this is a duplicate of #341 (at least the part where, when you try to turn the fan on, it immediately turns off). There is (and has always been) a bug in the handling of the fan for thermostats on the protobuf API. Until recently, protobuf API thermostats were quite rare (< 5% of the total) but it seems that Google is now moving a lot of thermostats from the REST API to the protobuf API, so many more people are encountering this issue than previously. In the next hour or so, I am to publish 4.5.2 which includes a whole bunch of fixes, including for this specific fan issue. Please give it a shot.

Regarding turning the fan on in the Nest app and seeing the state update in the Home app, there is actually what appears to be a bug in the protobuf API (on the Nest side) regarding fan handling. There are two 'signals' in the API that the fan may be running: the first is a fan speed state which, when set, makes the 'spinning fan' icon appear in the thermostat dial in the Nest app. There is also a fan timer expiry state which, when set, makes the words 'FAN RUNNING' appear under the thermostat dial in the Nest app. (It isn't clear to me what the significance of these two different indicators is from a UX standpoint.) These states are not always consistent - very often starting the fan updates the internal fan timer expiry state, but the fan speed state lags behind that by 30 seconds or more. And, when the fan stops or is stopped, the opposite is true, i.e. the fan physically stops moving a long time before the fan speed state updates. So there isn't any way to interpret the data consistently, i.e. without causing a delay in updating to the 'true' fan state on either the turn-on or turn-off conditions.

I am pretty sure this is a Nest API bug, and I am also pretty sure it has only started recently. I will need to do some more digging but this is not the first time Nest API bugs have appeared, and are then fixed days/weeks later, so I will probably just 'watch' this for the time being and see what happens.

**Comment by cscott365** [comment]
Fan appears to be firing correctly now. Might have more issues with node-red, but I do not think they are related to the Nest plugin. Will work some more processes and then close this if we are good. Thanks for the work on the API issues with REST vs protobuf!

**Comment by cscott365** [comment]
All is good now for me with the new changes. Had a small self-inflicted node-red issue in addition that I found once the API issues are resolved. Closing.
