### ISSUE TITLE
Can't Get Google Issue Token

### ISSUE THREAD

**Issue by polycat33** [chrisjshull/homebridge-nest#386]
I'm trying to set up Nest with my Homebridge (I migrated to my Google Account), but when I follow the directions to get the google auth details via Chrome/developer, I can't get the info from there. I get the dev view set up, but when I log in to the Nest website, I don't get any new lines in the dev area that are applicable (and definitely no hits if I filter on issueToken). 

Any ideas?

**Comment by adriancable** [comment]
@polycat33 - did you check 'Preserve Log' as step 3 tells you to?

**Comment by polycat33** [comment]
@adriancable Yes, I did. I even unchecked and re-checked it in case it hadn't taken.

**Comment by polycat33** [comment]
I just tried on my Raspberry Pi with it plugged in to my TV and externals, and I have the SAME results. Not a thing appears in the Network area after I log in to Nest on another tab (I tried a separate window still within Chrome and no-go). 

How do people do this at all? Why wouldn't it work for me on two separate browsers on separate devices but work for everyone else...?

**Comment by adriancable** [comment]
If you can take a screen recording showing you logging into home.nest.com and the sequence of actions you’re taking in the dev tools tab, and email it to me at adrian.cable@gmail.com I’ll take a look.

**Comment by adriancable** [comment]
Closing - resolved it privately.

**Comment by ajschwieterman** [comment]
@adriancable I'm having the same problem.  I can't find the `issueToken` after following the steps to sign into my Google account.
