### ISSUE TITLE
Status Ready & Active when Nest Protect disconnected

### ISSUE THREAD

**Issue by rbswift** [chrisjshull/homebridge-nest#387]
**Describe the bug**

**To Reproduce**
1. Disconnect both power sources (mains and batteries)
2. Wait 20 mins to be sure
3. Check Apple Home app for status
4. Observe "Smoke Sensor Ready" and "Status Active Yes"

**Expected behavior**

Change the status to reflect the device being offline

Include with your bug report this version info:
```# node --version
v12.20.2
# homebridge --version
Initializing HAP-NodeJS v0.9.4...
1.3.4

```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest` done

Also include debug log output from startup through seeing the issue:
```
Mar 17 09:21:01 pi4 homebridge[9185]: [3/17/2021, 9:21:01 AM] Registering platform 'homebridge-nest.Nest'
Mar 17 09:21:01 pi4 homebridge[9185]: [3/17/2021, 9:21:01 AM] [Nest] Initializing Nest platform...
Mar 17 09:21:01 pi4 homebridge[9185]: [3/17/2021, 9:21:01 AM] [Nest] Fetching Nest devices.
Mar 17 09:21:09 pi4 homebridge[9185]: [3/17/2021, 9:21:09 AM] [Nest] initing home_away_sensor "Home Occupied": deviceId: xx structureId: xx
Mar 17 09:21:09 pi4 homebridge[9185]: [3/17/2021, 9:21:09 AM] [Nest] initing protect "Downstairs": deviceId: x structureId: xx
```

**Comment by adriancable** [comment]
Hi @rbswift - thanks for the feedback. The Nest Protect is 'unusual' in that it's almost never actually connected to your Wi-Fi network. It does connect to your network every day or so to check it still can, and then of course if there's actually an alarm event it will connect to your network to notify the Nest API service. But most of the time really - actually - offline, and that's fine.

So why does the plug-in report it's 'online'? Well, the Nest service tells us it is, and by this it really means that the smoke alarm hasn't missed a 'ping', and therefore there's no evidence that it's offline. But as you've found out, the Nest service can't be sure! Your Nest Protect does not send out a 'dying scream' to the Nest API service when you unplug it, telling Nest that it's about to go offline. Instead, you need to wait for Nest to essentially 'time the device out', which is certainly > 24 hours and maybe even longer than that.

**Comment by rbswift** [comment]
Thanks @adriancable for the detailed explanation. In the Nest app the device is listed as "Power Off" status so I had hoped that would be passed through to Homebridge. I'll do some more experimenting with timings and checking what's on the nest home web site. I'd really like to know in Homebridge if there is a problem with my smoke alarms but I guess it's not the end of the world if it takes a day or so. If Homebridge just stays "Ready & Active" indefinitely when the alarm is actually dead then that would be a frightening false sense of security. I've yet to get the occupancy sensor to show up so need to play with that too. cheers

**Comment by rbswift** [comment]
I've done a bit more troubleshooting and discovered I can't log in to the home.nest.com site. It just hourglasses with "This may take a moment" forever. So could this possibly means that HomeBridge can't access either and the Ready & Active status is just a default? The last line in the log is:

`[Nest] initing protect "Stairs": deviceId: xx structureId: xx`

nothing is every logged to indicate this is completed. Is this normal?

**Comment by rbswift** [comment]
I realised the occupancy sensor seems to be reporting through to HomeBridge so I presume the smoke and CO sensors are working too. Sad that there's know easy way to test the connectivity is good but hopefully there's some safety in numbers. Thanks for the guidance and work on the project. Closing this now Cheers
