### ISSUE TITLE
Siri sets thermostat to auto (heat/cool) mode when asking it to change temperature and it is set on Cool

### ISSUE THREAD

**Issue by ronluna** [chrisjshull/homebridge-nest#388]
I currently facing the same exact issue described [here](https://github.com/chrisjshull/homebridge-nest/issues/47) Wondering if there is a way that will prevent the plugin from switching to Auto mode when asked to increase to a higher temperature from what the ambient sensor is ready.

**Comment by adriancable** [comment]
@ronluna - unfortunately there is no way to prevent this. This is Siri thinking it is being 'smart' and knowing better than you if you are (for example) in heat mode, and then try to set the thermostat to a higher temperature than the ambient.

Unfortunately there is no way to 'detect' this. HomeKit, for example, just asks us to change something and we do it. We have no way of knowing whether that request comes from Siri, a manual action, an automation, etc. So in this case we see a request to switch to 'Auto', and another to change the temperature, and unfortunately it looks no different from someone actually switching to 'Auto' and then changing the temperature.

My suggestion is you contact Apple support, or leave them feedback. No, that is not a joke suggestion! Apple (given its surprise) has actually been known to listen to customer feedback directly.

**Comment by ronluna** [comment]
I'll try!
