### ISSUE TITLE
Nest auth not working

### ISSUE THREAD

**Issue by beren12** [chrisjshull/homebridge-nest#392]
Nest auth token not working. I copied it correctly

**To Reproduce**

I have a nest account still, logged in on my laptop and copied the auth token (ends with ==) to my server with homebridge running in a docker container. Restart homebridge and it can't login. I refreshed my browser window and i'm still logged in.

**Expected behavior**

Include with your bug report this version info:
```sh
/homebridge # node --version
v14.16.0

/homebridge # homebridge --version
Initializing HAP-NodeJS v0.9.4...
1.3.4

homebridge-nest v4.5.3

```
Not sure how to do debug logs with docker

[4/6/2021, 9:58:59 PM] [Nest] Auth failed: access token specified in Homebridge configuration rejected
[4/6/2021, 9:58:59 PM] [Nest] Unable to authenticate with Google/Nest.
[4/6/2021, 9:58:59 PM] [Nest] NOTE: Because we couldn't connect to the Nest service, your Nest devices in HomeKit will not be responsive.

**Comment by adriancable** [comment]
@beren12 - the Nest access token does not end with ==, so you copied the wrong field.

**Comment by beren12** [comment]
Well damnit you are right. I do not like json, there's a 2nd access token in the middle of the page but it's under "weave" and I didn't realize. Sorry.

Mine started with b. (maybe give some hints for other people with tunnel vision :-) )
