### ISSUE TITLE
Google Auth using Smart Device Management (SDM) API

### ISSUE THREAD

**Issue by ninoz** [chrisjshull/homebridge-nest#393]
As we know the authentication via google is somewhat hit and miss as the tokens expire after a period of time.

Nest has now been added to the google Smart Device Management (SDM) API: https://developers.google.com/nest/device-access. There is a one off fee of $5 to gain access but I have found the API access to be more reliable and there is also the ability to refresh tokens automatically.  

This is an official method of access so different from the usual Selenium type hacks which google always block.

I have been using this to log my CH stats 
<img width="1517" alt="image" src="https://user-images.githubusercontent.com/1727961/114306082-9b0c0d00-9ad2-11eb-8126-37f4280b8868.png">

Documentation can be found here:
https://developers.google.com/nest/device-access/api/thermostat

Ill try and create a pull request but I've not dabbled in JS before :)

**Comment by cyberchan** [comment]
is there a way to use this to log in to google within the UI setup process? I keep getting the error that google cant log in
