### ISSUE TITLE
Temperature Sensor as Switch?

### ISSUE THREAD

**Issue by brn2prgrm** [chrisjshull/homebridge-nest#396]
I believe this was discussed 1+ years ago, but has there been another look at exposing Nest Temperature Sensors as switches for the Thermostat?

I know the Nest app allows Nest Sensors to be on a schedule, but I would like to create smarter automations that take advantage of the Nest Temp Sensors that I have throughout my house.  Ideally, the automations I would like to create involve determining room occupancy based on other lights or devices, and then assign the Nest Temp Sensor in that room as the primary temp reference for the thermostat.

I do have all necessary Nest devices, migrated to a Google account, if there's any help that I can provide in this process?

Thanks for any consideration!

**Comment by brn2prgrm** [comment]
Here's a link back to the stale discussion from about a year ago...thanks!

_Originally posted by @djrobx in https://github.com/chrisjshull/homebridge-nest/issues/38#issuecomment-626954110_

**Comment by AronEAnderson** [comment]
Thanks for resurfacing this question, @brn2prgrm!  I'd still love to see this implemented and remain willing to assist with testing.

**Comment by brn2prgrm** [comment]
Bump.

Any developer comments?

**Comment by sprabaryjon** [comment]
Pleaaaaaaase. 
This would be extremely useful. Thank you

**Comment by AronEAnderson** [comment]
@adriancable @chrisjshull  Any thoughts on this feature request?

**Comment by brimbey** [comment]
Hi I see that StarlingHub has this feature. however the starling hub is really spotty with homekit and the hub disconnects frequently, so I would rather use this directly from homebridge

**Comment by adriancable** [comment]
@award28 - I love this idea! Unfortunately I did a quick test tonight, and it appears that the Service.InputSource can only be added to a TV. (I tried adding it to a thermostat, and you got additional non-functional tiles in the app, but no nice scrolling list.) It's a real shame, because this would be lovely. I will spend more time on it when I can to confirm.

**Comment by award28** [comment]
That is unfortunate, the UX would have been so clean! I'm thinking of two ideas that have potential then. 

1. Each thermostat sensor could have an associated switch, with only one of the switches able to be on at once. IMHO this is the next best possible solution. 
2. We could create a TV anyways that has these inputs. My issue with this approach is that it's not intuitive nor clean to change the input on a tv and have your Temperature Sensor change 😂. If there is a way to make the TV an accessory on the thermostat (similar to the eco mode switch and fan), then that could be better. 

It might take me a bit to work my way around the code base, but if you'd like I could try to make these changes myself.
