### ISSUE TITLE
3rd gen Thermostat. Cant't set value.

### ISSUE THREAD

**Issue by Anzic23** [chrisjshull/homebridge-nest#398]
**Describe the bug**
I can't set the value, the thermostat is always in read mode. After setting any value, the data is updated and returned to the ones set on the thermostat. the impression is that the plugin works in "read-only" mode ."
**To Reproduce**
1. change the temperature

**Expected behavior**
the set values are accepted by the thermostat.

Include with your bug report this version info:
```sh
node: v12.22.1
homebridge 1.3.4
```

**Comment by Anzic23** [comment]
I updated the tokken, and the control started working. But why did he change? Can I set up automatic token updates?

**Comment by adriancable** [comment]
We are going to be moving to refresh tokens shortly, which have a much longer (if not indefinite) lifetime.
