### ISSUE TITLE
Add temperature sensor.

### ISSUE THREAD

**Issue by Anzic23** [chrisjshull/homebridge-nest#399]
**Is your feature request related to a problem? Please describe.**
It is not possible to use temperature sensors separately from the thermostat.

**Describe the solution you'd like**
The ability to add temperature sensors as stand-alone sensors.

**Additional context**
![image](https://user-images.githubusercontent.com/37106885/116241248-5d171600-a76d-11eb-930b-b954527ad012.png)

**Comment by adriancable** [comment]
Unfortunately temperature sensors rely on communicating with the thermostat - they don't have a direct network connection themselves. So using Nest temperature sensors independently of a paired thermostat isn't possible.
