### ISSUE TITLE
Can't set value on a Nest 3rd gen in Heat/Cool mode

### ISSUE THREAD

**Issue by borski** [chrisjshull/homebridge-nest#402]
**Describe the bug**
Whenever I try to set a value for the Nest in Heat/Cool mode, it doesn't take.
**To Reproduce**
1. Use the HOOBS UI to set a new temperature value for the Nest.
2. Notice it does not update the value on the actual Nest.

**Expected behavior**

Include with your bug report this version info:
```sh
node --version: v14.16.0
homebridge --version: Version 3.3.5 (Docker)
```

The logs seem to only have the following errors:
```
5/4/2021, 1:34:07 PM - [Nest] Setting Eco Mode for Upstairs Thermostat to: range
5/4/2021, 1:34:07 PM - [HOOBS 6EE5@Upstairs Thermostat@Eco Mode@On] SET handler returned write response value, though the characteristic doesn't support write response
```

So it seems to think that Eco mode is on, but it most certainly isn't. Help? :)

**Comment by adriancable** [comment]
@borski - have you tried restarting HOOBS?

What version of Homebridge are you running? (3.3.5 is not it - the latest is 1.3.x)

Can you edit config.json, and under "platform": "Nest", add:

"options": [ "Debug.Verbose" ],

Then run homebridge with the -D command line parameter (sorry, I do not use HOOBS, so you will need to Google how to pass Homebridge command line parameters with HOOBS). Then send me the complete log when you try to adjust the temperature value - this will include a lot more information.

The log messages you sent look fine, and don't imply the plug-in thinks that Eco Mode is on.

**Comment by borski** [comment]
Yes, you are supposed to set a temperature range. In Home Assistant it looks like this:

![image](https://user-images.githubusercontent.com/207674/117079785-54848980-acf1-11eb-9f3a-0334527f7ff9.png)

In HOOBS, it looks like this:

![image](https://user-images.githubusercontent.com/207674/117079799-5d755b00-acf1-11eb-9e62-f2df4f84efd5.png)

Neither works to set the values for the thermostat.

**Comment by adriancable** [comment]
@borski - what happens if you try to set the temperature range from HomeKit?

**Comment by borski** [comment]
Thanks, I hadn't thought to try it from HomeKit (duh) and the issue was a networking one - my docker was set to use the bridged network instead of the host network, and thus the homebridge bridge port wasn't being exposed.
