### ISSUE TITLE
Unable to Authenticate With Google

### ISSUE THREAD

**Issue by grabvba** [chrisjshull/homebridge-nest#405]
Getting the following authteication error when trying to add my Nest to homebridge via the plugin. It's a former Nest account  that I migrated to a Google account. Followed the steps closely and can't seem to get it to work. Homekit sees the Nest via homebridge but is "disconnected"

![nesterror](https://user-images.githubusercontent.com/21967964/118590768-ef507f80-b757-11eb-95dc-a82e5eef44f2.png)

![nesterror2](https://user-images.githubusercontent.com/21967964/118591002-52421680-b758-11eb-96cb-e73fa2d67d78.png)

**Comment by adriancable** [comment]
You haven't included the whole cookie string, but the error description ('Invalid character') tells you what's happening. You've possibly copied and pasted to a rich text editor before going into config.json, which has mangled some characters in there. Maybe when copying and pasting from your browser you didn't expand the field fully, so you have a Unicode ... in there. If you inspect the cookie string as you've pasted it, you should be able to eyeball the character. Then you just need to make sure you copy and paste the cookies string exactly at it appears.

**Comment by grabvba** [comment]
Hey thanks for the reply! I'll take a look a the cookie string again, I copied and pasted the entire cookie string directly from the browser to the Cookie: field that auto populates the config.json. Is it possible that the intermediary is causing the character issue?

**Comment by grabvba** [comment]
Came back to this after a couple of days and just tried again and it worked this time. Not sure why it wasn't working for me a couple days ago.
