### ISSUE TITLE
Expose nest occupancy sensor per thermostat rather than one per home.

### ISSUE THREAD

**Issue by ekobres** [chrisjshull/homebridge-nest#407]
**Describe the solution you'd like**
I would like for each Thermostat in my home to have it's own switch for occupancy so that it can be used to trigger the nest to go into eco mode, or other actions for the room where the nest is located. Currently the occupancy sensor is a home-wide concept. In a multi-nest home, it would be helpful to put uninhabited zones (e.g. guest rooms, office, etc.) into Eco mode automatically even though the home is occupied.

**Describe alternatives you've considered**
There are other occupancy sensors available that could overcome this limitation, but since each Nest has it's own occupancy sensor, it would be ideal to be able to use it.

**Additional context**
Since it would be useful to trigger automations based on the sensor, with this option it would only make sense for the occupancy sensor to be exposed as a switch rather than the home occupancy state of HomeKit. Nest can already set all thermostats in the home to Eco mode when the home is in "Away" mode.

**Comment by adriancable** [comment]
@ekobres - this would be wonderful, but I'm afraid it's not possible. The Nest API only reports the occupancy state on a per-structure basis. While the thermostat does have motion/occupancy sensors we do not have any access to that state information.

**Comment by ekobres** [comment]
Oops, I found a closed issue from 2019 asking for the same thing. Not available through API.
