### ISSUE TITLE
Accessories in homebridge not in homekit

### ISSUE THREAD

**Issue by lawrence-lee** [chrisjshull/homebridge-nest#412]
Can I get some help with my situation? This plugin used to work great, but I just noticed this recently. My nest accessories are not showing up in homekit but they show up in my homebridge

**Expected behavior**

Include with your bug report this version info:
I'm using v1.3.4 of homebridge and homebridge-nest v4.5.3

There are no startup issues as far as I can tell. My other homebridge accessories appear in homekit. I'm only having issues with the nest ones.  Is there anything I can do to verify that the issue is with either this plugjn or homebridge altogether?

**Comment by mbierman** [comment]
Just to confirm, "My other homebridge accessories appear in homebridge." do you mean, "My other homebridge accessories appear in **homekit**"?
