### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by kpagidas** [chrisjshull/homebridge-nest#418]
**Describe the bug**

**To Reproduce**
1. 15/07/2021, 19:02:09Nest BridgeNestiniting protect "VIP ROOM": deviceId: 6416660000CBA5A8 structureId: 1a43d631-023f-11ea-9398-0ac9f51ead87
15/07/2021, 19:02:19Nest BridgeERROR[Nest Bridge 1014@Upstairs Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:02:19Nest BridgeERROR[Nest Bridge 1014@Upstairs Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:02:19Nest BridgeERROR[Nest Bridge 1014@Downstairs Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9.5 exceeded minimum of 10
15/07/2021, 19:02:19Nest BridgeERROR[Nest Bridge 1014@Downstairs Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9.5 exceeded minimum of 10
15/07/2021, 19:02:19Nest BridgeERROR[Nest Bridge 1014@Bedroom Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:02:19Nest BridgeERROR[Nest Bridge 1014@Bedroom Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:02:23Nest BridgeERROR[Nest Bridge 1014@Upstairs Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:02:23Nest BridgeERROR[Nest Bridge 1014@Upstairs Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:02:23Nest BridgeERROR[Nest Bridge 1014@Downstairs Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9.5 exceeded minimum of 10
15/07/2021, 19:02:23Nest BridgeERROR[Nest Bridge 1014@Downstairs Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9.5 exceeded minimum of 10
15/07/2021, 19:02:23Nest BridgeERROR[Nest Bridge 1014@Bedroom Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:02:23Nest BridgeERROR[Nest Bridge 1014@Bedroom Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:02:24Nest BridgeERROR[Nest Bridge 1014@Upstairs Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:02:24Nest BridgeERROR[Nest Bridge 1014@Upstairs Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:02:24Nest BridgeERROR[Nest Bridge 1014@Downstairs Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9.5 exceeded minimum of 10
15/07/2021, 19:02:24Nest BridgeERROR[Nest Bridge 1014@Downstairs Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9.5 exceeded minimum of 10
15/07/2021, 19:02:24Nest BridgeERROR[Nest Bridge 1014@Bedroom Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:02:24Nest BridgeERROR[Nest Bridge 1014@Bedroom Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:03:28Nest BridgeERROR[Nest Bridge 1014@Upstairs Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:03:28Nest BridgeERROR[Nest Bridge 1014@Upstairs Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:03:28Nest BridgeERROR[Nest Bridge 1014@Downstairs Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9.5 exceeded minimum of 10
15/07/2021, 19:03:28Nest BridgeERROR[Nest Bridge 1014@Downstairs Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9.5 exceeded minimum of 10
15/07/2021, 19:03:28Nest BridgeERROR[Nest Bridge 1014@Bedroom Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:03:28Nest BridgeERROR[Nest Bridge 1014@Bedroom Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:03:32Nest BridgeERROR[Nest Bridge 1014@Upstairs Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:03:32Nest BridgeERROR[Nest Bridge 1014@Upstairs Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:03:32Nest BridgeERROR[Nest Bridge 1014@Downstairs Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9.5 exceeded minimum of 10
15/07/2021, 19:03:32Nest BridgeERROR[Nest Bridge 1014@Downstairs Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9.5 exceeded minimum of 10
15/07/2021, 19:03:32Nest BridgeERROR[Nest Bridge 1014@Bedroom Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:03:32Nest BridgeERROR[Nest Bridge 1014@Bedroom Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:03:33Nest BridgeERROR[Nest Bridge 1014@Upstairs Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:03:33Nest BridgeERROR[Nest Bridge 1014@Upstairs Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:03:33Nest BridgeERROR[Nest Bridge 1014@Downstairs Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9.5 exceeded minimum of 10
15/07/2021, 19:03:33Nest BridgeERROR[Nest Bridge 1014@Downstairs Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9.5 exceeded minimum of 10
15/07/2021, 19:03:33Nest BridgeERROR[Nest Bridge 1014@Bedroom Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:03:33Nest BridgeERROR[Nest Bridge 1014@Bedroom Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:04:13Nest BridgeERROR[Nest Bridge 1014@Upstairs Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:04:13Nest BridgeERROR[Nest Bridge 1014@Upstairs Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:04:13Nest BridgeERROR[Nest Bridge 1014@Downstairs Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9.5 exceeded minimum of 10
15/07/2021, 19:04:13Nest BridgeERROR[Nest Bridge 1014@Downstairs Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9.5 exceeded minimum of 10
15/07/2021, 19:04:13Nest BridgeERROR[Nest Bridge 1014@Bedroom Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:04:13Nest BridgeERROR[Nest Bridge 1014@Bedroom Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:05:12Ring BridgeRingERRORSnapshot for Front (stickup_cam_v4 - Spotlight Cam) failed to refresh after 70 attempts.  This is normal behavior since this camera is unable to capture snapshots while streaming
15/07/2021, 19:05:12Ring BridgeRingERRORSnapshot for Front (stickup_cam_v4 - Spotlight Cam) failed to refresh after 70 attempts.  This is normal behavior since this camera is unable to capture snapshots while streaming
15/07/2021, 19:06:15Nest BridgeERROR[Nest Bridge 1014@Upstairs Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:06:15Nest BridgeERROR[Nest Bridge 1014@Upstairs Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:06:15Nest BridgeERROR[Nest Bridge 1014@Downstairs Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9.5 exceeded minimum of 10
15/07/2021, 19:06:15Nest BridgeERROR[Nest Bridge 1014@Downstairs Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9.5 exceeded minimum of 10
15/07/2021, 19:06:15Nest BridgeERROR[Nest Bridge 1014@Bedroom Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:06:15Nest BridgeERROR[Nest Bridge 1014@Bedroom Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:06:16Nest BridgeERROR[Nest Bridge 1014@Upstairs Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:06:16Nest BridgeERROR[Nest Bridge 1014@Upstairs Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:06:16Nest BridgeERROR[Nest Bridge 1014@Downstairs Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9.5 exceeded minimum of 10
15/07/2021, 19:06:16Nest BridgeERROR[Nest Bridge 1014@Downstairs Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9.5 exceeded minimum of 10
15/07/2021, 19:06:16Nest BridgeERROR[Nest Bridge 1014@Bedroom Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:06:16Nest BridgeERROR[Nest Bridge 1014@Bedroom Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:06:17Nest BridgeERROR[Nest Bridge 1014@Upstairs Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:06:17Nest BridgeERROR[Nest Bridge 1014@Upstairs Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:06:17Nest BridgeERROR[Nest Bridge 1014@Downstairs Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9.5 exceeded minimum of 10
15/07/2021, 19:06:17Nest BridgeERROR[Nest Bridge 1014@Downstairs Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9.5 exceeded minimum of 10
15/07/2021, 19:06:17Nest BridgeERROR[Nest Bridge 1014@Bedroom Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:06:17Nest BridgeERROR[Nest Bridge 1014@Bedroom Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:06:18Nest BridgeERROR[Nest Bridge 1014@Upstairs Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:06:18Nest BridgeERROR[Nest Bridge 1014@Upstairs Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:06:18Nest BridgeERROR[Nest Bridge 1014@Downstairs Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9.5 exceeded minimum of 10
15/07/2021, 19:06:18Nest BridgeERROR[Nest Bridge 1014@Downstairs Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9.5 exceeded minimum of 10
15/07/2021, 19:06:18Nest BridgeERROR[Nest Bridge 1014@Bedroom Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:06:18Nest BridgeERROR[Nest Bridge 1014@Bedroom Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:06:19Nest BridgeERROR[Nest Bridge 1014@Upstairs Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:06:19Nest BridgeERROR[Nest Bridge 1014@Upstairs Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:06:19Nest BridgeERROR[Nest Bridge 1014@Downstairs Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9.5 exceeded minimum of 10
15/07/2021, 19:06:19Nest BridgeERROR[Nest Bridge 1014@Downstairs Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9.5 exceeded minimum of 10
15/07/2021, 19:06:19Nest BridgeERROR[Nest Bridge 1014@Bedroom Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:06:19Nest BridgeERROR[Nest Bridge 1014@Bedroom Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:06:20Nest BridgeERROR[Nest Bridge 1014@Upstairs Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:06:20Nest BridgeERROR[Nest Bridge 1014@Upstairs Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:06:20Nest BridgeERROR[Nest Bridge 1014@Downstairs Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9.5 exceeded minimum of 10
15/07/2021, 19:06:20Nest BridgeERROR[Nest Bridge 1014@Downstairs Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9.5 exceeded minimum of 10
15/07/2021, 19:06:20Nest BridgeERROR[Nest Bridge 1014@Bedroom Thermostat@@Target Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10
15/07/2021, 19:06:20Nest BridgeERROR[Nest Bridge 1014@Bedroom Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 9 exceeded minimum of 10

**Expected behavior**

Include with your bug report this version info:
```sh
node --version
homebridge --version
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

**Comment by adriancable** [comment]
... and beyond these warnings on your terminal, can you tell me what function, exactly, isn't working properly? Thank you.

**Comment by kpagidas** [comment]
everything Is working but is it normal to flood the log like this ?

because this does not stops ..

**Comment by adriancable** [comment]
Yes, it's normal. It's just a consequence of the fact that Nest limits heating threshold temperatures to 10 degrees, and then breaks its own rule for eco/safety temperatures. If you really want to stop it you can increase the lower end of your eco/safety temperature from 9 degrees to 10.
