### ISSUE TITLE
Auth failed: access token specified in Homebridge configuration rejected.

### ISSUE THREAD

**Issue by jawais84** [chrisjshull/homebridge-nest#419]
Followed per instructions, but keep receiving the title error.

In the instructions for using a Nest account and accessing the session to get the token, {"2fa_state":"not_enrolled","access_token":"XXX","email":"...","expires_in":"...", ...}, what exactly is at the end of the string to be looking for to ensure I'm copying it correctly? Below is a redacted version of the entire session info. I've tried various sections of it without success. Clearly, I'm doing it wrong and borking things.

Apologies and thanks in advance.

{"2fa_state":"none","access_token":"***REDACTED***","email":"rick@morty.com","expires_in":"Mon, 21-Aug-2021 21:21:21 GMT","urls":{"rubyapi_url":"https://home.nest.com/","czfe_url":"https://czfe30-front01-iad01.transport.home.nest.com","log_upload_url":"https://logsink.home.nest.com/upload/user","transport_url":"https://czfe30-front01-iad01.transport.home.nest.com","weather_url":"https://apps-weather.nest.com/weather/v1?query=","support_url":"https://nest.secure.force.com/support/webapp?","direct_transport_url":"https://transport03-rts29-iad01.transport.home.nest.com:443"},"2fa_enabled":true,"userid":"898171","2fa_state_changed":"1970-01-01 00:00:01.0","is_superuser":false,"language":"en_US","weave":{"service_config":"***REDACTED***=","pairing_token":"***REDACTED***=","access_token":"l***REDACTED***=="},"limits":{"thermostats_per_structure":20,"structures":3,"smoke_detectors_per_structure":18,"smoke_detectors":54,"thermostats":60},"user":"user.***REDACTED***","is_staff":false}

**Comment by adriancable** [comment]
The access token in my example is XXX, and in your example is the first occurrence of the word REDACTED. That’s what you want to put in the config - none of the other stuff in there is relevant. Hope this helps.

**Comment by jawais84** [comment]
Perfect! That did the trick. I knew I was looking at it wrong.

Thanks again!
