### ISSUE TITLE
Support for multiple homes

### ISSUE THREAD

**Issue by Tom2527** [chrisjshull/homebridge-nest#42]
Hi, we have 2 Nests in 2 separate homes. The current home bridge-nest supports both Nests, but they appear in the same home.  This leads to issues where if you set the temperate in HomeKit or with Siri, without specifying the thermostat, both Nests are adjusted.

Either it should be possible to add the 2 Nests to separate HomeKit homes. But I assume this would require duplicating the homebridge as this is added to a particular home. 

The alternative and relative easy solution would be to hide the second Nest so it's no longer visible in HomeKit. This is not possible at the moment, or at least I could not get it to work.

**Comment by chrisjshull** [comment]
Can you share your config file? BE SURE TO REMOVE the code and token.

~Chris

**Comment by Tom2527** [comment]
Hi, I recuperated this issue from a bug report from the old branch: https://github.com/KraigM/homebridge-nest/issues/85

I haven't switched to this version yet, as I assumed this was not addressed yet. But maybe I'm wrong?

**Comment by chrisjshull** [comment]
You want structureId (see the readme)
