### ISSUE TITLE
Nest will not login 

### ISSUE THREAD

**Issue by den0220** [chrisjshull/homebridge-nest#420]
![733FA021-CE8E-4637-8CAF-3D8CFBA38D4F](https://user-images.githubusercontent.com/15683379/126082547-5dd233b7-8e99-40b3-9a60-79dc76c4fcaf.jpeg)

**Comment by den0220** [comment]
Hi I just tried to get going with homebridge and the nest plug-in. 

I followed the directions, homebridge is confirmed up and running using the command line prompts. 

When downloading the homebridge nest, then logging in to my nest account and then opening home.nest……/session I add my really long key .. the homebridge software wants to restart which I do but then I get the errors in the photo

**Comment by adriancable** [comment]
@den0220 - how sure are you that you inserted the access token correctly? (I am 99% sure that's the issue.)

Feel free to post your config here (scrambling a few characters in the access token for your security) if you want further help.

**Comment by den0220** [comment]
@adriancable  hi - I just copied and pasted directly into the plugin field

**Comment by den0220** [comment]
![F73CFEFF-9BF5-4587-AEE2-F2D84EF54841](https://user-images.githubusercontent.com/15683379/126233798-f509a10e-2955-4f52-b507-b9aff5b2fdfc.jpeg)

**Comment by adriancable** [comment]
Sure but that's not what the instructions say. I'll repeat them for your convenience - please pay attention to the part I have marked in bold:


To use a Nest Account with homebridge-nest, you will need to obtain an access token from the Nest web app. (Note - no Nest developer account is required.) Simply go to https://home.nest.com in your browser and log in. Once that's done, go to https://home.nest.com/session in your browser, and you will see a long string that looks like this:

{"2fa_state":"not_enrolled","access_token":"XXX","email":"...","expires_in":"...", ...}

Simply set "access_token" in your config.json file under the "platform": "Nest" entry to **the value of access_token in the above string (the XXX)**, which will be a long string of letters and numbers and punctuation. Do not log out of home.nest.com, as this will invalidate your credentials. Just close the browser tab.

**Comment by den0220** [comment]
Yeah I also tried it manually in the code tab. I will try it again. Thanks

**Comment by adriancable** [comment]
You don't need to manually do it in the code tab. You just need to paste in the access token - **not absolutely everything produced by https://home.net.com/session** - just the access token and the access token alone, as per the instructions.

**Comment by den0220** [comment]
Ah that's where I'm wrong I pasted everything from the session. I'll have to locate the access token only. Thanks much. Will try shortly.

**Comment by den0220** [comment]
Perfect. It worked. I can see all nest accessories in hone bridge now I just need to figure out how to add to apple home. Bridge added perfectly but still don't see anything in apple home for nest.

**Comment by adriancable** [comment]
In the Apple Home app, press 'house' icon (top left), Home Settings, Hubs & Bridges, and then look in the Bridges section. Do you see Homebridge? If so, press Accessories and you should see all your Nest devices. If not, you may need to reset Homebridge and re-add to HomeKit.

**Comment by den0220** [comment]
Thanks, interesting it appears I can see thermostats in my home now but not smoke detectors. In home hubs and bridges I have homebridge but also above that there is a nest bridge where all accessories are. If I click on home bridge there is nothing . Shouldn’t nest be nested under homebridge? If so perhaps I will delete both and re add

**Comment by adriancable** [comment]
How are you expecting to see the smoke detectors? They don't appear as tiles, like controllable devices (e.g. thermostats) do. They just appear in the info strip at the top of the HomeKit Room they're in. Are you saying they don't appear in the info strip at the top of the Room they're in? Or, are you just saying they don't appear as tiles? If so, this is just the way HomeKit works.

If Nest is configured as a child bridge, it will presumably appear separately like what you're seeing. It doesn't mean anything is wrong.

**Comment by den0220** [comment]
Got it thanks - no on the nest protects I was just going to use for automation (motion) triggers. It seems I can see everything and all is working. Thank you so much for the help, really appreciate it. My next endeavor will be to see if I can get my ubiquiti doorbell and cameras working.  Again thank you so much for the help

**Comment by adriancable** [comment]
Sure, no problem! I know it's a steep learning curve, but everything will seem easier now as you add additional plug-ins, with the experience you've gained getting everything set up. Good luck!
