### ISSUE TITLE
Add ability to ask Siri to start the fan for x minutes?

### ISSUE THREAD

**Issue by vicc** [chrisjshull/homebridge-nest#426]
**Is your feature request related to a problem? Please describe.**
Currently, I can ask Siri the following: "Hey Siri, turn the fan on" and she will turn it on using the default fan duration (or custom one in the config file).

**Describe the solution you'd like**
I want to be able to ask, "Hey Siri, turn on the fan for x minutes", and for Siri to dynamically set the fan for that amount of time instead of the default time.

**Describe alternatives you've considered**
N/A

**Comment by adriancable** [comment]
@vicc - this would be great, unfortunately, we (same as any HomeKit accessory) have no influence over Siri at all. We can't change its behaviour, add new things you can ask it, etc.

I understand that in iOS 15, Siri adds some kind of time-based control. I think you can now say "hey Siri, turn on the light in 10 minutes" and maybe you can also set things to run for a specified time period, like you are asking for. Hope this helps.

**Comment by vicc** [comment]
Thanks for the reply, Adrian. That's unfortunate, but makes sense. Will try messing with automations to see if there's anything there.
