### ISSUE TITLE
USER_LOGGED_OUT - except I'm not...

### ISSUE THREAD

**Issue by hanzov69** [chrisjshull/homebridge-nest#429]
**Describe the bug**
Have been using homebridge-nest for a very long time (years?). Changed to google auth over a year ago, successfully configured and working, no issues. Noticed today that plugin was reporting unsuccessful google authentication, 
```
{
  error: 'USER_LOGGED_OUT',
  detail: 'No active session found.',
  status: undefined
}
```
Figured that my session token had expired or something along those lines. Went back through the setup process, logged in to nest, got issueToken, cookies, etc. changed config to reflect updated values... no love. 
I picked through my pasted issue token, noticed a couple of spaces, replaced with %20 thinking this might be the culprit... no change. 

Additionally- have an API key in my config, although the instructions don't seem to indicate where this is sourced (or if it's even needed). I've tried with both the key present in config or removed, no change. 

**Version Info**

node version: v14.17.1
homebridge version: 1.3.4
plugin version: homebridge-nest v4.5.3

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

```

[10/09/2021, 16:05:20] [Nest] Fetching Nest devices.
2021-09-10T15:05:20.052Z follow-redirects options {
  maxRedirects: 21,
  maxBodyLength: 10485760,
  protocol: 'https:',
  path: '/o/oauth2/iframerpc?action=issueToken&response_type=token%20id_token&login_hint=*******-SMCQLMJfOUep6S7tCekxsx2wauMdFIKB1WU1BrOkjh9E5AAuDsDstJLTCRQ6i4AEBGWlu6UYZ-L0Q3ni-pwbTxww&client_id=1111119279899-44tchle2kaa9afr5v9ov7jbuojfr9lrq.apps.googleusercontent.com&origin=https%3A%2F%2Fhome.nest.com&scope=openid%20profile%20email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fnest-account&ss_domain=https%3A%2F%2Fhome.nest.com',
  method: 'GET',
  headers: {
    Accept: 'application/json, text/plain, */*',
    'Sec-Fetch-Mode': 'cors',
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36',
    'X-Requested-With': 'XmlHttpRequest',
    Referer: 'https://accounts.google.com/o/oauth2/iframe',
    cookie: 'LSOLH=_SVI_******JMZkdjMFkwR19ZTThUdmZ2Ql9qRF92ZEJjEOnpjMjGwe4CIj9NQUVESGZfcTQ1RW43d0d1dHl4cmtmS29vWTdlcGlYNnJlOTdrQWxpaVl3RzBQZi1BVm8yNFFPS2xnQ0VyUUk_:26865637:72ba; __Host-3PLSID=doritos|o.chat.google.com|o.groups.google.com|o.mail.google.com|o.passwords.google.com|o.voice.google.com|s.blogger|s.youtube:****iUIBJrkFI1hdM7utuGGDm2ayy4exMCKEEhJaw8LhWwiEmzuSCEzy4UKuQVe6lmvUg.; __Secure-3PAPISID=*****3-KEFDGXHQ/AYMsWnj65rsCpWMjh; __Secure-3PSID=*****afKf9NQbRwC7ZLgfmrejYPsK5kmTp0zKug9wyuDHK61uv6k2jiuxH7jrjY50_niA.; __Secure-3PSIDCC=*****-mWLClz0fYHyFbVOclkc4pVvS16UAwnjXus5swbivQYIQt196SjfItZQLAS3rfUI8HPo; 1P_JAR=2021-09-10-14; NID=223=*****0NZ2hDTJwWXZIDH8ovjC7ZpYfkdhnWum4QUHBdiJnZpPNemFuL6Wm5lJ18BHS0-d5cXKkaVa5cbTBmtAyoTjlHo2HLD1UesKOazLvWRfRvrL8rATbBgpdSqvwBAYdHMyTjNIoQ_IVWhktFBZBIJC2qSCX56NgY-K5w4XEaZ18PtWyuWD7bBluukhUWRMC-2ZD4geX4DXP76rW6grRxAcRAknbrr_uGFKQQ7G8bEztMntkLnd8X5TRFsAH_VL3AD8NcqNYNOQWgBp9-6U5Np1DgCAXGX9Oj99IXNf1pq-RyCIte35NjzJYlJeaTCYEbRxDYiJJZmHkT-fTIa9aARo1byCdRQ8j6zfB-iwnwq57qd4JJk2jVeKv5CWgIZzNaFnC0Bn4MZzrezcpquIiRH23YHI8acv18TNUzREUtuLwQK6ZoxCa'
  },
  agent: undefined,
  agents: { http: undefined, https: undefined },
  auth: undefined,
  hostname: 'accounts.google.com',
  port: null,
  nativeProtocols: {
    'http:': {
      _connectionListener: [Function: connectionListener],
      METHODS: [Array],
      STATUS_CODES: [Object],
      Agent: [Function],
      ClientRequest: [Function: ClientRequest],
      IncomingMessage: [Function: IncomingMessage],
      OutgoingMessage: [Function: OutgoingMessage],
      Server: [Function: Server],
      ServerResponse: [Function: ServerResponse],
      createServer: [Function: createServer],
      validateHeaderName: [Function: hidden],
      validateHeaderValue: [Function: hidden],
      get: [Function: get],
      request: [Function: request],
      maxHeaderSize: [Getter],
      globalAgent: [Getter/Setter]
    },
    'https:': {
      Agent: [Function: Agent],
      globalAgent: [Agent],
      Server: [Function: Server],
      createServer: [Function: createServer],
      get: [Function: get],
      request: [Function: request]
    }
  }
}

[10/09/2021, 16:05:20] [Nest] Google authentication was unsuccessful. Make sure you did not log out of your Google account after getting your googleAuth parameters.
{
  error: 'USER_LOGGED_OUT',
  detail: 'No active session found.',
  status: undefined
}
```
(replaced some parts of values with * and 1 for safety)

**Comment by robertsfeir** [comment]
Reporting same thing. Has been happening since last week. Followed same steps as above and no love either.

[9/13/2021, 10:51:45 AM] [Nest] Google authentication was unsuccessful. Make sure you did not log out of your Google account after getting your googleAuth parameters.
{
  error: 'USER_LOGGED_OUT',
  detail: 'No active session found.',
  status: undefined
}
[9/13/2021, 10:51:45 AM] [Nest] Access token acquisition via googleAuth failed (code USER_LOGGED_OUT).
[9/13/2021, 10:51:45 AM] [Nest] Unable to authenticate with Google/Nest.
[9/13/2021, 10:51:45 AM] [Nest] NOTE: Because we couldn't connect to the Nest service, your Nest devices in HomeKit will not be responsive.

**Comment by robertsfeir** [comment]
Also the steps to go through getting a new access token are wrong now. Something about the headers changed but I don't have older reference to indicate what.

**Comment by hanzov69** [comment]
Bummer, seems like something may have changed on the google side, but I can't even begin to guess at where to look to try and monkeypatch it

**Comment by hanzov69** [comment]
@adriancable ^^

**Comment by adriancable** [comment]
@hanzov69 - thanks - I'll take a look and write back.

**Comment by adriancable** [comment]
Just went through the process as per the README and nothing has changed (at least for me). issueToken and cookies still look the same, and everything runs fine with the plug-in. So first I'd suggest the usual stuff - clear your cache, try a different browser, etc.

If still no good and you want me to take a closer look, then please email me your complete config.json to adrian.cable@gmail.com. Feel free to scramble a few characters here and there in the cookies for your security, but don't change the structure.

**Comment by hanzov69** [comment]
@adriancable thanks, shot you an email with my config.

**Comment by hanzov69** [comment]
@adriancable @robertsfeir random- I decided to try and fetch token/cookie from a different machine not behind my pihole. The request header cookie structure has changed a bit...and it works. 

I'm going to keep prodding, but this seems to maybe be cause by some blackhole happening on my side? Or possibly my incognito browsing session was still tainted somehow? 

Either way, for me at least this is resolved, although I honestly don't know what the issue was
