### ISSUE TITLE
Automation does not change temp 

### ISSUE THREAD

**Issue by adorabletechguy** [chrisjshull/homebridge-nest#432]
**Describe the bug**

**To Reproduce**
1.  Create automation to set to specific temp 

**Expected behavior**
Temperature should change to temp in automation. At the time specified. It does not. Worked in previous versions
Include with your bug report this version info:
```sh
node --version 10.24.0
homebridge --version hap node 0.9.4… 1.3.4
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`
[9/25/2021,
6:59:59 AM] [Nest] Setting
COoling threshold temperature to 28.9000000
00000002•C/ 84.02• F
[9/25/2021,6:59:59 AMT
[Nest] Settingheating threshold temperature to 21.1• C69.98•F
[9/25/2021, 6:59:59 AM] [Nest] Setting te
mperature to 28. 900000000000002•C / 84.0
2O F

**Comment by adriancable** [comment]
Since I haven't heard back from the OP, I am assuming this issue is no longer present. Closing.
