### ISSUE TITLE
4.6.0 not showing to update

### ISSUE THREAD

**Issue by toshibochan** [chrisjshull/homebridge-nest#435]
![F699073A-1ECB-4452-9B8C-5F45E5822483](https://user-images.githubusercontent.com/15816913/134823188-4bd4591d-d5a9-48a3-ad9f-70ff74c8f129.png)
I have Raspberry oi 3 homebridge-nest v4.5.3. V4.6.0 update not showing in plugging.

**Comment by adriancable** [comment]
@toshibochan - try again in a little bit. npm updates aren't always instant.

**Comment by toshibochan** [comment]
Now is showing
Thank you
