### ISSUE TITLE
homebridge-nest v4.6.0 (2021-09-26) Unable to install

### ISSUE THREAD

**Issue by collinburdick** [chrisjshull/homebridge-nest#437]
Hey There - the recent nest update is unable to be updated or installed. I even tried installing previous versions and the same error occurs.

Looks like an NPM registry issue. See errors attached.
![0B649998-C54A-4229-926D-138E3497D921](https://user-images.githubusercontent.com/10953036/134945476-4ac3ba23-5665-4651-951f-67500fd1cee0.jpeg)

**Comment by adriancable** [comment]
@collinburdick - works fine for me and no other reports of issues. Are you running a VM on macOS with VMware Fusion by any chance?

**Comment by collinburdick** [comment]
Hey @adriancable - Thanks for the quick reply. I troubleshooted and seemed I had an NPM issue. I removed, installed, updated and it's all set now. Thanks for your effort building and supporting this package!

**Comment by collinburdick** [comment]
Hey @adriancable - Thanks for the quick reply. I troubleshooted and seemed I had an NPM issue. I removed, installed, updated and it's all set now. Thanks for your effort building and supporting this package!
