### ISSUE TITLE
Unable to turn on my Nest Cam

### ISSUE THREAD

**Issue by Rubenfer** [chrisjshull/homebridge-nest#44]
I can't turn on/off my Nest Cam because the switcher don't appear on HomeKit.

**Comment by chrisjshull** [comment]
Please be sure to fill out the bug report template when filing bugs. You can find a copy of the template here: https://github.com/chrisjshull/homebridge-nest/issues/new?template=Bug_report.md

**Comment by adriancable** [comment]
The plug-in does not currently support the Nest Cam. Please take a look at the homebridge-nest-cam plug-in - it may do what you need.

**Comment by hilljon86** [comment]
The old version of this plugin did support this functionality.  Here was the nest-cam code that made this work.  When I updated to the new version of this plug-in, it stopped working. https://github.com/marcopullo/homebridge-nest/blob/4abefeae2856a044de79882ea9dac796ca5cba3a/lib/nest-cam-accessory.js

**Comment by adriancable** [comment]
@hilljon86 - the plug-in was rewritten so it no longer used the Works with Nest API which is being discontinued. Because I don't have a Nest Cam, I took out cam support for the time being.

I'm happy to try to put it back in but I'll need your help for this to see how cameras are exposed in the native API. Please do this:

1. Log into your account on home.nest.com
2. Start HAR file recording in your browser
3. Press 'Refresh' in your browser
4. Stop HAR recording and send me the file: adrian.cable@gmail.com

Thanks!

**Comment by Rubenfer** [comment]
Hi,

I share here some things I've found about Nest API for cameras.

To obtain a thumbnail image the url you must use is:
https://nexusapi-eu1.camera.home.nest.com/get_image?uuid=CAMERA_UUID

If the camera is off, it returns Not Found, and if you're not logged in returns Forbidden.

Other interesting url is: https://webapi.camera.home.nest.com/api/cameras.get_with_properties?uuid=CAMERA_UUID

Returns this JSON:

`{
  "status": 0,
  "items": [
    {
      "spoken_locale": "en_US",
      "talkback_stream_host": "stream-eu1-delta.dropcam.com:443",
      "is_streaming_enabled": false,
      "last_connected_time": 1564153186,
      "direct_nexustalk_host": "oculus80-eu1.dropcam.com",
      "doorbell_indoor_chime_enabled": true,
      "is_audio_recording_enabled": true,
      "rq_battery_battery_volt": 0,
      "timezone": "Europe/Madrid",
      "nexus_api_nest_domain_host": "nexusapi-eu1.camera.home.nest.com",
      "id": ID_HIDDEN,
      "weave_node_id": null,
      "is_streaming": false,
      "wwn_stream_host": "stream-eu1-delta.dropcam.com",
      "high_security": false,
      "full_camera_enabled": true,
      "hours_of_free_tier_history": 3,
      "uuid": "CAMERA_UUID_HIDDEN",
      "title": "",
      "trial_days_left": 0,
      "doorbell_indoor_chime_type": "mechanical",
      "capabilities": [
        "statusled.watching.on_off",
        "image.properties",
        "force_idr",
        "usb_setup",
        "streaming.data-usage-tier.120",
        "streaming.cameraprofile.VIDEO_H264_100KBIT_L30",
        "aspect_ratio_16x9",
        "audio.gain",
        "streaming.start-stop",
        "audio.microphone",
        "streaming.params",
        "streaming.cameraprofile.VIDEO_H264_2MBIT_L40",
        "video.flip",
        "btle_setup",
        "statusled",
        "streaming.data-usage-tier.300",
        "streaming.cameraprofile.VIDEO_H264_530KBIT_L31",
        "sharing",
        "backfill",
        "watermark",
        "talkback.chime",
        "labs",
        "notify.email",
        "audio.speaker",
        "talkback.chime.on_off",
        "dptz",
        "irled",
        "standby",
        "detectors.on_camera",
        "dptz.8x",
        "streaming.data-usage-tier.30",
        "statusled.watching",
        "statusled.on_off"
      ],
      "share_mode": 0,
      "is_trial_mode": false,
      "location": null,
      "mac_address": "HIDDEN",
      "is_trial_warning": false,
      "serial_number": "HIDDEN",
      "activation_time": 1487783683,
      "type": 8,
      "has_bundle": false,
      "owner_nest_user_id": "HIDDEN",
      "owner_id": "HIDDEN",
      "last_local_ip": "HIDDEN",
      "wwn_clips_host": "www.dropcam.com",
      "embed_url": "https://video.nest.com/embedded/live/HIDDEN",
      "description": "<null>",
      "timezone_utc_offset": 7200,
      "doorbell_chime_assist_enabled": false,
      "public_url": "https://video.nest.com/live/HIDDEN",
      "nest_where_id": "00000000-0000-0000-0000-00010000000d",
      "weave_fabric_id": null,
      "combined_software_version": "223-610050",
      "is_public": false,
      "properties": {
        "freetier.history.enabled": true,
        "audio.enabled": true,
        "udp.enabled": false,
        "audio.inputgainlevel": 0.75,
        "streaming.cameraprofile": "AUTO",
        "doorbell.chime_assist.enabled": false,
        "notify.mobile_push.enabled": true,
        "watermark.enabled": true,
        "low_motion_bitrate_ratio": 0,
        "audio.sounddetector.enabled": true,
        "irled.state": "auto_on",
        "streaming.data-usage-tier": 120,
        "preview.streaming.enabled": true,
        "audio.recording.enabled": true,
        "statusled.brightness": 0,
        "streaming.enabled": false,
        "doorbell.indoor_chime.enabled": true,
        "notify.sound.enabled": true,
        "nest.away.streaming.enabled": false,
        "statusled.watching.enabled": true,
        "video.flipped": false,
        "notify.offline.enabled": true,
        "audio.spoken_locale": "en_US",
        "notify.motion.enabled": true,
        "dptz.state": "1,1,0.5,0.5",
        "log.level": "None",
        "low_motion_bitrate_ratio.enabled": false,
        "websocket_nexustalk_host": "oculus80-eu1.dropcam.com:80",
        "video.motiondetector.enabled": true,
        "nest.away.notify.enabled": false,
        "audio.start-stop-sound": 1,
        "statusled.enabled": true,
        "face_tracking.enabled": false,
        "doorbell.theme": "default",
        "notify.enabled": false,
        "doorbell.indoor_chime.duration": 300,
        "doorbell.indoor_chime.type": "mechanical",
        "notify.email.enabled": true,
        "doorbell.quiet_time.enabled_until": 0,
        "bandwidth.iperf.enabled": false,
        "adaptive_bandwidth.enabled": true
      },
      "is_online": true,
      "rq_battery_temp": -1,
      "download_host": "legacy-trapworker-eu1.dropcam.com",
      "download_server_rtmps": "rtmps://stream-eu1-delta.dropcam.com/nexus/UUID_HIDDEN",
      "name": "Bedroom",
      "websocket_nexustalk_host": "oculus80-eu1.dropcam.com:80",
      "is_connected": false,
      "region": "eu1",
      "doorbell_indoor_chime_duration": 300,
      "live_stream_host": "oculus80-eu1.dropcam.com:1935",
      "nest_structure_id": "structure.e325e110-f3a6-11e6-ac11-22000b7ac0e1",
      "nexus_api_http_server": "https://nexusapi-eu1.dropcam.com",
      "public_token": "HIDDEN",
      "hours_of_recording_max": 0,
      "weave_service_config_hash": null,
      "where": "Bedroom",
      "nest_structure_name": "Casa",
      "rq_battery_vbridge_volt": 0
    }
  ],
  "status_description": "ok",
  "status_detail": ""
}`


To set the cam on/off, the URL called by browser is: https://webapi.camera.home.nest.com/api/dropcams.set_properties

**Comment by adriancable** [comment]
Thanks - this is useful. What I am hoping though (but suspect may not be the case) is that the cameras show up in the main home.nest.com API structure (just like under WWN they showed up under the same endpoint as the other devices), rather than via a separate endpoint. We'll have to see!

**Comment by Rubenfer** [comment]
How can I check if cameras are shown in main API structure?

**Comment by adriancable** [comment]
@Rubenfer - follow these steps to get me an API trace.

1. Go to home.nest.com in your browser, and log in.
2. Enable HAR recording in your browser.
3. Press 'Refresh'.
4. Stop HAR recording and send me the HAR file: adrian.cable@gmail.com
5. Log out of home.nest.com. (to invalidate the access token that will be saved in the HAR recording, for your security)

Thanks!

-Adrian

**Comment by Rubenfer** [comment]
Done!

**Comment by hilljon86** [comment]
You guys are awesome.  Thanks for looking into this.

**Comment by black01gt** [comment]
Im willing to help in anyway I can to get camera support.

**Comment by muzzymate** [comment]
If you believe it will help, I have a Nest Hello camera and can perform the HAR recording while performing an action (like press doorbell, pull up camera full screen view, etc.). Best of luck, and thanks for the awesome Homebridge plugin!

**Comment by adriancable** [comment]
@muzzymate - that would be super helpful. Thank you! Please email it to adrian.cable@gmail.com.

**Comment by muzzymate** [comment]
Sounds good. Yes, I can record and email it to you this evening. I saw the steps you outlined in the Nest Detect issue thread to initiate a recording. Should I create a separate recording for each event or is it ok to do it all in one recording? Based on your experience, anything specific you'd like me to attempt? Was thinking...

- After refreshing, walk up to doorbell (trigger motion alert)
- Ring doorbell (doorbell alert)
- Pull up video feed    (view camera stream)

**Comment by adriancable** [comment]
@muzzymate - separate HAR files would be ideal. So the sequence would be something like this:

1. Log into home.nest.com.
2. Start HAR recording.
3. Press Refresh in browser.
4. Stop HAR recording. (send me this file).
5. Restart HAR recording.
6. Walk up to doorbell (to trigger motion alert).
7. Confirm the motion alert has triggered in the web app - then stop HAR recording and send me the file.
8. Ring doorbell.
9. Confirm trigger in the web app - then stop HAR recording and send me the file.
10. Restart HAR recording.
11. Start video recording.
12. Stop HAR recording and send me the file.
13. Restart HAR recording.
14. Stop video recording.
15. Stop HAR recording and send me the file.

So should be 5 HAR files to send me in total. Thank you so much for doing this - it's super helpful.

**Comment by black01gt** [comment]
Attachments available until Sep 13, 2019
Here ae my files. I don’t have a door bell but I do have cameras.

Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAZAmHYkgl4I_F0_qXmMJrUV-NaA7ASJL_8yHQ8xygA16p-JiAI_67SS_%2F%24%7Bf%7D%3Fo%3DAnn9T-EBJ00AZqdaGvRQSinqwLRpMoHz7moLC0Ai63Td%26v%3D1%26x%3D3%26a%3DCAogIvGcXhRZ5Q84VncSTPhcaGcGRwYMCQXETBvYfXKqgvMSJxDo7PmNyS0Y6Pz04dItIgEAKggByAD_NaIXH1IEfjWgO1oE-u0kvw%26e%3D1568405274%26k%3D%24%7Buk%7D%26fl%3D%26r%3DBA774178-AF17-4DE4-9CD5-4045C4C82476-1%26ckc%3Dcom.apple.largeattachment%26ckz%3D280A44FB-9C00-47DF-94CD-CA2322870BDD%26p%3D28%26s%3DYrwPiBsUNqp6JT18Cnou4Ot7Ax4&uk=Ss9c6d2OgdopXvfmk5RkMw&f=Refresh%20home.nest.com.har&sz=24685822>Refresh home.nest.com.har
24.7 MB
Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAT6fbZvmA3UihkyyyoYgW8FKsKBqAVGhQ020t9srkPUnQItqEOOMb56B%2F%24%7Bf%7D%3Fo%3DAgJQTuTFbmmy_aGbSDvEyxATGN8WFmb2_iG12rJ82-7G%26v%3D1%26x%3D3%26a%3DCAog2Kb3sMoCPl5A8F7slkzn9Bk0yNc-FQmBNFFneqpDV3ESJxC-7vmNyS0Yvv704dItIgEAKggByAD_XDXkb1IESrCgaloEjG-egQ%26e%3D1568405274%26k%3D%24%7Buk%7D%26fl%3D%26r%3D0D97BD95-09AE-4A6B-8C3C-FFB4583BF4D9-1%26ckc%3Dcom.apple.largeattachment%26ckz%3D280A44FB-9C00-47DF-94CD-CA2322870BDD%26p%3D28%26s%3D0u3B8XrRLBDwS5Jg62b2Owo6zfM&uk=k4FKafmK9D3ucqzqdy3WBA&f=Stopped%20Recording%20Refresh%20home.nest.com.har&sz=29237510>Stopped Recording Refresh home.nest.com.har
29.2 MB
Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAVsLM67lPy-mfsOrfBX9LFcEwepDAR-mun8O6iJ0qjrDt_oD98XYWT47%2F%24%7Bf%7D%3Fo%3DAnvTZb9uMnbGl-f7_sb8hMDaufxrQV_TKNxoUudW_OZy%26v%3D1%26x%3D3%26a%3DCAogEVNr5ocsEOA1UCnZJT3Hw19ImW3tpYJ0QH-cJcycxh4SJxDB7_mNyS0Ywf_04dItIgEAKggByAD_Xv0idVIEBMHqQ1oE2Fk-Ow%26e%3D1568405274%26k%3D%24%7Buk%7D%26fl%3D%26r%3DE73E644F-E840-4A21-B5D4-7BFA12665A8A-1%26ckc%3Dcom.apple.largeattachment%26ckz%3D280A44FB-9C00-47DF-94CD-CA2322870BDD%26p%3D28%26s%3DbVIJrIjZLlM2VqQnx7zPgbEs8gQ&uk=XfShCp8L78F-jel3X9im3A&f=Recording%20Refresh%20home.nest.com.har&sz=25894984>Recording Refresh home.nest.com.har
25.9 MB

**Comment by nscheffer** [comment]
Hi Adrian,
I got 1x Nest Hello, 4x Nest Cam IQ Outdoor and 2x Nest Cam IQ Indoor....
Would love the Homekit support using your great Homebridge Nest plugin !
How far we are to have a such support ?
How could I help you ?

Thanks in advance.
Regards,
Nicolas

**Comment by Rubenfer** [comment]
Analyzing the traffic of the iOS app, the way to turn on / off the cam is creating a POST request to https://webapi.camera.home.nest.com/api/v1/dropcams.set_property with the following query: key=streaming.enabled&value=true&uuid=*********
 
key: streaming.enabled
value: true
uuid: NEST CAM UUID


Could help the User Agent: iPhone iOS 13.1 Dropcam/5.38.2.3 com.nestlabs.jasper.release Darwin

Integrate a switch to turn the cams on/off will be great. I don't need for the moment the stream because for that home bridge has other plugin.

**Comment by brn2prgrm** [comment]
Did this ever go anywhere? It would be super awesome if I had a HK switch to control my cameras!

**Comment by nscheffer** [comment]
Any progress for the Nest CAM and the Hello ?
Thanks in advance.

**Comment by Rubenfer** [comment]
No idea.
@adriancable do you discovered how to put the switch on HomeKit to turn on and off our Nest cameras?

**Comment by adriancable** [comment]
@nscheffer - I've implemented all the code needed on my side for full camera support. But for it to work, Homebridge needs to be updated to use HAP-NodeJS 0.5.0. Right now it is using 0.4.5. Since I'm not involved with that project, I don't know when this will happen, but as soon as it does, I'll release an updated version of the plug-in.

@Rubenfer - yes, I know how this is done but why is it necessary? (genuine question) If you leave the cameras enabled in the Nest app then you should be able to use them whenever you need.

**Comment by brn2prgrm** [comment]
I know I would appreciate an HK switch for my next cams so that I can use a door lock as a trigger. That way I can turn on my backyard camera whenever the back door is locked, regardless of Nest Home/Away assist.

**Comment by nscheffer** [comment]
@adriancable i have submitted an issue to Homebridge to move forward !

**Comment by adriancable** [comment]
@brn2prgrm - but why do you need to turn the camera on? Why not leave it on all the time, whether your back door is locked or not? I guess I don't understand why it's necessary to turn the camera off some of the time.

@nscheffer - thanks! I added some info on that thread.

**Comment by gabemunro** [comment]
@adriancable - in my use case, I have a camera in my living room that I use to keep an eye on my dog while I'm away, and turn on at night when I've shut down my house for the evening. I'd love the ability to use HomeKit to automate that again, and link it to things like my "Goodnight" scene.

**Comment by brn2prgrm** [comment]
@adriancable anytime a camera detects a person or a face, I get a notification on my phone. To minimize notifications I have most of my cameras turned off when I am not home, but I still would like the backyard camera turned on when I know nobody should be out there.  A switch would allow me to keep the cameras off when I am home and the door is unlocked, but when the door is locked it will be on and sending alerts when someone is detected in my back yard.

**Comment by jedis00** [comment]
@adriancable It seems homebridge is using "@oznu/hap-client": "^1.0.6" now. Can you add the cam toggle code now, please?

**Comment by jedis00** [comment]
@adriancable I submitted a pull request to bump hap-nodejs to v0.5.0. Hoping to get camera support added soon. https://github.com/nfarina/homebridge/pull/2366

**Comment by HammerAce42** [comment]
@adriancable, would you be willing to share instructions for how to manually upgrade hap-nodejs to v0.5.0 + the new experimental version with camera support so we can try it? Happy to reach out to you via e-mail if you'd prefer not to publish instructions here.

**Comment by nscheffer** [comment]
publish share will be great !

**Comment by brn2prgrm** [comment]
Has the on/off camera switch gotten anywhere? Or is there any way at all that I can help? Thanks @adriancable for your efforts!

**Comment by Rubenfer** [comment]
@brn2prgrm We're waiting for a new version of Homebridge using hap-nodes v0.5.0 or later. Developers are working on it, you can see the progress on https://github.com/nfarina/homebridge/pull/2391

**Comment by muzzymate** [comment]
@brn2prgrm - The camera on/off switch functionality is currently a part of the plugin https://github.com/Brandawg93/homebridge-nest-cam2

**Comment by Rubenfer** [comment]
@muzzymate Thanks for the information. I don't knew that plugin, but for the moment I haven't migrated my Nest account to Google account so I cannot use it. Moreover, I don't want to have two plugins for the same purpose (duplicates cams).

**Comment by popepay** [comment]
HomeBridge is now on HAP-NodeJS v0.6.9 since v1.0.3: https://github.com/homebridge/homebridge/commit/fb298768e80f652430de8055ac4e44c787d5d56e
