### ISSUE TITLE
Auth failed: access token specified in Homebridge configuration rejected

### ISSUE THREAD

**Issue by Colorado4Wheeler** [chrisjshull/homebridge-nest#441]
**Describe the bug**
Suddenly in the last several days, without any changes to Homebridge or my Nest account, I'm getting "Auth failed: access token specified in Homebridge configuration rejected" when starting the Nest plugin for Homebridge.  It's been working fine since I installed it in January.

I've intentionally not migrated to the Google account for Nest and I'm wondering if they have finally completely shut off Nest authentication.

**To Reproduce**
1. Nothing, it just started happening on its own

**Expected behavior**

Include with your bug report this version info:
```sh
node --version
homebridge --version
```
Node: 12.22.6
Homebridge: 1.3.4

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`
```[9/30/2021, 07:17:22] [Nest] Auth failed: access token specified in Homebridge configuration rejected
[9/30/2021, 07:17:22] [Nest] Unable to authenticate with Google/Nest.
[9/30/2021, 07:17:22] [Nest] NOTE: Because we couldn't connect to the Nest service, your Nest devices in HomeKit will not be responsive.```

**Comment by chaz-clark** [comment]
@Colorado4Wheeler see my reply on this error, it worked for me
https://github.com/chrisjshull/homebridge-nest/issues/443

**Comment by adriancable** [comment]
@Colorado4Wheeler - sometimes tokens expire for opaque reasons. Just get a new token as per the README and you should be good.

**Comment by Colorado4Wheeler** [comment]
@adriancable YES!  Thank you so much.  I hadn't even considered that and I should have, that resolved my problem!!!
