### ISSUE TITLE
Refresh token path - facing the same consistent issue, despite reinstalls and retires.  

### ISSUE THREAD

**Issue by KMarefat** [chrisjshull/homebridge-nest#442]
Adrian, Thanks for the great work that you and the team are doing.  I have downloaded and installed the latest version, followed the instructions to get the google code and pasted it back into the lgoin.js, and finally got the refresh token and updated the config file.  the errors below are consistent regardless of retires and reinstalls of the plugin.  

Any assistance will be greatly appreciated. 

[10/2/2021, 1:01:43 PM] [Nest] Access token acquisition via googleAuth failed (code 400).
[10/2/2021, 1:01:43 PM] [Nest] Unable to authenticate with Google/Nest.
[10/2/2021, 1:01:43 PM] [Nest] NOTE: Because we couldn't connect to the Nest service, your Nest devices in HomeKit will not be responsive.

**Comment by adriancable** [comment]
@KMarefat - remove the old googleAuth section from config.json?

**Comment by KMarefat** [comment]
> @KMarefat - remove the old googleAuth section from config.json?

@adriancable I don't see it.  Here is the config.json:

{
    "bridge": {
        "name": "Homebridge 552A",
        "username": "SOME:USER:NAME",
        "port": some port,
        "pin": "001-40-045"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 21036,
            "auth": "form",
            "theme": "blue",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "Nest",
            "refreshToken": " 1// I HAVE MASKED THIS :) /homebridge/node_modules/homebridge-nest # ",
            "platform": "Nest"
        }
    ]
}

**Comment by adriancable** [comment]
Do you have a space at the beginning of the refreshToken in your config.json? (And/or at the end?)

**Comment by KMarefat** [comment]
> Do you have a space at the beginning of the refreshToken in your config.json? (And/or at the end?)

I do indeed.  there is a space right before "1" and one after "#"

**Comment by chaz-clark** [comment]
@KMarefat try removing the spaces. I got mine to work after pasting the Google supplied code back into the terminal and copying the code w/o spaces into the settings file.

**Comment by KMarefat** [comment]
> @KMarefat try removing the spaces. I got mine to work after pasting the Google supplied code back into the terminal and copying the code w/o spaces into the settings file.

@chaz-clark I did remove the spaces.  the token now begins with "1//...." and ends with ".../homebridge-nest #"" but still not working.  I repeated the process and removed the spaces and retired, got the same results.

**Comment by KMarefat** [comment]
I also tried the cookie method but there is an "API Key" field that is not mentioned in the documentation and seems to be required.  An ideas on that?

**Comment by adriancable** [comment]
@KMarefat - why are you adding "..../homebridge-nest #" to the end? What is that?

Please, just copy and paste the token as produced by `login.js` into your `config.json`. Do not add spaces or other words at the beginning or the end.

**Comment by KMarefat** [comment]
> @KMarefat - why are you adding "..../homebridge-nest #" to the end? What is that?
> 
> Please just copy and paste the token as produced by `login.js` into your `config.json`. Do not add spaces or other words at the beginning or the end.

@adriancable I am not adding anything! that is the exact set of characters that the token ends with when the login.js returns it.

**Comment by adriancable** [comment]
@KMarefat - sure thing! Enjoy the plug-in.
