### ISSUE TITLE
Triplicate Nest Protects appearing in Homebridge

### ISSUE THREAD

**Issue by Danabw** [chrisjshull/homebridge-nest#454]
I have seven Nest Protects connected to Homebridge via the plugin, but for one of the Protects I have triplicate entries in Homebridge for Smoke and Carbon Monoxide. Screen shots below. 

![image](https://user-images.githubusercontent.com/24300160/138492134-107f978a-58b5-4c8e-8078-308f9eb5abb7.png)
![image](https://user-images.githubusercontent.com/24300160/138492421-0b98dd68-a974-486a-8f2e-6f378826d5d1.png)
![image](https://user-images.githubusercontent.com/24300160/138492446-d95e35eb-8456-415d-b622-21f4fd7a41f8.png)

Each instance has a different serial number, but all have the same MAC. 

Should I just hide two of the Smoke and Carbon Monoxide entries? And does it matter which two I hide?

**Comment by Danabw** [comment]
Thanks for the response and questions.

"No" - the Protects are also duplicated in HomeKit in the same way. I have three Kitchen Smoke and three Kitchen CO showing up on my IPad as well in the Home app. 

For some reason I can't get to the Bridges info you refer to: 
1. House icon in Home app at top left of Home app
....leads me to...
2. Dialog w/"Add Home" and "Done" at the top left and right. Only one hub is shown (my iPad)
3. The dialog does not have a "Home Settings" or "Hubs & Bridges" option - I've looked very carefully. 
4. The one link that is close is a "...go to the Settings app" in a section referring to notification settings. The link does not actually work - when I click on it I'm taken to the Notifications section of IOS Settings menu. Clicking on "Home Notification Settings" simply takes me back to the dialog in the Home app...so dead end there. 

I should probably note that I'm not normally an IOS user - the only thing I use my iPad for is to provide a home hub, and I primarily use Homebridge to allow Ring and Nest devices to interact w/Hubitat devices/automations in Node-RED flows. So when I'm choosing devices in Node-RED I'm seeting three Kitchen Smoke devices, and three Kitchen CO devices. Hope that makes sense.

**Comment by adriancable** [comment]
Conclusion: the three Nest Protects were genuine (not triplicated) but in different homes. So all is well!
