### ISSUE TITLE
When heating or cooling, fan status does not update

### ISSUE THREAD

**Issue by admoseremic** [chrisjshull/homebridge-nest#455]
**Describe the bug**
I'm not 100% sure if this is a bug or working as designed, but it seems like a bug. Whenever my thermostat calls for heat or cold (meaning the Nest app shows the orange or blue background that the HVAC is running) the associated fan switch in Homebridge and in the Home app does not also update to reflect that it is on.

I have some vent fans that need to come on when the system comes on (poor circulation in some rooms), and being able to turn them on/off when the HVAC turns on/off would be super awesome.

**To Reproduce**
1. Turn up the heat on your thermostat to trigger heating.
2. Wait for the HVAC to come on and begin heating your home (check that the Nest app shows that the thermostat is calling for heat)
3. Notice that the associated "Fan" accessory in Homebridge does not update to reflect that the fan is on.

**Expected behavior**
When the thermostat calls for heat, the fan status should update to reflect that it is on. If this isn't possible, perhaps a new switch could be added to show that "heating" is on or something?

Include with your bug report this version info:
node --version = v14.17.4
homebridge --version = Initializing HAP-NodeJS v0.9.4...
1.3.4

**Comment by squishycat92** [comment]
Hey @adriancable, has anything regarding this changed recently? Currently, the fan accessory turns on whenever the thermostat is actively heating or cooling.

(Wasn't sure to make a new issue or simply reply to this one, let me know if you'd like me to open a new one instead.)
