### ISSUE TITLE
Eco mode sets a temp even when it should be null

### ISSUE THREAD

**Issue by Hpridham** [chrisjshull/homebridge-nest#46]
**Describe the bug**
When the nest thermostat is on eco mode, home bridge always sets a temp for heating or cooling, even when the values are set to off. When set to off, heating or cooling values will show the last value they were set to. Even more odd, if you’ve never set a cooling value for eco, it will be set to 24c. So this bug is pulling some cached and pre-set default values.
In my case, 24c was too low for eco cooling. So, I set a cooling value of 32c (the highest) using the eco mode setting screen in the nest app, then I set eco cooling to off. Now my eco cooling is 32c. Better, but not a fix.

**To Reproduce**
1. Set Nest to Heat only, Cool only, or Off
2. Turn on Eco Mode
3. See that the Nest is now set to both Cool and Heat with a value of 24c for cooling if no Eco Mode cooling value had previously been set (same applies to Heat value)

**Expected behavior**
1. Eco mode should respect the mode the Nest thermostat is set to.
2. Eco Cooling value should respect the value it’s set to in the Nest app. If Eco Cooling is off, it should be set to off. Not the last set Eco Cooling value (same applies to Heat value)

**Include with your bug report this version info:**
node --version - v4.8.2
homebridge --version - 0.4.43

**Also include debug log output from startup through seeing the issue:**
Nothing is showing up in the log file other than cool mode is set.

**Comment by chrisjshull** [comment]
Please be sure to fill out the bug report template when filing bugs. You can find a copy of the template here: https://github.com/chrisjshull/homebridge-nest/issues/new?template=Bug_report.md

**Comment by ersan** [comment]
Can confirm, was trying to figure out what the heck was causing this until I remembered I updated homebridge-nest.

**Comment by chrisjshull** [comment]
@Hpridham, thanks for the info, but the logs are more useful than you know ;)
Please:
0) turn off homebridge
1) put you nest into eco mode
2) run `DEBUG=* homebridge -D`
3) attach the output before the scan/code.

Also, node version 4 is really old. Node version 8 is currently LTS: https://nodejs.org/

**Comment by toshibochan** [comment]
I disable home and eco mode by adding this to config

"disable": ["Thermostat.Home", "Thermostat.Eco"]

if what disable fan just add "Thermostat.Fan"

**Comment by idcrook** [comment]
Seeing following related Firebase API warning w.r.t. ECO mode

I haven't traced through the javascript, etc. but the `%s` makes me think it could be related to string templating somewhere? ...

```
Dec 01 06:47:55 rpih1 homebridge[19690]: [12/1/2018, 6:47:55 AM] [Nest] Setting Eco Mode for Hallway Thermostat to:
Dec 01 06:47:55 rpih1 homebridge[19690]: FIREBASE WARNING: set at /devices/thermostats/RAWxxx/hvac_mode failed: Invalid HVAC mode: %s
Dec 01 06:57:54 rpih1 homebridge[19690]: [12/1/2018, 6:57:54 AM] [Nest] Setting Eco Mode for Hallway Thermostat to:
Dec 01 06:57:54 rpih1 homebridge[19690]: FIREBASE WARNING: set at /devices/thermostats/RAWxxx/hvac_mode failed: Invalid HVAC mode: %s
```

**Comment by adriancable** [comment]
I believe this is fixed.
