### ISSUE TITLE
Nest in homebridge not working in Home app iphone

### ISSUE THREAD

**Issue by hansmestrum** [chrisjshull/homebridge-nest#463]
Hi there,

some time ago the Home app did not show the Nest or better Homebriges devices anymore.
On Homebridge the Nest accessories are also not working anymore as I can see that the temperature is wrong and also the camera is not showing up when on.
I updated the Nest plugin settings with a new token a.s.o but no result.
I removed all the devices on the home app and added them again. Not showing up.
The Homebridge appears not to detect the accessories as the temperature is wrong and also the nest cam is not showing up either.
How can I solve this?

**Comment by adriancable** [comment]
The Nest cam is handled by a separate plug-in, not related to this plug-in. So if neither work, it is a Homebridge issue (and not an issue with a specific plug-in) and so I suggest you re-post in one of the Homebridge forums e.g. on Discord or Github.
