### ISSUE TITLE
User based Fan timer

### ISSUE THREAD

**Issue by RaziAmin** [chrisjshull/homebridge-nest#466]
Using Google Home App, the app allows you to start the fan for xx minutes/hours. The plugin has a default value which can only be modified via the config in homebridge.

Is there a way to ask HomeKit/Siri to turn on the fan and run continuously for xx minutes/hours without changing the "fanDurationMinutes" in config?

**Comment by JeffroDB** [comment]
To add to this excellent question, is there a way to include a feature that created the fan as a separate accessory targetable by Home Automations?

**Comment by RaziAmin** [comment]
> To add to this excellent question, is there a way to include a feature that creates the fan as a separate accessory targetable by Home Automations?

You can control the fan via Automations and here is a screenshot of the options you can choose to control via Automation
![Nest](https://user-images.githubusercontent.com/72122030/143673185-9cca122c-2df8-47e0-b8fb-dd23bbb22d6b.jpg)

**Comment by adriancable** [comment]
@RaziAmin - how about setting fanDurationMinutes for a long time in the config, and then creating a Shortcut on iOS which turns the fan on, waits a certain amount of time, and then turns it off?

**Comment by adriancable** [comment]
Closing due to deafening silence!
