### ISSUE TITLE
Current Heating Cooling State

### ISSUE THREAD

**Issue by ThreeKus** [chrisjshull/homebridge-nest#468]
To be able to switch on and off the pump of my floor heating I would like to make use of the ' Current Heating Cooling State' state in Homebridge. It means that if value is 1 it the heater is on and if value is 0 the heater is off. I like to switch my three floorpumps of the floor heating with a controlled outlet on and off in sync with the heater to save some energy while it does not make sense to keep the floor pump running if there I no hot water. I would be great if the outlet switches off (and on) within certain time after the 'Current Heating Cooling State' changes value.

<img width="803" alt="Current Heating Cooling State off" src="https://user-images.githubusercontent.com/94626490/142440104-637748f3-616a-4b76-a766-ef29f62d72b5.png">
<img width="806" alt="Current Heating Cooling State on" src="https://user-images.githubusercontent.com/94626490/142440110-1f4ee5ea-dcf1-47ee-ba1d-0efe7102a388.png">

**Comment by adriancable** [comment]
@ThreeKus - you can use a third-party HomeKit app (like the great Home+) to create these kinds of automations. Hope this helps!
