### ISSUE TITLE
Access token acquisition via googleAuth failed (code 401).

### ISSUE THREAD

**Issue by rpolyano** [chrisjshull/homebridge-nest#473]
**Describe the bug**
I see error in startup logs:

```
[27/11/2021, 22:18:07] [Nest] Access token acquisition via googleAuth failed (code 401).
[27/11/2021, 22:18:07] [Nest] Unable to authenticate with Google/Nest.
```

Right before that, I see the request go out to

```
config: {
      url: 'https://oauth2.googleapis.com/token',
      method: 'post',
      data: 'refresh_token=1%2F%2F...&client_id=384....4at14p8j.apps.googleusercontent.com&grant_type=refresh_token'
```

and response is a 401:

```
data: { error: 'unauthorized_client', error_description: 'Unauthorized' }
```

**To Reproduce**
My Config (I tried without the Field Test feature but also got 401, but my account is an FT account):

```
 {
    "name": "Nest",
    "refreshToken": "1//<MASK>",
    "options": [
        "Nest.FieldTest.Enable"
    ],
    "platform": "Nest"
}
```

I followed the setup instructions, getting the token with `node login.js -f`

**Version**
```sh
node --version
v16.13.0
homebridge --version
1.3.8
```

I've been unable to use the cookie method as nothing shows up with the given filters and I can't seem to capture the request needed, so really hoping we can get this to work.

Please let me know if I can provide any more information, and thanks for any help!

**Comment by adriancable** [comment]
Hi @rpolyano - it may be that FT support is broken - since I do not have an FT account, it isn't easy for me to test. Let me look at the current state of the code and get back to you. Thanks!

**Comment by rpolyano** [comment]
Hi @adriancable , I should have just looked at the code myself. login.js requires a flag -ft not -f 

I thought it was weird that it was authoring with the regular nest app. Might just need a doc update. Looks like its working otherwise at the moment. 

If there are any other issues with ft accounts I would love to help you fix them if I can.

**Comment by adriancable** [comment]
Hi @rpolyano - I have just corrected the typo in the README so it does say `node login.js -ft` now. I am so sorry to have wasted your time over this! I'll close this for now, but please let me know if you encounter any issues with FT mode that will need fixing.

**Comment by rpolyano** [comment]
Thanks so much for replying so quickly. No time wasted at all. Thanks also for maintaining such an awesome plugin!
