### ISSUE TITLE
Heat Mode Delay

### ISSUE THREAD

**Issue by rice3253** [chrisjshull/homebridge-nest#474]
**Describe the bug**

When I select my Nest Thermostat E to heat via Siri, it first selects a different mode for a fraction of a second before the heat mode is selected, which triggers a mandatory 2:30 waiting period by the thermostat between modes.

**To Reproduce**
1. Trigger heat mode via Homebridge and observe the immediate start of a 2:30 delay timer on the Nest Thermostat 

**Expected behavior**
Heat mode should activate immediately

Include with your bug report this version info:
```sh
node --version v16.13.0
homebridge --version v1.3.8
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

**Comment by adriancable** [comment]
@rice3253 - sorry for the delay in getting back to you about this. Can you kindly send me full debug logs? Add "Debug.Verbose" to your "options" array in config.json as per the README, and then run `homebridge -D`, do the selection via Siri and then post the log. Thank you!

**Comment by rice3253** [comment]
Good evening @adriancable ! I tried this within the native Nest app, it does the same thing. Select heat in the nest app - first the system calls for cooling for a split second before switching to heating mode, resulting in the delay timer between modes to activate. This plugin is making the API call correctly, it appears the problem is with Nest itself. Thank you for taking the time to reach out to me! This plugin has been a lifesaver :)
