### ISSUE TITLE
Config won't save

### ISSUE THREAD

**Issue by TobyM23** [chrisjshull/homebridge-nest#475]
**After months of working fine the plugin suddenly stopped working due to invalid credentials (google cookie method as I do not know how to get a refresh token). i updated the details to no avail and even reinstalled the plugin but now it won't save the config and just returns to its previous state. I **

**To Reproduce**
1. 

**Expected behavior**

Include with your bug report this version info:
```sh
node --version 14.18.2
homebridge --version 1.3.4
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

**Comment by adriancable** [comment]
@TobyM23 - when you say "but now it won't save the config", what is the "it"? The `config.json` is just a text file. You can edit, and save, it with any text editor.

Instructions on how to get a refresh token are in the README.

**Comment by TobyM23** [comment]
Sorry, the advanced bit in the plugin where you enter the settings. I tried the instructions for the refresh token but it may be a bit beyond my skill set!

**Comment by TobyM23** [comment]
I run the command and terminal says "no module found"

**Comment by TobyM23** [comment]
<img width="597" alt="image" src="https://user-images.githubusercontent.com/95406604/144387581-eb533eac-b21e-4a02-84bf-1bb23ad69558.png">

When I click save after entering the info it just defaults to this

**Comment by adriancable** [comment]
@TobyM23 - my suggestion is that you try reposting in a HOOBS forum. I don't have any connection with HOOBS, and don't know anything about it, or how to fix it if things go wrong. Sorry!

**Comment by TobyM23** [comment]
Will do and thank you
