### ISSUE TITLE
Less bug, more my inexperience - can't find directory to run "node login.js" to get Google token

### ISSUE THREAD

**Issue by TCMITS-12866** [chrisjshull/homebridge-nest#476]
**Describe the bug**

Dumb question ... I'm trying to get a google token ... following the instructions in the wiki ... it says to go to the directory that contains the plugin and run "node login.js" ...  I am unable to find the directory with the plugin (it doesn't seem to be in the .homebridge directory).
Any suggestions ?

**Comment by adriancable** [comment]
Hi @TCMITS-12866 - have you tried searching for a file called `login.js` on your system to see where that's located? That will be the plug-in directory.

**Comment by TCMITS-12866** [comment]
Hi Adrian - thx for the feedback. 
Using "finder" (or "find login.js" in terminal) - I'm not able to find "login.js" (although the plugin says its running OK in Homebridge).
Any suggestions?

**Comment by TCMITS-12866** [comment]
OK - solved. Sorry for my ignorance. 
The key piece of information is where the "login.js" is stored. I wasn't properly searching (again, my ignorance) ... but might be helpful to let folks know that "/usr/local/lib/node_modules/homebridge-nest" is a good place to look ...

**Comment by adriancable** [comment]
@TCMITS-12866 - great - glad you found it! Can you tell us what platform you're using (PC, Mac, Raspberry Pi etc.) as the location will change between platforms. Thanks!

**Comment by TCMITS-12866** [comment]
Hi Adrian - I'm on Mac OS 12.0.1, on a Mac-Mini-M1
