### ISSUE TITLE
Can't set temperature range via Siri

### ISSUE THREAD

**Issue by JamesB41** [chrisjshull/homebridge-nest#481]
**Describe the bug**

When I try the phrase listed in the example: "Hey Siri, set the temperature range to between 65 and 70 degrees." with the Nest already in auto mode, it always says "Ok, setting the Nest to 50 degrees" and sets the lowest end of the temperature to 50, while leaving the upper end unchanged. Doesn't matter whether I say 20-40 degrees, 65-68 degrees, or 5000-9000 degrees. For what it's worth, the Home app on my phone shows the current temp in Fahrenheit but within the web ui, the tile shows it in Celsius.

**To Reproduce**
1. Say "Hey Siri, set the temperature range to between 65 and 70 degrees."

**Expected behavior**

I'd expect it to set it to 65-70 degrees.

**Debug Info**
node version v16.13.1
homebridge version 1.3.8

While watching the output of this:
`DEBUG=* homebridge -D`

I saw absolutely nothing during the course of my request. Not even a new line or random noise. This could certainly be user error, as this is the first time I've set up anything with Homebridge.

Edit: I do see this in the main logs when I make my request:

`[Nest] Setting heating threshold temperature to 10 °C / 50 °F`

**Comment by adriancable** [comment]
@JamesB41 - sorry for the delay in responding. Unfortunately, I don't think it's possible (any more?) to set a temperature range via Siri. If you find out otherwise, please let me know!
