### ISSUE TITLE
Auth failed: access token specified in Homebridge configuration rejected

### ISSUE THREAD

**Issue by ml452** [chrisjshull/homebridge-nest#482]
Cannot access Nest features through home kit

**To Reproduce**

1. Thermostat shows as "all off", smoke and CO detectors show as "no response"

Include with your bug report this version info:
```sh
node 14.17.4
homebridge 1.3.8
```

[12/16/2021, 7:31:27 PM] [Nest] Auth failed: access token specified in Homebridge configuration rejected
[12/16/2021, 7:31:27 PM] [Nest] Unable to authenticate with Google/Nest.
[12/16/2021, 7:31:27 PM] [Nest] NOTE: Because we couldn't connect to the Nest service, your Nest devices in HomeKit will not be responsive.

Has been working fine for a long time, have tried entering a new token a few times, no luck

**Comment by crissmil** [comment]
same here

**Comment by ml452** [comment]
tried putting another token in. This time when I went to nest.com/session it showed two access tokens, not sure why? I used the first token and this time it worked.

**Comment by contestabili** [comment]
> tried putting another token in. This time when I went to nest.com/session it showed two access tokens, not sure why? I used the first token and this time it worked.

For how long did it work? Mine worked for 24hrs even by leaving the browser tab open and the account logged in

**Comment by jorge-ramirez** [comment]
Mine also only works for a short time, usually a few hours or a day at the most, and then I get the error again.
