### ISSUE TITLE
hotWaterDurationMinutes seems to be now getting ignored - sending default 30mins

### ISSUE THREAD

**Issue by currybeast** [chrisjshull/homebridge-nest#483]
hotWaterDurationMinutes seems to be now getting ignored - sending default 30mins all the time.

"options": [
                "Thermostat.SeparateBuiltInTemperatureSensor.Enable",
                "Thermostat.SeparateBuiltInHumiditySensor.Enable",
                "hotWaterDurationMinutes:120"
            ],

**Expected behavior**
Sends the minutes specified in the options

Include with your bug report this version info:
```sh
node --version
homebridge --version


Node.js Version | v14.18.2

NPM v6.14.15

Homebridge 1.3.8
```
Nest plug-in is the latest

Many thanks

**Comment by adriancable** [comment]
@currybeast - that isn't (and never has been) how you set hotWaterDurationMinutes. Please read the README as it explains how to do it.

**Comment by currybeast** [comment]
Many thanks, fixed now.  What I had actually done is add; 
           
                "Thermostat.SeparateBuiltInTemperatureSensor.Enable",
                "Thermostat.SeparateBuiltInHumiditySensor.Enable"

Via the Config UI-X GUI, this deleted the hotWaterDurationMinutes entry!  So I re-added it to the feature options, which as you point out is wrong.  So its like this now and works fine;

            "hotWaterDurationMinutes": 120,
            "options": [
                "Thermostat.SeparateBuiltInTemperatureSensor.Enable",
                "Thermostat.SeparateBuiltInHumiditySensor.Enable"
            ],
       

Many thanks.  I still did not spot it even after reading the ReadMe 10 times.  Great plug-in, thanks for your continued support.
