### ISSUE TITLE
Error while getting current value: -70405

### ISSUE THREAD

**Issue by ckoeber83** [chrisjshull/homebridge-nest#485]
Hello,

I'm using the ham adapter (version 4.0.2) in iobroker (Node.js v14.18.2 NPM 6.14.15) and was able with the homebridge-nest plugin (version 4.6.3) to read out my NEST protect from Google API via [Google Account - refresh token method](https://github.com/chrisjshull/homebridge-nest#using-a-google-account---refresh-token-method).

After that I got in the object tree a structure of all of my NEST-protects.
But all numeric values are "null" and in log i got "_Error while getting current value: -70405_"

Here is my config.json:
```
{
    "refreshToken": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "name": "NEST-Protect",
    "platform": "Nest"
}
```

So i think the API communication is working fine to get the structure but why they could not receive any current values?

Can you please advise.

![ham_nest-proctect](https://user-images.githubusercontent.com/52466072/147256339-d3f2d94f-aae6-43f9-b2f5-a83585168bf9.png)

Thanks!

**Comment by adriancable** [comment]
This error isn't coming from this plug-in, and the screenshot is also not related to this plug-in, so I can't help. I am not familiar with iobroker or the ham adapter but those are the places you should redirect this question to. Sorry!

**Comment by ckoeber83** [comment]
Thanks adriancable!
Follow up in iobroker forum https://forum.iobroker.net/topic/50603/ham-homebridge-nest
