### ISSUE TITLE
Nest account problems

### ISSUE THREAD

**Issue by vzlgdu** [chrisjshull/homebridge-nest#487]
Hi, I'm using HB with nest plugin. As access toke I've used the token copied using web access to nest.
After the first start everithing works fine, but if I restart HB, I receive the following message:

[Nest] Auth failed: access token specified in Homebridge configuration rejected
[Nest] Unable to authenticate with Google/Nest.
[Nest] NOTE: Because we couldn't connect to the Nest service, your Nest devices in HomeKit will not be responsive.

Can you help me?
Thanks

**Comment by GledholtHall** [comment]
Im getting this too - it does still work with Nest accounts I assume ?
Mine doesn't even work on first start.

**Comment by adriancable** [comment]
@GledholtHall - everything still works with Nest accounts. If you are getting 'unable to authenticate', you are not putting the token into config.json correctly. If you follow the instructions, it will work.

**Comment by GledholtHall** [comment]
I apologise - I found the issue - there are two `access_tokens` that are displayed on the `https://home.nest.com/session` screen.  I was using the wrong one which is for weave I think ...  working now

**Comment by adriancable** [comment]
@vzlgdu - Nest does not know that you are restarting Homebridge, so that cannot be the trigger for your issue. Usually, when access tokens expire it's because you've logged out in your browser. Simply don't do this, and the Nest access token will last forever.

**Comment by kiat-huang** [comment]
> @vzlgdu - Nest does not know that you are restarting Homebridge, so that cannot be the trigger for your issue. Usually, when access tokens expire it's because you've logged out in your browser. Simply don't do this, and the Nest access token will last forever.

So authentication is preserved if one close one's browser nest.com tabs or even the whole browser? 

In Homebridge I am getting reauthentication failures (after successful auth and pulling of my Nest Protect states) despite not logging out of Nest.  I seem to be following the Homebridge instructions to the letter, but within 20-60 minutes auth to the Nest API is lost.

**Comment by henkied** [comment]
same here!
