### ISSUE TITLE
Cann't install the plugin on Hoobs 4.1.20

### ISSUE THREAD

**Issue by kdaimati** [chrisjshull/homebridge-nest#489]
Hi,

I'm trying to install this plugin for 2 days with no luck. When I try to use hoobs interface I got the following:
<img width="1299" alt="Screen Shot 2022-01-04 at 8 16 21 AM" src="https://user-images.githubusercontent.com/40270384/148067143-a1687722-8a35-4e39-b0cd-deb477b64b66.png">
yarn add vl.22.17
info No lockfile found.
[1/4] Resolving packages.
node: _tls_warp:411
owner.tIsuptions. isServer ?'server': 'client',err,
TypeError: Cannot read properties of undefined (reading 'isServer')
at TLSWrap.onerror (node:_tls_wrap:411:27)

I tried to install it manually and got the following:
hoobs@hoobs:~$ npm install -g homebridge
npm notice 
npm notice New minor version of npm available! 8.1.2 -> 8.3.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.3.0
npm notice Run npm install -g npm@8.3.0 to update!
npm notice 
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/lib/node_modules/homebridge
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/homebridge'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/homebridge'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/lib/node_modules/homebridge'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2022-01-04T13_20_37_739Z-debug.log
hoobs@hoobs:~$

**Comment by adriancable** [comment]
@kdaimati - maybe since you are using HOOBS this would be better in the HOOBS forums? I don't use HOOBS, so can't help you debug it, sorry.
