### ISSUE TITLE
Siri: switching mode while changing temp doesn't work

### ISSUE THREAD

**Issue by chrisjshull** [chrisjshull/homebridge-nest#49]
after doing some testing, it looks like we still need something like `setHeatCoolIfNeeded`, but tweaked.
What I tested:
 - PASS: put Nest in cool mode. put nest in eco mode. say "set the temperature to N°". expected: back in cool mode, temp set to N°
 - PASS: put Nest in heat mode. put nest in eco mode. say "set the temperature to N°". expected: back in heat mode, temp set to N°
 - PASS: put Nest in auto mode. put nest in eco mode. say "set the temperature to N°". expected: back in auto mode, (one of high or low) temp set to N°
 - FAIL: put Nest in heat mode. say "cool the house to N°". expected: switch to cool mode,  temp set to N°

**Comment by adriancable** [comment]
Siri doesn't interpret "cool the house to ..." as an instruction to change mode. It just interprets it as a way to change temperature. So I don't think there's anything we can do in the code to "know" that the user is trying to put the thermostat in cool mode ... HomeKit just doesn't pass that info to us. Closing for now.
