### ISSUE TITLE
Error in log after every action committed from the home app

### ISSUE THREAD

**Issue by Midifreakz** [chrisjshull/homebridge-nest#490]
When changing something in Homekit, The error log in Hoobs returns: 
SET handler returned write response value, though the characteristic doesn't support write response

I found an issue listing from the beginning of 2021, where the conclusion was  that it was addressed in 1.3.3. but I am seeing it in 1.3.5. On Reddit someone has seen it on 1.3.8.

All actions are sent to the thermostat thouh...

1. Configure plugin as usual
2. Make an action in Home app
3. Check log

**Expected behavior**

Include with your bug report this version info:

node -- 14.18.1
homebridge --1.3.5
```

**Comment by adriancable** [comment]
@Midifreakz - are you having a problem with a function of the plug-in, or is the "problem" just that you find the message ugly?

This is not an error, and does not indicate anything is wrong.
