### ISSUE TITLE
When using a Google account linked to multiple homes, Nest devices from every home are added

### ISSUE THREAD

**Issue by allyak** [chrisjshull/homebridge-nest#491]
**Describe the bug**
I have a Google account linked to two 'Home' profiles in the Google Home app (my primary residence and another property where I offer tech support). Each house uses a few different Nest Protect devices. I authenticate using the cookie method for HomeBridge Nest.

After adding my account, Nest devices from all of the homes linked to my Google account appear in the iOS Home app.

**To Reproduce**
1. Add a Google Account linked to multiple homes to Homebridge NEST using the Cookie Method for authentication.
2. All the Nest devices from all linked homes appear in HomeBridge and the iOS Home app.

**Expected behavior**
The ability to filter Nest devices in a a particular Home linked to the Google profile.

**Comment by adriancable** [comment]
@allyak - can you please tell me what is wrong with the existing feature that we have to filter Nest devices to a particular Home, as detailed in the README?

**Comment by adriancable** [comment]
No response from OP, so closing.
