### ISSUE TITLE
Instructions lead to dead end

### ISSUE THREAD

**Issue by adresner** [chrisjshull/homebridge-nest#492]
Hi, can you please tell me where to find the plug in?

"From your Mac or Linux Terminal or Windows Command Prompt, navigate to the directory where this plug-in is installed, then run:"  Been trying to find the plug in for a few days with no luck 

Thank you

**Comment by adriancable** [comment]
@adresner - I am not sure how I can tell you where the plug-in is installed. I do not have access to your machine, and you did not provide any information on how you installed the plug-in so I cannot even guess. Presumably you downloaded it, and extracted it to a folder. In that case, that is the folder where the plug-in will be.

If you used npm to install the plug-in, it will be located wherever npm installs global packages. You can find that in npm's settings.
