### ISSUE TITLE
Can't install the plugin

### ISSUE THREAD

**Issue by Johan8012** [chrisjshull/homebridge-nest#497]
![IMG_5831](https://user-images.githubusercontent.com/77528955/150628059-bfc5fb39-e1d1-4620-8c53-8e753fe5e1a9.jpeg)

I get this when trying to install nest plugin on hoobs version 4.1.21, node 16.13.2 and homebridge 1.3.9.

See picture for log.
What am I doing wrong?

**Comment by adriancable** [comment]
Closing as I don't know anything about HOOBS. Sorry.
