### ISSUE TITLE
Please explain how to get Nest Temperature Sensor Data

### ISSUE THREAD

**Issue by jhavens12** [chrisjshull/homebridge-nest#499]
Hi - Can you please explain how you are getting the Nest Temperature Sensor data if the API does not directly support it? I would like this information for myself, but not in homebridge. I have it working and reporting to homekit, but I would rather use a different dashboard. Any help would be appreciated - I don't code in Node so while I've looked through your code, it's very difficult for me to follow.

Thank you!

**Comment by adriancable** [comment]
@jhavens12 - I'm sorry but I don't understand. What do you mean "the API does not directly support it"? Clearly this isn't true because the Nest app supports temperature sensors and so does this plug-in, using the same API.

**Comment by jhavens12** [comment]
Hi - 
https://developers.google.com/nest/device-access/use-the-api
https://developers.google.com/nest/device-access/api/thermostat
https://developers.google.com/nest/device-access/traits/device/temperature

If it's in here then I must be looking past it, I'm able to pull the temperature from the thermostat itself via the API, but I cannot see the external temperature sensor. 

I can pull my Structure data, which lists my thermostat, but does not include the external temp sensor. I can pull the thermostat device, but it also does not include the external temperature sensor. I'm at a loss - thanks for your time.

**Comment by adriancable** [comment]
That’s a different API. We use the native Nest API - the same that the Nest app itself uses.

Feel free to take my homebridge-nest code and do whatever you want with it to log temperature sensor data or anything else - that’s why it’s available under a very permissive open source license. Good luck!

**Comment by jhavens12** [comment]
Thank you for the information - https://developers.nest.com/reference/api-thermostat

However, I don't see how you're getting the sensor data from this API either. Do you have an example call that you're making?

Also, is it possible to tell which sensor is the "active" sensor to base the heat off of? Or to change the active sensor without opening the app?

Thanks again,

**Comment by adriancable** [comment]
For REST API thermostats, the temperature sensors appear as `kryptonite` buckets in the returned data from the `subscribe` API call, which is invoked in `nest-connection.js` in the `updateData` function, line 483. The buckets have a property called `current_temperature` which indicates the temperature at the sensor. The active sensor is set via the `active_rcs_sensors` array property of the underlying thermostat, which appears as a `device` bucket. 

For Protobuf API thermostats, the temperature sensors appear as `DEVICE`s of type `nest.resource.NestKryptoniteResource` in the response to the `Observe` API call, which is issued by `nest-connection.js` line 619. They have a trait called `current_temperature`, which is decoded in `nest-connection.js` line 1048.

In both cases, these properties are ultimately copied to the internal tree of properties in the plug-in by the `apiResponseToObjectTree` function in `nest-connection.js`, specifically, line 1165, and they are then returned to HomeKit in `nest-tempsensor-accessory.js` by the `getSensorTemperature` function (line 41).
