### ISSUE TITLE
The Nest Smoke Detector details->Serial Number

### ISSUE THREAD

**Issue by harrywer** [chrisjshull/homebridge-nest#50]
When displaying the Nest Smoke Detector details the serial number is not displayed correctly. 
It's displaying the 'location', in my case 'Hallway' instead of the actual serial number of the device.

**To Reproduce**
1. Bring up the details for the Nest Smoke Detector in 'Home'
2. Scroll down to 'Serial Number'

**Expected behavior**

Include with your bug report this version info:
By using the official Nest app the serial number is being displayed correctly/

**Comment by adriancable** [comment]
Fixed.
