### ISSUE TITLE
Additional Temperature Sensors Not Showing Up

### ISSUE THREAD

**Issue by skbeez** [chrisjshull/homebridge-nest#502]
I have one additional nest temperature sensor (not the one in the thermostat). I see the hombridge logs recognizing it but it does not show up in the home app:

```
[1/30/2022, 1:50:01 PM] [Nest] initing temp_sensor (P) "Master Bedroom Entryway": deviceId: ***********************
```

**Comment by adriancable** [comment]
@skbeez - everything shown as 'initing' will be exposed to HomeKit. If you don't see it, it most likely isn't in the right Room. To see all your accessories, go to the Home app, 'house' icon top left, Home Settings, Hubs & Bridges, Homebridge, Accessories, then locate your temperature sensor in there, press it, the you can move it to the right room.

**Comment by skbeez** [comment]
That was it, thank you for explaining that to me!
