### ISSUE TITLE
Unable to update nor remove from Homebridge interface

### ISSUE THREAD

**Issue by Dieb25** [chrisjshull/homebridge-nest#503]

**Comment by adriancable** [comment]
Your message was blank so it's hard to troubleshoot without any information. But if your issue is with the Homebridge interface, maybe you should post there instead for better results? (and describe your problem)

**Comment by Dieb25** [comment]
Sorry, totally new to this… here’s a picture of what I get when trying to up(down)grade/uninstall…
![7C2A9FBD-431A-4AE0-9F4A-18BAA08C9FA5](https://user-images.githubusercontent.com/98716427/151734207-791dee66-bbdc-4c01-abb4-24cea8612dfc.png)
