### ISSUE TITLE
Homebridge Added, but No Nest Protect devices

### ISSUE THREAD

**Issue by pbadams** [chrisjshull/homebridge-nest#505]
Hi, I'm new to Homebridge, but fairly technical.

Here's what I have done so far:

* Homebridge running on a Pi 4 using the official Raspberry Pi Homebridge image
* ssh server configured for certificate authn, and non-standard port number. 
* Changed host name to `Homebridge.XXXX` (not actual name)
* added my own SSL cert to nginx for the new host name 
* Updated `avahi` with the new host name, Homebridge console is discoverable in Safari and I'm able to login and configure
* Deleted `admin/admin` account and created a new admin user with random user name and password, plus MFA enabled.
* Homebridge Nest plugin installed
* Google Refresh Token created and added to Homebridge Nest config
* Nest Protects detected and appearing in Homebridge Accessories
* Created Rooms in Homebridge Accessories to match the Rooms I have configured in HomeKit App
* Moved Nest Protects to Homebridge Rooms
* Added Homebridge Hub to HomeKit: I was asked to trust uncertified device, choose room, and confirm name

*Problem:* at no point during Homebridge Hub setup in HomeKit am I prompted to confirm devices, and the Nest Protect statuses are not shown in any room in my Home.

Am I missing anything? The only thing non standard is my three level domain name `homebridge.XXXX.local` and its cert. Could be an issue?

Cheers! Paul A.

**Comment by adriancable** [comment]
@pbadams - sounds like a HomeKit adding glitch. Remove Homebridge from the Home app ('house' icon top left, Home Settings, Home Hubs & Bridges, Homebridge, Remove from Home), then re-scan the Homebridge QR code to re-add it.

**Comment by adriancable** [comment]
Closing since nothing further from OP.
