### ISSUE TITLE
Thermostat Creating Separate Temperature Sensor without feature option enabled

### ISSUE THREAD

**Issue by dmrichards26** [chrisjshull/homebridge-nest#506]
I have recently deployed the plugin, and while my first thermostat is integrating as expected, my second thermostat is creating an additional ambient temperature sensor, as if I am using the _Thermostat.SeparateBuiltInTemperatureSensor.Enable_ feature option. 

![image](https://user-images.githubusercontent.com/25882554/153228394-b3ad5893-2c4e-41d4-87fe-ca7a123bc3c2.png)

I have tried using _Thermostat.SeparateBuiltInTemperatureSensor.Disable_ (and also tried the same option with .{SerialNumber}), but without luck. Using _TempSensor.Disable_ removes my actual temperature sensor, but the mystery ambient sensor remains. The only way to make the unexpected temperature sensor go away is by disabling the second thermostat entirely with _Thermostat.Disable.{SerialNumber}_

**node --version**
v16.14.0
**homebridge --version**
1.4.0

[2/9/2022, 6:56:46 AM] [Nest] initing thermostat "Living Room Thermostat": deviceId: 09AA01AC46****** structureId: d9bb72f0-bba4-11e6-aede-22000b******
[2/9/2022, 6:56:46 AM] [Nest] initing thermostat (P) "Garage Thermostat": deviceId: CCA7C10000****** structureId: d9bb72f0-bba4-11e6-aede-22000b******
[2/9/2022, 6:56:46 AM] [Nest] initing temp_sensor (P) "Garage": deviceId: 18B430CCA2****** structureId: d9bb72f0-bba4-11e6-aede-22000b******

Many thanks!

**Comment by adriancable** [comment]
@dmrichards26 - the plug-in will create a separate HomeKit temperature sensor service if (and only if) the thermostat also has Nest Temperature Sensors associated with it. In this case, the thermostat's reference temperature will be that of the active Temperature Sensor, so we need an additional HomeKit temperature sensor service to convey the actual temperature at the thermostat.

This is clearly what's happening in your case. You have Garage Thermostat but it has a Nest Temperature Sensor associated also called Garage. So you get one HomeKit temperature sensor for the thermostat itself, and one for the Nest Temperature Sensor.

Closing as this is correct / as designed.
