### ISSUE TITLE
Presence Sensing / Wake Display Sensor

### ISSUE THREAD

**Issue by kmantoine** [chrisjshull/homebridge-nest#508]
Hello,

Thank you for your hard work.

The Nest Thermostat has a sensor that monitors whenever you walk by, and wakes up the display whenever you’ approach. I think it is called the Activity sensor. Is it possible to add this to HomeKit asa motion sensor?

Thanks again!

**Comment by adriancable** [comment]
@kmantoine - sorry, the thermostat does not report the state of its motion sensor over the network / API, so we can't use it.
