### ISSUE TITLE
Enable "HomeAway.Disable" not working

### ISSUE THREAD

**Issue by niXta1** [chrisjshull/homebridge-nest#509]
Hi!

I can't disable "HomeAway" for my Nest Protect. My config is:

`{
    "name": "Nest",
    "refreshToken": "XXX",
    "options": [
        "\"HomeAway.Disable\""
    ],
    "_bridge": {
        "username": "YYY",
        "port": ZZZZZ
    },
    "platform": "Nest"
}`

I had a look at https://github.com/chrisjshull/homebridge-nest/issues/297 but couldn't get it working anyway. What am I doing wrong? I used the UI to add the value.

**Comment by adriancable** [comment]
@niXta1 - why the `"\"`? Just one `"` and everything will work as it should.
