### ISSUE TITLE
Running the HVAC Fan forever

### ISSUE THREAD

**Issue by squishycat92** [chrisjshull/homebridge-nest#516]
Hey, I really liked this plugin and was really impressed by the easy authentication method that came bundled with it! 

However, I've noticed that the fan is limited to what Nest imposes on their own app - certain increments (such as 15 minutes). I would like for there to be an option where the user can run the fan forever as long as the switch is enabled in HomeKit. Perhaps this could be done by having the plugin automatically renew the fan command every 15 minutes?

Thank you so much!

**Comment by adriancable** [comment]
@squishycat92 - I assume that this restriction on the Nest side is imposed for a good reason - presumably that furnace fans in general are not designed to run continuously. I am quite nervous to 'bypass' this because it could potentially cause HVAC problems/breakdowns/fires. Sorry!

**Comment by squishycat92** [comment]
I see, the HVAC breakdown and malfunction was a safety concern that I did not take into account. Is it possible to add a timer into the HomeKit app to show the amount of time remaining (similar to the UI shown with sprinklers)?

**Comment by adriancable** [comment]
Sorry, HomeKit does not have this capability in the UI for its fan service.

**Comment by squishycat92** [comment]
Alright. Thank you!
