### ISSUE TITLE
Native Eco Mode

### ISSUE THREAD

**Issue by squishycat92** [chrisjshull/homebridge-nest#517]
Hey, I have a quick question about the Eco mode of Nest thermostats with this plugin:

Would it be possible to create a separate entry in the Home app (along with auto, heat, cool, and off) for Eco mode? I haven't been able to find any information online on whether or not HomeKit allows you to create custom modes, but it would be great if they could be added to the app for Eco mode, as opposed to a switch.

If this is not possible at the time, then that is also okay. Just wanted to check in and see if it's something that is possible.

**Comment by adriancable** [comment]
Sorry, the Home app UI for temperature mode is not customizable.
