### ISSUE TITLE
Google authentication issue using Nest Protect

### ISSUE THREAD

**Issue by LawrenceEmlyn** [chrisjshull/homebridge-nest#518]
Hello,

After running fine for a few months I am now unable to connect HB to my Nest smoke detectors, unable to authenticate.

I'm attaching the log for your reference.

Any help is appreciated of course
[homebridge.log.txt](https://github.com/chrisjshull/homebridge-nest/files/8125932/homebridge.log.txt)
[config.json.txt](https://github.com/chrisjshull/homebridge-nest/files/8125948/config.json.txt)
!

**Comment by adriancable** [comment]
@LawrenceEmlyn - what happens when you get a new refresh token (repeat the process you went through to get the one you're using now)?

There are several things that can cause the refresh token to expire - changing the password on your Google account is the most common.

**Comment by LawrenceEmlyn** [comment]
So I logged in again using the Google refresh token method, copied the token to the config.json, restarted and got the exact same results. My Google account password has not changed.

@johnniemalm how do I see this?

**Comment by LawrenceEmlyn** [comment]
Ok, so I went ahead with the cookies method and it's working now.

Still wondering why? Does this mean I will be facing the same issue some time from now?

Thanks guys!

**Comment by adriancable** [comment]
Sorry, @LawrenceEmlyn , I'm really not sure what the root issue could be, and without other reports of anything similar it appears isolated and so hard to debug. Closing for now.
