### ISSUE TITLE
Yale lock set pin code

### ISSUE THREAD

**Issue by khuezy** [chrisjshull/homebridge-nest#519]
**Is your feature request related to a problem? Please describe.**
Feature request: Add API to programmatically set pin codes.
Use case: automatically assign pincodes for Airbnb guest (last 4 digits of their phone)

**Describe the solution you'd like**
API for creating/deleting pin codes. 

**Describe alternatives you've considered**
N/A

**Additional context**
It looks like the protocol supports it: https://github.com/openweave/openweave-core/blob/9f9d2450ba3308f16cc729324801992d37130813/src/adaptations/device-layer/trait-support/weave/trait/security/UserPincodesSettingsTrait.h#L140

https://github.com/openweave/openweave-schema-vendor-common/blob/master/weave/trait/security/user_pincodes_settings_trait.proto

**Comment by adriancable** [comment]
Sorry, this doesn't really have anything to do with HomeKit and is beyond the scope of a Homebridge plug-in. (Also, Nest x Yale Lock don't support OpenWeave - it's the other way around - OpenWeave is based on the proprietary Weave stack in the Next x Yale Lock and other Nest products.)

Maybe you can find another lock that has a public API to enable this?
