### ISSUE TITLE
Temprature discrepancy when running a scene/automation

### ISSUE THREAD

**Issue by QandnotU** [chrisjshull/homebridge-nest#52]
I have set two scenes:
1. Leave Home - Mode Cool, 80° F
2. Arrive Home - Mode Cool, 75° F

Initialize the Leave Home scene and the temperature is set to `Cooling to 68°` rather than 80°.

**Versions:**
`Node Version: 9.2.1`
`Homebridge: 0.4.44`
`Homebridge Nest: 2.1.4`

**Some things to note:**
I can reproduce by manually initializing the scene or through automation. It sets the scene correctly for the first 1 to 2 seconds, then it switches to 68° (seems to be honoring the Heating threshold temp). The Arrive home scene seems to be unaffected and executes correctly.

In an effort to troubleshoot, I've been blocked by the Nest API, so I will follow up with a DEBUG log shortly. In the meantime here is the terminal output in case you can glean anything from it.

**Leave Home Scene:**
```
[2018-7-4 17:17:47] [Nest] Queuing to set temperature 26.4
[2018-7-4 17:17:52] [Nest] Cooling threshold temperature set to 23.8 null
[2018-7-4 17:17:52] [Nest] Temperature set to 26.4 null
[2018-7-4 17:17:52] [Nest] Heating threshold temperature set to 20 null
[2018-7-4 17:22:27] [Nest] Queuing to set heating threshold temperature 20
[2018-7-4 17:22:27] [Nest] Queuing to set temperature 26.4
[2018-7-4 17:22:27] [Nest] Queuing to set cooling threshold temperature 23.8
[2018-7-4 17:22:33] [Nest] Heating threshold temperature set to 20 null
[2018-7-4 17:22:33] [Nest] Cooling threshold temperature set to 23.8 null
[2018-7-4 17:22:33] [Nest] Temperature set to 26.4 null
```
**Arrive Home Scene**
```
[2018-7-4 18:46:13] [Nest] Queuing to set temperature 23.8
[2018-7-4 18:46:13] [Nest] Queuing to set heating threshold temperature 20
[2018-7-4 18:46:13] [Nest] Queuing to set cooling threshold temperature 23.8
[2018-7-4 18:46:18] [Nest] Heating threshold temperature set to 20 null
[2018-7-4 18:46:18] [Nest] Cooling threshold temperature set to 23.8 null
[2018-7-4 18:46:18] [Nest] Temperature set to 23.8 null
```

**Comment by QandnotU** [comment]
@chrisjshull DEBUG log.


[homebridge-log.txt](https://github.com/chrisjshull/homebridge-nest/files/2167100/homebridge-log.txt)

**Comment by seannymurrs** [comment]
Came here to say I’ve noticed the same thing with my setup. I have a scene set to change the temp to 65 when I go to bed, and noticed this morning it actually set the temp to 55. If it helps, I didn’t notice this problem when my homebridge setup was running off my iMac. I switched to running it from a dedicated RPi 2 yesterday, and the issue seemed to start for me then.

**Comment by QandnotU** [comment]
@seannymurrs I'm running homebridge on a Mac mini, I think the change for you has more to do with the version than the platform.

**Comment by seannymurrs** [comment]
Still seeing this issue. Let me know if sending/posting logs would be helpful.

**Comment by QandnotU** [comment]
@chrisjshull. I’d be willing to send you some cash if we can get some love on this. It’s making Nest unusable in HomeKit

**Comment by christensonautohome** [comment]
I'm getting this same error... anyone have an idea what's causing the trouble?

**Comment by seannymurrs** [comment]
Has the developer given up on this project? A month later and still no response?

**Comment by chrisjshull** [comment]
@seannymurrs, I just have a full-time job that comes first ;)
Anyone is welcome to post a PR - I can usually get those thru faster.

**Comment by seannymurrs** [comment]
Sorry Chris, I meant no disrespect. I was just geniuinely curious whether the plugin was still actively being worked on. Unfortunately, I’m not sure I know enough about github of coding to do much other than post what I’m experiencing. I wish I could be of more help.

-- Sean Murray
"Run like a bravery. Sleep like a baby. Dream like a crazy. Replace can’t with maybe."
- Alexi Pappas
On Sat, Aug 4, 2018 at 2:09 PM, Chris J. Shull <notifications@github.com> wrote:
@seannymurrs [https://github.com/seannymurrs] , I just have a full-time job that comes first ;)
Anyone is welcome to post a PR - I can usually get those thru faster.

**Comment by QandnotU** [comment]
@chrisjshull any chance you'll have a moment to get to this, my wife is going to shank me and I really don't want to move away from the Nest. Help a brotha out, I'll throw some money your way.

**Comment by adriancable** [comment]
Fixed in latest commit.
