### ISSUE TITLE
Nest account with token not working after latest Homebridge version

### ISSUE THREAD

**Issue by LwsBtlr** [chrisjshull/homebridge-nest#521]
**Describe the bug**
Nest Thermostats are not showing up in Homebridge (or Home app)

**To Reproduce**
1. Updated to Homebridge 1.4.0 and it stopped working

**Expected behavior**
Nest thermostats show up in Homebridge status and Home app

Include with your bug report this version info:
```sh
node —version
16.4.0
homebridge —version
1.4.0
```

I have verified the token again, though it has not changed. I also removed the puling entirely and readied it, no change.

Nest plugin updated as of today to 4.6.5.

I am using hb-service to start and stop homebridge. If I run it manually with sudo, I get various errors (dreaded path error) and homebridge does not launch, but it launches and runs fine via hb-server.

the hb-service logs show:

[2/26/2022, 10:55:58 AM] Homebridge v1.4.0 (HAP v0.10.0) (Homebridge 73CD) is running on port 51274.
[2/26/2022, 10:55:58 AM] [Nest] Auth failed: access token specified in Homebridge configuration rejected
[2/26/2022, 10:55:58 AM] [Nest] Unable to authenticate with Google/Nest.
[2/26/2022, 10:55:58 AM] [Nest] NOTE: Because we couldn't connect to the Nest service, your Nest devices in HomeKit will not be responsive.

But the token has been checked and rechecked with Nest per instructions. it starts b.458… if that is useful, and it’s been the same since 2013.

**Comment by LwsBtlr** [comment]
How would I replace the token with a new token? This is the token that IO get from Nest when following the directions to get a token. I am editing via the Homebridge web face (which still sees the wyze devices without problem).

**Comment by adriancable** [comment]
That process should get you a new token. Can you kindly copy and paste the Nest section of your config.json file here? Feel free to change a few letters in the token for your security (although given it doesn't work as is, probably not needed) but please leave the structure/beginning/end unchanged.

**Comment by LwsBtlr** [comment]
And now, after removing the plugin and adding it again (third time is the charm?) It finally shows the thermostats, eco mode, and fans. Same token. ¯\_(ツ)_/¯.
