### ISSUE TITLE
Improved instructions for Google Account - refresh token method

### ISSUE THREAD

**Issue by dartiss** [chrisjshull/homebridge-nest#528]
I'm a real newbie with all of this but, if nothing else, I'm coming at this with a fresh set of eyes. When trying to use the refresh token method of authentication I get stuck at this point...

> From your Mac or Linux Terminal or Windows Command Prompt, navigate to the directory where this plug-in is installed

Is there any guidance for this? If I head into the Terminal option in Homebridge will that work and, if so, where do I navigate to?

Thanks.

**Comment by mbierman** [comment]
For this plugin that is /homebridge/node_modules/homebridge-nest

**Comment by adriancable** [comment]
```
cd /homebridge/node_modules/homebridge-nest
node login.js
```
