### ISSUE TITLE
Nest current temp as automation trigger

### ISSUE THREAD

**Issue by MWDelaney** [chrisjshull/homebridge-nest#53]
**Is your feature request related to a problem? Please describe.**
I would like to trigger an “automation” in HomeKit based on the current detected temperature on the Nest. Presently this sensor doesn’t appear to be available.

For instance, my thermostat doesn’t include cooling, but if I can detect that the temp is at or above a certain level (which HomeKit already shows in the iOS GUI), I could trigger my AC to turn on via HomeKit automation. 

I see elsewhere that Nest temp sensors are not supported by the API, but it’s not clear whether the Nest’s own sensor (which already delivers data to HomeKit) is included in this lack of support. 

Thanks for listening and for this great plugin!

**Comment by QandnotU** [comment]
@MWDelaney This is a limitation of the Apple Home app. You can use the Eve app or the paid Home app to create your desired automation.

**Comment by rossvarrette** [comment]
Or you can use ifttt (if this then that) service and it can automate it for you.
