### ISSUE TITLE
"navigate to the directory where this plug-in is installed" for Google refresh token method. Where???

### ISSUE THREAD

**Issue by prutsky** [chrisjshull/homebridge-nest#530]
So to get this working (again), I now need to login with my Google accoutn and use a refresh token. Teh readme says: "navigate to the directory where this plug-in is installed" and run "node login.js" there. 

So where is the plug-in installed by default?

**Comment by adriancable** [comment]
@prutsky - you asking me where you've installed the plug-in is like you asking me where in your fridge you keep your milk. How could I possibly know?

I can't even guess, given that you haven't shared how you installed the plug-in, what kind of machine you're running Homebridge on, etc.

**Comment by prutsky** [comment]
You don't know where I put the milk? That's good I think :)

Anyway. I have HomeBridge running on a Raspberry Pi and installed the Nest plugin using the Homebridge GUI.

**Comment by adriancable** [comment]
@prutsky - try using this path: `/usr/local/lib/node_modules/homebridge-nest`

Let me know how you get on.

**Comment by prutsky** [comment]
Thx Adrian,
I found it here `/usr/lib/node_modules/homebridge-nest`. It works again :-)

**Comment by adriancable** [comment]
Great! Thanks for the update. Glad you found the milk. 😀
