### ISSUE TITLE
Plugin Stops Receiving Updates on Homebridge

### ISSUE THREAD

**Issue by jdgorelick** [chrisjshull/homebridge-nest#532]
**Describe the bug**
The plugin works as expected when the physical Homebridge server is restarted, and it continues to work for about 10 hours. After this point (don't know exactly how long), the home bridge server stops receiving any updates from Google or Next (I have tried both methods of authentication) and no longer reads or writes to HomeKit. There are no errors or warnings that I can see in the logs when this happens; I can only see reauthentication was successful as the last log entry from this plugin. The only way to get it to start working again is to restart the RasPi my Homebridge is running on.

**To Reproduce**
1. Just wait until it stops working after server reboot

**Expected behavior**

Include with your bug report this version info:
```sh
node --version: 16.14.2
homebridge --version: 1.4.0
```

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

**Comment by jdgorelick** [comment]
Will do, it's already up to date. Added that line, and it is running in debug mode now. I will download the logs once I notice a failure again and send them over. Thanks

**Comment by jdgorelick** [comment]
I only have to restart the Raspberry Pi in order to get the Nest plugin to work again. Everything else is still functional.

**Comment by adriancable** [comment]
What happens with the Nest plug-in if you just restart Homebridge when this happens? Can I also have a log of that?

The Nest plug-in runs under Node with the rest of Homebridge. It really isn’t technically possible for it to continue to affect your machine after it’s been stopped. Homebridge cannot know you’ve rebooted your machine and so a Homebridge problem could not cause Homebridge to act differently between a simple restart of the process, and a reboot. My suspicion is that something else is periodically failing on your network or the Raspberry Pi itself, which for some reason is impacting connecting to the Nest service (or to HomeKit) more than other things.

**Comment by jdgorelick** [comment]
If I just restart Homebridge, it doesn't solve the problem. I've tried the plugin on a Homebridge instance on a laptop as well, and the same issue occurred with the server.

**Comment by adriancable** [comment]
Sounds like a network problem. I’m especially to see a log of what happens when you just restart Homebridge after this occurs (not rebooting). I want to see exactly what doesn’t work in that situation.

**Comment by jdgorelick** [comment]
Once it stops working I'll do a restart before I download the logs. Odd that only Nest would stop working consistently but nothing else, though.

**Comment by adriancable** [comment]
Fixed in 4.6.6 / 4.6.7.
