### ISSUE TITLE
All Nest devices in 2 houses show up as Homebridge accessories

### ISSUE THREAD

**Issue by jmporter34** [chrisjshull/homebridge-nest#533]
Hi,
I just installed your Nest plugin and am thrilled to see my Nest Protect smoke alarms in both Homebridge and Home Assistant.
The only issue is that I own two houses and have Protects in both.  In the Nest app, I have a separate Home defined for each, and I can select one home and see only its Protects, select the other home and see only its Protects.  All of them appear in Homebridge (and thus in Home Assistant as well).  Is there a way for me to "segregate" them into two Homes in your plug-in and/or in Homebridge ?  Sorry if there's an obvious answer that I'm overlooking, I'm new to Homebridge.
Thanks!

**Comment by adriancable** [comment]
Hi - glad you are enjoying the plug-in! Take a look at the README - it explains how to select a specific `structureId`.

**Comment by jmporter34** [comment]
Thanks for the quick reply on a weekend!  That hid the other house Protects on the Homebridge "Accessories" page.  I still see them in Home Assistant though.  Interesting - I guess the structureId filters them out in the Homebridge UI but doesn't prevent their info from being passed along to Homekit / Home Assistant.  Anyway, I know how to hide them there, so all good.  Thanks for the work you put into this, you saved me a ton of time.  Paypal donation on its way.
