### ISSUE TITLE
Can't link to thermostat

### ISSUE THREAD

**Issue by twswfit** [chrisjshull/homebridge-nest#543]
Hiya!
Running HOOBS here and am able to setup the Nest bridge using the suggested google refresh authentication.  After adding the bridge I'm able to add the "home occupied" switch but no other devices are found by the Home app.  I know this device works because I currently have it controlled via Alexa voice and it responds correctly.  Can you offer any insight?  Thanks!

**Comment by adriancable** [comment]
Almost always the cause of this is you’re signing into the wrong Google account.

**Comment by twswfit** [comment]
That was it!  Thanks for the help and great bridge, donating now!

**Comment by adriancable** [comment]
That is so kind - thank you! Glad all is now working for you.
