### ISSUE TITLE
Strange Error Message Logged

### ISSUE THREAD

**Issue by janusn** [chrisjshull/homebridge-nest#548]
**Describe the bug**
I have seen a strange error message logged. I don't have a device with the IP 10.10.10.10 nor have I configured this IP.
The Nest plugin seems working fine now. I don't know whether it was at the moment logged.

> [6/14/2022, 1:01:24 AM] [Nest] API observe: error Error: The pending stream has been canceled (caused by: connect ETIMEDOUT 10.10.10.10:443)
>     at new NodeError (node:internal/errors:372:5)
>     at closeSession (node:internal/http2/core:1136:20)
>     at ClientHttp2Session.destroy (node:internal/http2/core:1530:5)
>     at TLSSocket.socketOnError (node:internal/http2/core:2981:13)
>     at TLSSocket.emit (node:events:527:28)
>     at emitErrorNT (node:internal/streams/destroy:157:8)
>     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
>     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
>   cause: Error: connect ETIMEDOUT 10.10.10.10:443
>       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) {
>     errno: -110,
>     code: 'ETIMEDOUT',
>     syscall: 'connect',
>     address: '10.10.10.10',
>     port: 443
>   },
>   code: 'ERR_HTTP2_STREAM_CANCEL'
> }
> [6/14/2022, 1:01:24 AM] [Nest] ^^^^^ this message is for information only, it does not mean there is a problem, please do not file a ticket unless you actually have a problem with the function of the plug-in
> [6/14/2022, 1:01:24 AM] [Nest] Retrying in 10 seconds.

**To Reproduce**
1. I don't know how to reproduce it but it has happened twice.

**Expected behavior**
Clear of error message.

Include with your bug report this version info:
```sh
bash-5.1# node --version
v16.15.0
bash-5.1# homebridge --version
1.4.1
```
homebridge-nest v4.6.9

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

**Comment by adriancable** [comment]
@janusn - are you experiencing instability or other issues with the plug-in?

Per the message from the plug-in in your post:

```
[6/14/2022, 1:01:24 AM] [Nest] ^^^^^ this message is for information only, it does not mean there is a problem, **please do not file a ticket unless you actually have a problem** with the function of the plug-in
```

**Comment by janusn** [comment]
@adriancable 

Thanks for your quick respond. The Nest plugin seems working fine.

I didn't know the message following it referring to the error above.  Sorry for the trouble. My bad.

Take care.

**Comment by adriancable** [comment]
@janusn - the Internet (and the Nest service) is managed by humans, and therefore is not 100% reliable. There are a thousand ways this unreliability can manifest, including misconfigured endpoints which redirect to nonexistent IP addresses like 10.10.10.10. Any well-written client (and I have tried hard to write homebridge-nest well) will simply retry these API calls and not be affected at all by momentary blips. The fact the blip occurred is written to the log, but the plug-in also knows which kinds of mishaps matter and which don't. For those that don't, I also print a message telling you not to worry, and that filing a ticket isn't needed (which happened in this case).

Hope this reassures.
