### ISSUE TITLE
Obtain refresh token

### ISSUE THREAD

**Issue by sels70** [chrisjshull/homebridge-nest#549]
I have Homebridge and the Nest plugin installed on my Synology NAS. The instructions to obtain a refresh token only includes instructions using Terminal on the Mac. I was wondering if there is another way to obtain a refresh token. At the moment I'm using the cookies option but would prefer the refresh token option. Thanks.

**Comment by mbierman** [comment]
You could do what I do for other tokens that need to be updated in config.json. This script grabs a token and updates config.json. I run the script nightly before it expires. 

You could fork mine and make this work. https://gist.github.com/mbierman/dd45821b53d5d22147cef217f0c0fe95

**Comment by adriancable** [comment]
@sels70 - why do you say the instructions are only from Mac?

Cutting and pasting from the README:

```
To run the tool, from your Mac **or Linux Terminal** or Windows Command Prompt
```

**Comment by sels70** [comment]
Sorry, I should have clarified. I'm not sure where to find the directory where the plug-in is installed on my Synology NAS.

**Comment by adriancable** [comment]
Did you try looking in the two suggested directories in the README?
