### ISSUE TITLE
Optionally exclude Nest "accessories"

### ISSUE THREAD

**Issue by cstout1** [chrisjshull/homebridge-nest#55]
Please forgive me if this is already possible. I've been searching for a way to do this and I can't find anything. I almost feel bad even writing this because I know it was an implemented feature request to have it in the first place. Is it possible to manually exclude accessories such as "Fan" and "Eco Mode" so that I only have and utilize the Thermostat and Home/Away switch? I never run the fan manually and I have Eco mode configured to run when the Nest is set to Away so for the sake of reducing clutter and only seeing what is used/wanted, is this a possibility?

**Comment by highfalutintodd** [comment]
Hi - I was having the same issue. I neglected to notice in the readme file that there is a line you can add to the config that will take all of that extraneous garbage away: 

"disable": [] // optional list of features to disable ("Thermostat.Fan", "Thermostat.Home", "Thermostat.Eco")
