### ISSUE TITLE
Nest Protects

### ISSUE THREAD

**Issue by UKenGB** [chrisjshull/homebridge-nest#552]
I have a couple of these and they appear in Home.app so setup looks good, but puzzled over a couple of points.

What is the 'Home Occupancy' feature? I have enabled both sensor and switch and can see them in Home.app, but what is their purpose and function?

Is the switch in any way controlled by Nest or is it just provided as a 'dummy' switch to be used as desired.

With 2 Protects, what is the Sensor showing? Is it an amalgamation of motion detection of the 2 protects, so triggered if EITHER detects motion. So far it just seems to be permanently 'triggered', but what is it supposed to be doing?

Is there any way to utilise the motion detectors from the individual Protects? They do work as the built-in LEDs come on when they should and I'd like to be able to use one to help control other lighting in that area, but nothing currently showing in Homebridge or Home.app. Do I have to 'enable' that feature for the individual device?

**Comment by adriancable** [comment]
@UKenGB - the 'Home Occupied' switch maps to Nest's Home/Away switch. When that's set to Home, 'Home Occupied' is on. When that's set to Away, 'Home Occupied' is off. It isn't a dummy switch.

Wired (but not battery) Protects report occupancy state (not motion) over the network and the plug-in exposes this as an occupancy sensor. The plug-in already brings all information on the Protect's state available to HomeKit. Hope this helps.

**Comment by UKenGB** [comment]
Thanks. So 'Home Occupied' is a manual switch, but links to same 'switch' in the Nest account? However, could be switched and/or the sensor read by Automations?

We have battery powered Protects, so no automatic occupancy detection then. If we had mains powered ones, could I detect motion in an individual Protect?



Ken  G i l l e t t

_/_/_/_/_/_/_/_/
