### ISSUE TITLE
Nest Thermostat not showing up in HOME app

### ISSUE THREAD

**Issue by DodgerGuy22** [chrisjshull/homebridge-nest#553]
**Describe the bug**
I have followed all instructions to get the plugin up and running.  I have HOOBS 4 and when I am on their dashboard the Nest shows up  just fine but in the Home app it says ALL OFF
**To Reproduce**
1.  Enter the Homekit code to add a device.

**Expected behavior**
Nest added to Homekit and able to adjust temperature.
Include with your bug report this version info:
```sh
node --version
homebridge --version
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

**Comment by adriancable** [comment]
@DodgerGuy22 - I am happy to help you, but first please be clearer in describing what you are seeing. The title says the thermostat doesn't show up. The body says 'in the Home app it says ALL OFF'. How can something which doesn't show up say anything (ALL OFF or otherwise)?

Maybe attach a screenshot?

**Comment by DodgerGuy22** [comment]
Sorry about that. I didn’t phrase that very well.  Attached is a screenshot
of my Home app.  Thanks you.

**Comment by adriancable** [comment]
@DodgerGuy22 - no attachment that I can see. To post an image, I think you need to attach directly in Github issues rather than attaching to an email.

**Comment by DodgerGuy22** [comment]
![IMG_0248](https://user-images.githubusercontent.com/109709278/180669681-3e421454-8741-46c1-9ed2-4bd89c5ed8f2.jpg)

**Comment by adriancable** [comment]
What do you see if you touch the 'Nest Thermo' tile? (please send another screenshot - thanks)

My gut feel is this is an iOS 16 beta HomeKit bug (of which there are many many many - as expected from a beta).

**Comment by DodgerGuy22** [comment]
Here are some shots from a device with iOS 15.  
![IMG_5517](https://user-images.githubusercontent.com/109709278/180830089-c85214bb-3c69-4097-84cb-9c641741a6d6.PNG)
![IMG_5518](https://user-images.githubusercontent.com/109709278/180830092-e96ac7c0-056e-40b4-b0b1-7566aa172ecc.PNG)
![IMG_5519](https://user-images.githubusercontent.com/109709278/180830094-2932ae07-a7b2-4638-b694-55e22e2fb304.PNG)

**Comment by adriancable** [comment]
Is it just the Nest devices you are having issues with, or other Homebridge/HOOBS devices also?

I don’t know much about HOOBS, but from Googling there is a reset button on the Help page. Press this, then remove the ‘ghost’ HOOBS from Apple Home. (House icon top left, Home Settings, Home Hubs & Bridges, HOOBS, Remove from Home). Then follow the usual process on the HOOBS UI to re-add to HomeKit.

**Comment by DodgerGuy22** [comment]
The nest devices are the only ones with a problem.  Ring, Meross, and others work just fine.

**Comment by adriancable** [comment]
Can you try removing the Nest plug-in from HOOBS, then wait for the Nest devices to disappear from the Home app. Then, re-add the Nest plug-in in HOOBS?
