### ISSUE TITLE
Nest Thermostat not pairing

### ISSUE THREAD

**Issue by twswfit** [chrisjshull/homebridge-nest#555]
Hiya!
I've been able to link HOOBS / home bridge to my Nest account using the Google refresh token method.  However it only finds the home occupied switch, and not my 3rd gen thermostat running ver6.2-27. I am able to control this device separately via Alexa so there's not an equipment issue.  Any suggestions on how to get this into my home app?

Many thanks!
- L

**Comment by adriancable** [comment]
@twswfit - that means you're not signed into the correct account in the plug-in.

Also, do you have a Nest Account or a Google Account? There are different instructions for each. You can't sign into a Nest Account using a Google refresh token, so if you actually have a Nest Account [where the thermostat is] but you're signing into a Google account [where the thermostat isn't] using the refresh token method, then that is your problem.

**Comment by twswfit** [comment]
Yep, that was it.  I have a google account (migrated Nest).  I was misled because my iOS Nest App was pointing to a different gmail account.  Thanks for the speedy help!

**Comment by adriancable** [comment]
Sure! Happy to help. Enjoy the plug-in.
