### ISSUE TITLE
Cannot access my NEST Google account from Homebridge

### ISSUE THREAD

**Issue by batiatto** [chrisjshull/homebridge-nest#559]
after following the instructions i managed to get the refresh_token, I put it on the config.json but I keep getting the error:

[8/19/2022, 6:19:04 PM] [Nest] Access token acquisition via googleAuth failed (code 400).
[8/19/2022, 6:19:04 PM] [Nest] Unable to authenticate with Google/Nest.
[8/19/2022, 6:19:04 PM] [Nest] NOTE: Because we couldn't connect to the Nest service, your Nest devices in HomeKit will not be responsive.

the config.json looks like:

{
    "bridge": {
        "name": "Homebridge 998F",
        "username": "0E:D2:57:89:99:8F",
        "port": 51109,
        "pin": "MY_PIN_HERE",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Nest",
            "refreshToken": "MY_TOKEN_HERE",
            "platform": "Nest"
        }
    ]
}

Any idea of what I might be doing wrong?, I had it working in the past with the Nest account but now I moved to google account and I am having this issue.

thanks!

**Comment by adriancable** [comment]
You’ve not pasted the token into the config correctly. But without seeing an un-redacted version, I can’t give you any further advice.
