### ISSUE TITLE
How to keep Nest Protects from showing up?

### ISSUE THREAD

**Issue by highfalutintodd** [chrisjshull/homebridge-nest#57]
I don't want my Nest Protects to show up in the Home app through Homebridge, but they all are. I've turned off Permissions in the Nest Developer site but they're still there. If I'm missing something simple can someone point me in the right direction? Thanks!

**Comment by chrisjshull** [comment]
Have you removed Nest from your homebridge config?

**Comment by highfalutintodd** [comment]
Sorry, let me clearer: I still have other Nest devices I'd like to access through Homebridge (Nest Thermostats) - I just don't want to see the Protects cluttering up the interface.

**Comment by chrisjshull** [comment]
Workaround for now: you can unfavorite and put in a different room in the Home app.

**Comment by adriancable** [comment]
In the latest commit, add "Protect.All.Disable" to "options" in config.json.
