### ISSUE TITLE
duplicate thermostats showing up

### ISSUE THREAD

**Issue by fgonza2** [chrisjshull/homebridge-nest#58]
Two thermostats show up in the homekit screen, actually with one degree difference

1. install, open homekit and two thermostats appear

**Expected behavior**
only one thermostat should show up

version info:
```sh
node 8.11.1
homebridge 0.4.44
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

**Comment by chrisjshull** [comment]
> Also include debug log output from startup through seeing the issue:
DEBUG=* homebridge -D

**Comment by adriancable** [comment]
Stale - closing for now.
