### ISSUE TITLE
Can't see Eco Mode Switch in the Home App

### ISSUE THREAD

**Issue by madchicken** [chrisjshull/homebridge-nest#586]
While the plugin works correctly and I see all accessories mapped from the Web interface, I can see the Eco Mode Switch from the Home App.

**Expected behavior**
I expect to be able to turn on/off the eco mode from the Home App.

Node version: v16.16.0
Homebridge Version: 1.6.0

Config is just this:
```
        {
            "name": "Nest",
            "access_token": "***",
            "refreshToken": "***",
            "platform": "Nest"
        }

```

In logs I only have two entries from Nest plugin:

```
[01/12/2022, 17:33:43] [Nest] initing thermostat "Living Room Thermostat": deviceId: 09AA01AC281604GG structureId: f2a20131-3443-11ed-941f-0efe9844286d
[Living Room Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 0 exceeded minimum of 9
[01/12/2022, 17:33:44] [Nest] initing home_away_sensor "Home Occupied": deviceId: f2a20131-3443-11ed-941f-0efe9844286d structureId: f2a20131-3443-11ed-941f-0efe9844286d
```

**Comment by adriancable** [comment]
Please post a screenshot from the Apple Home app showing where you would expect to see the Eco Mode switch. Thanks!

My guess is you're accessing the thermostat from e.g. the Climate view, where you just get the thermostat and not the associated accessories. If you access via the Room it's in you'll see all the controls.

**Comment by madchicken** [comment]
Ok, got it: it was grouped. Sorry for the noise. Closing.

**Comment by madchicken** [comment]
Sorry @adriancable but I still have a problem: while now it works on the Home App on my laptop (I am still running OSX Monterey) I can't see the switch on the iPhone app (running the latest version of iOS 16). I attach here some screenshot from my phone es well.

![IMG_1AEFCF152182-1](https://user-images.githubusercontent.com/296618/205147836-e742cbff-e36a-45c7-9cf7-d24f3df4e5c1.jpeg)
![IMG_6E2ABB9D1C26-1](https://user-images.githubusercontent.com/296618/205147867-06cd87ae-73dc-4f96-b220-77863ec413db.jpeg)
![IMG_57B1CBF4DE4D-1](https://user-images.githubusercontent.com/296618/205147887-2346b760-ceb2-4a72-8b3c-bfba48242b9c.jpeg)

**Comment by adriancable** [comment]
Thermostat should have 'Show as Single Tile' set and then you'll see the eco mode switch as part of the thermostat control.

**Comment by madchicken** [comment]
As you can see from the screenshot the thermostat has `Show as Single Tile`. I see the switch on the Home app on my laptop, I don't see it on the iPhone
