### ISSUE TITLE
Nest-homebridge feature only works for a short time

### ISSUE THREAD

**Issue by piadam** [chrisjshull/homebridge-nest#590]
I had it working for some time, probably an hour or so...
Have been able to use Siri to set new temperatures and so...
After a while however it stopped working and the Homebridge-log told me:

[20/12/2022, 17:38:08] [Nest] Setting temperature to 21 °C / 69.8 °F
[20/12/2022, 18:10:07] [Nest] Reauthenticating on Nest service ...
[20/12/2022, 18:10:07] [Nest] Auth failed: access token specified in Homebridge configuration rejected
[20/12/2022, 18:10:08] [Nest] API observe: error not_connected
[20/12/2022, 18:10:08] [Nest] ^^^^^ this message is for information only, it does not mean there is a problem, please do not file a ticket unless you actually have a problem with the function of the plug-in
[20/12/2022, 18:10:08] [Nest] Retrying in 10 seconds.

After loggin in to my Nest account and installing a new access-token in the json file it worked again...

[20/12/2022, 22:11:32] [Nest] initing thermostat "Living Room Thermostat": deviceId: 09AA01ACXXX70091 structureId: 3aa0b250-f7b5-XXXX-XXXX-22000aa4XXX2
[Living Room Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 0 exceeded minimum of 9

I understand I should not logout from the Nest-site, I just closed the window, but I believe that somehow the token gets invalidated after some time.

Is there any way to keep it valid for a longer time, like days/weeks/months?

**Comment by EVfrank** [comment]
I believe that I'm getting a similar reply: 

[1/2/2023, 4:55:25 PM] [Nest] initing thermostat (P) "Living Room Thermostat": deviceId: 641666XXXE9A9A structureId: 93e25b00-cccc-11e8-XXXX-0e4083e004d4
[Living Room Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 0 exceeded minimum of 10
[1/2/2023, 4:55:25 PM] [Nest] initing home_away_sensor "Home Occupied": deviceId: 93e25b00-cccc-XXX

**Comment by adriancable** [comment]
@piadam & @EVfrank - please post your `config.json`. Thanks.

**Comment by EVfrank** [comment]
Here you go, hope that obscuring a few items doesn't impair troubleshooting!
I'm new to HB, so it's quite possible I've made multiple mistakes. Thanks for the review...

{
    "bridge": {
        "name": "Homebridge A942",
        "username": "0E:98:1E:XX:A9:42",
        "port": 51025,
        "pin": "826-XX-X46",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "refreshToken": "eyJhbGciOiJSUzI1NiIsImprdSI6Ii9vYXXXXXpbnRlcm5hbC9qd2tzIiwia2lkIjoiNGRjODQyZGIiLCJ0eXAiOiJKV1QifQ.eyJpYXQiOjE2NzI4NzE5MTYsImlzcyI6IlJpbmdPYXV0aFNlcnZpY2UtcHJvZDp1cy1lYXN0LTE6MGY4ZWY3NjIiLCJyZWZyZXNoX2NpZCI6InJpbmdfb2ZmaWNpYWxfYW5kcm9pZCIsInJlZnJlc2hfc2NvcGVzIjpbImNsaWVudCJdLCJyZWZyZXNoX3VzZXJfaWQiOjgzMzQ2MDgsInJuZCI6InVDdl84QWMwZVEiLCJzXXNzaW9uX2lkIjoiZjlmNTg1MGQtMjNjNC00MjJiLWI4MWEtNmY0MTEwOWY0YzI1IiwidHlwZSI6InJlZnJlc2gtdG9rZW4ifQ.Pd5qqe8hepuReZU4AeAy5S_TxeLzcM6sHxChTOcy_co-dHRfxXlZ-jxIPEI82B_XVAiAN8CKkQ6wOc0W3jX3JMsSdoyoKo24xvHJDZAo_GTp6K2_DHmPWgKsgFf9ZerC0oaDFkx1KdkwLXqF_smL961OPTe1s6lVXnmArDxk1wutGzJnmB9Q-Sh5UOVmFxrnx07BGK3NY3g5X5TB6979JsGxq-4V1PtqoHnoMdchFRNDefXciYeZOagAsIHNWHF4dhC136rCr97rIfjI8JcxXmbDG2HNQV6wjRVAs4HMxJ0DIkpU93jjMny-mi39Jng-fyueBKDy0rtKVNjKrU4KbQ",
            "unbridgeCameras": true,
            "hideCameraSirenSwitch": true,
            "hideInHomeDoorbellSwitch": true,
            "hideAlarmSirenSwitch": true,
            "cameraStatusPollingSeconds": 18,
            "platform": "Ring"
        },
        {
            "name": "Nest",
            "googleAuth": {
                "issueToken": "https://accounts.google.com/o/oauth2/iframerpc?action=issueToken&response_type=token%20id_token&login_hint=AJDLj6LQu-XXXXLMJfOUep6S7tCei6RmPTRbvb_xb9NzDTrzLzXim-8gr74liQZhJQO5AbOxsIU6luRiB5ti27WHwSvrMGwIxg&client_id=733249279899-44tchle2kaa9afr5v9ov7jbuojfr9lrq.apps.googleusercontent.com&origin=https%3A%2F%2Fhome.nest.com&scope=openid%20profile%20email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fnest-account&ss_domain=https%3A%2F%2Fhome.nest.com&include_granted_scopes=true",
                "cookies": "__Secure-3PSID=SAh_A_gGLnkbhUayHa5qRpPHrNbAcfdlGaVfY5hMKHwUehdGo5oxZOsH3a9Qw70j5qUmew.; __Secure-3PAPISID=FZOHAT_Hrowqc4Uk/AIBtSW0MYRCA9n011; NID=511=p3dojbpi75n5Te287kH4UkoyQXjDsme43ghgsFIUYYY9p6T8Hl8I7oNmqcvvAwGqaikftBRdEtvuuHevJ1adr-iPPwjRmJ0C4KPA1RAHvVuqc28J24qbjZfQeZddPJNJd6bWc0-n_5l14A7mt93J-ZNdc7DtEJ8CIisdTtDgIMniZVIthHxuV2EVHJZ9J7f-Y13wDg; __Host-3PLSID=s.youtube:SAh_A5XP3NSGR5yE9C04ZygzFNh3aA8Yl4pDusCu4uxvOxMF4ST6QCu21WddzORK-HaKGA.; __Secure-3PSIDCC=AIKkIs0mr9aY-CkE6bEoyKp_Tc4AGGiibcbTojUE3dFKn1LDwvEdx6IZU64Dklru6vNhLy19OQ"
            },
            "_bridge": {
                "username": "0E:A2:27:10:XX:9E",
                "port": 35148
            },
            "platform": "Nest"
        },
        {
            "platform": "Hue",
            "users": {
                "ECB5FAFFFE1131A3": "Rq6umdtXXEshBAoaRtvYwfNM1QrmBhNc9oIfjD-F"
            },
            "name": "Hue",
            "hosts": [
                "192.168.50.163"
            ],
            "anyOn": true,
            "effects": true,
            "groups": true,
            "lights": true,
            "linkButton": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "resource": true,
            "rules": true,
            "sensors": true
        }
    ]
}

**Comment by adriancable** [comment]
@EVfrank - just want to make sure I understand exactly what you're experiencing. You say the service is only working for a short time - how long?

**Comment by EVfrank** [comment]
Funny you ask! It seems, at the moment, not at all. I just restarted HB, and there was no connection - immediately. Perhaps this Log snip might be helpful:

[1/4/2023, 6:14:37 PM] [Nest] initing thermostat (P) "Living Room Thermostat": deviceId: 64166600008E9A9A structureId: 93e25b00-cccc-11e8-8eXX-0e4083e004d4
[Living Room Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 0 exceeded minimum of 10
[1/4/2023, 6:14:37 PM] [Nest] initing home_away_sensor "Home Occupied": deviceId: 93e25b00-cccc-11e8-8eXX-0e4083e004d4 structureId: 93e25b00-cccc-11e8-8eXX-0e4083e004d4

**Comment by adriancable** [comment]
What do you mean when you say there is 'no connection'? Those lines you posted look like the service is connecting normally, although it would be helpful to see the whole log.

**Comment by EVfrank** [comment]
Ah, I meant that the Nest data is visible in any of my HomeKit UIs. Thus, when I say it drops, I mean that it is indeed there, in Home for example, then it goes away. Often, rebooting Homebridge brings it back.
Here's a screenshot: 
<img width="665" alt="Screenshot 2023-01-04 at 6 46 43 PM" src="https://user-images.githubusercontent.com/87835675/210671247-f628cff9-0147-4805-8b4f-8312e4184bc4.png">

**Comment by adriancable** [comment]
Is Nest the only plug-in you're using, or do you have other plug-ins? If so, are they working right now?

**Comment by EVfrank** [comment]
I'm using a couple of other plug-ins, including Hue and Ring, and they seem to be working fine.

**Comment by adriancable** [comment]
First this is a very different problem to what @piadam is talking about, which is about expiring tokens or cookies. So that confused me for a while.

I would try removing the Homebridge instance from HomeKit, resetting the Homebridge instance (either via the UI, or change the bridge.username in `config.json`), and then re-adding. Also are you using the iOS 16.2 new architecture (that was withdrawn by Apple recently)? That seems to be causing a lot of problems for people, with random devices not working.

**Comment by EVfrank** [comment]
Yes, I'm running 16.2 - unfortunately I had faith that Apple had tested it! 

Let me try your other suggestions. As I said, I'm relatively new at this, so it'll take me a bit of time.

Thanks for your help!
