### ISSUE TITLE
Temp change errors

### ISSUE THREAD

**Issue by Aragorn27** [chrisjshull/homebridge-nest#592]
All devices are showing up (using the cookie method as described in documentation for google accounts) but when I try to change the temp in Homebridge or HomeKit I get no response. Logs are showing this Error:

![Screen Shot 2022-12-24 at 4 15 37 PM](https://user-images.githubusercontent.com/121363879/209453083-b8884daf-d528-4d1a-9da3-3d70100b34f5.jpg)

**Comment by adriancable** [comment]
Can you please add `"Debug.Verbose"` to `options` in `config.json`, and then run: `homebridge -D`

Then please try to change the temperature again, and post the log here, and I'll see if we can see what's going on. Thanks!

**Comment by adriancable** [comment]
Since I haven't heard back from you, I presume this is fixed and am closing it.
