### ISSUE TITLE
Google cookie method - no nest lock

### ISSUE THREAD

**Issue by severick** [chrisjshull/homebridge-nest#593]
When using a google account with cookie method, i get all my nest devices except nest x yale lock. Reverting back to refresh token method, the lock appears.

**To Reproduce**
1. Setup with cookie method

All nest devices are discoverd

Include with your bug report this version info:

Node.js Version | v16.16.0
homebridge-nest v4.6.9

**Comment by adriancable** [comment]
Please post logs in both cases with `"Debug.Verbose"` set in the `options` in `config.json` and running using `homebridge -D`.

**Comment by severick** [comment]
After switching back to the cookie method to grab that log, the lock appeared along with every other device. Issue is resolved.

**Comment by ejkeebler** [comment]
> After switching back to the cookie method to grab that log, the lock appeared along with every other device. Issue is resolved.

Can you tell me exactly what you did, my lock disappeared to and restarting the device doesnt seem to make it come back.  Did you just remove the plugin and readd?

**Comment by severick** [comment]
@ejkeebler So, I originally switched back to the refresh method and the lock was there. When going back to the cookie method, all I did was click the config button at the top, then restored to the previous backup that had the cookie info stored. Lock appeared. However, since my last comment, the lock has been spotty. A few days ago, it wasnt there. Just checked when i got this notification and it was there. I have done nothing since this original swap.

**Comment by ejkeebler** [comment]
> @ejkeebler So, I originally switched back to the refresh method and the lock was there. When going back to the cookie method, all I did was click the config button at the top, then restored to the previous backup that had the cookie info stored. Lock appeared. However, since my last comment, the lock has been spotty. A few days ago, it wasnt there. Just checked when i got this notification and it was there. I have done nothing since this original swap.

Thanks, I just tried to readd the plugin, was surprised i wasnt able to use the node login.js method anymore, but did the cookie method everything but the lock added back, it was there just the other day.  Very odd.

**Comment by adriancable** [comment]
@ejkeebler - as per my earlier request, please post logs with `"Debug.Verbose"` set in the `options` in `config.json` and running using `homebridge -D`.

Without this, there's no way for me to help.

**Comment by adriancable** [comment]
Closing this since I haven't heard back from you, therefore I assume this is fixed.
