### ISSUE TITLE
add OccupancySensor to battery powered protects

### ISSUE THREAD

**Issue by RezzZ** [chrisjshull/homebridge-nest#595]
**Is your feature request related to a problem? Please describe.**
Currently OccupancySensor is only supported for AC wired Protects only. Not the wireless / battery powered protects.

**Describe the solution you'd like**
Battery powered Protects also have this sensor so why not source it if the function is enabled for that protect?

**Comment by adriancable** [comment]
Sorry, not possible.

Battery-powered Protects only connect to the Wi-Fi network once every 24-48 hours (unless there's an emergency). So, there's no way for them to report occupancy state.

**Comment by RezzZ** [comment]
Ahh okay. That makes sense. Thanks for clarifying @adriancable !
