### ISSUE TITLE
[Heating Threshold Temperature] characteristic was supplied illegal value: number 0 exceeded minimum of 9

### ISSUE THREAD

**Issue by tooh** [chrisjshull/homebridge-nest#599]
**Describe the bug**

[16/01/2023, 07:30:47] [Nest] initing thermostat "Family Room Thermostat": deviceId: xxxxx
structureId: xxxxx
[Family Room Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 0 exceeded minimum of 9

**To Reproduce**
1. 

**Expected behavior**

Include with your bug report this version info:
```sh
node --version
homebridge --version
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

**Comment by adriancable** [comment]
What issue exactly are you having? Is something not working as you expect, or do you just not like the message? (which is not an error)

**Comment by tooh** [comment]
Just the warning. Sorry I introduced a likely duplicate. For me it is OK to close it.
