### ISSUE TITLE
can't cool but show cool option in homekit

### ISSUE THREAD

**Issue by dvd2000k** [chrisjshull/homebridge-nest#6]
Hi, i have installed the forked version of chrisjshull, my heating system is boiler type, can't cool, but in homekit it show cool options and in eco mode show the heat/cool temperature. Is there a way to remove the cool controls if not supported by system? Thankyou.

**Comment by chrisjshull** [comment]
looking for upstream help... https://github.com/KhaosT/HAP-NodeJS/issues/560
