### ISSUE TITLE
[Nest] Nest API call to subscribe to device settings updates returned an error: EAI_AGAIN

### ISSUE THREAD

**Issue by platini76** [chrisjshull/homebridge-nest#600]
hello, I have problem after converting nest account into google account.
my homeassistant config works and my homebridge not..

this is the error:
[Nest] Nest API call to subscribe to device settings updates returned an error: EAI_AGAIN

any ideas or help?
thanks very much

**Comment by stevenharman** [comment]
Homebridge. Though, I just did the whole dance:

1. remove structureId
2. restart Homebridge
3. add structureId back
4. restart Homebridge

And I'm no longer seeing the error in the logs. Weird.

**Comment by adriancable** [comment]
Sounds like a temporary Nest side service glitch which is now gone. Probably not related to the dance.
