### ISSUE TITLE
Nest Protect (One of Two) Occupancy Triggered Warning Won't Go Away

### ISSUE THREAD

**Issue by pxzel** [chrisjshull/homebridge-nest#603]
I've read through past bugs similar to this one (in Issues area) and haven't found a solution.

Two Nest protects (with Smoke Alarm Occupancy tiles)  and one is constantly showing "OCCUPIED". The other Nest Protect triggers (OCCUPIED in HomeBridge) when I walk by and then after 10 minutes of inactivity "OCCUPIED" message goes away.

I've reinstalled the plugin and unhooked and rehooked the actual Nest protect... still always showing OCCUPIED.

Im using  1.6
homebridge-nest 4.6.9
![IMG_0390](https://user-images.githubusercontent.com/124741883/217387012-313d11fc-2033-4e56-b5ca-f4a35b5a4a7d.JPG)
![IMG_0391](https://user-images.githubusercontent.com/124741883/217387027-9fa54770-ebed-4ae9-907e-27143b7fa715.PNG)
![IMG_0392](https://user-images.githubusercontent.com/124741883/217387029-8419e701-b018-4835-9a94-b4fcd0bf4c06.PNG)

**Comment by mschwartz** [comment]
Same here
