### ISSUE TITLE
Optional Field not working

### ISSUE THREAD

**Issue by xtinct101** [chrisjshull/homebridge-nest#604]
Hi,

I'm trying to disable these fields but they keep showing up in homekit. What am I doing wrong?   
```
            "name": "Nest",
            "googleAuth": {
                "issueToken": "xxx"
                "cookies": "xxx"
            },
            "options": [
                "\"Thermostat.Fan.Disable\"",
                "\"Thermostat.Eco.Disable\"",
                "\"HomeAway.Disable\""
            ],
            "_bridge": {
                "username": "xxx",
                "port": 48123
            },
            "platform": "Nest"
```

**Comment by adriancable** [comment]
`\”`

**Comment by xtinct101** [comment]
are you saying to remove the leading `\"`?
just as an FYI, I did not type any of these manually, this is all from the gui.

**Comment by adriancable** [comment]
I don't know why the `\"` is there. It shouldn't be. `options` is just an array of strings.

I don't have anything to do with the GUI. If you have an issue with it, please post an issue in homebridge-config-ui-x.

**Comment by xtinct101** [comment]
thanks
