### ISSUE TITLE
Yale Nest Lock Not Working

### ISSUE THREAD

**Issue by dwagner20** [chrisjshull/homebridge-nest#607]
The nest Yale lock does not seem to be working after latest home assistant updates.

**Comment by adriancable** [comment]
I don't use, or know anything about, Home Assistant so can't provide support to it. Maybe reach out to the HA community?

**Comment by dwagner20** [comment]
Sorry. I actually meant it's not showing up in Homebridge. My thermostat is
the still there but the locks are not connecting through the plugin.
