### ISSUE TITLE
StructureID

### ISSUE THREAD

**Issue by bBsS4** [chrisjshull/homebridge-nest#608]
Hi - Google account. Two homes, two raspberry pi's running homebridge. 3 Nest Learning Thermostats in Home 1, 2 Nest Learning Thermostats in Home 2. Devices were set up in Nest App and verified they're appropriately segregated by home in the Google Home App. I added the StructureID variable to the config file and specified the structureID of Home 1 on RPI#1 and structureID of Home 2 on RPI#2. Restarted each multiple times and all 5 thermostats are still in both homes. Do I need to exclude specific thermostats by serial number in the respective config files? Why isn't it filtering down to the structureID in each home? I'm not the most advanced user here on Github but I am pretty competent in terms of general tech issues. Config text below. Thank you for your help.

**Comment by bBsS4** [comment]
Will post config file if necessary. Thank you for your help.

**Comment by bBsS4** [comment]
{
            "name": "Nest",
            "googleAuth": {
                "issueToken": "XXX",
                "cookies": "XXX"
            },
            "platform": "Nest",
            "_bridge": {
                "username": "XXX",
                "port": XXX,
                "structureId": "XXX"
            }

**Comment by adriancable** [comment]
`structureId` goes in the main section of the configuration (i.e. same section as `name`, `googleAuth` etc.), not under `_bridge`.
