### ISSUE TITLE
ECONNABORTED

### ISSUE THREAD

**Issue by bBsS4** [chrisjshull/homebridge-nest#611]
I keep getting this error and I followed the process exactly correctly. I just reset my RPI and reinstalled homebridge from scratch - incognito, cleared cache, etc. Can't figure out why this keeps happening when I used to have all nest thermostats running perfectly. Never had problems with this before, started getting the ECONNABORTED alert in the logs one day and it wouldn't go away. Needed to reset RPI anyways so I thought I'd just clean house. Same error happening now. Any guidance ? Does this have something to do with Eero router or recent Node.js update? Can't come up with another explanation. Thanks.

[02/05/2023, 21:54:16] [Nest] Access token acquisition via googleAuth failed (code ECONNABORTED).
[02/05/2023, 21:54:16] [Nest] Retrying in 15 second(s).

**Comment by sooyoung0321** [comment]
Is that related to Nest home access_token? I felt the access token expires so quickly (within few hours)

**Comment by bBsS4** [comment]
Idk I converted my Nest acct to a Google account a few months ago. Been using the cookies method. Everything has always worked perfectly up until about three weeks ago when I spontaneously started getting this error message. Despite the error message, the thermostats continued to give me live readings within Homekit although they stopped being reliable in communicating any temperature adjustments I made within Homekit back to the nest thermostats themselves. Now nothing works so I reinstalled my homebridge and all plugins from scratch, only to get this same error. Except it's worse now because it refuses to display the thermostats in homekit, I'm assuming due to this error. I've repeated the process a bunch of different times, clearing cache, logging in and out, incognito, etc - but I'm getting consistent values for "issueToken" and "cookies" at this point so it doesn't seem like an unforced error on my part.

**Comment by adriancable** [comment]
@bBsS4 - HomeKit Secure Router on Eero has bugs which cause it to intermittently block devices for no reason. (one of the reasons why Eero is removing HSR support for new products). If you have HomeKit Accessory Security turned on, turn it off in the Eero app, then restart your Eero network and your RPi, and everything should then be OK.

**Comment by bBsS4** [comment]
@adriancable Thanks - yes so I have had this problem with other Homebridge things most notably checking the npmjs registry for node ; unfortunately I have turned all of this stuff off (Accessory security in Homekit as well as Eero advanced protect) and restarted homebridge and network many times; the issue still refuses to go away. Any further ideas?

**Comment by bBsS4** [comment]
Also perhaps worth mentioning is that I have an identical setup on several other networks and this is the only one giving me problems.

**Comment by adriancable** [comment]
@bBsS4 - what happens if you try to do other Internet things on the RPi? Open a browser and go to www.google.com and see what happens.

**Comment by bBsS4** [comment]
@adriancable So I am tech savvy but not great with command line stuff - I am running homebridge direct installed on the RPI - is it possible to browse from the terminal window within homebridge? Been meaning to set up Docker or something but since my home depends on it I kept the install as vanilla as possible.

**Comment by kostecky** [comment]
I'm having the same issue. This just started happening a few weeks ago. My nest integration is dead on homebridge and no matter how many times I refresh the issueToken and cookies, it doesn't work anymore. Was working for many months prior.

**Comment by carlosgamezvillegas** [comment]
I am having the same issue now, out of the blue I started getting the ECONNABORTED error

**Comment by bBsS4** [comment]
I think I fixed this. I run a mesh system and the rpi server was connected to an ethernet switch connected to one of the auxiliary mesh nodes. fixed it by plugging the rpi it into an ethernet switch connected to the cental node. a lot of homebridge problems went away this way, actually - most related to NPM.

**Comment by carlosgamezvillegas** [comment]
Thank you for the replay and looking into it.
