### ISSUE TITLE
Failed to set up

### ISSUE THREAD

**Issue by QuantumFunks** [chrisjshull/homebridge-nest#618]
Followed the google account setup and it has stopped working since updating HA.

This is the error:

> This error originated from a custom integration.
> 
> Logger: homeassistant.config_entries
> Source: custom_components/nest_protect/__init__.py:126
> Integration: Nest Protect (documentation, issues)
> First occurred: 11:43:24 AM (11 occurrences)
> Last logged: 7:04:05 PM
> 
> Error setting up entry Nest Protect for nest_protect
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
>     result = await component.async_setup_entry(hass, self)
>   File "/config/custom_components/nest_protect/__init__.py", line 126, in async_setup_entry
>     hass.config_entries.async_setup_platforms(entry, PLATFORMS)
> AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
>

**Comment by adriancable** [comment]
Sorry, this plug-in is not related to Home Assistant, or to the Home Assistant Nest Protect add-on (to which your error message refers).
