### ISSUE TITLE
Disable features only on some devices

### ISSUE THREAD

**Issue by zikphil** [chrisjshull/homebridge-nest#62]
Hey guys,

Here is my setup:

- 1 Nest Thermostat (also controls my central AC/Air)
- 3x Nest E Thermostat (only control heat, 1 in each room)

I'd like to disable Eco, Fan & Home on the Nest E's but to keep it on the main Nest that controls the Central Air. Is there a way to do that without having to hide stuff in a separate room?

Thanks,

Phil

**Comment by chrisjshull** [comment]
Sorry, not right now. A few follow up questions:
1) Do the Nest E's actually control any fans? (i.e. if you put then in fan mode what happens?)
2) Can you send debug log output from startup: `DEBUG=* homebridge -D`

**Comment by dew1803** [comment]
@zikphil Try adding this to your config to resolve: "disable": ["Thermostat.Fan", "Thermostat.Home", "Thermostat.Eco"]

**Comment by adriancable** [comment]
Latest commit now allows you to do what you want. You can set options for individual devices in config.json.

If you have two thermostats with device IDs for example ABC123 and DEF456, and you only want one Home/Away control, then add to "options" in config.json: "Thermostat.HomeAway.Disable.DEF456". That way you will only get one Home/Away control for your whole system. The device ID is listed as "Serial Number" in the Home app, if you view the settings for the device, or in the Homebridge logs.

Closing for now.
