### ISSUE TITLE
Google Nest no longer shows all functions.

### ISSUE THREAD

**Issue by connorjbeatty** [chrisjshull/homebridge-nest#625]
**Describe the bug**
Only able to get the "home occupied" switch despite uninstalling and redoing everything. This seems to be somewhat related to the Matter updates.

**To Reproduce**
1. If this still works for you, see what happens if your Nest has Matter available. Maybe try and remove and re-add it.

**Expected behavior**
All thermostat functionality and display, including fan control, temperature control and home occupancy toggles.

**Comment by mrfatboy** [comment]
I just installed this plugin and I'm only getting the Home occupied switch also. No thermostat. 

Any solution to this?

**Comment by adriancable** [comment]
I cannot reproduce this (even after adding the thermostat to Apple Home 'natively' via its Matter support, I still get the homebridge-nest thermostat in HomeKit in addition to the same thermostat exposed via Matter). Are you sure you're signed into the correct Google Account where the thermostat is located?

**Comment by mrfatboy** [comment]
I’m not using Matter at all. I’m not sure the of the thermostat has even been updated to Matter or if it even can be. It might be an older version. All I known is that 4 months ago I used this plugin to add my nest thermostat. It worked and showed up into HomeKit. Now only the occupancy sensor only shows in HomeKit. I will investigate more.

**Comment by mrfatboy** [comment]
An update for anybody coming here.  It looks like I had the config.json misconfigured.  I now have it working.  Here is the the config I used.  In this example I have 2 homes each has it's own Nest thermostat.  I'm running homebridge separately in each home. In each config I reverse and switch the structure ID and thermostate.disable ID's.

        {
            "name": "Nest",
            "googleAuth": {
                "issueToken": "XXXXXXX",
                "cookies": "XXXXXXXX"
            },
            "structureId": "XXXXXXXXX",
            "options": [
                "Thermostat.SeparateBuiltInTemperatureSensor.Enable",
                "Thermostat.EcoMode.ChangeEcoBands.Enable",
                "Thermostat.SeparateBuiltInTemperatureSensor.Enable",
                "Thermostat.Disable.XXXXXXXXX"
            ],
            "platform": "Nest"
        },
