### ISSUE TITLE
login.js URL results in error: Access blocked: Nest’s request is invalid

### ISSUE THREAD

**Issue by davidjgonzalez** [chrisjshull/homebridge-nest#626]
**Describe the bug**

Access blocked: Nest’s request is invalid

**To Reproduce**
1. run `node login.js`
2. Copy/paste the URL into your browser
3. Watch Google reject the URL.

**Expected behavior**

For the URL to work and give me the required authorization code.

**Comment by adriancable** [comment]
As per the documentation, the refresh token flow no longer works. You'll need to use the cookies flow instead.
