### ISSUE TITLE
Motion detection not working

### ISSUE THREAD

**Issue by garykinetic** [chrisjshull/homebridge-nest#63]
I just installed the plugin, set everything correctly and added the motion sensor to my home app. 

But the motion event never fires. It works fine in the Nest app but not in homekit. How to fix? Is it because I am using the camera v4 api?

**Comment by chrisjshull** [comment]
@garykinetic, please be sure to fill out the issue template...

Include with your bug report this version info:
```sh
node --version
homebridge --version
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

**Comment by ngrimes08** [comment]
i'm having this issue as well....

**Comment by dpyy** [comment]
Having same issue, anyone got a fix?

**Comment by Fuenti** [comment]
I am having the same problem. The Nest app is alerting me to motion and people. I have the Home app set to turn on the porch light when motion occurs. The porch light never gets turned on. 

I would like to trigger on a person being detected instead of just motion. Is there any hope?

**Comment by ngrimes08** [comment]
Still no luck. this used to work perfectly about 10 months ago or so.....

**Comment by ngrimes08** [comment]
I tired chasing my setting on nest developer website to use version 3 instead of version 4 for the cameras/motion, but that didn't seem to change anything, or maybe my change hasn't gone through yet. I did have to approve it on the nest app, but I haven't gotten a new token or anything along those lines for the config file.

**Comment by mkormendy** [comment]
Having this issue as well.

**Comment by ngrimes08** [comment]
Funny development, this seems to be working again. Not sure if it’s on it’s own, didn’t make any homebridge changes. But, I did get a free trial of Nest Aware, after complaingnto support that I used to be able to see more than 3 hours of history. Pretty sure they changed the rules of what’s included in nest aware, that or my first free trial worked longer than it should. So would be interesting to know if those of you also having problems are a nest aware customer as well. I was not but am on the trial.

**Comment by mkormendy** [comment]
I don't have Nest Aware, nor do I use the Nest Cams, just their Thermostat which has a motion sensor in it.

**Comment by ngrimes08** [comment]
Hmm. In my year or so with homebridge I’ve never had an motion sensor icon in Home for my thermostat

**Comment by mkormendy** [comment]
Well here’s my Nest Thermostat all grouped in the home app, the Motion Sensor showed up with the Nest when I added it to homebridge.


![5D1EE9D3-4480-467F-8E7E-8D8652CE18F9](https://user-images.githubusercontent.com/1437667/59576302-e6933280-9084-11e9-9d9b-213c30fdc88b.png)

**Comment by adriancable** [comment]
The plug-in does not currently support the Nest Cam. Please take a look at the homebridge-nest-cam plug-in - it may do what you need.
