### ISSUE TITLE
Nest dosent respond on homepods , on iphone and apple tv work

### ISSUE THREAD

**Issue by cvalord** [chrisjshull/homebridge-nest#632]
Any body with same problem , siri responds on iphone  and apple tvs , but on home pod it say
Thermostat not respond

**Comment by surooor** [comment]
same issue, any idea why or did you get a resolution?

**Comment by cvalord** [comment]
> same issue, any idea why or did you get a resolution?

Not yet , I just do all
Reinstall Homebridge 
Unpair the all the HomePods 
And same status not working on HomePods

**Comment by cvalord** [comment]
> same issue, any idea why or did you get a resolution?

Did you get a solution ?

**Comment by phatduckk** [comment]
Same here - I actually got here to see if anyone reported this. I always controlled the Nest via my HomePod and wasn't till I read this post that I thought I'd try from the phone: lo and behold that worked fine.

Certain commands do still work on my HomePod tho:

- hey Siri heat the house to 70
- hey siri is the thermostat on 

However - all combinations of the following work no longer function (but used to till about 1-2 weeks ago):
- hey Siri turn the heater|thermostat|AC off

**Comment by JackHammer29** [comment]
> Same here - I actually got here to see if anyone reported this. I always controlled the Nest via my HomePod and wasn't till I read this post that I thought I'd try from the phone: low and behold that worked fine.
> 
> Certain commands do still work on my HomePod tho:
> 
> * hey Siri heat the house to 70
> * hey siri is the thermostat on
> 
> However - all combinations of the following work no longer function (but used to till about 1-2 weeks ago):
> 
> * hey Siri turn the heater|thermostat|AC off

I'm the same, I can tell them to set the thermostat, but can't turn off the heating

**Comment by rice3253** [comment]
I've been having the same issue.... even rolled back to an older version, same thing. I suspect the issue might be with Apple tbh

**Comment by nickp85** [comment]
same problem here

**Comment by JackHammer29** [comment]
Noticed this issue has sorted itself....weird

**Comment by rice3253** [comment]
I’ve noticed that as well as of tvOS 17.2…..On Dec 27, 2023, at 7:26 AM, JackHammer29 ***@***.***> wrote:﻿
Noticed this issue has sorted itself....weird
