### ISSUE TITLE
Authenticate officially via Google

### ISSUE THREAD

**Issue by twcrews** [chrisjshull/homebridge-nest#638]
As it stands, the plugin is using a circumvention method to access a user's Google account. This is a flaky and usually temporary solution at best. 

I imagine this has been tried, but I couldn't find any issues related to it: have we tried to use Google's native third-party app auth process? Or at least something like app-specific passwords? 

Unless there's something specific to the Nest platform that blocks this, I'd be happy to give it a shot myself and send up a PR.

**Comment by louismcohen** [comment]
Home Assistant uses the proper Nest login configuration using real OAuth app credentials. It's somewhat cumbersome to set up (I did it the other week), but it is 100% legit:

https://www.home-assistant.io/integrations/nest/#configuration

**Comment by twcrews** [comment]
Dropping this because, as mentioned, it would break support for temperature sensors.
