### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by bwp91** [chrisjshull/homebridge-nest#642]
Sorry a duplicate of https://github.com/chrisjshull/homebridge-nest/issues/640

here from the homebridge collab team, was just checking if this plugin was _really_ still maintained, or if not could it be transferred back to homebridge so we can maintain it as best we can?

Cheers
Ben

**Comment by mbierman** [comment]
Thanks, @bwp91 I hope someone continues or picks up support for this plugin. A lot of us depend on this functionality!

**Comment by adriancable** [comment]
Hi @bwp91 - the issue is not that this plug-in is, or is not, maintained. The Nest devices supported by the plug-in haven't changed for several years, and there isn't a lot / any maintenance needed.

The main gripe is expiring cookies for some people. This is not a 'maintenance' issue, it's a consequence of Google assigning short cookie lifetimes to some accounts. See #633.

**Comment by chrisjshull** [comment]
@adriancable, I'm getting a few pings about PRs and such. Should we look to take on additional maintainers?

(Sorry all, I haven't actively participated in a while - no longer have a nest).

**Comment by kylehakala** [comment]
> @adriancable, I'm getting a few pings about PRs and such. Should we look to take on additional maintainers?
> 
> (Sorry all, I haven't actively participated in a while - no longer have a nest).

Hey there! I’m open to assisting here (albeit, I’m not an active contributor to things in Homebridge, I’m still pretty invested in keeping my Nest Thermostat up and running in my setup for the foreseeable future).

**Comment by chrisjshull** [comment]
@bwp91, I've checked out your other work and you seem safe enough to add as a maintainer (invites sent) :)

@kylehakala your offer is appreciated - perhaps start by submitting PRs for review? hopefully bwp91 and adriancable can provide sufficient cover for review.

**Comment by adriancable** [comment]
Hi @chrisjshull - I'm delighted to take on additional maintainers! I'll be more than happy to review PRs and the like. I think this is a good way of maintaining momentum to the project.

I think the biggest general concern is the cookie expiry issue, as people want to see integrations staying logged in stably over long periods of time and for some people this is not possible. I suspect that until this is resolved, the value in adding features, even things people are actively asking for, is probably limited. So I think that effort on how to get refresh tokens via the browser (which previously we did via the OOB flow, before Google removed that) would be well spent.
