### ISSUE TITLE
Added 2 x Nest Protect Smokeys to existing Nest Thermostat = they dont appear

### ISSUE THREAD

**Issue by woodgieboodgie** [chrisjshull/homebridge-nest#650]
Hi,

Awesome plugin! It has worked for ages with a Nest Thermostat.  I have recently purchased 2 x Nest Protect Smoke Detectors (wired) and they have been added to my Nest account.  Can see them in the Nest app, alas they dont appear on Homebridge.

Do I need to refresh token and cookie now that additional devices have been added or should they just appear? pls let me know if i am missing something?

**Comment by adriancable** [comment]
Are you looking in the right place? They appear in the status strip of the respective Rooms, not as tiles. If you haven't manually assigned them to a HomeKit room, they are probably in the Default Room or the room where Homebridge itself was added.
