### ISSUE TITLE
Automation not working

### ISSUE THREAD

**Issue by tcarr85** [chrisjshull/homebridge-nest#656]
I have a fully updated raspberry pi running a fully updated homebrige on the latest plugin, and whenever I set my automations, they never run for the thermostat. I see it in the logs, but when I look at the thermostat. It’s the previous temp before the automation ran. I have reinstalled the plugin, and tried everything I can possibly think of, this is the second time I’ve raised this,m. I went as far as to reset my thermostat. Any help would be appreciated

**Comment by rockman057** [comment]
Im seeing the same behavior with my setup.
