### ISSUE TITLE
Showing in Celsius

### ISSUE THREAD

**Issue by dew1803** [chrisjshull/homebridge-nest#66]
**Describe the bug**
Not sure when it changed, but my Temps are now showing in Celsius. I don't see anywhere where the option to display in Celsius is selected.

**To Reproduce**
Issue is persistent. Does not seem to show in F.

**Expected behavior**
Expect to see temp in F rather than C.

Include with your bug report this version info:
```sh
node v8.11.1
homebridge v0.4.45
```
Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`
Done

**Comment by chrisjshull** [comment]
Home just uses your iOS level setting: http://www.idownloadblog.com/2017/05/08/how-to-switch-celsius-fahrenheit-ios/
