### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by gman-wa** [chrisjshull/homebridge-nest#661]
I figured that this was the free unsupported version of what runs the Starling product, but that has gotten a ton of updates since the last release here was published.

Are we just waiting for Google to break something and then this is done?

**Comment by gman-wa** [comment]
Thanks bot - I guess that's the answer

**Comment by chrisjshull** [comment]
according to https://github.com/chrisjshull/homebridge-nest/issues/642#issuecomment-1872665916, @adriancable is still active (or at least was last December).

@adriancable, I'm getting a few pings about PRs and such. Should we look to take on additional maintainers?

(Sorry all, I haven't actively participated in a while - no longer have a nest).
