### ISSUE TITLE
Nest API call to subscribe

### ISSUE THREAD

**Issue by r8ders2k** [chrisjshull/homebridge-nest#664]
Getting this on my Homebridge's logs...
![Screenshot 2024-07-15 at 12 22 54 PM](https://github.com/user-attachments/assets/95c0e9d7-69bf-4f2e-af5b-dcde9c53b579)

**Comment by r8ders2k** [comment]
Think I fixed it by adding the API Key.

**Comment by marcelgood** [comment]
Getting this error, too. It started a few days ago. Restarting Homebridge resolves it, but it comes back several days later and another restart fixes it again. Google must have changed something and the certificate expires before the plugin requests a new one or something. I'm using the Refresh Token auth method and my token is apparently still valid as a simple restart of Homebridge resolves the issue for a while.
