### ISSUE TITLE
Nest Gen 4 Support

### ISSUE THREAD

**Issue by rroach3753** [chrisjshull/homebridge-nest#670]
**Is your feature request related to a problem? Please describe.**
Is there a way to add the functionality to support the Nest Gen 4?  With this new thermostat, you must use the Google Home app and the Nest App is no longer supported (the thermostat does not appear in the app and you cannot setup the Nest Gen 4 with it).

That's it.  That's the problem and the request.

TIA,
RR!

**Comment by jocamero** [comment]
+1

Note: I read today, Starling Home Hub v15 supports the Nest Learning Thermostat (4th gen) and additional functionality beyond Google's neutered Matter implementation. It would be great if homebridge-nest supported the additional features like it does with the 3rd gen thermostat. 🤞

https://starlinghome.io/so/6dP6VEJM7?languageTag=en&cid=82668c61-dfad-4ab0-a2a4-e876684225aa

**Comment by jocamero** [comment]
Followup: I purchased and setup a Starling hub. It works great with the 4th gen Nest Thermostat.

**Comment by rroach3753** [comment]
> Followup: I purchased and setup a Starling hub. It works great with the 4th gen Nest Thermostat.

I shouldn't need to buy another product to make this work.

**Comment by mdecaro** [comment]
Any updates on Nest Gen4 thermostat support?
