### ISSUE TITLE
Homebridge 2.0 compatibility

### ISSUE THREAD

**Issue by mao832** [chrisjshull/homebridge-nest#671]
As you probably already know, Homebridge 2.0 is coming and homebridge-nest plugin is already marked as officially not supported actually is his "as is" version:

[Updating To Homebridge v2.0](https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0)

Are you planning to adapt the plugin and make it compatible?

Thanks in advance 👍

**Comment by jakepez** [comment]
#663 is open to fix Homebridge v2.0 compatibility.
