### ISSUE TITLE
Relationship to Starling Home Hub Project

### ISSUE THREAD

**Issue by gman-wa** [chrisjshull/homebridge-nest#673]
Can someone explain the relationship between this Homebridge plugin and Starling?

Did they start from the same codebase and at some point they forked and now this project is two years behind in new features and bug fixes and any improvements will be tinkering around the edges?

Should the subtle Starling marketing message in the README really read - 'this project is abandoned by the original authors as all efforts are going to the commercial side - if you want 'it just works' functionality then just buy a Starling hub'?

That's what it seems like to me anyway.  And to be clear this is totally fine and I would probably do the same thing - but if this project is really not going to get any love then just stick a fork in it and call it a day.

**Comment by tomblixt** [comment]
@gman-wa checkout this issue https://github.com/chrisjshull/homebridge-nest/issues/642#issuecomment-2264069070

**Comment by gman-wa** [comment]
> @gman-wa checkout this issue [#642 (comment)](https://github.com/chrisjshull/homebridge-nest/issues/642#issuecomment-2264069070)

@tomblixt - I've seen that thread but it doesn't answer anything.  The last meaningful commit to master here was in October 2022.  Meanwhile Starling Home Hub has added a bunch of new features and fixes in the last two years.
