### ISSUE TITLE
Homebridge service don't start when Nest config is set 

### ISSUE THREAD

**Issue by bobybob69** [chrisjshull/homebridge-nest#68]
**Describe the bug**
When adding Nest config to config.json , Homebridge service doesn't start. However when removing the Nest config, Homebridge is starting as expected. The Nest module break the Homebridge script I don't know why. 

**To Reproduce**
1. open config.json 
2. add Nest config to the template
3. launch terminal command : sudo homebridge 
4. you'll notice Homebridge not launching, QR Code doesn't appear and nothing happen

**Expected behavior**
Homebridge should launch normally, QR Code ready to be scanned 

Include with your bug report this version info:
```sh
node --version 10.1.0
homebridge --version 0.4.45
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
sudo DEBUG=* homebridge -D
[2018-10-25 20:12:27] Loaded config.json with 0 accessories and 4 platforms.
[2018-10-25 20:12:27] ---
[2018-10-25 20:12:27] Loaded plugin: homebridge-config-ui-x
[2018-10-25 20:12:27] Registering platform 'homebridge-config-ui-x.config'
[2018-10-25 20:12:27] ---
[2018-10-25 20:12:27] Loaded plugin: homebridge-edomoticz
[2018-10-25 20:12:27] Registering platform 'homebridge-edomoticz.eDomoticz'
[2018-10-25 20:12:27] ---
[2018-10-25 20:12:28] Loaded plugin: homebridge-melcloud
[2018-10-25 20:12:28] Registering platform 'homebridge-melcloud.Melcloud'
[2018-10-25 20:12:28] ---
[2018-10-25 20:12:28] Loaded plugin: homebridge-nest
[2018-10-25 20:12:28] Registering platform 'homebridge-nest.Nest'
[2018-10-25 20:12:28] ---
[2018-10-25 20:12:28] Loading 4 platforms...
[2018-10-25 20:12:28] [eDomoticz] Initializing eDomoticz platform...
[2018-10-25 20:12:28] [Config] Initializing config platform...
[2018-10-25 20:12:28] [Config] Spawning homebridge-config-ui-x with PID 1268
[2018-10-25 20:12:28] [Melcloud] Initializing Melcloud platform...
[2018-10-25 20:12:28] [Melcloud] Fetching Melcloud devices...
[2018-10-25 20:12:28] [Nest] Initializing Nest platform...
[2018-10-25 20:12:28] [Nest] Fetching Nest devices.
[2018-10-25 20:12:28] Loading 0 accessories...
[2018-10-25 20:12:28] [eDomoticz] There was an error while getting the MQTT Hardware Device from Domoticz.
Please verify that you have added the MQTT Hardware Device and that the hardware device is enabled.
[2018-10-25 20:12:29] [Config] Using Form Authentication
  express:application set "x-powered-by" to true +0ms
  express:application set "etag" to 'weak' +2ms
  express:application set "etag fn" to [Function: generateETag] +0ms
  express:application set "env" to 'development' +1ms
  express:application set "query parser" to 'extended' +0ms
  express:application set "query parser fn" to [Function: parseExtendedQueryString] +0ms
  express:application set "subdomain offset" to 2 +0ms
  express:application set "trust proxy" to false +0ms
  express:application set "trust proxy fn" to [Function: trustNone] +1ms
  express:application booting in development mode +0ms
  express:application set "view" to [Function: View] +0ms
  express:application set "views" to '/Users/loris/views' +0ms
  express:application set "jsonp callback name" to 'callback' +0ms
  express:router use '/' query +3ms
  express:router:layer new '/' +0ms
  express:router use '/' expressInit +1ms
  express:router:layer new '/' +0ms
  express:router use '/' helmet +0ms
  express:router:layer new '/' +0ms
  express:router use '/' initialize +0ms
  express:router:layer new '/' +0ms
  express:router use '/' authenticate +1ms
  express:router:layer new '/' +0ms
  express:router:route new '/' +0ms
  express:router:layer new '/' +0ms
  express:router:route get '/' +0ms
  express:router:layer new '/' +0ms
  express:router:route get '/' +1ms
  express:router:layer new '/' +0ms
  express:router use '/assets/snapshot.jpg' <anonymous> +0ms
  express:router:layer new '/assets/snapshot.jpg' +0ms
  express:router use '/' serveStatic +0ms
  express:router:layer new '/' +0ms
  express:router use '/' corsMiddleware +1ms
  express:router:layer new '/' +0ms
  express:router use '/' jsonParser +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/' +1ms
  express:router:layer new '/' +0ms
  express:router:route post '/' +0ms
  express:router:layer new '/' +0ms
  express:router use '/api/login' router +0ms
  express:router:layer new '/api/login' +0ms
  express:router:route new '/' +0ms
  express:router:layer new '/' +1ms
  express:router:route get '/' +0ms
  express:router:layer new '/' +0ms
  express:router use '/api/settings' router +0ms
  express:router:layer new '/api/settings' +0ms
  express:router:route new '/' +0ms
  express:router:layer new '/' +0ms
  express:router:route get '/' +0ms
  express:router:layer new '/' +0ms
  express:router use '/api/backup/config.json' queryTokenAuthHandler +0ms
  express:router:layer new '/api/backup/config.json' +1ms
  express:router use '/api/backup/config.json' router +0ms
  express:router:layer new '/api/backup/config.json' +0ms
  express:router use '/api' formAuthHandler +0ms
  express:router:layer new '/api' +0ms
  express:router:route new '/restart' +0ms
  express:router:layer new '/restart' +0ms
  express:router:route put '/restart' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/reset-homebridge' +1ms
  express:router:layer new '/reset-homebridge' +0ms
  express:router:route put '/reset-homebridge' +0ms
  express:router:layer new '/' +0ms
  express:router:route put '/reset-homebridge' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/qrcode.svg' +0ms
  express:router:layer new '/qrcode.svg' +0ms
  express:router:route get '/qrcode.svg' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/token' +1ms
  express:router:layer new '/token' +0ms
  express:router:route get '/token' +0ms
  express:router:layer new '/' +0ms
  express:router use '/api/server' router +0ms
  express:router:layer new '/api/server' +0ms
  express:router:route new '/' +0ms
  express:router:layer new '/' +0ms
  express:router:route get '/' +0ms
  express:router:layer new '/' +0ms
  express:router:route get '/' +1ms
  express:router:layer new '/' +0ms
  express:router:route new '/' +0ms
  express:router:layer new '/' +0ms
  express:router:route post '/' +0ms
  express:router:layer new '/' +0ms
  express:router:route post '/' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/:id' +0ms
  express:router:layer new '/:id' +0ms
  express:router:route delete '/:id' +1ms
  express:router:layer new '/' +0ms
  express:router:route delete '/:id' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/:id' +0ms
  express:router:layer new '/:id' +0ms
  express:router:route put '/:id' +0ms
  express:router:layer new '/' +0ms
  express:router:route put '/:id' +0ms
  express:router:layer new '/' +1ms
  express:router use '/api/users' router +0ms
  express:router:layer new '/api/users' +0ms
  express:router:route new '/' +0ms
  express:router:layer new '/' +0ms
  express:router:route get '/' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/update' +0ms
  express:router:layer new '/update' +0ms
  express:router:route put '/update' +1ms
  express:router:layer new '/' +0ms
  express:router:route put '/update' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/uninstall' +0ms
  express:router:layer new '/uninstall' +0ms
  express:router:route post '/uninstall' +0ms
  express:router:layer new '/' +0ms
  express:router:route post '/uninstall' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/install' +0ms
  express:router:layer new '/install' +0ms
  express:router:route post '/install' +1ms
  express:router:layer new '/' +0ms
  express:router:route post '/install' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/homebridge' +0ms
  express:router:layer new '/homebridge' +0ms
  express:router:route get '/homebridge' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/homebridge/upgrade' +0ms
  express:router:layer new '/homebridge/upgrade' +0ms
  express:router:route put '/homebridge/upgrade' +0ms
  express:router:layer new '/' +1ms
  express:router:route put '/homebridge/upgrade' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/changelog/:package' +0ms
  express:router:layer new '/changelog/:package' +0ms
  express:router:route get '/changelog/:package' +0ms
  express:router:layer new '/' +0ms
  express:router:route get '/changelog/:package' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/config-schema/:package' +0ms
  express:router:layer new '/config-schema/:package' +0ms
  express:router:route get '/config-schema/:package' +1ms
  express:router:layer new '/' +0ms
  express:router:route get '/config-schema/:package' +0ms
  express:router:layer new '/' +0ms
  express:router use '/api/packages' router +0ms
  express:router:layer new '/api/packages' +0ms
  express:router:route new '/' +0ms
  express:router:layer new '/' +0ms
  express:router:route get '/' +0ms
  express:router:layer new '/' +1ms
  express:router:route get '/' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/' +0ms
  express:router:layer new '/' +0ms
  express:router:route post '/' +0ms
  express:router:layer new '/' +0ms
  express:router:route post '/' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/backups' +0ms
  express:router:layer new '/backups' +0ms
  express:router:route get '/backups' +1ms
  express:router:layer new '/' +1ms
  express:router:route get '/backups' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/backups/:backupId(\\d+)' +0ms
  express:router:layer new '/backups/:backupId(\\d+)' +0ms
  express:router:route get '/backups/:backupId(\\d+)' +0ms
  express:router:layer new '/' +0ms
  express:router:route get '/backups/:backupId(\\d+)' +0ms
  express:router:layer new '/' +1ms
  express:router:route new '/backups' +0ms
  express:router:layer new '/backups' +0ms
  express:router:route delete '/backups' +0ms
  express:router:layer new '/' +0ms
  express:router:route delete '/backups' +0ms
  express:router:layer new '/' +0ms
  express:router use '/api/config' router +0ms
  express:router:layer new '/api/config' +0ms
  express:router:route new '/layout' +1ms
  express:router:layer new '/layout' +0ms
  express:router:route get '/layout' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/layout' +0ms
  express:router:layer new '/layout' +0ms
  express:router:route post '/layout' +0ms
  express:router:layer new '/' +0ms
  express:router use '/api/accessories' router +0ms
  express:router:layer new '/api/accessories' +0ms
  express:router use '/api' router +1ms
  express:router:layer new '/api' +0ms
  express:router:route new /^((?!api\/).)*$/ +0ms
  express:router:layer new /^((?!api\/).)*$/ +0ms
  express:router:route get { /^((?!api\/).)*$/ fast_star: false, fast_slash: false } +0ms
  express:router:layer new '/' +1ms
  express:router:route get { /^((?!api\/).)*$/ fast_star: false, fast_slash: false } +0ms
  express:router:layer new '/' +0ms
  express:router use '/' notFound +0ms
  express:router:layer new '/' +1ms
  express:router use '/' errorHandler +0ms
  express:router:layer new '/' +0ms
[2018-10-25 20:12:29] [Config] Console v3.8.11 is listening on port 5555.
  express:router dispatching GET /api/server/token +1s
  express:router query  : /api/server/token +2ms
  express:router expressInit  : /api/server/token +0ms
  express:router helmet  : /api/server/token +1ms
  express:router initialize  : /api/server/token +10ms
  express:router authenticate  : /api/server/token +0ms
  express:router serveStatic  : /api/server/token +1ms
  send stat "/usr/local/lib/node_modules/homebridge-config-ui-x/public/api/server/token" +1ms
  express:router corsMiddleware  : /api/server/token +1ms
  express:router jsonParser  : /api/server/token +1ms
  body-parser:json skip empty body +0ms
  express:router trim prefix (/api) from url /api/server/token +1ms
  express:router formAuthHandler /api : /api/server/token +0ms
  express:router trim prefix (/api/server) from url /api/server/token +3ms
  express:router router /api/server : /api/server/token +0ms
  express:router dispatching GET /token +0ms
  express:router dispatching GET /api/packages/homebridge +32ms
  express:router query  : /api/packages/homebridge +0ms
  express:router expressInit  : /api/packages/homebridge +1ms
  express:router helmet  : /api/packages/homebridge +0ms
  express:router initialize  : /api/packages/homebridge +1ms
  express:router authenticate  : /api/packages/homebridge +0ms
  express:router serveStatic  : /api/packages/homebridge +1ms
  send stat "/usr/local/lib/node_modules/homebridge-config-ui-x/public/api/packages/homebridge" +0ms
  express:router corsMiddleware  : /api/packages/homebridge +0ms
  express:router jsonParser  : /api/packages/homebridge +1ms
  body-parser:json skip empty body +0ms
  express:router trim prefix (/api) from url /api/packages/homebridge +0ms
  express:router formAuthHandler /api : /api/packages/homebridge +0ms
  express:router dispatching GET /api/settings +5ms
  express:router query  : /api/settings +0ms
  express:router expressInit  : /api/settings +0ms
  express:router helmet  : /api/settings +0ms
  express:router initialize  : /api/settings +1ms
  express:router authenticate  : /api/settings +0ms
  express:router serveStatic  : /api/settings +0ms
  send stat "/usr/local/lib/node_modules/homebridge-config-ui-x/public/api/settings" +0ms
  express:router corsMiddleware  : /api/settings +1ms
  express:router jsonParser  : /api/settings +0ms
  body-parser:json skip empty body +1ms
  express:router trim prefix (/api/settings) from url /api/settings +0ms
  express:router router /api/settings : /api/settings +0ms
  express:router dispatching GET / +0ms
  express:router dispatching GET /api/server/qrcode.svg +1ms
  express:router query  : /api/server/qrcode.svg +0ms
  express:router expressInit  : /api/server/qrcode.svg +0ms
  express:router helmet  : /api/server/qrcode.svg +0ms
  express:router initialize  : /api/server/qrcode.svg +2ms
  express:router authenticate  : /api/server/qrcode.svg +0ms
  express:router serveStatic  : /api/server/qrcode.svg +0ms
  send stat "/usr/local/lib/node_modules/homebridge-config-ui-x/public/api/server/qrcode.svg" +0ms
  express:router corsMiddleware  : /api/server/qrcode.svg +0ms
  express:router jsonParser  : /api/server/qrcode.svg +0ms
  body-parser:json skip empty body +0ms
  express:router trim prefix (/api) from url /api/server/qrcode.svg +0ms
  express:router formAuthHandler /api : /api/server/qrcode.svg +0ms
  express:router trim prefix (/api/packages) from url /api/packages/homebridge +1ms
  express:router router /api/packages : /api/packages/homebridge +0ms
  express:router dispatching GET /homebridge +0ms
  express:router trim prefix (/api/server) from url /api/server/qrcode.svg +4ms
  express:router router /api/server : /api/server/qrcode.svg +0ms
  express:router dispatching GET /qrcode.svg +0ms
[2018-10-25 20:12:37] [Melcloud] ContextKey: 98A2CE9208F6458784B1C0FDEBB798
[2018-10-25 20:12:39] [Melcloud] Found device: Chambre
[2018-10-25 20:12:39] [Melcloud] Found device: Salon
[2018-10-25 20:12:39] [Melcloud] Initializing platform accessory 'Chambre'...
HAP Warning: Characteristic 00000029-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000004A-0000-1000-8000-0026BB765291. Adding anyway.
HAP Warning: Characteristic 0000006C-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000004A-0000-1000-8000-0026BB765291. Adding anyway.
HAP Warning: Characteristic 0000007B-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000004A-0000-1000-8000-0026BB765291. Adding anyway.
HAP Warning: Characteristic 0000006E-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000004A-0000-1000-8000-0026BB765291. Adding anyway.
HAP Warning: Characteristic 0000007D-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000004A-0000-1000-8000-0026BB765291. Adding anyway.
[2018-10-25 20:12:39] [Melcloud] Initializing platform accessory 'Salon'...
HAP Warning: Characteristic 00000029-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000004A-0000-1000-8000-0026BB765291. Adding anyway.
HAP Warning: Characteristic 0000006C-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000004A-0000-1000-8000-0026BB765291. Adding anyway.
HAP Warning: Characteristic 0000007B-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000004A-0000-1000-8000-0026BB765291. Adding anyway.
HAP Warning: Characteristic 0000006E-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000004A-0000-1000-8000-0026BB765291. Adding anyway.
HAP Warning: Characteristic 0000007D-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000004A-0000-1000-8000-0026BB765291. Adding anyway.

**Comment by adriancable** [comment]
Old, probably no longer an issue.
