### ISSUE TITLE
Devices not visible in Apple Home

### ISSUE THREAD

**Issue by RareSpawn** [chrisjshull/homebridge-nest#683]
I can manage the devices with the Homebridge webui, but I am unable to see/add them with the Apple Homkit anymore.   Loggin is working.  Not seeing any errors in the log.   Thanks

**Comment by mark-addams001881** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modify the accessory registration process to ensure devices are properly added to HomeKit after authentication.

You can review changes in this commit: https://github.com/mark-addams001881/chrisjshull-homebridge-nest-683/commit/798aa59358843348274791ea178ebd7e1caecf45.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by RareSpawn** [comment]
I was able to fix by unpairing the Bridge under Settings-->Bridges, then repairing with Apple device.

**Comment by RareSpawn** [comment]
I was able to fix by unpairing the Bridge under Settings-->Bridges, then repairing with Apple device.
