### ISSUE TITLE
Siri temp reporting issue

### ISSUE THREAD

**Issue by Chivs** [chrisjshull/homebridge-nest#7]
One bug I noticed, asking Siri the current temp, she accurately reports the temp of the requested thermostat, but also reports 'going down to....' and references the Eco low temp setting. So somehow the Eco settings are being mixed up with the current high/low settings.
Example: My Eco setting is 50 Low 80 High. With a Thermostat home setting of 66 low and 75 high on Auto, Siri reports current temp 68 going down to 50...

**Comment by Chivs** [comment]
Grabbed this file with your referenced fix, but no change to Siri temp reporting.
Currently tested. T-stat in Eco mode, Siri reporting temp 70, going down to 50

**Comment by chrisjshull** [comment]
sorry, bad copy and paste to that commit message. I'm still working on this issue.

**Comment by chrisjshull** [comment]
fix merged
