### ISSUE TITLE
Nest detect

### ISSUE THREAD

**Issue by Rens93** [chrisjshull/homebridge-nest#75]
Hi,

Is it possible to add Nest Detect (the sensor of Nest Secure) so we can use the motion sensor of it to control lights?
Now I have different motion sensors in my room, it would be nice if I can use just one sensor for security and also for my lights :)

Thanks!

**Comment by adriancable** [comment]
It is possible, but I don't have a Nest Detect. If you're interested in helping out providing some data so I can add this, feel free to reach out.

**Comment by Rens93** [comment]
How can I help?

**Comment by adriancable** [comment]
@Rens93 - most useful would be HAR files showing me API responses from the Nest Detect.

1. Go to home.nest.com and log in. Select your Nest Detect.
2. Start HAR file recording in your browser.
3. Press 'Refresh' in the browser.
4. Trigger the motion sensor, and check that's shown in the web app.
5. Send me the HAR file.

Thanks!

**Comment by Rens93** [comment]
Thank you I’ll  look coming week!

**Comment by Rens93** [comment]
Well.. I guess its to hard.. There's a lot of data and I don't know which file I have to send. There are a lot of files

**Comment by adriancable** [comment]
@Rens93 - if you follow my instructions above to produce a HAR file you will get just one HAR file. That's what I need - that single file.

**Comment by Rens93** [comment]
I have followed those steps:

HAR
A HAR capture (HTTP Archives) records the requests and responses that your browser makes with the Box Web Application.
 
Chrome
In Chrome, go to the page within Box where you are experiencing trouble.
At the top-right of your browser window, click the Chrome menu (⋮).
Select Tools > Developer Tools. The Developer Tools window opens as a docked panel at the side or bottom of Chrome.
Click the Network tab.
Select Preserve log.
You will see a red circle at the top left of the Network tab. This means the capture has started. If the circle is black, click the black circle to start recording activity in your browser.
Refresh the page and reproduce the problem while the capture is running.
After you successfully reproduce the issue, right click on any row of the activity pane and select Save as HAR with Content.
Select the Console tab.
Right-click anywhere in the console and select Save as....
Name the log file Chrome-console.log.
Send both files as shared links in a reply to your case. 

But then I have a full list of files

**Comment by brn2prgrm** [comment]
Were the proper responses ever captured for you Adrian? If not I will submit them this evening when I get home. Can I also record the API responses for Arm/Disarm? Or do we already know for sure they are not accessible?

**Comment by adriancable** [comment]
@brn2prgrm - I never got the responses so if you can provide them that would be really great. Please do try to also record separate HAR files for the arm and disarm actions - I don't know if they are accessible or not but with this data I can find out!

**Comment by brn2prgrm** [comment]
Did this ever progress into anything?  Is there anything else I can help with?

**Comment by brn2prgrm** [comment]
Any update?

**Comment by dgmltn** [comment]
I've implemented this, [here]([url](https://github.com/dgmltn/homebridge-nest/tree/nest-detect-accessory)). @adriancable are you accepting PRs?
