### ISSUE TITLE
Video source support for the Nest camera's?

### ISSUE THREAD

**Issue by iWebbers** [chrisjshull/homebridge-nest#76]
We have 7 Nest indoor camera's and 1 Nest Hello doorbell. All turn up nice as motion sensors within Homekit. Great job ;)

Is there any change we might get video source support from these camera's as well somewhere soon?

I know (tried and succeeded) you can use the FFMPEG plugin to get the video source of these camera's but I would love the video and motion detection be combined as one (as in an original Homekit camera). This way the options are endless...

T.i.a.

**Comment by adriancable** [comment]
The plug-in does not currently support the Nest Cam. Please take a look at the homebridge-nest-cam plug-in - it may do what you need.

**Comment by derek-miller** [comment]
I would like to take a stab at implementing this. I have spent the last few days looking at the code in homebridge-nest-cam and it doesnt look too bad. Any thing I should know or any prior work done here wrt this plugin?

**Comment by adriancable** [comment]
@derek-miller - I now actually have a complete implementation of Nest Camera support working. It is actually rather complicated to do properly. In order to support audio and video together, and keep them synchronised, I needed to implement a full RTSP media server on the plug-in side. I don't recommend trying to repeat this, since it wasn't fun!

I haven't yet released the updated plug-in, because it requires an update to Homebridge to work properly. First, Homebridge needs to update to HAP-NodeJS 0.5.0, and there are some also some additional patches required to support cameras in bridged mode, which is required for a good user experience. Once Homebridge has made the changes (and I don't have an ETA for this, since I'm not involved with the project), I'll release an update to the plug-in with full camera support.

**Comment by derek-miller** [comment]
@adriancable Sounds good. This is exactly why I reached out! Let me know if you need any help. Thanks for this great plugin!

**Comment by adriancable** [comment]
@derek-miller - if you are interested in testing the new plug-in (and feel good about patching Homebridge with my guidance), email me at adrian.cable@gmail.com.

**Comment by muzzymate** [comment]
Both video and audio from the camera? Nice! Looking forward to it rolling out

**Comment by Kraiggers** [comment]
Hello. Thanks for your efforts!  Homebridge (and the Nest module) have really been an extremely pleasant discovery.  Kudos to the folks who've done the work.

Any news on this Camera issue(s)?  Still waiting for HomeBridge update (as mentioned above)? I guess?  I'm very much looking forward to getting them back working again in HomeKit!

**Comment by titoudoc** [comment]
> @derek-miller - if you are interested in testing the new plug-in (and feel good about patching Homebridge with my guidance), email me at [adrian.cable@gmail.com](mailto:adrian.cable@gmail.com).

Hi, I’ve sent you an e-mail. I would be pleased if I could help you testing.

**Comment by titoudoc** [comment]
> @derek-miller - I now actually have a complete implementation of Nest Camera support working. It is actually rather complicated to do properly. In order to support audio and video together, and keep them synchronised, I needed to implement a full RTSP media server on the plug-in side. I don't recommend trying to repeat this, since it wasn't fun!
> 
> I haven't yet released the updated plug-in, because it requires an update to Homebridge to work properly. First, Homebridge needs to update to HAP-NodeJS 0.5.0, and there are some also some additional patches required to support cameras in bridged mode, which is required for a good user experience. Once Homebridge has made the changes (and I don't have an ETA for this, since I'm not involved with the project), I'll release an update to the plug-in with full camera support.

Hi Adrian Cable, any chance you will publish the update ? Since you moved your effort to
starling home hub, I’m worried you leave
the homebridge community...

**Comment by adriancable** [comment]
Hi – just to reassure everyone I am still alive and active! As mentioned in the original post, the update requires an update to Homebridge to work fully. As you can see on the thread, there have been requests to update to HAP-NodeJS 0.5.0 or later, but it hasn’t been actioned yet. This isn’t a complaint against the Homebridge maintainers – I’m sure they have other parts of their lives too!

**Comment by titoudoc** [comment]
Hello Adrian, any update on this ?

**Comment by popepay** [comment]
HomeBridge is now on HAP-NodeJS v0.6.9 since v1.0.3: https://github.com/homebridge/homebridge/commit/fb298768e80f652430de8055ac4e44c787d5d56e

Do you need anything else to be able to push the camera support?

**Comment by adriancable** [comment]
@popepay - I no longer plan to add camera support. Since October @Brandawg93 has taken over the homebridge-nest-cam project and added Google support and audio, which were the main things missing. I actually think the reworked plug-in is quite good now, and don't want to compete with it.
