### ISSUE TITLE
Occupancy sensor based on Home/Away status

### ISSUE THREAD

**Issue by nielsth** [chrisjshull/homebridge-nest#77]
**Is your feature request related to a problem? Please describe.**
Nest Protect detects occupancy in the house and changes the Home/Away status based on that. This makes a good opportunity for an occupancy sensor which can be included in the Home status screen an can serve as a trigger for automations. 

**Describe the solution you'd like**
An Occupancy sensor that is triggered when the Home/Away status of Nest is set to Home, and is in its default state when the Nest status is set to Away. 

Ideally, under the Details of the Occupancy sensor it would report how many users have been detected. (Not sure if this is official part of the HomeKit specs of Occupancy sensors, but I think it is. Also I'm not sure if you can find the number of people who are at Home in the Nest API). 

**Describe alternatives you've considered**
I currently have Nest linked to Home Assistant and linked that to HomeKit. By default in HA, the Home/Away status is listed in HomeKit but the wrong way around (Away = triggered, Home = default). I then created a ghost/fake sensor in HA to make it work the right way around. See the result in the image below. (I'm trying to ditch HA since the HomeKit integration is pretty useless, so hoping to achieve this Occupancy detection with Homebridge).

![img_0013](https://user-images.githubusercontent.com/13969232/50758148-a6bc5980-1261-11e9-9624-a61e2b7373dd.png)

**Comment by adriancable** [comment]
homebridge-nest 3.0.0 now exposes the Nest Protect occupancy sensor.

**Comment by nielsth** [comment]
Thanks @adriancable!
