### ISSUE TITLE
Occupancy sensor stuck to 'on/triggered'

### ISSUE THREAD

**Issue by mkormendy** [chrisjshull/homebridge-nest#80]
**Describe the bug**
Occupancy sensor stuck in "Occupancy detected in Nest" mode, or doesn't seem to change ever.
I've never really took notice to this, since I never used the sensor until now, and now I notice it never triggers when there's motion due to it always seeming being detecting occupancy. (the debug logs just show it as Home Occupied for Living Room Thermostat is: 1)

**To Reproduce**
1. Perform standard install this repo in homebridge and gather authentication for configuration.
2. Alter config accordingly and restart homebridge.

**Expected behavior**
I expect the sensor to switch back to not detecting any occupancy, but it never does.

Include with your bug report this version info:
```sh
node --version: v11.7.0
homebridge --version: 0.4.46
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
[1/28/2019, 1:37:17 AM] [Nest] [NestFirebase] User null is logged in with custom
[1/28/2019, 1:37:17 AM] [Nest] initing thermostat "Living Room Thermostat": deviceId: VfIpEhg5JFUOsIJHZ9X58uMZx0L2EiP9 structureId: -K9_9Q90Z2qsanN7D6EVCi0EW9eDW9Ezc2I9ebOxoIXuuTnhdEb6Yw
[1/28/2019, 1:37:17 AM] [Nest] { ambient_temperature_c: 20.5,
  ambient_temperature_f: 69,
  away_temperature_high_c: 24,
  away_temperature_high_f: 76,
  away_temperature_low_c: 10,
  away_temperature_low_f: 50,
  can_cool: true,
  can_heat: true,
  device_id: 'VfIpEhg5JFUOsIJHZ9X58uMZx0L2EiP9',
  eco_temperature_high_c: 24,
  eco_temperature_high_f: 76,
  eco_temperature_low_c: 10,
  eco_temperature_low_f: 50,
  fan_timer_active: false,
  fan_timer_duration: 15,
  fan_timer_timeout: '1970-01-01T00:00:00.000Z',
  has_fan: true,
  has_leaf: false,
  humidity: 35,
  hvac_mode: 'heat-cool',
  hvac_state: 'off',
  is_locked: false,
  is_online: true,
  is_using_emergency_heat: false,
  label: '',
  last_connection: '2019-01-28T07:26:39.206Z',
  locale: 'en-US',
  locked_temp_max_c: 22,
  locked_temp_max_f: 72,
  locked_temp_min_c: 20,
  locked_temp_min_f: 68,
  name: 'Living Room',
  name_long: 'Living Room Thermostat',
  previous_hvac_mode: '',
  software_version: '5.9.3-6',
  structure_id: '-K9_9Q90Z2qsanN7D6EVCi0EW9eDW9Ezc2I9ebOxoIXuuTnhdEb6Yw',
  sunlight_correction_active: false,
  sunlight_correction_enabled: false,
  target_temperature_c: 20,
  target_temperature_f: 68,
  target_temperature_high_c: 21.5,
  target_temperature_high_f: 71,
  target_temperature_low_c: 20,
  target_temperature_low_f: 68,
  temperature_scale: 'F',
  time_to_target: '~0',
  time_to_target_training: 'ready',
  where_id: 'tVu666ZugueS0HJ5n9sEyW1W80eZoGDfeCE3sG40dc_kgHIDys9Vdg',
  where_name: 'Living Room' }
[1/28/2019, 1:37:17 AM] [Nest] Temperature unit for Living Room Thermostat is: Fahrenheit
[1/28/2019, 1:37:17 AM] [Nest] Current temperature for Living Room Thermostat is: 20.5 °C and 68.9 °F
[1/28/2019, 1:37:17 AM] [Nest] Current humidity for Living Room Thermostat is: 35%
[1/28/2019, 1:37:17 AM] [Nest] Target temperature for Living Room Thermostat is: 20.5 °C and 68.9 °F
[1/28/2019, 1:37:17 AM] [Nest] Target heating/cooling state for Living Room Thermostat is: Auto
[1/28/2019, 1:37:17 AM] [Nest] Cooling threshold temperature for Living Room Thermostat is: 21.6 °C and 70.88 °F
[1/28/2019, 1:37:17 AM] [Nest] Heating threshold temperature for Living Room Thermostat is: 20 °C and 68 °F
[1/28/2019, 1:37:17 AM] [Nest] Home Occupied for Living Room Thermostat is: 1
[1/28/2019, 1:37:17 AM] [Nest] Initializing platform accessory 'Living Room Thermostat'...

**Comment by mkormendy** [comment]
Ticket #77 also seems to have issues with the occupancy detection.

**Comment by adriancable** [comment]
Try homebridge-nest 3.0.0 and let me know if this issue is resolved.

**Comment by mkormendy** [comment]
Ever since about three weeks ago the entire nest plugin doesn’t work for me so I have no way to test this anymore. I blame google and their shit acquisition of nest and the developer platform they screwed and plan to screw up further.

**Comment by adriancable** [comment]
Mike - try the latest version. It doesn't use the developer platform any more. It may just work for you.

-Adrian

**Comment by mkormendy** [comment]
Well I have access to the nest again! I’m gonna have to see how you managed to do that.

So the occupied accessory showing up unexpectedly as a switch, and not a sensor.
There’s a motion detector on the Nest Thermostat,... that’s what this thread is talking about.

**Comment by adriancable** [comment]
You're welcome! :-)

The Nest home/away really is an on/off switch not a sensor, because you can manually override it from the app. That capability is mirrored in this plug-in. I'll look at adding an option in the config to make it appear as a sensor not a switch, but then of course you lose the capability to override.

I know the Thermostat has a motion detector (to support Farsight etc.) but I'm not sure how (or if it at all) the sensor is exposed via the API.

**Comment by mkormendy** [comment]
For semantic purposes I would have that switch labelled as "Away", and when off, your code sets the thermostat as "Home" or to normal operating schedule. Then it's less confusing as some sort of indeterminate state of occupancy, because in the actual thermostat, the "Away" setting does exactly that: it turns the thermostat into "Away" mode which is a low energy consumption mode for the furnace/AC/HVAC it controls.

**Comment by mkormendy** [comment]
@adriancable, can you provide evidence that you cannot access the sensor?

**Comment by adriancable** [comment]
I didn't say I couldn't access the sensor - just that I don't know how to today. I will keep this open for now.

**Comment by mkormendy** [comment]
Cool thanks! On a side note, I’d like to ask you how you did your 2FA implementation for this module for homebridge as I am attempting to do the same with an alarm.com plugin I maintain. Are you on hangouts or anything? PM me .. mike at somethinginteractive dot com.

**Comment by adriancable** [comment]
Closing for now, will update if and when a motion sensor is added to the Protect code.
