### ISSUE TITLE
Error setting temperature in a scene

### ISSUE THREAD

**Issue by wolfiegrr** [chrisjshull/homebridge-nest#83]
I have a Homekit Scene automation where every morning, at 5:45AM, my automation turns on a set of lights, and sets two Nest thermostats to 68 degrees.  I'm getting mixed results every day.

Some days: 
- it sets one to 68, the other does not change.
- it sets one to 75, the other to 68

The results are very sporadic.   Just this morning I manually ran the scene, and it set one to 75 (where it should have returned 68).  I have to manually set it to 68 in the Nest app itself because occasionally the Home app will revert its temperature back to 75 on read as if the change did not process.

**To Reproduce**
1. Setup two Nest's, configure Homebridge-nest to work, and set automations or scenes to use two Nest thermostats.  Have those scenes set to identical temperatures.

**Expected behavior**
Appropriate temperature should be set for each independent thermostat.

**Comment by wolfiegrr** [comment]
Posting another note on this -- anyone else having a similar problem?

**Comment by adriancable** [comment]
Try homebridge-nest 3.0.0 and let me know how you get on.

**Comment by adriancable** [comment]
Closing since I believe this should be fixed now. @wolfiegrr - please reopen if it doesn't work for you.
