### ISSUE TITLE
No camera for Nest Hello but there is a motion sensor

### ISSUE THREAD

**Issue by opswhisperer** [chrisjshull/homebridge-nest#86]
**Describe the bug**

**To Reproduce**
1. setup per the readme

**Expected behavior**
I have a nest hello doorbell. I expected to see a camera but all I get is a motion sensor called "Front Door".  No errors in the log.

Include with your bug report this version info:
```sh
node --version v8.15.0
homebridge --version 04.46
```

Have not attached logs because I wasn't sure if I needed to scrub anything from them.

**Comment by opswhisperer** [comment]
[homebridge.log](https://github.com/chrisjshull/homebridge-nest/files/2896344/homebridge.log)

**Comment by opswhisperer** [comment]
[homebridge.log](https://github.com/chrisjshull/homebridge-nest/files/2896348/homebridge.log)

**Comment by ngrimes08** [comment]
you need the other nest plugin for the camera to work, search for nest cam. this one only works the sensors and thermostat, however I can't get the motion sensor to work currently, it used to work then it  stopped working when I switched my home bridge to a different machine and have updated all the components in the process.

**Comment by adriancable** [comment]
The plug-in does not currently support the Nest Cam. Please take a look at the homebridge-nest-cam plug-in - it may do what you need.
