### ISSUE TITLE
Nest Cam Switcher to turn it on

### ISSUE THREAD

**Issue by Rubenfer** [chrisjshull/homebridge-nest#87]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I've a scene to activate when I leave home, what set away my security systems, but I don't have the option of turn on my Nest Cam.

**Describe the solution you'd like**
I think that the solution is add a simple switcher to turn on/off the Nest Cam.

**Describe alternatives you've considered**
The best solution is the switcher. This plugin have a switcher to turn on/off thermostat ECO mode, but not to turn on/off the Nest cam.

**Comment by dhniels** [comment]
i dont think this plugin supports the nest cam...

**Comment by adriancable** [comment]
The plug-in does not currently support the Nest Cam. Please take a look at the homebridge-nest-cam plug-in - it may do what you need.
