### ISSUE TITLE
Can not get a pin code from nest ... is there a workaround ?

### ISSUE THREAD

**Issue by WIMWG** [chrisjshull/homebridge-nest#91]
Thank you for your interest in the Works with Nest program. We're currently restructuring our developer program **and are no longer accepting new developers to the program** or performing client integration reviews for existing developers until the new program is implemented. Stay tuned for further details and announcements.

**Comment by BrunoCoimbra** [comment]
I see the same message and can't get a Client Secret.

**Comment by adriancable** [comment]
homebridge-nest 3.0.0 no longer requires Works With Nest.
