### ISSUE TITLE
Works with Nest API deprecation date

### ISSUE THREAD

**Issue by DJay-X** [chrisjshull/homebridge-nest#94]
@chrisjshull Any chance to keep your great plugin working after the Google announcement?
I use the plugin for years now reliable with my 1. Nest Protect. 
Thanks for your great work and hopefully ongoing development. 

Dear Works with Nest developer,

Today, Nest and Google Home teams have joined forces and are now Google Nest, and we want to share some news about upcoming changes to Works with Nest that will affect your product integration.

Works with Nest was created in 2014, at a time when there was no central platform to manage and control Nest devices alongside other smart home devices. Since we introduced Works with Nest, the Google Assistant has evolved into a leading connected home platform, letting users manage all their connected home devices from Google, Nest, and third-party device partners in one place. 

Moving forward, we will wind down the Works with Nest developer program on August 31, 2019, and focus on delivering a single consumer and developer experience through the Works with Google Assistant program. 

As a Works with Nest developer, you and your users will no longer be able to access and control Nest devices once the Works with Nest APIs are turned off on August 31. Because we understand this may impact your users’ experience with our products, we want to notify you well in advance so you can prepare for these changes. 

Important dates, information, and resources to help you through the transition: 

• Works with Nest API deprecation date. Nest device APIs will be turned off August 31, 2019.
--
• Nest Account to Google Account migration. Early this summer, we will invite Nest Account holders to migrate to a Google Account to align our systems, accounts, and platforms. - During account migration, users will be asked to remove their Works with Nest connections. - Once migration is completed, all of their Works with Nest connections will no longer work. This action is not reversible.
• Works with Nest badge retirement.We are officially retiring the Works with Nest consumer-facing badge. If you are currently using the Works with Nest badge, we ask that you remove it no later than August 31. For packaging and hard marketing material, please remove it at your next revision.
• Service Shutdown Reminder. We will notify all Nest Account holders and developers by email at least 2 weeks before the Works with Nest service is turned off.
• For more detailed information, see our What’s Happening at Nest FAQ page. Please provide this link to customers who want to learn more about these changes.

We appreciate you being a partner of Works with Nest. We encourage you to visit the Actions on Google Smart Home developer site to learn how to integrate your devices or services with the Google Assistant. 

Sincerely,

The Google Nest team

**Comment by chrisjshull** [comment]
It’s a question of what replacement APIs are going to be available. It’s unclear to me what we will be able to do now.

~Chris

**Comment by chrisjshull** [comment]
This could be bad…

> Third parties will no longer be able to ask for permission to directly access or control your Nest devices, thus keeping your data more private.

https://nest.com/whats-happening/#how-is-works-with-google-assistant-different-from-works-with-nest

**Comment by chrisjshull** [comment]
On the other hand:

> The Request Sync feature allows a cloud integration to send a request to the Home Graph to send a new SYNC request. The Report State feature allows a cloud integration to proactively provide the current state of devices to the Home Graph 

https://github.com/actions-on-google/smart-home-nodejs

That sounds good…?

**Comment by n0rt0nthec4t** [comment]
Given the FAQ, which states 

"I’m a Works with Nest developer. Will I be able to access and control Nest devices moving - >No. The Actions on Google Smart Home platform does not provide open API access to Nest devices, so it cannot be used to access and control Nest devices. Instead, managing and controlling Google Home, Nest, and thousands of third-party smart home devices is done through the Google Home app and the Google Assistant"

Not very confidante that we'll get the same functionality as previous with the Nest API. I down use this plugin, but learned from it initial to develop my own Nest Thermostat accessory for HAP-NodeJS integration our hydronic heating and wifi-controlled aircon system. Might be time to throw the Nest out and go Excobee...

**Comment by chrisjshull** [comment]
Yeah, and the sample app’s readme for the new API seems both very complicated and incomplete :(

~Chris

**Comment by n0rt0nthec4t** [comment]
> Yeah, and the sample app’s readme for the new API seems both very complicated and incomplete :( ~Chris
> […](#)

Just seems they want you to use the Google Assistant to perform voice commands to control stuff

**Comment by wfltaylor** [comment]
In a worst case scenario it could work by relying the request to the Google assistant through a text command. It could extract data from responses using regex or something.

**Comment by perote2000** [comment]
Do you think that Alexa will loose compatibility as well?  I dont think so.  I think would be a good idea to ask to amazon if alexa will be able to control nest since September 1st. That might force google to continue keeping an open API.

**Comment by n0rt0nthec4t** [comment]
There maybe in the short term a way around this. The FAQ states that the nest app will be around atm, so using teh un-offical API can still make it work. This is a reference https://github.com/gboudreau/nest-api

Just hard to work out how subscribe to changes on the device and then almost back to normal. Half coded my thermostat accessory form HAP-NodeJS to work this way as a backup.. On the plus side, get access to battery levels now :-)

**Comment by adavison007** [comment]
GOOD NEWS -- 

https://www.cnet.com/news/google-reverses-course-on-cutting-off-works-with-nest/?ftag=COS-05-10aaa0b&linkId=67471322&fbclid=IwAR2wzeAccgEJ91AplZHl3bui0K2BmgxjEbBQSEFeEpwgj4A1H6CkXyMIqaw

**Comment by chrisjshull** [comment]
> The most important change is that if you keep your Nest account, any recipes or automations you have set up with third party gadgets will keep working after August 31st, you just won't be able to add new ones.

Not being able to add new integrations is still bad, as it means we still can’t get new users :(

**Comment by codebykenny** [comment]
As far as I can tell there is no longer any way to create a new developer account, the page just shows their deprecation notice.

Does that mean at the moment there is currently no way for users to use homebridge-nest? I cannot find a way to create a clientId/clientSecret.

**Comment by chrisjshull** [comment]
Correct

**Comment by DJay-X** [comment]
The only "positive" point is, that Google will no longer be deprecating WWN, and existing connections will still be available.

http://bit.ly/2EvDpqb
> Our team has made some updates — we'll no longer be deprecating WWN, and existing connections will still be available on your Nest account — but you won’t have access to new features available with a Google Account: https://goo.gl/ZRKSCT

**Comment by mrjackyliang** [comment]
What bad timing. Just installed two Nest devices realizing I cannot create apps on Works with Nest. Only glad that I didn't spend that much because of the rebate Con Edison is doing.

**Comment by dhniels** [comment]
When i go to the nest developer site and hit "sign up" it gives me a nginx forbidden error. Assuming that means no new signups? What a bummer. Are those with existing keys setup still working, and they've only cut off new users from signing up? I'm super bummed about this as I just got my nest but now im ready to ebay it and get an ecobee like i should have done in the first place....

**Comment by cannikin** [comment]
@dhniels Same here, nginx error. Have you found any cameras that send notifications when motion is seen? At WWDC they mentioned analyzing video on a HomePod (if you have one), but I wonder if that happens by default, or if cameras will need a firmware update to start doing this: https://www.theverge.com/2019/6/3/18646453/apple-homekit-support-smart-home-security-routers-wwdc-2019

**Comment by adriancable** [comment]
homebridge-nest 3.0.0 no longer requires Works With Nest.

**Comment by mrjackyliang** [comment]
Wow! Awesome work Nest Developers! I feel super happy and want to say THANK YOU for those that worked on it!

**Comment by perote2000** [comment]
Excelent!!! Great news and great job, can’t wait to test it at home.

Enviado desde mi iPhone

**Comment by perote2000** [comment]
Works perfect... excellent job!!
