### ISSUE TITLE
Siri says nest is unresponsive.

### ISSUE THREAD

**Issue by raulfunkie** [chrisjshull/homebridge-nest#96]
**Describe the bug**
- Tell "Hey Siri turn on the AC"
- She replies with "The AC is unresponsive".

**To Reproduce**
1. Tell Siri to turn the AC on.

**Expected behavior**
- Siri should turn the AC on.

```
$ node --version
v8.16.0
$ homebridge --version
0.4.50
```

**Summary**
So I tell Siri to turn on the AC. She replies with "The AC is unresponsive". I check HomeKit app and the AC seems to be off but doesn't show any unresponsive behavior. I can turn it on manually from the HomeKit app.

Siri does turn the AC off, changes temperature and whatnot. But it won't turn the AC on. Any ideas what could be causing this?

**Comment by adriancable** [comment]
Can you try the latest commit on github and see if it works now?

**Comment by adriancable** [comment]
Works in the latest commit. Closing for now.
