### ISSUE TITLE
Way to differentiate Nest Protects

### ISSUE THREAD

**Issue by cr3ative** [chrisjshull/homebridge-nest#98]
Hello! 

At the moment with more than one Nest Protect it's difficult/impossible to tell which is in which room without deliberately starting a fire in one room and seeing which goes off in Homebridge.

If there's any room identifiers from the Nest Not-An-API, could we pass those through to the name of the device in Homekit?

Thank you!

**Comment by DJay-X** [comment]
@cr3ative You can do that in the Nest App by adding a "Label". Restart Homebridge.
Hope this helps.

![Napkin 2 20 07 19, 12 38 38 PM](https://user-images.githubusercontent.com/3874239/61577701-57e25d00-aaeb-11e9-845f-4a77f6297c30.png)

**Comment by cr3ative** [comment]
Ooh good tip. Thank you!
